### ISSUE TITLE
在component中, 如何读取父componet的数据?

### ISSUE THREAD

**Issue by GordonHuangYong** [alibaba/fish-redux#100]
typedef ViewBuilder<T> = Widget Function(
  T state,
  Dispatch dispatch,
  ViewService viewService,
);
看了定义, ViewBuilder只传了当前组件的数据, 上一级组件的数据有没有办法获取?

**Comment by zjuwjf** [comment]
一个组件只要关心自己的数据就足够了，如果需要关心其他组件的数据，说明它的数据定义是不对的。

另一个方面，能力越大（state越大），责任越大。

**Comment by GordonHuangYong** [comment]
举个简单的例子.
adpater的行组件, 想要读取当前有多少行, 以便动态隐藏最后一行的分隔线.

这种情况关心自己的数据是不能实现的吧

**Comment by zjuwjf** [comment]
这个是一个观念上的转变，如何真正的去遵循 数据驱动展现的原则。

以提到的例子来看，需要的是一个表达是否隐藏分隔线的字段，而不是一个需要父类数据的问题。

**Comment by GordonHuangYong** [comment]
是的.就是这个意思
看来只能在行组件里加字段了. 然后在父组件中,改写这个字段的值.
只是这样子处理, 要改动的地方太多.感觉有点累赘.

**Comment by GordonHuangYong** [comment]
目前我在上级state中,增加了一个delegate属性, 一个抽象类,这个delegate必须实现这个抽象类的方法. 抽象类的方法是用于读取上级state的数据的.
这个方式我觉得是最方便的.

**Comment by zjuwjf** [comment]
设计里的State期望是尽可能简单的POJO。

尽管你通过delegate来为实现做了一次实现，但是它通过破坏设计原则而带来的一点点的便利，相比丢失的代码的可维护性（易读，易测，易调试）而言，我觉得是舍大取小了。

**Comment by GordonHuangYong** [comment]
明白你的意思. 每个State就相当于一个表. 只有纯数据.
我现在发现了更好的方法.
PageState state =  PageProvider.tryOf(viewService.context).store.getState(); 
这样就可以在组件的widget方法中, 获取到page的数据了.

**Comment by zjuwjf** [comment]
原则性和便利性的矛盾。

像上面那样的话，你仅仅看到了PageState，但是看不到PageState的变化。

这个问题和 #134 是有一定的共性的。
