### ISSUE TITLE
发现effect中dispatch一次, 导致reducer调用多次.

### ISSUE THREAD

**Issue by GordonHuangYong** [alibaba/fish-redux#102]
这是一个adpapter的行组件
 
effect.dart代码
> 
> void _onSelectCell(Action action, Context<CellState> ctx) async {
>   ctx.dispatch(CellActionCreator.select(action.payload));
> }

----
reducer.dart代码

> Reducer<CellState> buildReducer() {
>   return asReducer<CellState>(<Object, Reducer<CellState>>{
>     CellAction.selectCell: _select, //指定action的类型及对应的处理方法
>   });
> }
> CellState _select(CellState state, Action action) {
>   if (state.uniqueId != action.payload) {
>    //发现本方法会多次调用, 不得不增加一个判断, 有多少行就调用多少次.
>     return state;
>   }
>   final CellState newState = state.clone();
>   return newState;
> }

----
是使用不当, 还是bug?

**Comment by zjuwjf** [comment]
设计上，是符合预期的。性能开销很小，一般都是微妙级别。如果有性能问题，可以使用filter。

**Comment by GordonHuangYong** [comment]
//发现了这个.使用过滤器也是一种方式
ReducerFilter<CellState> filter() {
  return (CellState cellState, Action action) {
    //过滤掉,不是选中的行的数据;
    if (action.type == CellAction.selectCell) {
      return cellState.uniqueId == action.payload.uniqueId;
    }
    return true;
  };
}
