### ISSUE TITLE
在page中 的effect  找不到对应的Scaffold.of(ctx.context)

### ISSUE THREAD

**Issue by tom1918** [alibaba/fish-redux#103]
我在代码中 增加了如下的方法
Scaffold.of(ctx.context).showSnackBar(SnackBar(content: Text("网络错误，请重新尝试"),));
我在view 中是定义了 return一个 Scaffold的  但是提示我找不到对应的 Scaffold；
![image](https://user-images.githubusercontent.com/6824136/54807719-15358300-4cb9-11e9-825c-ba800961e727.png)

![image](https://user-images.githubusercontent.com/6824136/54807663-ea4b2f00-4cb8-11e9-8cb6-164909f732a1.png)
![image](https://user-images.githubusercontent.com/6824136/54807737-23839f00-4cb9-11e9-9d4a-f898cad0b13d.png)

**Comment by GordonHuangYong** [comment]
没有调用到buildView吧. 所以是空的对象.

**Comment by tom1918** [comment]
> 没有调用到buildView吧. 所以是空的对象.
![image](https://user-images.githubusercontent.com/6824136/54808309-d6083180-4cba-11e9-8be7-fd4bfb2db0ac.png)
是有调用 buildView的 不然页面是不能显示的

**Comment by GordonHuangYong** [comment]
showSnackBar(...)是在哪里写的?
你试试
ctx.context.widget.showSnackBar(....);

**Comment by tom1918** [comment]
showSnackBar  不是 widget 的方法， 是 Scaffold 的方法

**Comment by GordonHuangYong** [comment]
哦哦.
我这边按照你的说法试了, 在page.的effect是会这样子
在子组件里没发现这种现象,是正常的.

**Comment by GordonHuangYong** [comment]
百度了一下.这个是用法不当.可参考这里的解决方案:
https://www.jianshu.com/p/58f69596df56

**Comment by tom1918** [comment]
> 哦哦.
> 我这边按照你的说法试了, 在page.的effect是会这样子
> 在子组件里没发现这种现象,是正常的.

所以我感觉可能是这个框架的问题

**Comment by zjuwjf** [comment]
> > 哦哦.
> > 我这边按照你的说法试了, 在page.的effect是会这样子
> > 在子组件里没发现这种现象,是正常的.
> 
> 所以我感觉可能是这个框架的问题

Scaffold.of() 需要的是 Scaffold 以内的buildContext， 而ctx.context 是 Component的buildContext， 也就是Scaffold范围以外的buildContext， 所以这样在page是错误的，而在子组件是正确的。

建议的做法是 对Scaffold使用builder，想builder的context传递给action，然后在effect内使用

Scaffold.of(action.payload);

**Comment by tom1918** [comment]
> 百度了一下.这个是用法不当.可参考这里的解决方案:
> https://www.jianshu.com/p/58f69596df56

谢谢 我理解了。

**Comment by tom1918** [comment]
> > > 哦哦.
> > > 我这边按照你的说法试了, 在page.的effect是会这样子
> > > 在子组件里没发现这种现象,是正常的.
> > 
> > 
> > 所以我感觉可能是这个框架的问题
> 
> Scaffold.of() 需要的是 Scaffold 以内的buildContext， 而ctx.context 是 Component的buildContext， 也就是Scaffold范围以外的buildContext， 所以这样在page是错误的，而在子组件是正确的。
> 
> 建议的做法是 对Scaffold使用builder，想builder的context传递给action，然后在effect内使用
> 
> Scaffold.of(action.payload);

OK 我懂了 谢谢！
