### ISSUE TITLE
如何使用已经封装成widget的listview?

### ISSUE THREAD

**Issue by GordonHuangYong** [alibaba/fish-redux#104]
比如:github的这个项目,已经listview封装了成了一个widget

https://github.com/Realank/flutter_section_table_view/

如何在fish-redux的adpater方式下使用这种widget?

貌似只能当普通widget使用了. 无法体现adapter的作用.
求大神解答

**Comment by zjuwjf** [comment]
listadapter 转成widget或者widgets 应该很方便
