### ISSUE TITLE
如何在界面加载完后马上请求数据使用showDialog

### ISSUE THREAD

**Issue by cbyniiaii** [alibaba/fish-redux#105]
我想完成一个自动登录的功能。希望在登录的界面加载完后马上进行登录：

```
class LoginPage extends Page<LoginState, Map<String, dynamic>> {
  LoginPage()
      : super(
          initState: initState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          middlewares: <Middleware<LoginState>>[
            logMiddleware(tag: 'LoginPage'),
          ],
        );
}
```
```
LoginState initState(Map<String, dynamic> args) {
  final LoginState state = LoginState();
  return state;
}
```
```
Effect<LoginState> buildEffect() {
  return combineEffects(<Object, Effect<LoginState>>{
    Lifecycle.initState: _init,
    LoginAction.onLogin: _onLogin,
  });
}

void _init(Action action, Context<LoginState> ctx) {
    _onLogin(action, ctx);
}

void _onLogin(Action action, Context<LoginState> ctx) async{
  showDialog(
      context: ctx.context,
      builder: (BuildContext context) {
        return AlertDialog(
            title: Text('正在请求数据'),
            content: Row(
                children:[
                  CircularProgressIndicator(),
                  Container(margin: EdgeInsets.only(left: 10.0), child: Text('请稍候...', style: TextStyle(color: Colors.grey)))
                ]
            ),
          );
      });
  Response response = await post('http://localhost/login',
      body: json.encode({'usercode': '123', 'password': '123'}));
  dynamic data = json.decode(response.body);
  if(data != null) {
    Navigator.of(ctx.context)
        .pushReplacement(MaterialPageRoute(
        builder: (BuildContext buildCtx) => HomePage().buildPage(<String, dynamic>{})));
  }
}
```

可是我得到了：
`
Unhandled Exception: inheritFromWidgetOfExactType(_LocalizationsScope) or inheritFromElement() was called before ComponentState<LoginState>.initState() completed.
`

有相应的例子吗？

**Comment by zjuwjf** [comment]
将初始化的函数， 挂在 didChangeDependencies 上吧， initState的buildContext 是无法调用inheritFromWidgetOfExactType的。

**Comment by xchenzhen** [comment]
我在didChangeDependencies 调showDialog也报错
`// Effect
class ExpandFunctionEffect {
  static Effect<ExpandFunctionState> buildEffect() {
    return combineEffects(<Object, Effect<ExpandFunctionState>>{
      Lifecycle.didChangeDependencies: _init,
    });
  }

  // 初始化
  static _init(Action action, Context<ExpandFunctionState> ctx) async {
    showLoading(ctx.context);
    HBResponse response = await MeApi.getExtendServiceAccount();
    if (!response.isSuccess()) {
      ViewUtils.showToast(response.getErrorInfo());
      // dismissLoading(ctx.context);
      return;
    }
}`

错误信息：
10-28 15:20:53.764 29913-29973/im.huoban.test E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
    This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
    The widget on which setState() or markNeedsBuild() was called was:
      Overlay-[LabeledGlobalKey<OverlayState>#1eac4](state: OverlayState#d728b(entries: [OverlayEntry#878df(opaque: false; maintainState: false), OverlayEntry#94900(opaque: false; maintainState: true), OverlayEntry#64393(opaque: false; maintainState: false), OverlayEntry#e00e4(opaque: false; maintainState: true)]))
    The widget which was currently being built when the offending call was made was:
      _PageWidget<ExpandFunctionState, Map<String, dynamic>>(state: _PageState<ExpandFunctionState, Map<String, dynamic>>#2bfc4)
    #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3503:11)
    #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3529:6)
    #2      State.setState (package:flutter/src/widgets/framework.dart:1133:14)
    #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:346:5)
    #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
    #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:180:11)
    #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:895:11)
    #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1742:11)
    #8      BoostContainerState.push (package:flutter_boost/container/boost_container.dart:224:30)
    #9      showGeneralDialog (package:flutter/src/widgets/routes.dart:1558:53)
    #10     showDialog (package:flutter/src/material/dialog.dart:705:10)
    #11     showLoading (package:huoban_im_flutter/component/dialog/loading_dialog.dart:46:3)
    #12     ExpandFunctionEffect._init (package:huoban_im_flutter/page/setting/state/expand_function_state.dart:72:5)

**Comment by andyxiaoxi** [comment]
@xchenzhen  我跟你遇到一样的问题，请问你解决了吗
