### ISSUE TITLE
listview adapter缓存

### ISSUE THREAD

**Issue by layou1989** [alibaba/fish-redux#107]
我有一个列表,里面分别有三个组件,分别显示没图片、有图片、有多张图片的列表item展示,代码如下
![image](https://user-images.githubusercontent.com/7498703/54815393-d6112d00-4ccc-11e9-8382-eb26776821e9.png)
![image](https://user-images.githubusercontent.com/7498703/54815408-de696800-4ccc-11e9-8467-5189afba69c8.png)
但当我刷新列表的时候，往列表后面插入数据没有问题，但当我像列表前面插入数据，取得的组件是插入之前缓存的,比如我更新之前的第一个组件是有三张图片,但是当我重新插入一部分数据，第一个组件变成没有图片的组件，但是还是adapter还是获取的三张图片的组件，这边是怎么回事?
插入数据的方法:
![image](https://user-images.githubusercontent.com/7498703/54815579-5041b180-4ccd-11e9-9257-5b35266dbd75.png)
感觉是我重新插入数据，但是adapter还是获取的原来item项中的组件

**Comment by zjuwjf** [comment]
能提一个可以复现的sample么？

**Comment by layou1989** [comment]
@zjuwjf  https://github.com/layou1989/test_fish_redux.git
当点击+按钮时，数字三的背景色应该为蓝色，但却显示为了红色，红色是第一次加载组件色颜色

**Comment by zjuwjf** [comment]
非常感谢提供了可以复现的Sample。

原因：
1. fish-redux 里的Component 设计的是一个装配工厂。
它输出的是一个 ComponentWidget<T> 的widget。
所以当 no_image,one_image,three_image 为同一个T的时候，它们就是同一个类型的widget。

2. flutter listview的复用规则
- a. 比较widget类型
- b. 比较widget的key
- c. 比较index

a,b,c 3个条件同时满足即复用。

这也就解释了为什么appends to the end 是对的，而 insert at the position 0 是会有问题。

绝大多数情况下我们会为一个T， 设计一个Component。 所以这个时候它和我们的期望是一致的。

目前 fish-redux 支持上
1. 可以为component 增加一个key字段
2. 对3个state 分别定义。 

后续通过做一次很小的优化来消除极端情况下的和常规预期不一致现象。

最后，感谢这样一个非常有意义的问题和sample。

**Comment by layou1989** [comment]
@zjuwjf 我明白了，非常感谢耐心的解释
