### ISSUE TITLE
action如何修改当前页面的reducer

### ISSUE THREAD

**Issue by jefferybai** [alibaba/fish-redux#109]
请问在view里面dispatch action 和在effect里面dispatch action有没有区别，
我的理解是当前页面的的state来自于被绑定的connector，
而当前页面的state能够在当前页面的reducer里面被修改状态，
为啥我在view里面派发了action不能起到修改当前页面state的作用？

**Comment by zjuwjf** [comment]
从view，还是effect发出的action并无区别。检查下是不是action被自己的effect消费了，所以没有走到reducer。

另一个要纠正的是，view或effect发出的action如果没有被自己消费，就会走到reducer，这里的reducer是整体的reducer，包括自己的局部reducer。

**Comment by jefferybai** [comment]
好的，我这个页面并未注册过effect。我查看了局部reducer值已经改变了，但是局部页面并没刷新。

**Comment by zjuwjf** [comment]
一个action会修改数据A（reducerA），也会修改数据A.sub（reducerSub）？

**Comment by zjuwjf** [comment]
给个最小集的sample会好理解些。

**Comment by jefferybai** [comment]
一个action会修改数据A（reducerA），也会修改数据A.sub（reducerSub）。                 对的，就是这样。 但是A.sub已经变化了，但是对应的view并未刷新。

**Comment by zjuwjf** [comment]
可以通过middleware观察下，a.sub的变化过程？

**Comment by jefferybai** [comment]
`class MenuComponent extends Component<MenuState> {
  MenuComponent()
      : super(
          view: buildView,
          reducer: buildReducer(),
        );
}



Widget buildView(
  MenuState state,
  Dispatch dispatch,
  ViewService viewService,
) {
  int i = -1;
  print('buildView'); print(state.selectedIndex);
  List<Widget> menus = state.menus.map((item) {
        i ++;
        bool selected = false;
        if(i == state.selectedIndex) { selected = true; }
        return MenuItem(item['icon'], 
              item['label'], item['txt'], 
              (pageName, index) => dispatch(MenuComponentActionCreator.changePage(pageName, index)), 
              i, selected, item['pageName']);
      }
    ).toList(growable:true);
  return Container(
    width: ScreenUtil().setWidth(350),
    height: ScreenUtil().setHeight(536),
    child: Column(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: menus,
    ),
  );
}

Reducer<MenuState> buildReducer() {
  return asReducer(
    <Object, Reducer<MenuState>>{
        MenuComponentAction.changePageName: _selectedIndex
      },
  );
}

MenuState _selectedIndex(MenuState state, Action action) {
  print('_selectedIndex');
  print(action.toString());
  return state.clone()..selectedIndex = action.payload['selectedIndex'];
}
`

现在buildView 会被打印一次， 点击了菜单进行切换_selectedIndex会被打印， 但是buildView不会再被打印了

**Comment by jefferybai** [comment]
@zjuwjf  现在主要是buildView在更新reducer之后并未被触发

**Comment by zjuwjf** [comment]
贴一下ReduxerSub是怎么写的？是否返回了一个新的state？

**Comment by jefferybai** [comment]
@zjuwjf 我刚才贴的的代码全是子页面的 ，     sub reducer如下：
Reducer buildReducer() {
return asReducer(
<Object, Reducer>{
MenuComponentAction.changePageName: _selectedIndex
},
);
}
MenuState _selectedIndex(MenuState state, Action action) {
print('_selectedIndex');
print(action.toString());
return state.clone()..selectedIndex = action.payload['selectedIndex'];
}

**Comment by jefferybai** [comment]
@zjuwjf    page   reducer如下， 
Reducer<CoursePageState> buildReducer() {
  return asReducer(
    <Object, Reducer<CoursePageState>>{
        CoursePageAction.initCoursePage: _coursePageReducer,
        MenuComponentAction.changePageName: _pageName
      },
  );
}

CoursePageState _pageName(CoursePageState state, Action action) {
  return state.clone()..moduleName = action.payload['pageName'];
}

CoursePageState _coursePageReducer(CoursePageState state, Action action) {
  final MenuState menuState = action.payload['menuState'] ?? MenuState();
  final ReportState reportState = action.payload['report'] ?? ReportState();
  final ClassroomState classroomState = action.payload['classroom'] ?? ClassroomState();
  final ReadState readState = action.payload['readState'] ?? ReadState();
  final IpssState ipssState = action.payload['ipssState'] ?? IpssState();
  final CoursePageState newState = state.clone();
  newState.reportState = reportState;
  newState.classroomState = classroomState;
  newState.readState = readState;
  newState.ipssState = ipssState;
  newState.menuState = menuState;
  return newState;
}

**Comment by zjuwjf** [comment]
看上除了没有泛型约束，都没问题，有connector，dependencies， shoudUpdate吗

**Comment by jefferybai** [comment]
@zjuwjf page是这么写的
class CoursePage extends Page<CoursePageState, Map<String, dynamic>> {
  CoursePage()
      : super(
          initState: initState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          dependencies: Dependencies<CoursePageState>(
              // adapter: CourseListAdapter(),
              slots: <String, Dependent<CoursePageState>>{
                'menu': MenuConnector() + MenuComponent(),
              }),
          middlewares: <Middleware<CoursePageState>>[
            logMiddleware(tag: 'CoursePage'),
          ],
        );
}

**Comment by zjuwjf** [comment]
建议还是根据middleware看看menestate是否发生了变化

**Comment by jefferybai** [comment]
@zjuwjf 

A reducer 的clone
CoursePageState _pageName(CoursePageState state, Action action) {
return state.clone()..moduleName = action.payload['pageName'];
}
=====================================================
A.subreducer 的clone
MenuState _selectedIndex(MenuState state, Action action) {
  print('_selectedIndex');
  print(action.payload['selectedIndex']);
  state = state.clone()..selectedIndex = action.payload['selectedIndex'];
  print(state.toString());//我做了如下打印state确实变了， 但是viewbuider的确没有被执行
  return state;
}

**Comment by zjuwjf** [comment]
我是说state的clone方法是如何写的？另外确定buildcomponent（menu）有调用吗

**Comment by jefferybai** [comment]
@zjuwjf 

```
 @override
  MenuState clone() {
    return MenuState()
      ..selectedIndex = selectedIndex
      ..info = info;
  }
```


```
Row(
              children: <Widget>[
                viewService.buildComponent('menu'),
                viewService.buildComponent(state.moduleName),
              ],
            )
```

**Comment by zjuwjf** [comment]
一切看上去都非常合理。如果有个能运行的demo，也许我能帮助排查下。

从预期看，应该两个效果都发生。

**Comment by jefferybai** [comment]
@zjuwjf 我终于发现一个问题
```
class MenuConnector extends ConnOp<CoursePageState, MenuState> {
  @override
  MenuState get(CoursePageState state) {
    final MenuState menuState = state.menuState ?? MenuState(); //把这行代码改成
    return menuState;
  }

  @override
  void set(CoursePageState state, MenuState substate) {}
}

```
    final MenuState menuState = state.menuState ?? MenuState(); //把这行代码改成
    final MenuState menuState =  MenuState(); //把这行代码改成buidView终于执行了。 莫非每次都只能从这里取值， 而不能更改自己的子reducer状态？

**Comment by zjuwjf** [comment]
😀这就是问题的根源。connector的get表示如何从读取，set表示如何更新。

**Comment by jefferybai** [comment]
那我不能每次都拿到一个初始的MenuState吧？ 
如何做到只更新sub reducer？

**Comment by zjuwjf** [comment]
你要写set。

**Comment by tom1918** [comment]
> class MenuComponent extends Component {
> MenuComponent()
> : super(
> view: buildView,
> reducer: buildReducer(),
> );
> }
> 
> Widget buildView(
> MenuState state,
> Dispatch dispatch,
> ViewService viewService,
> ) {
> int i = -1;
> print('buildView'); print(state.selectedIndex);
> List menus = state.menus.map((item) {
> i ++;
> bool selected = false;
> if(i == state.selectedIndex) { selected = true; }
> return MenuItem(item['icon'],
> item['label'], item['txt'],
> (pageName, index) => dispatch(MenuComponentActionCreator.changePage(pageName, index)),
> i, selected, item['pageName']);
> }
> ).toList(growable:true);
> return Container(
> width: ScreenUtil().setWidth(350),
> height: ScreenUtil().setHeight(536),
> child: Column(
> mainAxisAlignment: MainAxisAlignment.spaceBetween,
> children: menus,
> ),
> );
> }
> 
> Reducer buildReducer() {
> return asReducer(
> <Object, Reducer>{
> MenuComponentAction.changePageName: _selectedIndex
> },
> );
> }
> MenuState _selectedIndex(MenuState state, Action action) {
> print('_selectedIndex');
> print(action.toString());
> return state.clone()..selectedIndex = action.payload['selectedIndex'];
> }
> 
> 现在buildView 会被打印一次， 点击了菜单进行切换_selectedIndex会被打印， 但是buildView不会再被打印了

请问一下你的 ScreenUtil() 应该是一定在MaterialApp的home中的页面设置的
ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);

想问问你的项目是怎么设置才能生效

**Comment by jefferybai** [comment]
@tom1918 在每个page的view里面设置一下
