### ISSUE TITLE
跟 flutter_redux 一样的还是有什么改进吗？

### ISSUE THREAD

**Issue by fengqiangboy** [alibaba/fish-redux#11]
跟 flutter_redux 一样的还是有什么改进吗？

**Comment by zjuwjf** [comment]
不 flutter_redux 的不同之处
1.

**Comment by zjuwjf** [comment]
闲鱼早期试用过flutter_redux框架。flutter_redux 做为flutter 下比较早期的框架，从分层看，它的特点是集中，缺少分治。

但如果需要一个：
1. 集中的状态管理 
2. 分治，可插拔的组件管理 
3. 展示和逻辑解耦
4. 完善的通信能力
5. ListView下更好性能的组件模型

你可以试试fish-redux。
