### ISSUE TITLE
配合 built value 创建 state 合理吗？

### ISSUE THREAD

**Issue by TshineZheng** [alibaba/fish-redux#111]
手动组装 state 的 clone 有点麻烦，都是重复操作。
所以尝试了下 built value，配合 IDE 的 snippet，感觉方便很多，同时也更大限度的保证了 state Immutable，就是感觉 clone 好像有点多余。
这样做，有什么隐患吗？或者说有什么需要注意的？

题外话，我记得公众号提到过 `fish-serializable` ? 有时间计划么，很期待。

**Comment by zjuwjf** [comment]
fish redux 对state的clone的要求是一个最低限度的浅拷贝。 
没用过built value所以不确定是不是会有性能上的下降。

**Comment by TshineZheng** [comment]
> fish redux 对state的clone的要求是一个最低限度的浅拷贝。
> 没用过built value所以不确定是不是会有性能上的下降。

感谢回复。
`built value` 执行拷贝时，如果在未做任何修改，引用的是同一个对象，只在有数据改动时会创建新对象，然后做数据引用，大概是这样（使用 identical 对比后的结论）。
和 clone 唯一的不同是，clone 每次都会创建新对象做浅拷贝，而 built value 只有在数据改变时会创建新对象做浅拷贝。

遗憾的是，刚刚仔细看了下，发现 fish redux 的 Connector set 方法只能对父 state 的引用做数据修改。而 built value 做的对象全部是 Immutable 的……所以这就导致无法通过 set 把子 state 的数据传递给父 state 了。

**Comment by TshineZheng** [comment]
也就是说如果 state 是 Immutable 的话，fish redux connector set 方法就走不通了。
不知道还有其他啥好办法不。

**Comment by hyjfine** [comment]
state Immutable是合理的啊，这样reducer每一次数据操作都返回一个新对象，而不会在原来的数据上作修改，这样才符合reducer无副作用的定义。
fish redux connector set 方法走不通这个结论是怎么得出来的呀？

**Comment by TshineZheng** [comment]
> state Immutable是合理的啊，这样reducer每一次数据操作都返回一个新对象，而不会在原来的数据上作修改，这样才符合reducer无副作用的定义。
> fish redux connector set 方法走不通这个结论是怎么得出来的呀？

```dart
class MsgConnector extends ConnOp<PageState, MessageState> {
  @override
  MessageState get(PageState state) {
    ...
  }

  @override
  void set(PageState state, MessageBarState substate) {
       // 这里 state 如果是 Immutable，就无法将 substate 的数据传递到 state 了。state 没有 set 方法。
  }
}
```

**Comment by hyjfine** [comment]
emmmm，fish redux的state不是immutable，至少example不是，可能这么设计在有些情况下性能会好点吧。但感觉不太对，这个Connector的set的设计意图是方便子state回传父state的话，有点粗暴啊 @zjuwjf

**Comment by zjuwjf** [comment]
非常棒的问题。

1. 首先 connector运行在哪里呢？
[参考](https://github.com/alibaba/fish-redux/blob/master/doc/concept/what's-connector.md)

截取自 src/redux/combine_reducers.dart
```dart
/// Connector<T, P> + Reducer<P> => SubReducer<T>
SubReducer<T> subReducer<T, P>(Connector<T, P> connector, Reducer<P> reducer) {
  return (T state, Action action, bool isStateCopied) {
    final P props = connector.get(state);

    /// It's unnecessary to apply a sub-reducer if the sub-state is null
    if (props == null) {
      return state;
    }

    final P newProps = reducer(props, action);
    final bool hasChanged = newProps != props;
    final T copy = (hasChanged && !isStateCopied) ? _clone<T>(state) : state;
    if (hasChanged) {
      connector.set(copy, newProps);
    }
    return copy;
  };
}
```

所以 connector 是运行在 Reducer 内部的代码， 它是将ReduxJs中combineReducers和语言相关部分上升为语言特性无关的抽象。

2. 如果有一个immutable库， 如何使用到fish-redux中？
大概需要优化下 connector.set 的签名（State, SubState）=> State

目前短期计划内不会引进immutable，但它应该可以做为一个可选项是合适的。
对应的签名体系会考虑优化，用以支持。
欢迎高水平的同学们来PR 👏

**Comment by TshineZheng** [comment]
同期待 PR，暂时增加了个方法先用着。

**Comment by TshineZheng** [comment]
你们觉得增加一个 mixin   的方案怎么样？ @zjuwjf 
# 修改
增加
```dart
mixin Immutable<S, P> on Connector<S,P>{
  @override
  S set(S state, P subState);
}
```
然后在 subReducer 中判断
```dart
SubReducer<T> subReducer<T, P>(Connector<T, P> connector, Reducer<P> reducer) {
  return (T state, Action action, bool isStateCopied) {
    final P props = connector.get(state);
    if (props == null) {
      return state;
    }
    final P newProps = reducer(props, action);
    final bool hasChanged = newProps != props;
    final T copy = (hasChanged && !isStateCopied) ? _clone<T>(state) : state;
    if (hasChanged) {
      if(connector is Immutable<T,P>){
        return connector.set(copy, newProps);
      }
      connector.set(copy, newProps);
    }
    return copy;
  };
}
```
# 使用
```dart
class MsgConnector extends ConnOp<PageState, MessageState> with Immutable{
  @override
  MessageState get(PageState state) {
    ...
  }

  @override
  PageState set(PageState state, MessageState substate) {
    return state.rebuild((b)=>b..msgBarState.msg = substate.msg);
  }
}
```
上一次 PR 考虑到尽量不用类型判断，后来发现源码中也用了一些 is ，那就不差这一个了。
代码已经提交到我的分支中了。

**Comment by zjuwjf** [comment]
1. immutable下 是不用要clone的。
2. 这里用is，说明的还是抽象程度不足以支撑底层的实现，需要改进。

**Comment by TshineZheng** [comment]
多谢指教，精益求精啊。
就要看期望的是“兼容”，还是“支持”了。
Immutable clone 问题到是可以继承一下原来的 Cloneable 做兼容。
在不增加额外太多理解成本的情况下，暂时还未想到更好的方案，等有时间整体好好看看，希望在这之前有合理的 PR 提交，在线等挺急的（开玩笑）。

**Comment by hyjfine** [comment]
这看起来是一个API设计的问题，下班我会试着看看，但我下班挺晚的。。。

**Comment by zjuwjf** [comment]
> 多谢指教，精益求精啊。
> 就要看期望的是“兼容”，还是“支持”了。
> Immutable clone 问题到是可以继承一下原来的 Cloneable 做兼容。
> 在不增加额外太多理解成本以及改动的情况下，暂时还未想到更好的方案，等有时间整体好好看看，希望在这之前有合理的 PR 提交，在线等挺急的（开玩笑）。

目前对immutable的支持，已经在 feature_immutable_state  分支上了。
预期这个改进会尽快合入master

**Comment by TshineZheng** [comment]
好消息！
等下去看看。

**Comment by zjuwjf** [comment]
这里做一下 目前的方案和调整的说明


1. 有社区同学和我交流，是否可以只要如下最小化的改动
```
/// Connector<T, P> + Reducer<P> => SubReducer<T>
SubReducer<T> subReducer<T, P>(Connector<T, P> connector, Reducer<P> reducer) {
  return (T state, Action action, bool isStateCopied) {
    final P props = connector.get(state);

    /// It's unnecessary to apply a sub-reducer if the sub-state is null
    if (props == null) {
      return state;
    }

    final P newProps = reducer(props, action);
    final bool hasChanged = newProps != props;
    final T copy = (hasChanged && !isStateCopied) ? _clone<T>(state) : state;
    if (hasChanged) {
      /// only changes here
      final result = connector.set(copy, newProps);
      if(result != null) {
            return result;
      }
    }
    return copy;
  };
}
```

基于 (State, SubState) => State 是 (State, SubState) => void的的一个协变，只要将返回值为State即能支持immutable-state的特性。

但这个方案有一些缺点是：
- a: 存在多余clone的问题
- b: 签名会有所发散，导致无法合理的约束代码的演进。 比如 返回了一个不合理类型？

2. 目前的方案
    1. 原有的connector的抽象(get&set&clone)是为mutable-state而设计的。
    2. 而immutable-state的connector需要的是（get&set{返回State}）
    3. 所以上升一下它们的抽象， 应该是 get & subreducer。 

```
abstract class MutableConn<T, P> implements AbstractConnector<T, P> {
  const MutableConn();

  void set(T state, P subState);

  @override
  SubReducer<T> subReducer(Reducer<P> reducer) {
    return (T state, Action action, bool isStateCopied) {
      final P props = get(state);
      if (props == null) {
        return state;
      }
      final P newProps = reducer(props, action);
      final bool hasChanged = newProps != props;
      final T copy = (hasChanged && !isStateCopied) ? _clone<T>(state) : state;
      if (hasChanged) {
        set(copy, newProps);
      }
      return copy;
    };
  }
}

abstract class ImmutableConn<T, P> implements AbstractConnector<T, P> {
  const ImmutableConn();

  T set(T state, P subState);

  @override
  SubReducer<T> subReducer(Reducer<P> reducer) {
    return (T state, Action action, bool isStateCopied) {
      final P props = get(state);
      if (props == null) {
        return state;
      }
      final P newProps = reducer(props, action);
      final bool hasChanged = newProps != props;
      if (hasChanged) {
        final T result = set(state, newProps);
        assert(result != null);
        return result;
      }
      return state;
    };
  }
}
```

4. 对上层使用的改动
1. 原先通过 implements Connector, 需要改为 extends Connector
2. 将 Connector 标记为 deprecated

这里其实是一个比较有成本，也纠结的一块，是历史代码的不合理导致的。可以强行兼容， 但是兼容会带来更大的历史负担。

**Comment by TshineZheng** [comment]
* 抽象出 Connector subReducer 除了对支持 Immutable State 之外, 还带来了哪些好处? 
* 如果要采用 Connector 方案, 建议将 普通 `reducer` 逻辑 和 `connector set` 逻辑分开，connector 不应该处理 reducer 的逻辑。

**Comment by zjuwjf** [comment]
> * 抽象出 Connector subReducer 除了对支持 Immutable State 之外, 对以后还带来了哪些好处?
> * 如果要采用 Connector 方案, 建议将 普通 `reducer` 逻辑 和 `connector set` 逻辑分开，connector 不应该处理 reducer 的逻辑。

回到初衷，connector概念的产生，它要解决的问题是 如何将一个 Reducer<P> 变成 Reducer<T> 的标准的一部分。

其中的get&set&clone是对对应实现部分的抽象提取。
注：set = (State, SubState) => void

当我们面临immutable-state的情况下， 原有的
```dart
/// Connector<T, P> + Reducer<P> => SubReducer<T>
SubReducer<T> subReducer<T, P>(Connector<T, P> connector, Reducer<P> reducer) {
 ...
}
```
是一个面向mutable-state的实现， 也无法无损的在这里兼容。

对于immutable-state的情况下，将一个 Reducer<P> 变成 Reducer<T>所需的要素成了get&set*
注：set* = (State, SubState) => State

1. 还能带来哪些好处？
  将对应的实现都放在了component／connector上， redux核心提供最基础的抽象概念即可，层次上这是更合理的。

2. “毕竟 connector 主要场景是 父 state 和 子 state 的变换”。这是面对实现而言的，对实现的部分并无改动。 只是背后有subReducer， 会有不同的机制。

**Comment by TshineZheng** [comment]
基于实现来说的，你的解释也没错。
只是觉得将 connector 里的 reducer 处理剥离，有利于缩小 connector 可能会产生的影响。
如果实在有需要自己对 connector 做处理，不会影响到普通 reducer。
有没有这种需求暂时还未知。

**Comment by hyjfine** [comment]
3.25下班时看到 @zjuwjf 提了一个分支去实现这个特性，当时感觉是提高了复杂度还没有实现我想要的（后来发现是还没有写完）
![WechatIMG23](https://user-images.githubusercontent.com/1013953/55050559-45e83480-508c-11e9-93ce-72b935c55969.png)
上图是我想要的效果，因为我觉得对state的修改默认应该是immutable的，所以回家也尝试提了个[PR](https://github.com/hyjfine/fish-redux/tree/for_immutable)去实现。

沟通后会有两个问题
a: 存在多余clone的问题（这种兼容方式无法避免，set需要copy参数，copy的参数需要set执行的返回决定是否clone，互为依赖了，用mixin可以解决但又是另外的问题了）
b: 签名会有所发散，导致无法合理的约束代码的演进。 比如 返回了一个不合理类型？（这个理论上范型约束和加asset检查可以避免，只是这里的约束确实变弱了）
同时zjuwjf更新了PR，这时再看意图是清晰的，也实现了我的诉求，合理的抽象也不算额外增加复杂度。

我理解connect是一个链接大小state的部件，但真正操作state是reducer，所以这么看AbstractConnector这么抽象是更科学了 @TshineZheng

**Comment by TshineZheng** [comment]
AbstractConnector 比之前合理是肯定的，感谢 @zjuwjf 的辛苦和努力。
@hyjfine 我也认为 connector 主要面向大小 state ，姑且认为我们说的是一个意思。
但目前 Connector 实际上有去处理 reducer 工作
```dart
abstract class ImmutableConn<T, P> implements AbstractConnector<T, P> {
  const ImmutableConn();

  T set(T state, P subState);

  @override
  SubReducer<T> subReducer(Reducer<P> reducer) {
    return (T state, Action action, bool isStateCopied) {
      final P props = get(state);
      if (props == null) {
        return state;
      }
      final P newProps = reducer(props, action);
      final bool hasChanged = newProps != props;
     // 以上是处理 reducer

     // 以下是真正的回到大小state处理。
      if (hasChanged) {
        final T result = set(state, newProps);
        assert(result != null);
        return result;
      }
      return state;
    };
  }
}
```
当然这个问题如 @zjuwjf 所言在实现层是不会有什么影响的。
实际上 Immutable 的问题也已经得到很好的解决，该问题单可以随时关闭。
谢谢！
