### ISSUE TITLE
我希望统计应用所有页面间的跳转时长，应该怎么做，是写一个middleware吗？

### ISSUE THREAD

**Issue by 519818538** [alibaba/fish-redux#115]
比如点击按钮开始计时，跳转下一个页面直到下一个页面build完成作为结束时间，然后把时间差存起来，在某个时刻上报云端。
是可以写一个middleware给page用，还是直接在page的effect里的生命周期函数里打桩？

**Comment by zjuwjf** [comment]
这一块和路由跳转有关。目前还不能由fishredux单独来完成（fishredux目前只能知道page加载完成，而无法知道什么时候开始执行跳转）。

如果有需求的话，可以反馈在 #96 中，我们会计划完成一个roadmap，以此来推动fishredux持续的演进，丰富flutter生态，也欢迎社区的同学加入进来。
