### ISSUE TITLE
有没有关于AOP这块的说明呢?

### ISSUE THREAD

**Issue by ws4349893** [alibaba/fish-redux#116]

**Comment by zjuwjf** [comment]
是指 middleware 还是指 [utils/aop.dart](https://github.com/alibaba/fish-redux/blob/master/lib/src/utils/aop.dart) ?

**Comment by ws4349893** [comment]
middleware 这一块大概了解到了,想了解家aop.dart 这一块做了哪些工作

**Comment by zjuwjf** [comment]
aop.dart 是做了对 dart-function aop 所需的抽象。

1. 面向函数的aop是怎么定义的。
2. 对通用aop应该如何去实现。
3. 内置了一些常用的aop能力。

框架本身和示例代码都并无相关的使用。但是这块代码对上层的支持会起到比较不错的作用。

举个例子， 我们在响应式编程中，常见的防止快速点击的处理：

```dart

void _onClick(Action action, Context<T> ctx) { }

Effect<T> buildEffect() {
  return combineEffects(<Object, Effect<T>>{
    Action.onClick:  AOP([debounce(500)]).withTwo<void,Action,Context<T>>( _onClick),
  });
}

```

**Comment by ws4349893** [comment]
看了一下源码,提供的常用能力,都是在事件之前插入一些处理,可不可以在事件之后增加处理呢?

**Comment by zjuwjf** [comment]
> 看了一下源码,提供的常用能力,都是在事件之前插入一些处理,可不可以在事件之后增加处理呢?
AOP 并不局限于埋入代码是在函数之前还是之后，它提供的是完整的能力，也包括：修改入参，出参。
参考 [performanceAOP][logAOP]

**Comment by hyjfine** [comment]
OOP一样，AOP也是一种编程范式，通过添加切面点，在不改动已有核心逻辑代码的前提下，添加功能或更改代码流程。Spring AOP 了解一下

**Comment by zjuwjf** [comment]
#144 #147
