### ISSUE TITLE
能否在https://pub.dartlang.org/flutter发布啊

### ISSUE THREAD

**Issue by yifan** [alibaba/fish-redux#12]
这样比较容易大家都搜得到，更好使用吧

**Comment by huangjianke** [comment]
+1





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by OPEN-LJW** [comment]
这个小程序是官方的吗

**Comment by yangyxd** [comment]
支持发布到pub

**Comment by huangjianke** [comment]
@OPEN-LJW 是我个人开发的，开源地址：https://github.com/huangjianke/Gitter

**Comment by danieldai** [comment]
是啊，赶紧发布吧，小心fish_redux的名字被占了

**Comment by keluokeda** [comment]
+1

**Comment by zjuwjf** [comment]
不错的建议，我们已经上传上去了。
```
dependencies:
    fish_redux: 0.1.0
```

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/53932386-56803d00-40d4-11e9-8b63-c5c55432884b.png)
可能是还没更新？
@zjuwjf

**Comment by zjuwjf** [comment]
我检查了下，我的环境能work。你要不再试一下？

**Comment by danieldai** [comment]
我这也刚刚能下载了

**Comment by shining228** [comment]
pub中的版本过老了，缺少route模块
