### ISSUE TITLE
整体的路由配置该怎么配置，有例子吗

### ISSUE THREAD

**Issue by GuangmingWu** [alibaba/fish-redux#124]

**Comment by zjuwjf** [comment]
路由目前还不在fish-redux的范畴内，如果你有这方面的期待，可以发表到 #96 

现阶段可以参考 [annotation_route](https://github.com/alibaba-flutter/annotation_route) 或者 [fluro](https://github.com/theyakka/fluro) .

**Comment by GuangmingWu** [comment]
好的，谢谢
