### ISSUE TITLE
使用ListView配合使用Scrollbar,使用Adapter实现的时候会产生滚动条抖动

### ISSUE THREAD

**Issue by layou1989** [alibaba/fish-redux#129]
https://github.com/layou1989/test_fish_redux2.git
例子如上,当滑动页面时，部分item隐藏或显示时会造成滚动条抖动，这种问题如何处理，求指导!!!

**Comment by zjuwjf** [comment]
看上去和框架无的问题，因为demo非常简单，可以先排除框架的部分试试。

**Comment by layou1989** [comment]
是跟框架无关，我在看看

**Comment by GoAheadForever** [comment]
> 

我遇到了相同的问题，请问有解决方法了吗
