### ISSUE TITLE
Component能否支持Middleware?

### ISSUE THREAD

**Issue by diegoeddy** [alibaba/fish-redux#130]
在开发Component过程中，也想使用Middleware来处理内部的耗时操作，例如网络API、与原生的交互等。现在只能把以上操作放到Page的Middleware中，导致Page的State中需要维护大量的Component所需的state。
Middleware作为redux的标准模块，可装载于Store中，并基于Store指定的State完成各种AOP操作。fishi_redux是否也能支持Component级的Middleware？

**Comment by zjuwjf** [comment]
例如网络API、与原生的交互等这些应该放在effect中。
