### ISSUE TITLE
page之间数据如何通讯交互?

### ISSUE THREAD

**Issue by GordonHuangYong** [alibaba/fish-redux#131]
现在有一个数据,需要从page的effect ,  dispatch到另个page的reducer, 如何实现?
我做了些尝试, 感觉少了点什么,所以才无效.
详情如下:
ctx.dispatch(xxActionCreator.xxfunction(xxparam));//无效
ctx.pageBroadcast(xxActionCreator.xxfunction(xxparam));//无效
ctx.appBroadcast(xxActionCreator.xxfunction(xxparam));报错
 

> E/flutter (25936): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:fish_redux/src/redux_component/provider.dart': Failed assertion: line 66 pos 12: 'provider != null': Please check if the AppProvider is mounted.
> E/flutter (25936): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
> E/flutter (25936): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
> E/flutter (25936): #2      AppProvider.appBroadcast (package:fish_redux/src/redux_component/provider.dart:66:12)
> E/flutter (25936): #3      DefaultContext.appBroadcast (package:fish_redux/src/redux_component/context.dart:86:17)
> E/flutter (25936): #4      _viewDidLoad.<anonymous closure> (package:wt_assistant_v2/Pages/ScanDevice/effect.dart:43:11)
> E/flutter (25936): #5      _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (25936): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (25936): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
> E/flutter (25936): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
> E/flutter (25936): #9      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
> E/flutter (25936): #10     Future._complete (dart:async/future_impl.dart:473:7)
> E/flutter (25936): #11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> E/flutter (25936): #12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
> E/flutter (25936): #13     _rootRun (dart:async/zone.dart:1120:38)
> E/flutter (25936): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (25936): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (25936): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (25936): #17     _rootRun (dart:async/zone.dart:1124:13)
> E/flutter (25936): #18     _CustomZone.run (dart:async/zone.dart:1021:19)
> E/flutter (25936): #19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> E/flutter (25936): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> E/flutter (25936): #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> E/flutter (25936): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by zjuwjf** [comment]
目前需要 AppProvider 在最外层的包裹。面向application的需求，fish-redux做的不多。
你可以提在 #96 中表达你的想法，我们会对大家的想法做出一个roadmap，以此推动fish-redux的持续演进。

**Comment by tom1918** [comment]
> 目前需要 AppProvider 在最外层的包裹。面向application的需求，fish-redux做的不多。
> 你可以提在 #96 中表达你的想法，我们会对大家的想法做出一个roadmap，以此推动fish-redux的持续演进。

我现在正如您说的 我试用了 flutter provide 这个组件用来做全局参数功能，但是对于fish-redux 的生命周期而言很不友好，期待你们的roadmap 但是想问问你们计划会在什么时候开源这个功能？

**Comment by hyjfine** [comment]
如果是登录状态这种信息或者你可以试试维护一个全局的store实例

**Comment by tom1918** [comment]
> 如果是登录状态这种信息或者你可以试试维护一个全局的store实例

请教一下如何用  fish-redux 做一个全局的store  以及 使用 effect 和 reducer？

**Comment by GordonHuangYong** [comment]
目前发现可以使用AppProvider实现跨页面传数据.
我介绍一下方法.可能很多人和我一样小白.
至于roadmpa什么的,我暂时不了解, 就不发炎了.
1. 在main.dart中. app那里,最外层包裹.如图示.
2. 发出action, 使用AppProvider.appBroadcast(ctx.context, xxActionCreator.onDoing(param));
3. 在另一个page的effect中, 接收回调.不是在reduce中.在reducer无法接收, 原因不明.
![image](https://user-images.githubusercontent.com/20039800/55207498-61e0f880-51a8-11e9-894a-7c71d469072f.png)

**Comment by hyjfine** [comment]
#90 看看这个[示例](https://github.com/hyjfine/flutter_redux_sample/commit/0c2afeba00987cdb643a3a9a75b14efc41d1eb45)  和 [调用](https://github.com/hyjfine/flutter_redux_sample/commit/0533b5f946f8ed8d1d6b46bc046bc787d9bf4d8d)是不是能满足你的需求

**Comment by zjuwjf** [comment]
> 目前发现可以使用AppProvider实现跨页面传数据.
> 我介绍一下方法.可能很多人和我一样小白.
> 至于roadmpa什么的,我暂时不了解, 就不发炎了.
> 
> 1. 在main.dart中. app那里,最外层包裹.如图示.
> 2. 发出action, 使用AppProvider.appBroadcast(ctx.context, xxActionCreator.onDoing(param));
> 3. 在另一个page的effect中, 接收回调.不是在reduce中.在reducer无法接收, 原因不明.
>    ![image](https://user-images.githubusercontent.com/20039800/55207498-61e0f880-51a8-11e9-894a-7c71d469072f.png)

感谢反馈，已经在master分支上fix。
