### ISSUE TITLE
能否在是用list adapter时，子component的action只发送到相应的子reducer？

### ISSUE THREAD

**Issue by danieldai** [alibaba/fish-redux#134]
能否在是用list adapter时，子component的action只发送到相应的子reducer？比官方示例中的 todo_componnet中的reducer，在一个todo项目上点击了完成，所有的todo state都会受到这个action，然后各个子component的reducer里都要判断被操作的todoState是不是本component的todoState。

```dart
ToDoState _edit(ToDoState state, Action action) {
  final ToDoState toDo = action.payload;
  if (state.uniqueId == toDo.uniqueId) {
    return state.clone()
      ..title = toDo.title
      ..desc = toDo.desc;
  }
  return state;
}

ToDoState _markDone(ToDoState state, Action action) {
  final String uniqueId = action.payload;
  if (state.uniqueId == uniqueId) {
    return state.clone()..isDone = !state.isDone;
  }
  return state;
}
```

这在简单的情况下，还好处理，但是如果 list adapter中的子component 包含下一级component就，这个下一级的component的reducer就会失去独立性，需要祖父component的信息来判断是否要更新本component的state。

**Comment by zjuwjf** [comment]
你是指类似
```
T {
  id,
  subA,
  subB
} 
```
的情况下， reducer<T>还好写， reducer<SubA> 不好写 ？

**Comment by zjuwjf** [comment]
普通的做法是：
```
T {
  id,
  subA,
  subB
} 

SubT {
  id,
  subA
}
```
通过不断的拆分和组合。可以参考 [reselect](https://github.com/reduxjs/reselect)，甚至可以有一层缓存，做到性能的极致。
缺点是有一点点啰嗦。优点是设计和实现上没有黑魔法。

**Comment by danieldai** [comment]
嗯，是的，我是说的这种情况

```
T {
  id,
  subA,
  subB
} 

SubT {
  id,
  subA
}
```
目前我也采用这种方式把id传递到 SubT中。我的问题就是SubA中的action能否只在SubA内部传播，不传播到外部，这样SubA就不需要id信息了。

**Comment by zjuwjf** [comment]
> 我的问题就是SubA中的action能否只在SubA内部传播，不传播到外部，这样SubA就不需要id信息了。

这里有集中和分治的一点点的矛盾。
事实上在fish-redux中，一个页面的Reducer几乎是在编译的期间（通过dependencies的配置）就可以确定的，而非它的运行期间，所以它并不和具体的component的创建与否相关。这一点和ReduxJS 是相似的。

当然也必须承认的一点是，这带来了一定程度上的分治的不彻底，就像你上面给出的很好的例子。

目前能想到的方案
1. 做一个类似 reselect 的connector， 目前就能解决这个问题。
2. 对component做一次mixin， 比如设计一个 ReducerBoundary，来达到在reducer上的彻底的分治。

**Comment by zjuwjf** [comment]
#111

**Comment by hyjfine** [comment]
可能不太行，因为fish redux是一个page一个store，dispatch范围和reducer关系在store创建是确定了。 @danieldai 你描述的这个问题能提供个最小实例demo，具体问题具体看下嘛？

**Comment by danieldai** [comment]
@hyjfine 我找时间做个demo

**Comment by zjuwjf** [comment]
刚刚有个想法是，直接使用substate做为key呢？

enum PrivateAction { ByRef }

Action createPrivateAction<T>(T state, Action action) {
  return Action(PrivateAction.ByRef,
      payload: Tuple2<Object, Action>(state, action));
}

Reducer<T> privateReducer<T>(Reducer<T> reducer) {
  return (T state, Action action) {
    if (action.type == PrivateAction.ByRef) {
      final Tuple2<Object, Action> tuple2 = action.payload;
      if (tuple2.i0 == state) {
        return reducer(state, tuple2.i1);
      }
    }
    return state;
  };
}

void onInit<T>(Action _, Context<T> ctx) {
  final Action action = ...;
  ctx.dispatch(createPrivateAction<T>(ctx.state, action));
}

**Comment by TshineZheng** [comment]
正好也发现这个问题。
@zjuwjf 用 state 做 key 感觉好像有点不妥？state 会变的。
比如异步 effect 的情况，如果异步时，其他 action 改变了 component 的 state。在 effect 中的异步执行完毕后再次发送的 action 还能正确执行吗？

**Comment by zjuwjf** [comment]
@TshineZheng 在context中拿到的state永远是最新的，所以在实际使用过程中，并无问题。

**Comment by TshineZheng** [comment]
> @TshineZheng 在context中拿到的state永远是最新的，所以在实际使用过程中，并无问题。

原来是这样，谢谢回复。

**Comment by TshineZheng** [comment]
component 复用也会碰到这个问题，要所有 action 都带上 id，reducer 再做判断……
虽然可以解决，但感觉挺不方便的，希望早日确定方案。

**Comment by zjuwjf** [comment]
#139 

添加了一个 PrivateReducerMixin 

示例：
```
ComponentA extends Component<A> with PrivateReducerMixin<A> {
  ///...
}
```

经过这个mixin处理后，自身的reducer只接受自身发出的action。

@danieldai @TshineZheng enjoy ～

**Comment by danieldai** [comment]
@zjuwjf 棒棒的， 这样component的复用性会大大提高

**Comment by johnhollon** [comment]
还得加上PrivateReducerMixin？
只要是正常人思维而且精神状况是正常的（没精神病的），都认为组件应该默认就是自己dispatch自己的action，与其他的组件无关。到底是出于什么想法，才能做出一个组件对象发布事件，此类组件所有对象全部发布同样事件，而且携带相同的payload，这到底是什么“神逻辑”？

**Comment by zjuwjf** [comment]
> 只要是正常人思维而且精神状况是正常的（没精神病的），都认为组件应该默认就是自己dispatch自己的action，与其他的组件无关。到底是出于什么想法，才能做出一个组件对象发布事件，此类组件所有对象全部发布同样事件，而且携带相同的payload，这到底是什么“神逻辑”？

没有“神逻辑”，这是从顶层设计和现实场景综合考虑下的结果。

Redux 能成为状态管理领域中的绝对的领先者，是和它的三原则密不可分的。其中最重要的一条原则： 单一数据源。如果能真正理解这一点，你大概能明白我们这些“精神病”人在讨论什么问题了。

如果是基于多store，隔离同类型的组件之间的Reducer影响一件非常轻松的事。
但是fish-redux是选择了一条既要集中又要分治的充满挑战的路线，我们享受集中所带来的巨大的好处，也会承受一些分治上的损失。

对于同类型的组件之间的Reducer影响是有一点点的瑕疵，但它一方面不是普遍的，一方面上层也是易解。在我们内部的场景中，在一个列表中，有大量同类型的component， 一般往往都是dumb-component。

而通过上面的通用型的mixin，对同类型的组件之间的Reducer影响的问题，基本算是一个终极解法。但是它依然不会被放入到logic内部的默认实现，而选择以mixin的形态存在。它有“副作用”，它会一定程度的让reducer函数变得狡猾而难以预测。

这是我目前的认识。

**Comment by TshineZheng** [comment]
@zjuwjf PrivateReducerMixin  后，子 Component 都会收不到 action，这算使用限制吗？
看 fish-redux 代码时，偶然发现，验证了下好像还真是这样。

**Comment by zjuwjf** [comment]
> @zjuwjf PrivateReducerMixin 后，子 Component 都会收不到 action，这算使用限制吗？
> 看 fish-redux 代码时，偶然发现，验证了下好像还真是这样。

可否有个demo？和我的预期不一样。 当然也说明了目前测试用例的不足，后面也会补充完整。

**Comment by johnhollon** [comment]
> Redux 能成为状态管理领域中的绝对的领先者，是和它的三原则密不可分的。其中最重要的一条原则： 单一数据源。如果能真正理解这一点，你大概能明白我们这些“精神病”人在讨论什么问题了。
> 
即便同一个Store，也不应该意味着一个组件对象抛出一个事件会被其他同类组件对象同时抛出。如果非得说这个问题是由于单一数据源，那我的确很难理解。

这明显就是错误的设计！
