### ISSUE TITLE
该怎么配合路由使用？

### ISSUE THREAD

**Issue by log225** [alibaba/fish-redux#137]
初学者，有错误请指教。
 fluro 这个路由要传个widget作为参数，
但是这个fish-redux 好像只能用buildPage来创建一个widget，而且也获取不到page当中的store。如果我下一个page也要用当前page中的store（共享store），那岂不是没啥好用的办法了？
用component的话也可以buildcomponent 来获取一个widget，这个时候也要传入store，同上面说的，获取不到第一个page的store，那不是只能新建一个store了？
这种时候应该怎么搞啊？

**Comment by zjuwjf** [comment]
你是要一个基于app级别的store，而非基于page级别的？#96

**Comment by log225** [comment]
哦，我定义了一个global的store
```
class StoreUtil {
  static PageStore<HomeState> _globalStore;
  static PageStore<HomeState> get globalStore {
    if (_globalStore == null) {
      _globalStore = createPageStore<HomeState>(initRootState({}), buildReducer());
    }
    return _globalStore;
  }
}
```
然后HomeComponent里面也写了dependencies, 这个时候我再路由里面要定义一个新的component作为路由（是home的dependency），那么现在应该是buildComponent产生一个widget,传入的第一个参数应该是个store<T>，我现在要手动调用ConnOp的某个方法转换一下state吗？还是说有什么方法可以自动转换？

**Comment by yuwenhuisama** [comment]
需要一个跨Page的Store，比如音乐播放器有PlayController({Play, Pause, Stop,}之类的状态)，先把PlayController作为Component放到MainPage中，但是需要用Navigator跳转到PlayListPage去同时保持PlayController的状态，这样一来想要在新的Page中同样使用MainPage中的store就很困难。

**Comment by log225** [comment]
主要是跨配置的store 不知道应该怎么写在代码里面啊。感觉这个框架封装的page 看不到store，也无法修改或者替换store（只看到了createStore的方法），怎么把上面那种global的store替换到page或者component中去呢，让他们共同使用一个store？

**Comment by hyjfine** [comment]
fish redux专注的是page级别的store，application级别的store暂时还没内置支持。请问你是开发船新版本的app吗？

**Comment by zjuwjf** [comment]
所以我了解到，实际的场景是部分页面是共享一个store， 部分页面是独立store。
于是 Page 应该有一个能够接收store为参数的buildPage函数？

**Comment by log225** [comment]
@zjuwjf 是啊，这个后面的版本有支持的计划吗？

**Comment by zjuwjf** [comment]
可以关注下 #153 是同一个问题

**Comment by DDDrop** [comment]
@log225 #60 使用的 annotation_route，可能会有些帮助。
