### ISSUE TITLE
当一个页面多次使用一个组件，在一个组件对象中dispatch action，则所有同类型组件都会dispatch action

### ISSUE THREAD

**Issue by johnhollon** [alibaba/fish-redux#143]
这是框架的BUG，还是本来就是这样设计的？

**Comment by zjuwjf** [comment]
设计如此。 这对较少接触过redux的同学来说可能会有一些奇怪。

总的来说就是集中和分治的矛盾性，当我们享受集中所带来的巨大的好处，也会带来一些分治上的一些损失。同时分治上的问题也并非是不能解的问题。

Duplicate of #134
