### ISSUE TITLE
能否对State中的final属性提供更好的支持

### ISSUE THREAD

**Issue by johnhollon** [alibaba/fish-redux#149]
如某个state
```
class ExampleState implements Cloneable<ExampleState> {
  final bool editable;
  final Color color;
  final String id;
  String value;
  ExampleState({this.editable, this.color, this.id})
      : assert(editable != null),
        assert(color!= null),
        assert(id!= null);
  @override
  ExampleState clone() {
    return ExampleState (
      editable: editable,
      color: color,
      id: id,
    )
      ..value= value;
  }
}
```

对于上面这个State，要正常使用，必须在page的initstate或component的connector中做出特殊写法，例如：

对于Page的initstate
```
ExampleState Function(Map<String, dynamic>) initState(bool editable, Color color, String id) {
  return (parms) => ExampleState ( editable: editable,
      color: color,
      id: id,
  );
}
```

Page的构造函数：

```
class ExamplePage extends Page<ExampleState, Map<String, dynamic>> {
final bool editable;
final Color color;
final String id;
ExamplePage({this.editable, this.color, this.id})
      : super(
          initState: initState(editable, color, id),
...// 后面的代码省略
```

若这个State用于Component，则需要在Connector中进行类似的特殊处理，如：

```
class ExampleConnector extends ConnOp<ParentState, ExampleState> {
  final bool editable;
  final Color color;
  final String id;
  ExampleConnector({this.editable, this.color, this.id});
  @override
  ExampleState get(ParentState state) {
    return ExampleState (
      editable: editable,
      color: color,
      id: id,
    )..value=state.ExampleValue;
  }

  @override
  void set(ParentState state, ExampleState subState) {}
```

然后在使用此组件的page中：

```
class ParentPage extends Page<ParentState, Map<String, dynamic>> {
  final bool editable;
  final String id;
  ParentPage ({this.editable = false, this.id})
      : super(
        // ... 省略代码
          dependencies: Dependencies<ParentState>(slots: <String, Dependent<ParentState>>{
            "exampleComponent": ExampleConnector(editable: editable, color: _colorsMap['ExampleTypeId'], id: 'ExampleTypeId') + ExampleComponent(),
          }),
         // ... 省略代码
        );
}

```

其实可以看得出来，State中的final属性应该来自于组件，如果能够让Component也具有initState方法，而且在initState函数中传入Component对象，就能够方面的为State中的final属性赋值了，也就不需要在initstate、组件构造函数、connector里面出现像变魔术一样变着花儿似的垃圾代码了。

这是否有必要呢？

**Comment by hyjfine** [comment]
首先，state是否加final取决于你怎么用，框架是支持immutable的，我自己也倾向于这么用。
然后，示例代码是mutable写法，vuex也支持这么写，特点是方便
其次，page本来就继承于component, initstate应该是种设计意图，页面需要，而子组件的数据来源于页面，这样比较方便数据驱动，是redux数据集中的体现。

**Comment by hyjfine** [comment]
mutable 写法在有些场景下是有性能优势的，毕竟少对象生成，react的redux提倡是immutable 带来数据可视操作可回溯的好处

**Comment by johnhollon** [comment]
这里讲的是部分属性是final的，部分不是final的。

**Comment by hyjfine** [comment]
你都写成final的啊，会有问题吗？大概写成这样：
![image](https://user-images.githubusercontent.com/1013953/55300360-a64eeb80-5469-11e9-9abb-e4dd7c008fb5.png)

**Comment by johnhollon** [comment]
不会有问题。
但没必要，而且对于集合类型没啥用。

**Comment by zjuwjf** [comment]
1. state里定义final或者非final字段是上层的自由选择。

2. page，component，及 connector里不要定义具体业务字段。它们是配置或者一种抽象关系。

如果你能遵循 第2点，你就不会发生上面这样的特殊写法。

**Comment by johnhollon** [comment]
比如说要展示一个企业的信息页，需要向这个页面传入企业的ID吧？
Flutter技术比较新，有些程序员可能会忘记传参，或者一些重要参数无法被完整全部传入。
如果在使用组件或页面的时候，构造方法就要求必须传入参数，这些程序员就忘不掉应该传入的参数了。
就如同要展示企业信息页，构造这个Page的时候就不需传入企业的ID。
这些参数都是final的。

**Comment by zjuwjf** [comment]
所以这个诉求和state里有没有final字段无关？我也不好理解为什么state里有final字段，就要把final字段表达在page，component，及 connector里面。

那么这个诉求是如何避免传参遗漏？

**Comment by johnhollon** [comment]
这些final字段本身就是“死值”，是这个页面或组件本身就应该具有的“特性”，使用这个页面或组件，就必需提供这些值，这些值在这个页面或组件的整个生命周期中都不会发生任何改变。即便放到page或component里面，会导致语义、程序逻辑或其他什么问题吗？
而且，的确解决了传参的问题，通过框架降低了技术难度，规范了页面和组件的使用方式。
我知道状态存储数据，页面和组件只负责组织各个组成部分，但对于这些页面或组件本身就应该具备的、整个生命周期都不会变的值，为啥就不能直接通过页面和组件赋给状态呢？

**Comment by johnhollon** [comment]
我建议，将State这个语义进行一个更科学的划分。划分为可变的状态及组件属性2部分。
可变的状态当然是immutable、mutable都行，毕竟状态一变，或者是状态的属性值变，或者是整个状态对象都变了（或者干脆都统一为对象变了）。
组件属性是只读的，整个生命周期不可变，值来自组件的构造方法。但是，要知道，这些组件属性，仍然影响view effect reducer的实现逻辑，所以应该是可访问的。

**Comment by zjuwjf** [comment]
数据就应该集中表达中一个地方，而不是随地都是。 对违背Redux基础原则的建议，是不被接纳的。

上面的例子中， 通过常规的做法，显然比上面的变着花样的做法合理。 同时这个问题和本身state里是否有final字段无关。

至于避免传参遗漏问题， 建议添加一些 required和校验，就能避免。

**Comment by zjuwjf** [comment]
然后这里面我也发现了， 在一些概念和思维习惯上的差异，导致习惯了OOP和不了解Redux的同学的一些误解和常见的不合理的做法。

感觉本质上还是doc，example的问题。

**Comment by johnhollon** [comment]
请问，你能不能试试，如果在State里面有final字段，除了上面变着花样的写法外，是否有所谓的“正规”写法？这几个final属性怎么赋初始值？

**Comment by zjuwjf** [comment]
1. 你是通过构造函数 page<T>, component<K> 完成final字段的传递
2. 设计是通过 connector <T, K> 完成数据传递

2的方法是预期的“正规”写法。 同时2的方法并不限定字段是final还是非final。你可以试下2的路径，如果有遇到困难可以继续给我们issue。
