### ISSUE TITLE
能否在dependencies中添加对同类组件数组的支持

### ISSUE THREAD

**Issue by johnhollon** [alibaba/fish-redux#150]
举个例子，在实际业务开发中会遇到这种情况：

1. 一个页面有拥有多个同类数据驱动的组件，比如在展示一家企业信息的时候，需要展示这个企业的股东信息，这些股东信息并不是按照ListView的方式展示的，进行了大量定制化，或者根本就无法在页面中进行连续展示，每个股东信息区块之间有其他信息区块间隔。

2. 展示这家企业，要展示这家企业的4类相关档案，每类档案有多个版本，每个版本有多类档案页，每类档案页有多张照片或文档。

目前，dependencies对以上两种业务没有很好的支持？

对于第一种情况，似乎只能通过StatelessWidget，然后向此widget传入state, dispatch, viewService才能实现。
对于第二种情况，只能在dependencies中写死要在界面中出现几套档案（数据库中可以通过字段值控制是否显示某类档案，但app是写死的，一旦需求变更，需要增加或减少显示档案类别，那么就必须修改app代码）。

**Comment by zjuwjf** [comment]
在你的case中，无论是1，还是2，都非常适合使用 StaticFlowAdapter

1. StaticFlowAdapter下面的component或者adapter可以高度定制化。
 - 非常不建议向 widget传入state, dispatch, viewService。 如果你需要这么做，一个view的表达函数也一定能更加简便的完成。

2. StaticFlowAdapter下面的component或者adapter显示与否可以灵活控制。

**Comment by hyjfine** [comment]
遇到这种情况第一反应是找pm和ux动之以情，晓之以理。不行的话，我会具体问题具体分析，这个问题我可能也会用dependenies去写，毕竟是同类型还定制，那给每个类型写个component，用mixin复用点代码，也是能接受的。需求改了，App重新上个架，但你这企业档案也不会经常变，对吧。

**Comment by johnhollon** [comment]
我能在
super(adapter: StaticFlowAdapter<ItemBodyState>(slots: <Dependent<SomeState>>[]))
里面循环股东信息吗？
那后判断如果是大股东，则在股东信息后面增加一个关联企业信息块以及个人基本信息区块，如果不是大股东，则在股东信息后面只增加一个个人基本信息区块。
另外，结合我之前我提到的final属性的问题，这里需要一个企业ID，这个企业ID应该是final属性，如何优雅的放到state里面？

**Comment by zjuwjf** [comment]
> 我能在
> super(adapter: StaticFlowAdapter(slots: <Dependent>[]))
> 里面循环股东信息吗？
> 那后判断如果是大股东，则在股东信息后面增加一个关联企业信息块以及个人基本信息区块，如果不是大股东，则在股东信息后面只增加一个个人基本信息区块。
> 另外，结合我之前我提到的final属性的问题，这里需要一个企业ID，这个企业ID应该是final属性，如何优雅的放到state里面？

如果你能做好对业务展示逻辑的抽象，它一定就是几个adapter或者component的组合关系。

以你的例子说明， 你可以在StaticFlowAdapter下配置一个大股东信息的sub-adapter，以及小股东信息的adapter，仅此而已。

**Comment by johnhollon** [comment]
> 可以在StaticFlowAdapter下配置一个大股东信息的adapter，以及小股东信息的adapter。
我怎么在小股东组件中的
super(adapter: StaticFlowAdapter(slots: <Dependent>[]))
内部，循环出所有小股东？

**Comment by zjuwjf** [comment]
> 我怎么在小股东组件中的
> super(adapter: StaticFlowAdapter(slots: []))
> 内部，循环出所有小股东？

根据你为小股东adapter定义的数据T

**Comment by johnhollon** [comment]
···
super(adapter: StaticFlowAdapter(slots: [
  小股东List.foreach((){
    // 这样写吗？
  })
]))
···

**Comment by zjuwjf** [comment]
```dart
class MinorityShareholder extends CustomAdapter<T> {

}

class MajorShareholder extends CustomAdapter<T> {

}


super(adapter: StaticFlowAdapter(slots: [
  ConnOps1 + MinorityShareholder(),
  ConnOps2 + MajorShareholder(),
]))
```
