### ISSUE TITLE
关于effect和reducer实践流的疑问

### ISSUE THREAD

**Issue by mikiXuan** [alibaba/fish-redux#151]
新手求教：
例子如下：
条件
     1、page发起一个action 
     2、所有effect内注册事件均反馈void 
     3、所有effect和reducer注册统一action
情况
     情况一：在page和component的effect及reducer内均注册。则只执行page的effect；
     情况二：在page内注册reducer；在component内注册effect和reducer；则执行所有的注册
     情况三：在page和component内注册reducer；则执行所有注册
请问从这个情况是否是代码例子写错了？还是理应这个情况？
从文档上描述

> 如果它的返回值是一个非空值，则代表自己优先处理，不再做下一步的动作；否则广播给其他组件的 Effect 部分，同时发送给 Reducer。
>
情况一应该会通知所有注册，如果effect会拦截action，则情况二应该不会执行component内的reducer

**Comment by zjuwjf** [comment]
设计如此。也符合文档的描述。

事实上，框架层面，组件看到的是一个Effect函数，而不是注册的某一个分支函数。
某一个分支函数的返回值并无意义，参考下面的真实的Effect函数是怎么产生的
```dart
Effect<T> combineEffects<T>(Map<Object, SubEffect<T>> map) =>
    (map == null || map.isEmpty)
        ? null
        : (Action action, Context<T> ctx) {
            final SubEffect<T> subEffect = map[action.type];
            return subEffect?.call(action, ctx) ?? subEffect != null;
          };
```
