### ISSUE TITLE
如何等待在reducer执行之后, 再执行下一步.

### ISSUE THREAD

**Issue by GordonHuangYong** [alibaba/fish-redux#164]
在effect.dart中.  接收文字输入

> void _onInput(Action action, Context<InputState> ctx) {
>   InputState state = action.payload;
>   String text = state.inputTextController.text;
>   if (text == null || text.trim().length == 0) {
>     return;
>   }
>   //增加一行, 需要在reducer执行完成后,再执行滚到最后一行,否则永远差一行.
>   ctx.dispatch(CVSActionCreator.addAction((text)));
> 
>   // ToDo: 由于视图未刷新, 马上滑动到最后, 就导致永远还差一行显示不了.
>   ScrollController _scrollController = PrimaryScrollController.of(ctx.context);
>   if (_scrollController == null) {
>     return;
>   }
>   _scrollController.animateTo(_scrollController.position.maxScrollExtent,
>       duration: const Duration(milliseconds: 500), curve: Curves.easeOut);
> }

**Comment by zjuwjf** [comment]
1. reducer是同步函数，所以立即执行完成的，不存在延迟。

2. fish-redux 对视图的刷新做了优化，在reducer完成后，会根据当前的flutter的schedule-binding状态判断是立即做setstate还是postframe里做。所以我们再也不会有setstate的异常或失败。

3. 即使做了setstate，也仅仅是做了一个脏标记，并不是立即刷新。

4. 对你的case的建议是执行完reducer后 await下，或者postframe。

**Comment by zjuwjf** [comment]
补充下，

final a = ctx.state
ctx.dispatch(reducer-action)
final b = ctx.state

经过一个reducer处理后，a,b是两个不同的对象。

**Comment by GordonHuangYong** [comment]
> 1. reducer是同步函数，所以立即执行完成的，不存在延迟。
> 2. fish-redux 对视图的刷新做了优化，在reducer完成后，会根据当前的flutter的schedule-binding状态判断是立即做setstate还是postframe里做。所以我们再也不会有setstate的异常或失败。
> 3. 即使做了setstate，也仅仅是做了一个脏标记，并不是立即刷新。
> 4. 对你的case的建议是执行完reducer后 await下，或者postframe。

新手小白再请教一下, 这个时候如何await(其实postframe也不懂)? 难道是delay一下?

**Comment by zjuwjf** [comment]
😅 你可以把effect变成async函数，然后如何await 一段时间，你可以百度下。

**Comment by zsmjhtn** [comment]
> * fish-redux 对视图的刷新做了优化，在reducer完成后，会根据当前的flutter的schedule-binding状态判断是立即做setstate还是postframe里做。所以我们再也不会有setstate的异常或失败。
> * 即使做了setstate，也仅仅是做了一个脏标记，并不是立即刷新。

看代码，当触发PageStore的_batchedNotify后，Page的_ViewUpdater的onNotify 里做了对setState(() {})的try catch。
<img width="575" alt="image" src="https://user-images.githubusercontent.com/18029210/55461676-9aa92380-5627-11e9-8523-2b5475123e71.png">
请问这里是担心setState(() {})会出什么错？或者按照上面的说法，优化了setState的时机后，再也不会有setstate的异常或失败了，那这里的try catch是不是也不需要了？

**Comment by zjuwjf** [comment]
> > * fish-redux 对视图的刷新做了优化，在reducer完成后，会根据当前的flutter的schedule-binding状态判断是立即做setstate还是postframe里做。所以我们再也不会有setstate的异常或失败。
> > * 即使做了setstate，也仅仅是做了一个脏标记，并不是立即刷新。
> 
> 看代码，当触发PageStore的_batchedNotify后，Page的_ViewUpdater的onNotify 里做了对setState(() {})的try catch。
> <img alt="image" width="575" src="https://user-images.githubusercontent.com/18029210/55461676-9aa92380-5627-11e9-8523-2b5475123e71.png">
> 请问这里是担心setState(() {})会出什么错？或者按照上面的说法，优化了setState的时机后，再也不会有setstate的异常或失败了，那这里的try catch是不是也不需要了？

对，是这样的，理论上不会发生 FlutterError。

**Comment by guodf** [comment]
effect终于支持异步了，等了好久

**Comment by zjuwjf** [comment]
> effect终于支持异步了，等了好久


> effect终于支持异步了，等了好久

一直支持，可能没有在example里体现出来。

**Comment by GordonHuangYong** [comment]
> 😅 你可以把effect变成async函数，然后如何await 一段时间，你可以百度下。

不是这个意思. 我是不知道应该await什么方法/属性, 才能达到这种效果.
我是要在listview添加数据完成后, 再滚动到最后一行.

**Comment by guodf** [comment]
> > effect终于支持异步了，等了好久
> 
> 一直支持，可能没有在example里体现出来。
> 
> 这也是为什么在Effect中的签名是 (Action, Contetx) => dynamic 不是 (Action, T, Contetx) => dynamic
> 
> 因为在一个异步函数中，state是可能会发生变化的，所以应该通过ctx.state的形式获得最新的state.

```dart
Effect<TestState> buildEffect() {
  return combineEffects(<Object, Effect<TestState>>{
    Lifecycle.initState: _init,
  });
}

Future _init(Action action, Context<TestState> ctx) async{}
```
以前这么会提示语法错误，现在可以这么写了

**Comment by guodf** [comment]
> > 😅 你可以把effect变成async函数，然后如何await 一段时间，你可以百度下。
> 
> 不是这个意思. 我是不知道应该await什么方法/属性, 才能达到这种效果.
> 我是要在listview添加数据完成后, 再滚动到最后一行.

你这种估计做不到，已经超出了fish-redux得功能得范围
你可以定义一个callback当ListView.builder的最后一个item对应的widget的mounted为true时调用callback，在这个callback中执行滚动

**Comment by mengxin1995** [comment]
> > 😅 你可以把effect变成async函数，然后如何await 一段时间，你可以百度下。
> 
> 不是这个意思. 我是不知道应该await什么方法/属性, 才能达到这种效果.
> 我是要在listview添加数据完成后, 再滚动到最后一行.

所以最后你是怎么解决的呢

**Comment by guodf** [comment]
ScrollController _scrollController=ScrollController();

  _scrollToEnd() {
    Future.delayed(Duration(milliseconds: 100), () {
      _scrollController.animateTo(_scrollController.position.maxScrollExtent,
          curve: Curves.easeOutExpo, duration: Duration(milliseconds: 1000));
    });
  }

 @override
  Widget build(BuildContext context) {
    _scrollToEnd();
    return ListView.builder(
            controller: _scrollController,
    );
}

**Comment by guodf** [comment]
> > > 😅 你可以把effect变成async函数，然后如何await 一段时间，你可以百度下。
> > 
> > 
> > 不是这个意思. 我是不知道应该await什么方法/属性, 才能达到这种效果.
> > 我是要在listview添加数据完成后, 再滚动到最后一行.
> 
> 所以最后你是怎么解决的呢

ScrollController _scrollController=ScrollController();

_scrollToEnd() {
Future.delayed(Duration(milliseconds: 100), () {
_scrollController.animateTo(_scrollController.position.maxScrollExtent,
curve: Curves.easeOutExpo, duration: Duration(milliseconds: 1000));
});
}

@override
Widget build(BuildContext context) {
_scrollToEnd();
return ListView.builder(
controller: _scrollController,
);
}
