### ISSUE TITLE
Lifecycle的生命周期的hot-reload问题

### ISSUE THREAD

**Issue by hanmingkang** [alibaba/fish-redux#166]
widget的生命周期转移到Lifecycle中，发现没有reassemble周期方法，请问如何在开发时，触发reassemble方法

**Comment by zjuwjf** [comment]
目前确实没有，不过可以将它以action的形式发出来。欢迎PR 👏

**Comment by hanmingkang** [comment]
1.lib/src/redux_component/lifecycle.dart中添加如下代码
![1554343082(1)](https://user-images.githubusercontent.com/19572365/55524586-70f00b00-56c0-11e9-947b-5f022f74fc18.png)
![1554343102(1)](https://user-images.githubusercontent.com/19572365/55524587-72213800-56c0-11e9-80d4-2b5085cfed34.png)
2.lib/src/redux_component/component.dart中添加action触发
![1554343318(1)](https://user-images.githubusercontent.com/19572365/55524680-b7456a00-56c0-11e9-8cda-50d9e8228ef6.png)
3.在代码中使用如下：
![1554343382(1)](https://user-images.githubusercontent.com/19572365/55524734-e5c34500-56c0-11e9-8454-0b509e58ca83.png)
![1554343434(1)](https://user-images.githubusercontent.com/19572365/55524750-f8d61500-56c0-11e9-8de5-3da8b251ab35.png)
待续：追踪initState方法到recycle_context.dart目录，暂不清楚这个文件的作用，可能存在后续问题，待开发深入后持续研究= =

**Comment by zjuwjf** [comment]
#170
