### ISSUE TITLE
求助0-0

### ISSUE THREAD

**Issue by zhangruiyu** [alibaba/fish-redux#167]
0-0大佬,你好! 有个不是fish_redux的问题,我想了解下咸鱼动态化方面的,但是找不到什么路径,我详细看了2篇关于这个的文章,目前遇到问题:1,final String name = ASTUtils.getNodeString(namedExp.name);
if (name == 'children') {
continue;
}时为children为什么要跳过去呢,第一篇文章说widget 的children 放在list里面,但是并没有看到这样的步骤啊.如果可以想看下ASTUtils代码具体片段.
2,FunctionExpressionParser.parse(namedExp.expression)能否详细让看下呢,不太清楚这个步骤是把方法解析成什么返回回来,解析出的方法返回值,在客户端怎么用呢
3,交互事件怎么做动态化？这部分感觉很难懂的!
感觉自己好菜0-0,只能求助了!实在找不到方向0-0,能帮助下吗,感谢!

**Comment by njiang1987** [comment]
首先感谢对于Flutter动态化方案的关注，这个方案还在完善中，期待与大家多多沟通。


#1. 关于children跳过的问题
第2篇文章里面只截取了AST解析ArgumentList的片段，这块代码的功能是将ASTNode转换成ConstrutorNode，大体逻辑如下：

void visitAstNodeEntity(AstNode astNode, int treeDeepLevel, ConstructorNode currentNode){
	
	if (astNode is InstanceCreationExpression) {
		创建child ConstructorNode

		if(当前解析的label == 'children'){
			就把child ConstructorNode添加到树结构里面
		}
		else {
			....
		}
	}
	else if(astNode is ArugmentList){
		解析ArugmentList结构
	}

	// 遍历astNode.childEntities
	for(SyntacticEntity syntacticEntity in childEntities){
		....
	}

}

解析children的逻辑其实在解析InstanceCreationExpression的时候就做掉了，所以在ArgumentList就跳过了。不过这块是历史遗留的逻辑，正常逻辑应该是再递归遍历children，后续我们会考虑优化这块逻辑。

ASTUtils代码只是做了String的解析，比如在获取StringLiteral会带有":"、"'"、"\""，只是做了裁剪。

#2. 关于FunctionParser
可以参考下Flutter Framework里面的MethodInvocation，它主要由3部分组成：target、methodName和argumentList。这块的逻辑，就是将这些数据解析出来，
例如：openURL(data.hints[0].href, data.hints[0].paras];
会解析成为
{
    "actionName": "openURL",
    "argumentsList": ["data.hints[0].href", "data.hints[0].params"]
}

这块逻辑写的相对来说比较简单，可以再继续扩展。
具体怎么用可以参考#3。

#3. 关于交互逻辑

简单来说，就是在创建widget的时候，先把处理事件埋好，然后在这里面动态的查找要处理的事件，事件其实就是#2中的字符串`actionName`。
拿#2中的例子，端侧就需要先预埋`openURL`的函数，
当点击的时候，取出处理函数，暂且叫`OpenURLImpl`。
接下来就是怎么处理传参，需要先根据路径，从data里面取出参数，然后以list的形式传给处理的函数。上面的例子有2个参数：`data.hints[0].href`, `data.hints[0].params`；第一个类型是String，第二个类型是map，那么参数列表如下：
[
	String,
	Map<String, dynamic>
]
拿到上面的结构，再塞给`OpenURLImpl`就可以了。

**Comment by njiang1987** [comment]
> 0-0大佬,你好! 有个不是fish_redux的问题,我想了解下咸鱼动态化方面的,但是找不到什么路径,我详细看了2篇关于这个的文章,目前遇到问题:1,final String name = ASTUtils.getNodeString(namedExp.name);
> if (name == 'children') {
> continue;
> }时为children为什么要跳过去呢,第一篇文章说widget 的children 放在list里面,但是并没有看到这样的步骤啊.如果可以想看下ASTUtils代码具体片段.
> 2,FunctionExpressionParser.parse(namedExp.expression)能否详细让看下呢,不太清楚这个步骤是把方法解析成什么返回回来,解析出的方法返回值,在客户端怎么用呢
> 3,交互事件怎么做动态化？这部分感觉很难懂的!
> 感觉自己好菜0-0,只能求助了!实在找不到方向0-0,能帮助下吗,感谢!

------------------------------------------------------------
首先感谢对于Flutter动态化方案的关注，这个方案还在完善中，期待与大家多多沟通。


#1. 关于children跳过的问题
第2篇文章里面只截取了AST解析ArgumentList的片段，这块代码的功能是将ASTNode转换成ConstrutorNode，大体逻辑如下：

void visitAstNodeEntity(AstNode astNode, int treeDeepLevel, ConstructorNode currentNode){
	
	if (astNode is InstanceCreationExpression) {
		创建child ConstructorNode

		if(当前解析的label == 'children'){
			就把child ConstructorNode添加到树结构里面
		}
		else {
			....
		}
	}
	else if(astNode is ArugmentList){
		解析ArugmentList结构
	}

	// 遍历astNode.childEntities
	for(SyntacticEntity syntacticEntity in childEntities){
		....
	}

}

解析children的逻辑其实在解析InstanceCreationExpression的时候就做掉了，所以在ArgumentList就跳过了。不过这块是历史遗留的逻辑，正常逻辑应该是再递归遍历children，后续我们会考虑优化这块逻辑。

ASTUtils代码只是做了String的解析，比如在获取StringLiteral会带有":"、"'"、"\""，只是做了裁剪。

#2. 关于FunctionParser
可以参考下Flutter Framework里面的MethodInvocation，它主要由3部分组成：target、methodName和argumentList。这块的逻辑，就是将这些数据解析出来，
例如：openURL(data.hints[0].href, data.hints[0].paras];
会解析成为
{
    "actionName": "openURL",
    "argumentsList": ["data.hints[0].href", "data.hints[0].params"]
}

这块逻辑写的相对来说比较简单，可以再继续扩展。
具体怎么用可以参考#3。

#3. 关于交互逻辑

简单来说，就是在创建widget的时候，先把处理事件埋好，然后在这里面动态的查找要处理的事件，事件其实就是#2中的字符串`actionName`。
拿#2中的例子，端侧就需要先预埋`openURL`的函数，
当点击的时候，取出处理函数，暂且叫`OpenURLImpl`。
接下来就是怎么处理传参，需要先根据路径，从data里面取出参数，然后以list的形式传给处理的函数。上面的例子有2个参数：`data.hints[0].href`, `data.hints[0].params`；第一个类型是String，第二个类型是map，那么参数列表如下：
[
	String,
	Map<String, dynamic>
]
拿到上面的结构，再塞给`OpenURLImpl`就可以了。

**Comment by zhangruiyu** [comment]
> > 0-0大佬,你好! 有个不是fish_redux的问题,我想了解下咸鱼动态化方面的,但是找不到什么路径,我详细看了2篇关于这个的文章,目前遇到问题:1,final String name = ASTUtils.getNodeString(namedExp.name);
> > if (name == 'children') {
> > continue;
> > }时为children为什么要跳过去呢,第一篇文章说widget 的children 放在list里面,但是并没有看到这样的步骤啊.如果可以想看下ASTUtils代码具体片段.
> > 2,FunctionExpressionParser.parse(namedExp.expression)能否详细让看下呢,不太清楚这个步骤是把方法解析成什么返回回来,解析出的方法返回值,在客户端怎么用呢
> > 3,交互事件怎么做动态化？这部分感觉很难懂的!
> > 感觉自己好菜0-0,只能求助了!实在找不到方向0-0,能帮助下吗,感谢!
> 
> 首先感谢对于Flutter动态化方案的关注，这个方案还在完善中，期待与大家多多沟通。
> 
> #1. 关于children跳过的问题
> 第2篇文章里面，[打通前后端逻辑，客户端Flutter代码一天上线](https://mp.weixin.qq.com/s/hFdBtDQo1TvvxBGHLV3Stw)，只截取了AST解析ArgumentList的片段，这块代码的功能是将ASTNode转换成ConstrutorNode，大体逻辑如下：
> 
> ```
> void visitAstNodeEntity(AstNode astNode, int treeDeepLevel, ConstructorNode currentNode){
> 	
> 	if (astNode is InstanceCreationExpression) {
> 		创建child ConstructorNode
> 
> 		if(当前解析的label == 'children'){
> 			就把child ConstructorNode添加到树结构里面
> 		}
> 		else {
> 			....
> 		}
> 	}
> 	else if(astNode is ArugmentList){
> 		解析ArugmentList结构
> 	}
> 
> 	// 遍历astNode.childEntities
> 	for(SyntacticEntity syntacticEntity in childEntities){
> 		....
> 	}
> }
> ```
> 解析children的逻辑其实在解析InstanceCreationExpression的时候就做掉了，所以在ArgumentList就跳过了。不过这块是历史遗留的逻辑，正常逻辑应该是再递归遍历children，后续我们会考虑优化这块逻辑。
> 
> ASTUtils代码只是做了String的解析，比如在获取StringLiteral会带有":"、"'"、"""，只是做了裁剪。
> 
> #2. 关于FunctionParser
> 可以参考下Flutter Framework里面的MethodInvocation，它主要由3部分组成：target、methodName和argumentList。这块的逻辑，就是将这些数据解析出来，
> 例如：openURL(data.hints[0].href, data.hints[0].paras];
> 会解析成为
> {
> "actionName": "openURL",
> "argumentsList": ["data.hints[0].href", "data.hints[0].params"]
> }
> 
> 这块逻辑写的相对来说比较简单，可以再继续扩展。
> 具体怎么用可以参考#3。
> 
> #3. 关于交互逻辑
> 
> 简单来说，就是在创建widget的时候，先把处理事件埋好，然后在这里面动态的查找要处理的事件，事件其实就是#2中的字符串`actionName`。
> 拿#2中的例子，端侧就需要先预埋`openURL`的函数，
> 当点击的时候，取出处理函数，暂且叫`OpenURLImpl`。
> 接下来就是怎么处理传参，需要先根据路径，从data里面取出参数，然后以list的形式传给处理的函数。上面的例子有2个参数：`data.hints[0].href`, `data.hints[0].params`；第一个类型是String，第二个类型是map，那么参数列表如下：
> [
> String,
> Map<String, dynamic>
> ]
> 拿到上面的结构，再塞给`OpenURLImpl`就可以了。

哇 明白啦  万分感谢您的回复

**Comment by zhangruiyu** [comment]
> > 0-0大佬,你好! 有个不是fish_redux的问题,我想了解下咸鱼动态化方面的,但是找不到什么路径,我详细看了2篇关于这个的文章,目前遇到问题:1,final String name = ASTUtils.getNodeString(namedExp.name);
> > if (name == 'children') {
> > continue;
> > }时为children为什么要跳过去呢,第一篇文章说widget 的children 放在list里面,但是并没有看到这样的步骤啊.如果可以想看下ASTUtils代码具体片段.
> > 2,FunctionExpressionParser.parse(namedExp.expression)能否详细让看下呢,不太清楚这个步骤是把方法解析成什么返回回来,解析出的方法返回值,在客户端怎么用呢
> > 3,交互事件怎么做动态化？这部分感觉很难懂的!
> > 感觉自己好菜0-0,只能求助了!实在找不到方向0-0,能帮助下吗,感谢!
> 
> 首先感谢对于Flutter动态化方案的关注，这个方案还在完善中，期待与大家多多沟通。
> 
> #1. 关于children跳过的问题
> 第2篇文章里面，[打通前后端逻辑，客户端Flutter代码一天上线](https://mp.weixin.qq.com/s/hFdBtDQo1TvvxBGHLV3Stw)，只截取了AST解析ArgumentList的片段，这块代码的功能是将ASTNode转换成ConstrutorNode，大体逻辑如下：
> 
> ```
> void visitAstNodeEntity(AstNode astNode, int treeDeepLevel, ConstructorNode currentNode){
> 	
> 	if (astNode is InstanceCreationExpression) {
> 		创建child ConstructorNode
> 
> 		if(当前解析的label == 'children'){
> 			就把child ConstructorNode添加到树结构里面
> 		}
> 		else {
> 			....
> 		}
> 	}
> 	else if(astNode is ArugmentList){
> 		解析ArugmentList结构
> 	}
> 
> 	// 遍历astNode.childEntities
> 	for(SyntacticEntity syntacticEntity in childEntities){
> 		....
> 	}
> }
> ```
> 解析children的逻辑其实在解析InstanceCreationExpression的时候就做掉了，所以在ArgumentList就跳过了。不过这块是历史遗留的逻辑，正常逻辑应该是再递归遍历children，后续我们会考虑优化这块逻辑。
> 
> ASTUtils代码只是做了String的解析，比如在获取StringLiteral会带有":"、"'"、"""，只是做了裁剪。
> 
> #2. 关于FunctionParser
> 可以参考下Flutter Framework里面的MethodInvocation，它主要由3部分组成：target、methodName和argumentList。这块的逻辑，就是将这些数据解析出来，
> 例如：openURL(data.hints[0].href, data.hints[0].paras];
> 会解析成为
> {
> "actionName": "openURL",
> "argumentsList": ["data.hints[0].href", "data.hints[0].params"]
> }
> 
> 这块逻辑写的相对来说比较简单，可以再继续扩展。
> 具体怎么用可以参考#3。
> 
> #3. 关于交互逻辑
> 
> 简单来说，就是在创建widget的时候，先把处理事件埋好，然后在这里面动态的查找要处理的事件，事件其实就是#2中的字符串`actionName`。
> 拿#2中的例子，端侧就需要先预埋`openURL`的函数，
> 当点击的时候，取出处理函数，暂且叫`OpenURLImpl`。
> 接下来就是怎么处理传参，需要先根据路径，从data里面取出参数，然后以list的形式传给处理的函数。上面的例子有2个参数：`data.hints[0].href`, `data.hints[0].params`；第一个类型是String，第二个类型是map，那么参数列表如下：
> [
> String,
> Map<String, dynamic>
> ]
> 拿到上面的结构，再塞给`OpenURLImpl`就可以了。

老哥,我是之前在fish_redux发问题的那个0-0,我看到回答后目前对于点击事件逻辑怎么处理大致了解了下,目前只能通过预先埋好方法来做,但是如果点击事件有逻辑代码的话就很难受了!现在我想后台通过dart转成js,然后同过native端执行js获取返回值并回调对应方法,这样就可以处理点击事件里的复杂点的逻辑了,而且获取方法参数也会方便很多,不知道这种方案可行不!还有目前

static
 
Widget
 wrapContainer
(
Map
<
String
,
 
dynamic
>
 pars
)
 
{
  
return
 
new
 
Container
(
    padding
:
 pars
[
'padding'
],
    color
:
 pars
[
'color'
],
    child
:
 pars
[
'child'
],
    decoration
:
 pars
[
'decoration'
],
    width
:
 pars
[
'width'
],
    height
:
 pars
[
'height'
],
    alignment
:
 pars
[
'alignment'
]
  
);
这样的方式添加组件感觉好多啊,有啥简单的方案不,一个一个来,很头大0-0!感谢您之前给我的回复!0-0

**Comment by FKLam** [comment]
> void visitAstNodeEntity(AstNode astNode, int treeDeepLevel, ConstructorNode currentNode){
> 	
> 	if (astNode is InstanceCreationExpression) {
> 		创建child ConstructorNode
> 
> 		if(当前解析的label == 'children'){
> 			就把child ConstructorNode添加到树结构里面
> 		}
> 		else {
> 			....
> 		}
> 	}
> 	else if(astNode is ArugmentList){
> 		解析ArugmentList结构
> 	}
> 
> 	// 遍历astNode.childEntities
> 	for(SyntacticEntity syntacticEntity in childEntities){
> 		....
> 	}
> }

可以展示全一些代码吗？虽然看过分享的文章，但是源码还是无法实现Astnode的遍历，和放入自定义的结构体中，麻烦再提供一下思路，谢谢。
