### ISSUE TITLE
Pub中的版本能否更新一下，现在的0.1.3没法用example中的一些新特性，比如PageRoutes

### ISSUE THREAD

**Issue by shining228** [alibaba/fish-redux#168]
pub中只包含这些模块
export 'src/redux/redux.dart';
export 'src/redux_adapter/redux_adapter.dart';
export 'src/redux_component/redux_component.dart';
export 'src/utils/utils.dart';

**Comment by zjuwjf** [comment]
#170

**Comment by devswift2017** [comment]
I'm have same issue on macos development.
#Quick Fix replace lib in github resource to path ‎⁨Disk/Users⁩/⁨{Your user}/.pub-cache⁩/⁨hosted⁩/⁨pub.dartlang.org⁩/fish_redux-0.1.3⁩/⁨lib⁩

**Comment by devswift2017** [comment]
let update to pub packages. Thanks
