### ISSUE TITLE
关于多个 store 设计的疑问

### ISSUE THREAD

**Issue by my9074** [alibaba/fish-redux#172]
目前看来，`store` 是以 `page` 为划分的，多个页面可以存在多个 `store`。但我理解，这和 `redux` 最佳实践所设想的是有区别的，它更提倡单一的 `store`，这么做的好处更利于 Redux DevTools，还能简化数据的持久化及深加工、精简订阅的逻辑处理。目前的设计更像是 `flux`，如果多个 `page` 之前需要共享数据的话该怎么办？请问当初是如何考虑和设计的吗？

**Comment by zjuwjf** [comment]
Duplicate of #153
