### ISSUE TITLE
view中页面组件dispose问题

### ISSUE THREAD

**Issue by hanmingkang** [alibaba/fish-redux#178]
问题：
   使用Chewie视频组件后需要在dispose中进行回收，同时需要动态改变Chewie的成员变量（比如：url）。
我的方法：将组件写入state中，在初始化时赋值组件，在数据变化时还要初始化组件。
期望：有没有可以dispatch改变state.url这样类似的方法，使用redux动态赋值，同时在dispose的时候回收组件
![1554781755(1)](https://user-images.githubusercontent.com/19572365/55772131-8482e380-5abd-11e9-8842-f868154604b5.png)

**Comment by zjuwjf** [comment]
没有特别理解你的上下文？如果有更多代码的话，便于理解。

**Comment by hanmingkang** [comment]
不好意思，最近有点忙！
chewie组件中需要在dispose的生命周期的方法中回收chewieController和videoPlayerController，effect中生命周期如何获取两个值，并回收该值

/state.dart
![1555322305(1)](https://user-images.githubusercontent.com/19572365/56123955-21ef8300-5fa8-11e9-9a42-5d93bd12f18f.png)
/effect.dart
![1555322473(1)](https://user-images.githubusercontent.com/19572365/56124136-8f9baf00-5fa8-11e9-8ccf-4ac06dc88968.png)
在此过程中，我还要动态改变url的的值，所以需要获取url的值，传入action.payload中，在reducer中重新生成state
![image](https://user-images.githubusercontent.com/19572365/56124319-fa4cea80-5fa8-11e9-9d2e-2cdbc298ab32.png)
以放入state属性中这样的方法用起来比较麻烦，view层进入了control层，有没有更好的方法

**Comment by coldfox** [comment]
看来了前面的回答, 提问的人, 应该是希望在view中提供init/dispose的功能..确实在实际的时候,有些功能只有在view中才需要用到,  就完全没必要放到effect 这些逻辑代码里面, 难道没有更多人关注过这样的问题么?

**Comment by zjuwjf** [comment]
> 看来了前面的回答, 提问的人, 应该是希望在view中提供init/dispose的功能..确实在实际的时候,有些功能只有在view中才需要用到, 就完全没必要放到effect 这些逻辑代码里面, 难道没有更多人关注过这样的问题么?

设计上view层只处理 ui表达， 不处理生命周期。 生命周期都放在effect中处理。
目的是为了更好的逻辑和ui的解耦。
