### ISSUE TITLE
reducer支持异步吗?

### ISSUE THREAD

**Issue by guodf** [alibaba/fish-redux#179]
```dart
Reducer<TestState> buildReducer() {
  return asReducer(<Object, Reducer<TestState>>{
    TestAction.init: _init
  });
}

Future<TestState> _init(TestState state, Action action) async{}

```

**Comment by zjuwjf** [comment]
reducer 不支持 异步， 因为异步会带来不可预测性，也不是pure-function。

**Comment by guodf** [comment]
这么说就是所有的获取数据等其它的操作都应该放在action中进行了，而reducer仅仅只是为了更新状态

**Comment by hyjfine** [comment]
获取数据是有副作用的，应该在effect里做。

**Comment by GuangmingWu** [comment]
> reducer 不支持 异步， 因为异步会带来不可预测性，也不是pure-function。

请问一下，action的payload怎么传多个参数，难道我每次要新建一个类传给payload吗

**Comment by guodf** [comment]
明天什么意思了，定义onAction，在view中触发onAction，在onAction中触发Action，然后触发reducer更新state，最后view更新

action的payload可以传递任意类型，如果要传递多个就传递个[]就行了

**Comment by zjuwjf** [comment]
> > reducer 不支持 异步， 因为异步会带来不可预测性，也不是pure-function。
> 
> 请问一下，action的payload怎么传多个参数，难道我每次要新建一个类传给payload吗

可以使用 Tuple2, Tuple3...

**Comment by GuangmingWu** [comment]
> Tuple2
谢谢，看到了，这个类好
