### ISSUE TITLE
action的传递流程，和优先级问题

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#183]
我用demo测试，监听同一个action，adapter中effect会收到一次，adapter的Reducer中会收到一次。adapteritem的Component的reducer中为收到3次（adapter的item总数是3）。但是如果adapteritem的Component的effect也做了监听，那只会在这个effect中收到。其他地方都不会接收到这个action。

能不能解释一下adapter中effect不会拦截action，会继续传递给reducer，而在Component的effect则会拦截action，并不传递给reducer

**Comment by zjuwjf** [comment]
一个组件的action，如果自己的effect不消费，则其他组件的effect都会收到（广播），同时store也会收到。

**Comment by a398452027** [comment]
@zjuwjf 那adapteritem的Component的reducer收到3次，是为什么呢？

**Comment by zjuwjf** [comment]
> @zjuwjf 那adapteritem的Component的reducer收到3次，是为什么呢？

你看下 #134 的讨论，是同一个问题
