### ISSUE TITLE
可以在工具类中派发事件吗

### ISSUE THREAD

**Issue by layou1989** [alibaba/fish-redux#184]
可以在工具类中派发一个事件吗?例如我在网络请求中拦截到未登陆错误码，需要跳转到登陆页面，这个时候如何产生这个事件，Dispatch如何获取?

**Comment by jkyeo** [comment]
有相同的疑问，等待解答。

**Comment by zjuwjf** [comment]
当参数传递进去

**Comment by hyjfine** [comment]
你的工具类是咋样的？按道理网络请求在effect里发起，是有ctx可以拿到Dispatch的啊

**Comment by layou1989** [comment]
懂了

**Comment by XingXiaoWu** [comment]
想问类似的问题，如何通过action去进行路由跳转

**Comment by XingXiaoWu** [comment]
找到了找到了
https://github.com/alibaba/fish-redux/issues/333
https://github.com/alibaba/fish-redux/issues/264
