### ISSUE TITLE
DynamicFlowAdapter中的Component出现ViewService和State对不上的问题

### ISSUE THREAD

**Issue by onlylikews** [alibaba/fish-redux#185]
我使用过程中碰见Component的ViewService和State对不上的问题，具体场景是这样的：
ComponentA 对应 父State 
ComponentA 中定义Dependencies，Dependencies定义了 子ComponentA，子ComponentA 对应着 子StateA
ComponentB 对应 父State（与ComponentA的State一样）
ComponentB 中定义Dependencies，Dependencies定义了 子ComponentB，子ComponentB 对应着 子StateB
上述的ComponentA和ComponentB的poolKey是不同的。发现当数据的位置发生变化时，子Component和子State类型会对应不上。
经过一番调试后发现，是Component复用时ViewService没有更新，后来我把ComponentState类的每次build过程中再重新构造ViewService就可以了，但不确定这样有没有其他影响，请问有什么更好的处理方案吗？

类ComponentState的build函数改后代码如下：
  Widget build(BuildContext context) {
    _mainCtx = widget.component.createContext(
      store: widget.store,
      buildContext: context,
      getState: () => widget.getter(),
    );
   return _viewUpdater.buildView(_mainCtx.state, _mainCtx.dispatch, _mainCtx);
  }

**Comment by zjuwjf** [comment]
建议 写一个class stateb extends statea {}

后面我会再细看下原因。

**Comment by zjuwjf** [comment]
> build过程中再重新构造ViewService就可以了

设计上这样做是不合理的。
能提供一个最小复现的demo么？
