### ISSUE TITLE
dispose问题

### ISSUE THREAD

**Issue by LXD312569496** [alibaba/fish-redux#186]
问题：effect中进行了异步操作，在拿到数据之前，切换到别的tab页面，这个时候，之前的页面已经dispose了，要怎么处理，才不会报错: DisposeException

**Comment by zjuwjf** [comment]
> 问题：effect中进行了异步操作，在拿到数据之前，切换到别的tab页面，这个时候，之前的页面已经dispose了，要怎么处理，才不会报错: DisposeException

你可以在异步处理中根据context.isDisposed 判断是否已经被dispose，来觉得后续的流程的及时终止。
这里在debug模式下会主动抛DisposeException，是为了让这个问题提前发现。
在release模式下并不会有这个抛DisposeException行为。

**Comment by LXD312569496** [comment]
嗯嗯，好，谢谢解答
