### ISSUE TITLE
关于如何使用State的求助

### ISSUE THREAD

**Issue by johnhollon** [alibaba/fish-redux#188]
一些view中需要的整个声明周期都不会变的“属性”，放到state里面合适吗？比如：

* FocusNode
* TextEditingController
* GlobalKey
* 用于防抖的定时器

是否有更好的编码规范，能够不在state中存储这些“非数据”属性？

**Comment by zjuwjf** [comment]
1. 建议将FocusNode、TextEditingController、GlobalKey放在state里，保证数据源是唯一的。

2. “防抖”可以通过通用的AOP的方案，比如针对一个effect

```

Effect<T> buildEffect() {
  return combineEffects(<Object, Effect<PageState>>{
    ActionT.onClick:  AOP([debounce(500)]).withTwo<void,Action,Context<T>>(_onClick),
  });
}

void _onClick(Action action, Context<T> ctx) {}

```

**Comment by johnhollon** [comment]
还有一点，是否有可能在框架内部完成基于id（这个id由框架自动生成，对客户程序员透明）或其他对客户程序员透明的验证，确保reducer被执行一次？

**Comment by johnhollon** [comment]
还有一个疑问。一个Component带有一个输入框，这个输入框需要使用一个state属性为autoFocus，表示这个组件的输入框是否要自动获得焦点。若自动获得焦点，则输入框自动获得焦点，且以后不得再次自动获得焦点。
对于这个autoFocus属性，需要connector从父state中connector到此组件的state，get，set都需要，但是，由于这个属性值是“一次性”的，父state中承载此属性值的后期状态实在没有必要，框架针对此类问题，是否有更优雅的解决方案？

**Comment by zjuwjf** [comment]
> 还有一点，是否有可能在框架内部完成基于id（这个id由框架自动生成，对客户程序员透明）或其他对客户程序员透明的验证，确保reducer被执行一次？

对这个问题已有标准解法，#134

**Comment by zjuwjf** [comment]
> 还有一个疑问。一个Component带有一个输入框，这个输入框需要使用一个state属性为autoFocus，表示这个组件的输入框是否要自动获得焦点。若自动获得焦点，则输入框自动获得焦点，且以后不得再次自动获得焦点。

虽然通过EffectPart或者ViewPart可以有一些local的状态的存在， 但是我依然认为将所有状态都表达在唯一的state中是最合理的。它会更容易被理解和被调试。

**Comment by johnhollon** [comment]
感谢耐心回复，解决了我的问题。
对于state，我还是建议：
1. 将整个生命周期不发生变化的属性从state里面拆分出来，因为这些属性是组件“在这个页面得以存在”的前提，这些属性在组件的整个生命周期内必然是final（非static）不可变的，这些属性最好是放到组件的构造函数中。
2. 将分治进行的更彻底一些，允许组件持有自有状态，这些状态不通过connector从父级获得，也不经由connector影响上级状态。这可能得要求reducer分类，分成现在的reducer以及仅对组件内部有影响的reducer。
我对redux没什么了解，但是从使用和理解习惯上，我个人更偏爱于上面的意见。从直觉上，感到能让state更趋近于纯净的可变数据。

**Comment by guodf** [comment]
@johnhollon 你这种想法属于事件驱动类似与传统的winfrom或dom操作，而fish-redux属于数据驱动，一切围绕一个状态树进行管理，这也符合redux的设计。
 fish-redux如果按照事件驱动的方式来做不满足flutter的设计，因为每次状态改变widget都应该重绘，重绘的话就不存在什么不变的常量值，如果你觉的不符合你的预期，你应该将变化的部分再次做成commponent来达到效果，在flutter中也就是再次封装变化的widget让变化影响范围更小

**Comment by johnhollon** [comment]
> 你应该将变化的部分再次做成commponent来达到效果，在flutter中也就是再次封装变化的widget让变化影响范围更小

connector的set不会导致父级组件的重绘？

**Comment by guodf** [comment]
connector就是用来做局部刷新的，目的就是为了防止父组件重绘。

>1.  将整个生命周期不发生变化的属性从state里面拆分出来，因为这些属性是组件“在这个页面得以存在”的前提，这些属性在组件的整个生命周期内必然是final（非static）不可变的，这些属性最好是放到组件的构造函数中。

不可变的属性不应该跟可变的属性在一个component中，因为可变的必然导致component重绘

**Comment by johnhollon** [comment]
能不能在buildComponent方法中添加一个参数，向组件传递这种整个生命周期不发生变化的属性、或者“一过性”的属性，或者由组件自己管理（不需要与上级状态connect）的属性呢？

**Comment by johnhollon** [comment]
@guodf 万分感谢！

还有一个小问题，问问看有没有更好的解决方案。

现在项目中需要做一个组件，这个组件内部有一个textfield,组件需要一个可变属性autoFocus，表示这个组件中的textfield是否要自动获得焦点。

如果autoFocus为true，那么textfield就要自动获得焦点，而且无论是否成功获得了焦点之后，都不再次自动获得焦点（也就是，如果textfield失去了焦点之后就不再自动重新获得焦点）。

现在的问题是，如果这个组件被其他组件使用（作为其他组件的子组件，这个其他组件姑且称之为父组件），那么autoFocus就需要父组件的state经connector get而来，这意味着父组件需要持有这个autoFocus，而且子组件的autoFocus发生变化，需要connector set到父组件的autoFocus。只有这样，才能保证textfield失去焦点之后，不再重新自动获得焦点。

其实，我个人理解，从这个用例来讲，父组件根本没必要持有这个autoFocus，这个属性的初始值是由子组件外部提供的，但这个属性之后的变化是是子组件自己的一个内部状态（与父级状态没什么必然联系，而且也应该由子组件自己维持），不应该扩展到父状态上去。

这个问题除了通过connector get set外，是否有更优雅的解决方案呢？

此外，父状态是子状态的全集，这从纯净的“业务数据”角度来讲，理应如此，然而对于“状态”这个概念，这样做是否特别合适？我个人理解是未必完全合适，因为状态并非是完完全全纯净的业务数据。它里面含有组件之所以存在的、整个生命周期都不会变的的组件本身的属性；含有应该由组件自己管理的属性。

其实，从我个人理解，这些状态可以从两个维度进行分类：

* 第一个维度姑且叫做“可变性”：在组件整个生命周期内可能发生变化的状态，在组件整个生命周期内绝不会发生变化的状态；
* 第二个维度姑且叫做“驱动性”：可能导致界面重绘的状态，绝不会导致界面重绘的状态。

在展示用户的Page中，可能存在下列属性：

final String userId;    // 这是不可变的属性，用于确定当前这个页面展示的是哪个用户。在页面的整个生命周期内都不会改变。

final TextEditingController controller; // 这个controller不会导致界面重绘。

UserModel model; // 这个是可变状态，会导致界面重绘的状态。即纯净的业务数据。

由于父状态是子状态的全集，那就要求父组件的状态存储所有子组件的状态，哪怕这些状态对于父组件来讲毫无意义。

我不知道这么理解对不对，只是在编写代码的时候感到有违直觉。是不是能够在buildComponent方法中添加一个参数，向组件传递这种整个生命周期不发生变化的属性、或者“一过性”的属性，或者由组件自己管理（不需要与上级状态connect）的属性呢？

**Comment by guodf** [comment]
你这个跟我遇见的问题一样，按照事件驱动你这样理解没有问题，但是按照数据驱动就不对了，在redux中一切皆为状态，你要改变思维
