### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by LXD312569496** [alibaba/fish-redux#192]
想实现美团点菜的那种左右两个listview的联动效果，我现在是这样弄的，页面是一个page，左边listview实现成一个component，右边的实现也是带listview的component，然后这两个component里面的listview要实现联动效果。
问题：1、将scrollController的设置放在effect里面，正确吗？还是要放在buildView那里设置
           2、构成列表的item的component，buildView里面需要知道当前是在哪个index，请问如何获取。
          3、问个另外的问题哈，listview怎么滚动到指定index的item
麻烦解答一下，谢谢

**Comment by zjuwjf** [comment]
1. 是在effect的init里创建。
2. 如果需要知道index，那么index 也应该成为 state的一部分。
3. 类似listview滑动到指定的index，要自己做index到position的转化，可以看看flutter类似的issue。

**Comment by LXD312569496** [comment]
嗯嗯，看了flutter的issue，固定高度的item就好解决，position就是直接index乘高度。但是不固定高度的就很麻烦。
谢谢
