### ISSUE TITLE
Effect Lifecycle.init中ctx.dispatch死循环问题怎么解决

### ISSUE THREAD

**Issue by guodf** [alibaba/fish-redux#193]
#58 
Effect Lifecycle.init中通过ctx.dispatch触发reducer设置一个AnmationController，但是如果在reducer对state进行clone则会导致页面死循环，我的现在的解决方式有两种：
1. 在Effect Lifecycle.init不触发reducer，直接修改state的AnmationController属性值
2. 在reducer中不对state进行clone，直接修改state的AnmationController属性值

上面的第一种方法我还能理解，但是第二种按照reducer的约定不应该直接修改state的值（先clone再修改）

请问这种情况是我使用不对还是什么问题?

**Comment by zjuwjf** [comment]
能贴一个具体的代码片段吗？

**Comment by guodf** [comment]
应该是使用错误，不知道问题出在哪里，重头又写了一边好了
