### ISSUE TITLE
关于buildPage传参的问题.

### ISSUE THREAD

**Issue by ws4349893** [alibaba/fish-redux#194]
page1 initState 异步获取参数 p
page1 中 通过 buildPage(p) 得到page2
在这中间: page1 第一次 buildPage2 p = null
第二buildPage2 p != null,但是page2的initeState并没有调用,导致page2的参数一直是null. 这种场景下我是不是不能这么传值呢?

**Comment by zjuwjf** [comment]
大概是对initState的作用有误解，它是一个简单的pure function，目的是返回一个页面的初始的state。
