### ISSUE TITLE
AppbarPreferSize

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#196]
AppbarPreferSize这个demo里没有，是自定义的么

**Comment by zjuwjf** [comment]
有更多的上下文的话，会让他人更理解你的内容 - -

**Comment by xfhomedream** [comment]
![image](https://user-images.githubusercontent.com/14237960/56422663-33ec6100-62db-11e9-899b-f2ec2075c737.png)
我想buildComponent appbar 但是会报类型强转异常怎么破

**Comment by zjuwjf** [comment]
如果可以贴更多信息的话，可能能帮助到你
