### ISSUE TITLE
DynamicFlowAdapter的问题

### ISSUE THREAD

**Issue by johnhollon** [alibaba/fish-redux#197]
在下面的程序中,无法通过remote页面State中List的元素,从而使得Adaptor减少元素，而且会导致PullLoading组件类型转换异常（PullLoadingState不是JiatCardState类型异常）。

状态传导关系：

页面State <---> connector <---> 父级组件State <---> adaptor

代码目录：

* 页面State
* 页面的connector
* 页面的reducer
* 页面中使用的组件（Adaptor的父组件）State
* Adaptor

###  页面State

```dart
YewuService _yeWuService = YewuService();
void _jiatTapped(BuildContext context, JiatModel jiatModel) {
  showDialog(
    context: context,
    barrierDismissible: false,
    builder: (context) => JiatInfoPage().buildPage(
          JiatInfoState(jiatModel.id, showopps: true),
        ),
  );
}

Future<CommonResult<List<JiatModel>>> _queryFunction(JiatModelCondition condition, PageModel pageModel) {
  return _yeWuService.queryJiat(condition, pageModel);
}

class YewPageState implements Cloneable<YewPageState> {
  final String defaultZhuangt;
  final bool secret;
  JiatListState<JiatModelCondition> listState;
  JiatConditionState conditionState;

  /// 构造函数
  YewPageState({
    this.defaultZhuangt,
    this.secret = false,
  });
  @override
  YewPageState clone() {
    return YewPageState()
      ..listState = listState
      ..conditionState = conditionState;
  }
}

YewPageState initState(YewPageState state) {
  state = state?.clone();
  String defaultZhuangt = state?.defaultZhuangt;
  JiatListState<JiatModelCondition> listState = JiatListState<JiatModelCondition>(
    secret: state.secret,
    refreshIndicatorKey: GlobalKey<RefreshIndicatorState>(),
    jiatTapped: _jiatTapped,
    queryFunction: _queryFunction,
    needRefresh: true,
  );
  JiatConditionState conditionState = JiatConditionState(
    defaultZhuangt: defaultZhuangt,
    textfieldAutoFocus: false,
    textfieldHintText: "输入姓名或身份证号查询",
  );
  if (state == null) {
    state = YewPageState()
      ..conditionState = conditionState
      ..listState = listState;
  } else {
    if (state.conditionState == null) {
      state.conditionState = conditionState;
    }
    if (state.listState == null) {
      state.listState = listState;
    }
  }
  return state;
}
```

### 页面的connector

``` dart
class JiatListConnector extends ConnOp<YewPageState, JiatListState<JiatModelCondition>> {
  @override
  JiatListState<JiatModelCondition> get(YewPageState state) {
    return state.listState;
  }

  @override
  void set(YewPageState state, JiatListState<JiatModelCondition> subState) {
    state.listState = subState;
  }
}

class JiatConditionConnector extends ConnOp<YewPageState, JiatConditionState> {
  @override
  JiatConditionState get(YewPageState state) {
    return state.conditionState;
  }

  @override
  void set(YewPageState state, JiatConditionState subState) {
    state.conditionState = subState;
    JiatListState<JiatModelCondition> listState = state.listState.clone();
    listState.condition = subState.condition;
    listState.needRefresh = true;
    state.listState = listState;
  }
}
```

### 页面的reducer

``` dart
Reducer<YewPageState> buildReducer<C>() {
  return asReducer(
    <Object, Reducer<YewPageState>>{
      YewPageActionTypes.jiatChanged: _jiatChanged,
      YewPageActionTypes.jiatRemoved: _jiatRemoved,
    },
  );
}

YewPageState _jiatChanged(YewPageState state, Action action) {
  JiatModel jiat = action.payload;
  YewPageState newstate = state.clone();
  int index = newstate.listState.jiatList?.indexOf(jiat);
  if (index != null && index > -1) {
    newstate.listState.jiatList?.removeAt(index);
    newstate.listState.jiatList?.insert(index, jiat);
    return newstate;
  }
  return state;
}

YewPageState _jiatRemoved(YewPageState state, Action action) {
  JiatModel jiat = action.payload;
  YewPageState newstate = state.clone();
  newstate.listState.jiatList?.remove(jiat);
  return newstate;
}

```

### 页面中使用的组件（Adaptor的父组件）State

``` dart

class JiatListState<C> implements Cloneable<JiatListState> {
  /// 下拉重新加载KEY
  GlobalKey<RefreshIndicatorState> refreshIndicatorKey;

  /// 点击某个家庭执行的操作
  final void Function(BuildContext, JiatModel) jiatTapped;

  /// 查询方法
  final Future<CommonResult<List<JiatModel>>> Function(C, PageModel) queryFunction;

  /// 需要对关键数据进行遮盖保密。
  final bool secret;

  /// 是否正在执行查询
  bool querying = false;

  /// 是否需要重新查询。
  bool needRefresh;

  /// 查询后的提示信息
  String queryMoreMessage;

  /// 查询条件
  C condition;

  /// 家庭查询结果
  List<JiatModel> jiatList = List();

  /// 分页器
  PageModel pageModel = PageModel();

  /// 构造函数
  JiatListState({
    this.secret = false,
    this.refreshIndicatorKey,
    this.jiatTapped,
    this.queryFunction,
    this.needRefresh = true,
  })  : assert(secret != null),
        assert(needRefresh != null),
        assert(queryFunction != null) {
    refreshIndicatorKey = refreshIndicatorKey ?? GlobalKey<RefreshIndicatorState>();
  }
  @override
  JiatListState<C> clone() {
    return JiatListState(
      secret: secret,
      refreshIndicatorKey: refreshIndicatorKey,
      jiatTapped: jiatTapped,
      queryFunction: queryFunction,
      needRefresh: needRefresh,
    )
      ..condition = condition
      ..jiatList = jiatList
      ..pageModel = pageModel
      ..queryMoreMessage = queryMoreMessage
      ..querying = querying;
  }
}
```

### Adaptor
``` dart
class JiatListAdapter<C> extends DynamicFlowAdapter<JiatListState<C>> {
  JiatListAdapter()
      : super(
          pool: <String, Component<dynamic>>{
            'jiatCard': JiatCardComponent(),
            'loading': PullLoading(),
          },
          connector: _JiatListConnector<C>(),
        );
}

class _JiatListConnector<C> extends ConnOp<JiatListState<C>, List<ItemBean>> {
  @override
  List<ItemBean> get(JiatListState<C> state) {
    List<ItemBean> list;
    if (state.jiatList?.isNotEmpty == true) {
      list = state.jiatList
          .map<ItemBean>(
            (JiatModel data) => ItemBean(
                  'jiatCard',
                  JiatCardState(
                    state.jiatTapped,
                    state.secret,
                  )..jiat = data,
                ),
          )
          .toList(
            growable: true,
          );
    } else {
      list = <ItemBean>[];
    }
    list.add(
      ItemBean(
          "loading",
          PullLoadingState()
            ..loading = state.querying
            ..message = state.queryMoreMessage),
    );
    return list;
  }

  @override
  void set(JiatListState<C> state, List<ItemBean> jiatList) {
    state.jiatList = jiatList
        .where(
          (itemBean) => itemBean.type == 'jiatCard',
        )
        .map<JiatModel>(
          (ItemBean data) => (data.data as JiatCardState).jiat,
        )
        .toList(
          growable: true,
        );
  }
}
```

**Comment by zjuwjf** [comment]
> ```
Reducer<YewPageState> buildReducer<C>() {
  return asReducer(
    <Object, Reducer<YewPageState>>{
      YewPageActionTypes.jiatChanged: _jiatChanged,
      YewPageActionTypes.jiatRemoved: _jiatRemoved,
    },
  );
}

YewPageState _jiatChanged(YewPageState state, Action action) {
  JiatModel jiat = action.payload;
  YewPageState newstate = state.clone();
  int index = newstate.listState.jiatList?.indexOf(jiat);
  if (index != null && index > -1) {
    newstate.listState.jiatList?.removeAt(index);
    newstate.listState.jiatList?.insert(index, jiat);
    return newstate;
  }
  return state;
}

YewPageState _jiatRemoved(YewPageState state, Action action) {
  JiatModel jiat = action.payload;
  YewPageState newstate = state.clone();
  newstate.listState.jiatList?.remove(jiat);
  return newstate;
}
```

问题在上面的reducer里，你这里需要clone jiatList 及它以上的父字段

**Comment by johnhollon** [comment]
> 问题在上面的reducer里，你这里需要clone jiatList 及它以上的父字段。你现在相当于是是在直接操作了old-state，这和redux的设计是不符的。

万分感谢！

您是说问题出在jiatList上，我在对state进行clone后，对于state中的集合类型，还要重新创建一个集合对象，然后通过allAll一类的方法将原状态中的集合元素重新添加到新的集合对象中吗？

**Comment by zjuwjf** [comment]
> > 问题在上面的reducer里，你这里需要clone jiatList 及它以上的父字段。你现在相当于是是在直接操作了old-state，这和redux的设计是不符的。
> 
> 万分感谢！
> 
> 您是说问题出在jiatList上，我在对state进行clone后，对于state中的集合类型，还要重新创建一个集合对象，然后通过allAll一类的方法将原状态中的集合元素重新添加到新的集合对象中吗？

可以 jiatList.toList();

**Comment by johnhollon** [comment]
> 可以 jiatList.toList();

我没理解错误的话，我们正在说state的clone方法实现环节上的问题。应该把“页面中使用的组件（Adaptor的父组件）State”的clone代码改为：

``` dart
@override
  JiatListState<C> clone() {
    return JiatListState(
      secret: secret,
      refreshIndicatorKey: refreshIndicatorKey,
      jiatTapped: jiatTapped,
      queryFunction: queryFunction,
      needRefresh: needRefresh,
    )
      ..condition = condition
      ..jiatList = jiatList?.toList() // 这里对集合类对象进行特殊处理
      ..pageModel = pageModel
      ..queryMoreMessage = queryMoreMessage
      ..querying = querying;
  }
```

是这个意思吗？

**Comment by zjuwjf** [comment]
> > 可以 jiatList.toList();
> 
> 我没理解错误的话，我们正在说state的clone方法实现环节上的问题。应该把“页面中使用的组件（Adaptor的父组件）State”的clone代码改为：
> 
> ```dart
> @override
>   JiatListState<C> clone() {
>     return JiatListState(
>       secret: secret,
>       refreshIndicatorKey: refreshIndicatorKey,
>       jiatTapped: jiatTapped,
>       queryFunction: queryFunction,
>       needRefresh: needRefresh,
>     )
>       ..condition = condition
>       ..jiatList = jiatList?.toList() // 这里对集合类对象进行特殊处理
>       ..pageModel = pageModel
>       ..queryMoreMessage = queryMoreMessage
>       ..querying = querying;
>   }
> ```
> 
> 是这个意思吗？

我觉得在reducer里做 
newState.jiatList = oldStatejiatList?.toList()
更加合适

**Comment by johnhollon** [comment]
经测试，问题仍然存在。

修改后的reducer(remove方法)

```dart
YewPageState _jiatRemoved(YewPageState state, Action action) {
  JiatModel jiat = action.payload;
  YewPageState newstate = state.clone();
  List list =  state.listState.jiatList?.toList();
  list?.remove(jiat);
  newstate.listState.jiatList = list;
  return newstate;
}
```

BUG仍然存在：

* 移除了State中List中的元素，但界面上仍然存在此元素。
* 向下滑动，渲染PullLoading组件时，抛出异常：type 'PullLoadingState' is not a subtype of type 'JiatCardState'

**Comment by zjuwjf** [comment]
> 经测试，仅在reducer中对list进行处理，无法解决问题。
> 
> 修改后的reducer(remove方法)
> 
> ```dart
> YewPageState _jiatRemoved(YewPageState state, Action action) {
>   JiatModel jiat = action.payload;
>   YewPageState newstate = state.clone();
>   List list =  state.listState.jiatList?.toList();
>   list?.remove(jiat);
>   newstate.listState.jiatList = list;
>   return newstate;
> }
> ```
> 
> BUG仍然存在：
> 
> * 移除了State中List中的元素，但界面上仍然存在此元素。
> * 向下滑动，渲染PullLoading组件时，抛出异常：type 'PullLoadingState' is not a subtype of type 'JiatCardState'
> 
> ### 通过修改State的clone方法，经测试，似乎解决了问题：
> 页面的State（clone方法）
> 
> ```dart
>   @override
>   YewPageState clone() {
>     return YewPageState()   // 对子状态执行了克隆
>       ..listState = listState?.clone()   // 对子状态执行了克隆
>       ..conditionState = conditionState?.clone();
>   }
> ```
> 
> Adaptor的父组件的State（clone方法）
> 
> ```dart
>   @override
>   JiatListState<C> clone() {
>     return JiatListState(
>       secret: secret,
>       refreshIndicatorKey: refreshIndicatorKey,
>       jiatTapped: jiatTapped,
>       queryFunction: queryFunction,
>       needRefresh: needRefresh,
>     )
>       ..condition = condition
>       ..jiatList = jiatList?.toList()  // 这里对集合类型的状态属性进行了特殊处理
>       ..pageModel = pageModel
>       ..queryMoreMessage = queryMoreMessage
>       ..querying = querying;
>   }
> ```

做的不错。

当然问题的本质是引用关系。

如果你在reducer中
newState.a.b.c = newValue
也将使得
oldState.a.b.c = newValue
因为它们是同一个a，b.

所以正确的做法是

newState.a = oldState.a.clone()..b = (oldState.a.b.clone() ..c = newValue..)

可以参考标准的redux的做法。
