### ISSUE TITLE
使用PrivateReducerMixin之后，组件的Reducer不再被调用

### ISSUE THREAD

**Issue by johnhollon** [alibaba/fish-redux#198]
若A组件使用了PrivateReducerMixin，其状态通过connector连接至父组件（非Page，而是Component），则A组件的reducer失效。

**Comment by zjuwjf** [comment]
可能需要贴下你的connector和component的代码

**Comment by huang12zheng** [comment]
This it My think:
若A组件使用了PrivateReducerMixin,A组件的action只发送到相应的A组件.So 父组件 can't use reducer of A组件失效
