### ISSUE TITLE
关于在MaterialApp的home中的页面设置flutter_ScreenUtil

### ISSUE THREAD

**Issue by tom1918** [alibaba/fish-redux#199]
![image](https://user-images.githubusercontent.com/6824136/56180091-8e1ac700-603a-11e9-9174-25a6f389e94f.png)

ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);
我尝试在第一个fish-redux 的页面做这个事情，但是没有成功，请问我应该放哪里？
我应该如何获取根页面的 context？

**Comment by baij930312** [comment]
我也有用过这个flutter_ScreenUtil 库做屏幕适配,我当时是第一个页面的effect对应生命周期init中,不过我有遇到问题,我当时的情况是在debug模式下 一切正常,当打包成release下Android端会不起效.
猜测可能的原因:
1,flutter_ScreenUtil 本身有问题看该库的issues中有不少类似的提问(大概看了下这个库发现单例的实现方式好像有点问题-.-)
2,fish-redux Android在debug和release下实现不同导致安卓端无法获取ctx?(可能性很小吧``)
3,flutter本身在不同模式下实现不同导致?

**Comment by jefferybai** [comment]
在page的view里面设置一下

**Comment by jefferybai** [comment]
@baij930312 @tom1918 
https://github.com/flutter/flutter/issues/25827

**Comment by baij930312** [comment]
> @baij930312 @tom1918
> [flutter/flutter#25827](https://github.com/flutter/flutter/issues/25827)

cool~  我把源码修改了一下、不在一开始的时候赋值而是每次获取的时候计算一下，不知道会不会有性能问题，如果有也可以计算的时候先判断是否为0，当不是0的时候就赋值给当前的属性以后每次就直接用这个属性去适配就好不用每次计算了、不过目前来看是一切正常的  https://github.com/baij930312/inventory_management/blob/master/lib/common/screen_adapter.dart
