### ISSUE TITLE
DynamicFlowAdapter的使用方式

### ISSUE THREAD

**Issue by baij930312** [alibaba/fish-redux#200]
我需要在一个listView上显示两种component ,目前的做法是在一个list中放了两种类型的state,在adapter中判断类型,这样的做法会不会不太好? 正确的方式是怎样的.

**Adapt.dart:**

class MemoEditAdapter extends DynamicFlowAdapter<MemoEditState> {
  MemoEditAdapter()
      : super(
          pool: <String, Component<Object>>{
            'image': MemoImageComponent(),
            'text': MemoNotesComponent(),
          },
          connector: _MemoEditConnector(),
          reducer: buildReducer(),
        );
}

class _MemoEditConnector extends ConnOp<MemoEditState, List<ItemBean>> {
  @override
  List<ItemBean> get(MemoEditState state) {
    if (state.images?.isNotEmpty == true) {
      return state.images.map<ItemBean>((data) {
        if (data is MemoImageState) {
          return ItemBean('image', data);
        } else {
          return ItemBean('text', data);
        }
      }).toList(growable: true);
    } else {
      return <ItemBean>[];
    }
  }

  @override
  void set(MemoEditState state, List<ItemBean> items) {
    if (items?.isNotEmpty == true) {
      state.images = List<MemoImageState>.from(
          items.map<MemoImageState>((ItemBean bean) => bean.data).toList());
    } else {
      state.images = <MemoImageState>[];
    }
  }

  @override
  subReducer(reducer) {
    return super.subReducer(reducer);
  }
}

**Comment by jefferybai** [comment]
```
pool: <String, Component>{
'image': MemoImageComponent(),
'text': MemoNotesComponent(),
},
```
你这就是正确的方式啊

**Comment by baij930312** [comment]
> ```
> pool: <String, Component>{
> 'image': MemoImageComponent(),
> 'text': MemoNotesComponent(),
> },
> ```
> 你这就是正确的方式啊

if (data is MemoImageState) {
return ItemBean('image', data);
} else {
return ItemBean('text', data);
}
那就是需要在这里判断类型 并且 state.images 这个数组只能是List<dynamic> ,导致在reducer中对数据操作的时候都要先判断类型```` 不过好像也可以也可以在这两个state之上做一个父类进行一个统一行为的封装..  不知道有没有更好的方式

**Comment by baij930312** [comment]
> > ```
> > pool: <String, Component>{
> > 'image': MemoImageComponent(),
> > 'text': MemoNotesComponent(),
> > },
> > ```
> > 你这就是正确的方式啊
> 
> if (data is MemoImageState) {
> return ItemBean('image', data);
> } else {
> return ItemBean('text', data);
> }
>
 那就是需要在这里判断类型 并且 state.images 这个数组只能是List<dynamic> ,导致在reducer中对数据操作的时候都要先判断类型```` 不过好像也可以也可以在这两个state之上做一个父类进行一个统一行为的封装.. 不知道有没有更好的方式
