### ISSUE TITLE
buildView调用的时机

### ISSUE THREAD

**Issue by YuiFn** [alibaba/fish-redux#201]
场景：1个页面等待页面后跳转到另外一个页面，现在的做法是在page的initstate中初始化一个延迟的Future，到点时发出一个action，然后跳转到另外一个页面。
在跟踪buildView调用的时候，首次运行有时候两个page都只会调用一次，有时候page1会调用两次，有时候是page2调用两次
在hotreload情况下有时候会是下面的输出
```
flutter: page1 build view
flutter: ---------- [Page1Page] ----------
flutter: [Page1Page] $DebugOrReport.debugUpdate Page1Page
flutter: ========== [Page1Page] ================
flutter: page1 build view
flutter: ---------- [Page1Page] ----------
flutter: [Page1Page] $DebugOrReport.debugUpdate Page1Page
flutter: ========== [Page1Page] ================
flutter: page2 build view

```
buildView是什么时候被调用的呢？多次被调用会有什么后果？

```dart
// app.dart
class DemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final AbstractRoutes routes = PageRoutes(
      pages: <String, Page<Object, dynamic>>{
        '/p1': Page1Page(),
        '/p2': Page2Page(),
      },
    );

    return MaterialApp(
        theme: ThemeData.light(),
        home: routes.buildPage("/p1", null),
        onGenerateRoute: (RouteSettings settings) {
          return MaterialPageRoute<Object>(builder: (BuildContext context) {
            return routes.buildPage(settings.name, settings.arguments);
          });
        });
  }
}
```
page1 中的effect.dart
```dart
Effect<Page1State> buildEffect() {
  return combineEffects(<Object, Effect<Page1State>>{
    Lifecycle.initState: _onInit,
    Page1Action.action: _onAction,
  });
}

void _onInit(Action action, Context<Page1State> ctx) {
  const deadline = Duration(seconds: 2);
  Future.delayed(deadline, () => ctx.dispatch(Page1ActionCreator.onAction()));
}

void _onAction(Action action, Context<Page1State> ctx) {
  Navigator.of(ctx.context).pushNamed("/p2");
}
```

其他代码均为模版自动生成

**Comment by zjuwjf** [comment]
init应该是一个纯函数，只是为了将路由参数转化为store的初始state。

**Comment by YuiFn** [comment]
类似的功能需求，应该怎么在fish中组织呢？如果是webscoket的场景应该怎么做初始化和数据流动

**Comment by zjuwjf** [comment]
在effect中，处理lifecycle的部分

**Comment by YuiFn** [comment]
> 在effect中，处理lifecycle的部分

具体是指？
刚才又实验了下，按照你之前的说法，在initState，发出一个action表示界面加载了，然后在里面设置延迟时间
```dart
Effect<Page1State> buildEffect() {
  return combineEffects(<Object, Effect<Page1State>>{
    Page1Action.initLoad: _onAction,
    Page1Action.click: _onAction,
    Lifecycle.initState: _onInit
  });
}

void _onAction(Action action, Context<Page1State> ctx) async {
  debugPrint("dispatch....");
  await Future.delayed(const Duration(seconds: 2));
  Navigator.of(ctx.context).pushNamed("/p2");
}

void _onInit(Action action, Context<Page1State> ctx) {
  debugPrint("real init");
  ctx.dispatch(Page1ActionCreator.initLoad());
}
```
又单独实验了下，没有fish的情况，发现home页面在hot reload的build方法都会被调用两次，这是什么原因呢？

**Comment by lujiayi1228** [comment]
> > 在effect中，处理lifecycle的部分
> 
> 具体是指？
> 刚才又实验了下，按照你之前的说法，在initState，发出一个action表示界面加载了，然后在里面设置延迟时间
> 
> ```dart
> Effect<Page1State> buildEffect() {
>   return combineEffects(<Object, Effect<Page1State>>{
>     Page1Action.initLoad: _onAction,
>     Page1Action.click: _onAction,
>     Lifecycle.initState: _onInit
>   });
> }
> 
> void _onAction(Action action, Context<Page1State> ctx) async {
>   debugPrint("dispatch....");
>   await Future.delayed(const Duration(seconds: 2));
>   Navigator.of(ctx.context).pushNamed("/p2");
> }
> 
> void _onInit(Action action, Context<Page1State> ctx) {
>   debugPrint("real init");
>   ctx.dispatch(Page1ActionCreator.initLoad());
> }
> ```
> 
> 又单独实验了下，没有fish的情况，发现home页面在hot reload的build方法都会被调用两次，这是什么原因呢？

所以是什么原因导致会调用两次呢
