### ISSUE TITLE
TextFormField光标一直在前面

### ISSUE THREAD

**Issue by insipidness** [alibaba/fish-redux#203]
child: new TextFormField(
                  // keyboardType: TextInputType.number,
                  decoration: new InputDecoration(
                    labelText: '工号',
                    hintText: '请输入工号',
                    icon: Icon(Icons.account_circle)
                  ),
                  controller: state.usernameController,
                  focusNode: state.focusNodeUsername
                ),

**Comment by insipidness** [comment]
这种方式添加了controller，当输入框输入文字时，光标不会调至最后面

**Comment by zjuwjf** [comment]
这个问题应该和框架无关。

**Comment by insipidness** [comment]
我的我的，reducer中的方法我自己写错了。
