### ISSUE TITLE
如何处理跨页面公用一个数据

### ISSUE THREAD

**Issue by pheart** [alibaba/fish-redux#205]
1: 类似用户信息，多个页面都要使用用户信息，某页面修改用户信息以后，其他页面如何同步
2:某页面需要其他页面的数据集合，如何获取
感觉少一个共同数据管理的一种方式

**Comment by zjuwjf** [comment]
可以通过 AppRoutes + reselect

**Comment by pheart** [comment]
thanks, bro!
