### ISSUE TITLE
RefreshIndicator 在fish-redux 中的使用问题

### ISSUE THREAD

**Issue by jkyeo** [alibaba/fish-redux#208]
RefreshIndicator 定义如下:
```
const RefreshIndicator({
    Key key,
    @required this.child,
    @required this.onRefresh,
    ....
})
```
其中onRefresh 是一个返回Future 类型的方法:
```
/// A function that's called when the user has dragged the refresh indicator
/// far enough to demonstrate that they want the app to refresh. The returned
/// [Future] must complete when the refresh operation is finished.
final RefreshCallback onRefresh;
```

也就是说，刷新完成是靠此方法返回了Future 结果。
但是在fish-redux 中，刷新时dispatch 一个刷新意图，刷新结果通常是在reducer 中dispatch 一个newState。
请问这种情况下，在fish-redux 中如何更好的使用下拉刷新组件？

**Comment by zjuwjf** [comment]
非常棒的问题，目前最简单的解决方案是：
```dart

/// view.dart
final Completer<void> completer = Completer<void>();

  dispatch(Action('refresh', payload: () {
    completer.complete();
  }));

  final Future<void> future = completer.future;

/// effect.dart
final Function complete = action.payload;
...
complete();
```

**Comment by jkyeo** [comment]
很好的解决方案！典型的函数式编程思想。大赞！👍

**Comment by zjuwjf** [comment]
我觉得这个问题，可以继续开放着，也许会有其他同学的不同的想法。

**Comment by zjuwjf** [comment]
#209

**Comment by moshoujingli** [comment]
看到了熟悉的‘在一个CountDownLatch上await然后另外某个地方countDown’的操作。。。
果然这骚操作还真是哪都需要啊hhh

不过说实话，如果说都考虑用redux思想来搞的话，干脆就自己造个数据驱动的下拉刷新的轮子是不是更漂亮一点（逃

**Comment by danielwii** [comment]
请教一个问题，是否在 view 中可以使用 `StateBuilder` 来构建一个可以渲染自己的小组件，比如 [smooth_star_rating](https://pub.dartlang.org/packages/smooth_star_rating) 这个插件，他会产生大量的拖动事件，并且伴随着用户的拖动需要更新该组件的样式。

**Comment by zjuwjf** [comment]
> 请教一个问题，是否在 view 中可以使用 `StateBuilder` 来构建一个可以渲染自己的小组件，比如 [smooth_star_rating](https://pub.dartlang.org/packages/smooth_star_rating) 这个插件，他会产生大量的拖动事件，并且伴随着用户的拖动需要更新该组件的样式。


这两者并没有什么矛盾的地方。
- 一个是显示的调用setState
- 一个是通过reducer，由框架来触发变更。

```
/// view.dart
onRatingChanged(v) {
    dispatch(Action('RatingChanged', payload : v));
}

/// reducer
_onRatingChanged(state, action) {
    return state.clone()..rate = action.payload;
}
```

**Comment by danielwii** [comment]
奇怪的是我在使用 StateBuilder 的时候调用 setState 并没有触发组件的刷新。
另外确实可以使用 dispatch，但问题就在于他会产生大量的拖动事件，产生非常多的 dispatch。
还有一个状况，就是最新的 0.1.7 在使用的过程中也发现 reducer 没有触发 build，shouldUpdate 的日志显示的也是 true，最终退回了 0.1.6 的版本。

**Comment by zjuwjf** [comment]
> 奇怪的是我在使用 StateBuilder 的时候调用 setState 并没有触发组件的刷新。
> 另外确实可以使用 dispatch，但问题就在于他会产生大量的拖动事件，产生非常多的 dispatch。
> 还有一个状况，就是最新的 0.1.7 在使用的过程中也发现 reducer 没有触发 build，shouldUpdate 的日志显示的也是 true，最终退回了 0.1.6 的版本。

能给我一个可运行的demo么？  也许是测试用例里缺少这样的case。

**Comment by henry-hz** [comment]
@zjuwjf  thanks for the solution,
I found what would be a simpler solution in [this](https://github.com/bozaigao/fish-redux-demo/blob/master/lib/routes/home_module/home_page/view.dart) demo.

```
 onRefresh: () async {
                  return dispatch(HomeActionCreator.onRefresh());
                },
```

Let me suggest to add it to the documentation, it works perfectly. In fact, maybe the documentation should have a list of 'design-patters' with common solution for these cases.
