### ISSUE TITLE
是不是会有Intellij/Android Studio和VS Code的插件支持？

### ISSUE THREAD

**Issue by yohom** [alibaba/fish-redux#21]
记得之前在公众号上看到过会有插件支持？生成一部分样板代码。

**Comment by zjuwjf** [comment]
可能会提供插件支持，但这点不能给予保证。目前我们优先的工作会放在完善文档和使用说明上。以Android Studio为例，可以通过第三方插件PackageTemplates来自定义完成样板代码的生成。

**Comment by yohom** [comment]
OK，了解了，多谢开源，加油！

**Comment by TshineZheng** [comment]
@zjuwjf AS 上没有找到这个插件。用过 AS 自带的 Live Templates，想试试你提到的这个。

**Comment by huangjianke** [comment]
https://github.com/huangjianke/fish-redux-template

写了个比较简单的插件(VS Code)，有需要的可以试试

**Comment by zjuwjf** [comment]
> https://github.com/huangjianke/fish-redux-template
> 
> 写了个比较简单的插件(VS Code)，有需要的可以试试
> 
> @yohom @zjuwjf

非常感谢 @huangjianke 提供VSCode插件

Android Studio
可以安装 http://ceh9.github.io/PackageTemplates/

基本步骤是
1. 编写File Templates
2. 安装插件
3. 配置插件

enjoy ～

**Comment by zjuwjf** [comment]
> https://github.com/huangjianke/fish-redux-template
> 
> 写了个比较简单的插件(VS Code)，有需要的可以试试
> 
> @yohom @zjuwjf

用了下，非常不错。给个建议，是否可以把代码模版都完整生成了。
比如有
Action，ActionCreator, Effect, View, State，Component 等里面的代码样例。

**Comment by huangjianke** [comment]
感谢支持，这个后面优化下

目前也可以自定义模版文件

右键菜单，打开模版文件夹目录，替换为自己的模版





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by tom1918** [comment]
> > https://github.com/huangjianke/fish-redux-template
> > 写了个比较简单的插件(VS Code)，有需要的可以试试
> > @yohom @zjuwjf
> 
> 非常感谢 @huangjianke 提供VSCode插件
> 
> Android Studio
> 可以安装 http://ceh9.github.io/PackageTemplates/
> 
> 基本步骤是
> 
> 1. 编写File Templates
> 2. 安装插件
> 3. 配置插件
> 
> enjoy ～

我试用了你说的这个模板插件，按照教程试用但是发现 在创建模板文件的时候并不支持dart语言，仅支持 java和kotlin

**Comment by BakerJQ** [comment]
弄了一个Android Studio版的插件，有兴趣的话可以试试
https://github.com/BakerJQ/FishReduxTemplateForAS

@yohom @zjuwjf

**Comment by zjuwjf** [comment]
@huangjianke @BakerJQ 如果你们允许的话，我可以将你们的插件放在fish-redux的首页中 👏

**Comment by BakerJQ** [comment]
> @huangjianke @BakerJQ 如果你们允许的话，我可以将你们的插件放在fish-redux的首页中 👏

当然可以的 @zjuwjf

**Comment by huangjianke** [comment]
@zjuwjf 可以的，感谢支持。
另外，请问下，插件是否可以使用fish-redux当前的logo？

**Comment by tom1918** [comment]
> 弄了一个Android Studio版的插件，有兴趣的话可以试试
> https://github.com/BakerJQ/FishReduxTemplateForAS
> 
> @yohom @zjuwjf

谢谢你，但是我发现这个插件没法输入 Module name

**Comment by BakerJQ** [comment]
> > 弄了一个Android Studio版的插件，有兴趣的话可以试试
> > https://github.com/BakerJQ/FishReduxTemplateForAS
> > @yohom @zjuwjf
> 
> 谢谢你，但是我发现这个插件没法输入 Module name

你到我的repo下提个issue吧，在那讨论
