### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Mrjen** [alibaba/fish-redux#211]
安装fish-redux 0.1.6 , flutter 版本 1.5.9-pre.43抛出如下错误
`Because test >=1.6.1 <1.6.2 depends on test_core 0.2.3 and test >=1.3.0 <1.6.1 depends on stream_channel ^1.6.0, test >=1.3.0 <1.6.2 requires test_core 0.2.3 or stream_channel ^1.6.0.

And because test >=1.6.2 depends on test_core 0.2.4 and every version of flutter_test from sdk depends on stream_channel 2.0.0, if flutter_test any from sdk and test >=1.3.0 then test_core 0.2.3 or 0.2.4.

And because test_core >=0.2.2 depends on analyzer >=0.35.3 <0.37.0 and json_serializable 1.5.1 depends on analyzer >=0.32.2 <0.34.0, one of flutter_test any from sdk or test >=1.3.0 or json_serializable 1.5.1 must be false.

Because every version of deviceinfo from path depends on json_serializable ^1.5.1 and no versions of json_serializable match >1.5.1 <2.0.0, every version of deviceinfo from path requires json_serializable 1.5.1.

Thus, one of flutter_test any from sdk or test >=1.3.0 or deviceinfo from path must be false.

And because shauchi_app depends on fish_redux 0.1.6 which depends on test ^1.3.0, flutter_test from sdk is incompatible with deviceinfo from path.
So, because shauchi_app depends on both deviceinfo from path and flutter_test any from sdk, version solving failed.
pub get failed (1)`

**Comment by zjuwjf** [comment]
你试试 0.1.7 ？移动了对test的依赖。

**Comment by Mrjen** [comment]
可以了
