### ISSUE TITLE
如何监听到Adapter生命周期的appear|disappear

### ISSUE THREAD

**Issue by jefferybai** [alibaba/fish-redux#213]
我做了个测试

这是adapter
```
class ListAdapter extends DynamicFlowAdapter<CourseListState> {
  ListAdapter()
      : super(
          pool: <String, Component<Object>>{
            'week': WeekitemComponent(),
            'cs': CsitemComponent()
          },
          connector: _ListConnector(),
        );
}
```
这是CsitemComponent中的effect

```
Effect<Map> buildEffect() {
  return combineEffects(<Object, Effect<Map>>{
    CsitemAction.action: _onAction,
    Lifecycle.appear: _appre,
    Lifecycle.disappear: _appre
  });
}

void _appre(Action action, Context<Map> ctx) {
  print('_appre');
}
```
现在组件显示出来了，我滑动listview，却无法print _appre

**Comment by zjuwjf** [comment]
```dart 
CsitemAdaper extends Adaper with VisibleChangeMixin<T> {
    adapter: asAdapter(view),
    ...
}

```

Component生命周期是和自身widget-state是一直的，所以不会有appear和disappear。
adapter的生命周期会提升到和listview一样，所以会有appear和disappear。

**Comment by jefferybai** [comment]
@zjuwjf 
我的理解是， adaper抽象了appear和disappear两个功能能够控制绑定的component的创建和释放？StaticFlowAdapter绑定是单个Component, 而DynamicFlowAdapter绑定的是一个list， 那list上单个item就不能享受adaper的性能优化啦？

**Comment by zjuwjf** [comment]
> 我的理解是， adaper抽象了appear和disappear两个功能能够控制绑定的component的创建和释放？StaticFlowAdapter绑定是单个Component, 而DynamicFlowAdapter绑定的是一个list， 那list上单个item就不能享受adaper的性能优化啦？


抱歉这么久才回复。

Adapter分2大类

1. CustomAdapter
    你可以理解为它类似于Component， 只是Component 在UI上只能表达一个Widget， 而CustomAdapter 可以表达一组的Widget。

2. StaticFlowAdapter 和 DynamicFlowAdapter 是组装者的角色， 把一组Component或者Adapter的混合的集合，组装成一个更大的Adaper， 以供 ListView的使用。
    StaticFlowAdapter和DynamicFlowAdapter之间只有组装策略上的不同。
    - StaticFlowAdapter 
       组装的模版是Array， 而驱动的数据是Map。 
      它往往更加适合用于一些不那么像feeds(ListView)的场景。 比如一些详情, 它由非常多的小的模块顺序组合而成，有些条件下，显示[A, B, C, D], 有些条件下显示[A, C, E，F，G] 。 同时它的驱动的数据往往是一个maplike的对象，而非数组。它非常适合将负责的页面划分成非常独立的多个模块。

   - DynamicFlowAdapter 
     组装的模版是Map， 而驱动的数据是Array。
     这是最常见的长ListView的场景。

而 appear|disappear 又是怎么回事呢？
我们知道 flutter ListView里的widget是没有appear|disappear 事件的， 它只有init和dispose。

我们在做ListView的上层优化中，将每一个子项的Adapter的生命周期提升到和ListView一致。这带来一些好处：
- 模块业务完全独立。 
     子项的生命周期和ListView一致，所以每一个模块可以自己决定自己在什么实际去做数据的初始化。没有这个能力前， ListView的大量的逻辑都是耦合在ListView的容器中， 各个模块只是简单的展示模块。

- 额外得到了appear|disappear 事件
  但是这个需要做一个with VisibleChangeMixin<T>， 目前并没有放在默认的Adapter内部实现中。 

- 更加极致的性能优化。

**Comment by jefferybai** [comment]
看了您的回复， 进一步加深了， 对adapter的理解。
StaticFlowAdapter在模块不多的情况下也可以使用Component 下的dependencies  -> slots进行业务逻辑拆分。
web redux开发中 会有一个container和component的概念，一般在container中集中处理逻辑， 像StaticFlowAdapter这种拆解了ListView中的业务逻辑分发到每个big-cell中处理的方式确实让开发更加简单清晰。同时每个big-cell还能够获得appear|disappear事件。
