### ISSUE TITLE
如何只更新子组件UI通过Reducer并不通过Connector的set方式呢？

### ISSUE THREAD

**Issue by cbyniiaii** [alibaba/fish-redux#214]
```
Page(父)      ->     Component(子)
    |                         |
reducer                  reducer
   |                          |
state->     connector    <-state
```

如何只通过reducer修改子的state来达到子UI的更新
目前是在父state里引用子的state，然后通过Connector 的set方法来使父state.子state来更新。

引用一下 @danieldai  ：https://github.com/danieldai/fish_redux_simple_example 
#50

**Comment by zjuwjf** [comment]
你大概是想要多数据源（多store）的驱动？
如果是想要单一数据源的话，就不得不有connector。

**Comment by cbyniiaii** [comment]
对的。如何做得多store驱动呢？

**Comment by zjuwjf** [comment]
参考 #153
