### ISSUE TITLE
buildPage传参 initState没有调用

### ISSUE THREAD

**Issue by longgui0318** [alibaba/fish-redux#218]
相关关键代码如下
1、使用全局store的方式 
```dart
   AppRoutes(preloadedState: AppState.initialState(), pages:{
           "details":DetailsConn() + DetailsPage()
   });
```
2、路由实现
```dart
   onGenerateRoute: (RouteSettings item) {
      return MaterialPageRoute<Object>(builder: (BuildContext context) {
        return AppRoute.global.buildPage(item.name, item.arguments);
      });
    }
```
3、实际使用及传参
```dart
Navigator.of(viewService.context).pushNamed("details",arguments: {"id": 1});
```

4、状态初始化
```dart
DetailsState initState(Map<String, dynamic> args) {
  return DetailsState(args["id"]);
}
```

5、Page引用
```dart
import 'package:fish_redux/fish_redux.dart';

import 'effect.dart';
import 'reducer.dart';
import 'state.dart';
import 'view.dart';

class DetailsPage extends Page<DetailsState, Map<String, dynamic>> {
  DetailsPage()
      : super(
            initState: initState,
            effect: buildEffect(),
            reducer: buildReducer(),
            view: buildView);

}

```

问题描述：
    当界面跳转时，DetailsState 中的initState没有被调用到，请问，是否是我使用方式有问题呢。查看了相关的 Issues没有得到比较明确的答案，故提一个，望解答

**Comment by zjuwjf** [comment]
AppRoutes.pages 下注册的（从签名看）都是Component，所以并不会调用到Page的initState。
而你需要的是在对应的Component处，添加一个对 RouteAction.route 的reducer的处理（接受路由的入参）。

目前关于AppRoutes，文档还未增加。

设计成这样的根本原因是：
1. Page 是用来做 一个页面一个store的case， initState 函数是用来接收路由的参数，从而构建store的初始化state。

2. AppRoutes 是多页面共享一个store，它的初始state由preloadedState确立了。 而各个页面的state都是appState的一部分，通过各种的connector来获取。 当发生路由跳转， AppRoutes对应路由下的组件会收到一个RouteAction.route action，来处理对应的页面state的变化。

**Comment by longgui0318** [comment]
@zjuwjf 感谢，大概知道如何改了，不过，目前通过发一个RouteAction.route action的方式，感觉比较绕，也让代码可读性没有像fish-redux原本拆开的模块那么清晰了，后续是否会调整呢？

**Comment by zjuwjf** [comment]
> @zjuwjf 感谢，大概知道如何改了，不过，目前通过发一个RouteAction.route action的方式，感觉比较绕，也让代码可读性没有像fish-redux原本拆开的模块那么清晰了，后续是否会调整呢？

这个可能还需要大家更多的反馈，看要如何调整。 整体而言， Page是闲鱼内部通用的使用模式， AppRoutes是为了满足更多基于flutter为主的应用的单一数据源驱动多页面的模式， 我们内部还没有特别多的使用。
