### ISSUE TITLE
关于对effect的函数测试

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#221]
需要对effect的函数进行单元测试。使用mock的出得Context，在执行dispatch会出错。请问有没有比较合理的测试方法，或者demo。我是这样做的：
test.dart

```
class MockContext extends Mock implements Context<demoState> {}

void main() {
  group("login", () {

    test("inputFailEmail result email fail ", () {
      final mockContext=MockContext();
      Action action = demoActionCreator
          .onLoginAction(Map()..putIfAbsent("email", () => "1234")..putIfAbsent('password', ()=>"123456"));
      //需要mock dispatch函数
      when(mockContext.dispatch).thenReturn((action)=>"");
      //测试的登陆函数
      onLogin(action,mockContext);
      verify(mockContext.dispatch(demoActionCreator.onEmailFail()));
    });
  });
```

Effect.dart

```
Effect<demoState> buildEffect() {
  return combineEffects(<Object, Effect<demoState>>{
    demoAction.login: onLogin,
  });
}

void onLogin(Action action, Context<demoState> ctx) {
  ctx.dispatch(demoActionCreator.onEmailFail());

}
```

报错

NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'Action')

**Comment by zjuwjf** [comment]
> 需要对effect的函数进行单元测试。使用mock的出得Context，在执行dispatch会出错。请问有没有比较合理的测试方法，或者demo。我是这样做的：
> test.dart
> 
> ```
> class MockContext extends Mock implements Context<demoState> {}
> 
> void main() {
>   group("login", () {
> 
>     test("inputFailEmail result email fail ", () {
>       final mockContext=MockContext();
>       Action action = demoActionCreator
>           .onLoginAction(Map()..putIfAbsent("email", () => "1234")..putIfAbsent('password', ()=>"123456"));
>       //需要mock dispatch函数
>       when(mockContext.dispatch).thenReturn((action)=>"");
>       //测试的登陆函数
>       onLogin(action,mockContext);
>       verify(mockContext.dispatch(demoActionCreator.onEmailFail()));
>     });
>   });
> ```
> 
> Effect.dart
> 
> ```
> Effect<demoState> buildEffect() {
>   return combineEffects(<Object, Effect<demoState>>{
>     demoAction.login: onLogin,
>   });
> }
> 
> void onLogin(Action action, Context<demoState> ctx) {
>   ctx.dispatch(demoActionCreator.onEmailFail());
> 
> }
> ```
> 
> 报错
> 
> NoSuchMethodError: The method 'call' was called on null.
> Receiver: null
> Tried calling: call(Instance of 'Action')


```dart
verify(mockContext.dispatch);
```
dispatch 是一个字段。

**Comment by a398452027** [comment]
如果这样验证怎么知道action的类型是否正确了？

**Comment by zjuwjf** [comment]
> 如果这样验证怎么知道action的类型是否正确了？

抱歉这么久才回复，看上去是一个fish-redux的设计不合理，应该将dispatch变成是函数而非字段。
（虽然作为字段，对内部实现会更加简单）。

我会近期修复这个问题。

你们做针对Effect的单元测试，非常棒 ！

**Comment by a398452027** [comment]
你好,感谢您的修改，希望早日能更新版本。
还有一个问题，我看了一下你们的widget测试，大概知道了流程，现在又遇到一个坑，在测试网络请求的时候。在testWidgets里面在操作过程中有网络请求，但是在测试中执行都返回400，我用的dio执行的请求。例如我要effect中网络请求，请求的结果会导致发给reducer的action不同，这个怎么测试呢？如果用mock应该怎么操作了？不知道你们有没有遇到这种情况

**Comment by zjuwjf** [comment]
> 你好,感谢您的修改，希望早日能更新版本。
> 还有一个问题，我看了一下你们的widget测试，大概知道了流程，现在又遇到一个坑，在测试网络请求的时候。在testWidgets里面在操作过程中有网络请求，但是在测试中执行都返回400，我用的dio执行的请求。例如我要effect中网络请求，请求的结果会导致发给reducer的action不同，这个怎么测试呢？如果用mock应该怎么操作了？不知道你们有没有遇到这种情况

如果是mock， 是否可以
``` dart
 class MockDio extends Mock implements Dio {}
```

**Comment by a398452027** [comment]
思考了一下，可以mock 自己写的http工具类，来模拟返回Future，只不过现在只想到用静态变量的方式让effect和test都能设置这个工具类。大致是这样
```dart
class HttpRequest{
 Future<dynamic> post(){
  dio...
 }
}

class API {
   static HttpRequest request;
}

effect
void onLogin(Action action, Context<demoState> ctx) {
  API.request??=HttpRequest(API.BASE_URL);
}

test
class MockRequest extends Mock implements HttpRequest {}
 MockRequest mockRequest = MockRequest();
      API.request=mockRequest;
      String loginSuccessReslut='{"state"="success"}';
      when(mockRequest.post(any, any)).thenAnswer((_) => Future.value(json.decode(loginSuccessReslut)));
tester...


```
