### ISSUE TITLE
Page或者Component可以有继承关系么？

### ISSUE THREAD

**Issue by baij930312** [alibaba/fish-redux#224]
例如App中有很多页面有list都需要下拉刷新 加载更多 loading这种动作，如果在每个page的State和reduce中都定义相同的状态和方法是不是太过重复，对于这种情况有没有什么最佳实践？或者有类似js里边的high order之类的？

**Comment by baij930312** [comment]
另外想问一下大佬对Google IO上推荐的 provider 这个状态管理库什么看法，感觉像是对bloc的扩展，是否会是一个不错的选择？

**Comment by zjuwjf** [comment]
> 例如App中有很多页面有list都需要下拉刷新 加载更多 loading这种动作，如果在每个page的State和reduce中都定义相同的状态和方法是不是太过重复，对于这种情况有没有什么最佳实践？或者有类似js里边的high order之类的？

在类似上面的需求中，组合是比继承更好的，没有侵入性和灵活的解决方案。

比如
```dart
class ShellState<T> {
    T data;
    boolean isLoading;
    boolean isEmpty;
    ...
}

class ShellComponent<T> extends Component<ShellState<T>> {
    ShellComponent(
       Component<T> main,
       ):
        super(
            view: shellView,
            reducer: shellReducer,
           dependencies: {
               'main': shellConn() + main,
           }
        );
}
```

1. 你可以完成一个业务的组件  DetailComponent<T>。
2. 定义一个通过通用的包含多种状态（loading，empty，error）的ShellComponent<T>。
3. 然后以插槽参数的形式，将DetailComponent注入到ShellComponent。

**Comment by baij930312** [comment]
很棒的思路，把通用的状态封装在一个component中，子节点的组件就能派发ShellComponent的action去更新状态，避免了 很多重复的reducer，但是就我目前想到的场景，这样应该还是要在业务组件的state中定义isLoading和isEmpty 然后在conn中去关联，是否有可能让子节点的组件更简单的能够访问到父以及以上组件的state？ 例如以 Inheritedwidgets 的方式？

**Comment by baij930312** [comment]
另外 我发现在在ShellComponent初始化的需要传入业务组件'main'但是组件的参数关系是预先定义在conn中的，那是否意味着需要在state中定义component这样会不会导致问题变复杂。还有 在全局唯一store下 这些公共状态是只有一份的，也就是说多个组件公用的是同一个isLoading？这会不会导致一些不希望的结果..  :D

**Comment by zjuwjf** [comment]
> 还有 在全局唯一store下 这些公共状态是只有一份的，也就是说多个组件公用的是同一个isLoading？这会不会导致一些不希望的结果.. :D

#239 做了一些更好的数据驱动的灵活性

:D

由于语法的关系，上面的组合确实用起来确实不如JS方便。

可能让State去mixin 一个KV结构 会更加容易些。
