### ISSUE TITLE
问个关于生命周期的问题

### ISSUE THREAD

**Issue by chenxianqi** [alibaba/fish-redux#225]
创建一个page 我在初始化状态的时候 实例化一个ScrollController，然后在Effect>Lifecycle.initState生命周期里面去监听，实际上我在这里拿不到这个ScrollController对象，我通过把这个initState 加上async 异步延迟1秒才能拿到这个ScrollController对象，是我的写法有问题么？
![image](https://user-images.githubusercontent.com/27764334/57602083-c4dbf280-7590-11e9-8889-69acdfd842ea.png)

**Comment by zjuwjf** [comment]
> async

这个取决于你在哪里去赋值ScrollController对象。

**Comment by chenxianqi** [comment]
我在初始化状态的时候实例化滚动条对象

**Comment by chenxianqi** [comment]
> > async
> 
> 这个取决于你在哪里去赋值ScrollController对象。

![image](https://user-images.githubusercontent.com/27764334/57620546-a93a1180-75bb-11e9-8799-ae038b1d704a.png)
![image](https://user-images.githubusercontent.com/27764334/57620577-beaf3b80-75bb-11e9-8979-b197d213811f.png)

**Comment by chenxianqi** [comment]
知道问题，我没在clone里面处理

**Comment by chenxianqi** [comment]
确实拿不到对象看图片这里会报错，希望看看这是什么问题？
![image](https://user-images.githubusercontent.com/27764334/57623218-e4d7da00-75c1-11e9-8ddd-77e6909aaf45.png)
![image](https://user-images.githubusercontent.com/27764334/57623250-f9b46d80-75c1-11e9-86e6-20528e93857f.png)
最小的复现代码

// 状态
class HomeState implements Cloneable<HomeState>{
  ScrollController scrollViewController; // 滚动条控制器
  @override
  HomeState clone() {
    return HomeState()
   ..scrollViewController = scrollViewController;
  }
}

// 初始化数据
HomeState initState(Map<String, dynamic> args) {
  HomeState homeState = HomeState();
  homeState.scrollViewController = ScrollController();
  return homeState;
}

// Effect
Effect<HomeState> buildEffect() {
  return combineEffects(<Object, Effect<HomeState>>{
    Lifecycle.initState: _init,
  });
}

// initState 生命周期
void _init(Action action, Context<HomeState> ctx){
  print(ctx.state.scrollViewController.offset);
  // 监听滚动条
  ctx.state.scrollViewController?.addListener(() => _onScrollViewControllerAddListener(ctx));
}

**Comment by chenxianqi** [comment]
先打开，以便其他人查看
