### ISSUE TITLE
page里面复用同一个Component的问题

### ISSUE THREAD

**Issue by learyR** [alibaba/fish-redux#227]
The following assertion was thrown building Container:
I/flutter ( 9610): Duplicate keys found.
I/flutter ( 9610): If multiple keyed nodes exist as children of another node, they must have unique keys.
 I/flutter ( 9610): Column(direction: vertical, mainAxisAlignment: start, crossAxisAlignment: center) has multiple
 I/flutter ( 9610): children with key [<ReportComponent>].
 When the exception was thrown, this was the stack:

因为一个page里面有很多相似的Component，在复用Component的时候会出现这个错误。请问一下如何才能在一个page里面正确的多次加载相同的Component

**Comment by zjuwjf** [comment]
能贴下你的最小集代码么？

**Comment by learyR** [comment]
view里面
 Row(
          children: <Widget>[
            viewService.buildComponent('mine_course'),
            viewService.buildComponent('mine_student'),
            viewService.buildComponent('mine_lecture'),
          ],
        )
page里面
dependencies: Dependencies<MineState>(
              adapter: null,
              slots: <String, Dependent<MineState>>{
                'mine_course':
                    CourseProcessConnector() + CourseProcessComponent(),
                'mine_student':
                    CourseProcessConnector() + CourseProcessComponent(),
                'mine_lecture':
                    CourseProcessConnector() + CourseProcessComponent(),
              }),

事实上我在你们的example里面也这样试了，就是多次加载那‘report’的component，也会出现我遇到的错误

**Comment by learyR** [comment]
问题解决了，我在viewService.buildComponent('mine_course')外面再嵌套了一个Contair，这样一个避免了一个Widget中出现两个相同的Component。

**Comment by zsfbest** [comment]
如果我想添加这个Duplicate keys, 应该要怎么写
