### ISSUE TITLE
希望作者能比较详细的说一下redux和fish-redux的对比

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#228]
我们团队正准备用flutter完全重构现有的项目，正在选择状态管理框架。在bloc与redux对比中，我们认为redux对比较复杂的业务逻辑支持较好。所以现在确定是redux这个方向。但是在传统的redux和fish-redux中又开始纠结了。稍微简单的了解了这俩个框架（写了一些逻辑很简单的demo），觉得fish-redux模版代码较多，而且学习门槛更高，但是目前没有感受到fish-redux的优势，但是我相信闲鱼能用这个框架一定有它的优势，只是我现在不明确，希望作者能比较详细的对比传统的redux和fish-redux在复杂应用中，使用的不同和优势。我相信很多初入flutter的小伙伴，很多人都想知道。谢谢

**Comment by zjuwjf** [comment]
## 一、架构分层差异：
![image](https://user-images.githubusercontent.com/9562940/57896186-0b2b9d00-7882-11e9-8e26-7659c210cec7.png)

左图是fish-redux的分层设计，右图是传统的react-redux的分层。
虽然都使用了redux作为集中式的数据管理，但因为分层设计的差异，产生了下面的一些不同：

### 代码模块划分维度不同
   react-redux，同层的redux和component，开发者要同时维护redux和component的两个模块。redux 负责尽可能多的逻辑，component尽可能的是以dumb-component形态存在。

    fish-redux，通过两层设计，将Redux放在Component层的下面，这样面向开发者的是Component层。它的组件化为更加内聚（组件相关的代码都在组件内部），同时，redux的树形组织架构和component的树形组织架构有极大的重合度，框架自动省去了开发者自己组装维护Redux的繁琐。


### 他们都强调了逻辑和展现解耦
fish-redux是基于组件粒度内的解耦，react-redux是基于应用粒度的解耦。

简单总结是fish-redux上下两层设计的好处：
1. 组件内聚。
2. 结构复用。

### 但是也存在一定的缺点：
个别场景下，fish-redux结构灵活度不如react-redux结构（fish-redux使用者降低了对redux的依赖和把控）。

## 二. fish-redux 完善的插拔式组件化
这一层，相比其他的框架做的更近一步，让我们更加容易的处理复杂场景。

![image](https://user-images.githubusercontent.com/9562940/57897306-b8a0af80-7886-11e9-807b-389abb07fc13.png)
### 第一种是将大组件以插槽的形式，拆解成小的组件，对map 的形式，划分蛋糕。

![image](https://user-images.githubusercontent.com/9562940/57897463-657b2c80-7887-11e9-97d5-f15c69930068.png)
### 第二种是将面向ListView的场景，拆解成小的部件，对Array 的形式，划分模块。

第二种创新的方式，得到下面的一些好处：
1.  ListView下模块的更好的独立性和内聚
2. 更好的性能
3. 更多的生命周期事件

## 三. 更多
fish-redux 目前正在做的
   1. 继续完善之前推出的应用级别store的使用
   2. 更加完善的框架AOP能力
   3. 一定程度上的动态能力
   4. 对OOP的友好型

非常欢迎大家反馈在使用过程中的问题和意见。

**Comment by a398452027** [comment]
那我可以认为fish-redux与传统的redux，主要的优点组件可插拔和复用吗？

**Comment by zjuwjf** [comment]
> 那我可以认为fish-redux与传统的redux，主要的优点组件可插拔和复用吗？

1、组件内聚。
2、结构复用。
