### ISSUE TITLE
发布的框架里example，热更新不更新，非得手动点个按钮才行，要是没按钮就得重新跑了，好不方便。

### ISSUE THREAD

**Issue by chedechao111** [alibaba/fish-redux#23]
非得手动点个按钮执行个action，要是没按钮就得重新跑了，好不方便。

**Comment by chedechao111** [comment]
还是我使用的姿势不对。。Android studio 3.2，小米noti LTE API 6 ，flutter 1.0

**Comment by zjuwjf** [comment]
你提到的是hot-reload？ shift + r

**Comment by chedechao111** [comment]
是的

**Comment by chedechao111** [comment]
> 你提到的是hot-reload？ shift + r
是的

**Comment by hyjfine** [comment]
AS3.3, flutter1.2, XR模拟器运行demo也有这个现象，修改view代码，hot reload无效。
猜测原因：是数据驱动视图block了自带的hot reload机制？@zjuwjf
临时解决：用hot restart（对于小工程两者体验差不多），⚡️按钮旁边那个按钮
官方hot reload不支持的情况：https://flutter.dev/docs/development/tools/hot-reload#limitations

**Comment by chedechao111** [comment]
> AS3.3, flutter1.2, XR模拟器运行demo也有这个现象，修改view代码，hot reload无效。
> 猜测原因：是数据驱动视图block了自带的hot reload机制？@zjuwjf
> 临时解决：用hot restart（对于小工程两者体验差不多），⚡️按钮旁边那个按钮
> 官方hot reload不支持的情况：https://flutter.dev/docs/development/tools/hot-reload#limitations

emm，我的是怎样都hot reload无效，呃。。。问个题外话，你的flutter 1.2版本能跑api 6的安卓机型么，我的小米 note lte跑不起来。。

**Comment by hyjfine** [comment]
> > AS3.3, flutter1.2, XR模拟器运行demo也有这个现象，修改view代码，hot reload无效。
> > 猜测原因：是数据驱动视图block了自带的hot reload机制？@zjuwjf
> > 临时解决：用hot restart（对于小工程两者体验差不多），⚡️按钮旁边那个按钮
> > 官方hot reload不支持的情况：https://flutter.dev/docs/development/tools/hot-reload#limitations
> 
> emm，我的是怎样都hot reload无效，呃。。。问个题外话，你的flutter 1.2版本能跑api 6的安卓机型么，我的小米 note lte跑不起来。。

看了下是android目录下缺少build.gradle文件

**Comment by zjuwjf** [comment]
请提供可以复现的flutter环境，我们可以再check下。fish redux 不会去影响任何的flutter特性。

**Comment by chedechao111** [comment]
> 请提供可以复现的flutter环境，我们可以再check下。fish redux 不会去影响任何的flutter特性。
查了一下那个小米 note lte run起来是flutter 自身的问题，回到1.0版本就好了，不过sample在hot-reload在flutter 1.0，as 3.3下不会hot-reload，找个按钮点一下才会显示

**Comment by hyjfine** [comment]
复现的方式是，进到编辑页面，修改todo_edit_page下的view的appTitle字段：todo=》todoTest，点击hot reload，观察视图的title没有变化。点击editableFlied，界面刷新，字段显示正常。@zjuwjf

**Comment by zjuwjf** [comment]
感谢反馈，已经修复了
