### ISSUE TITLE
在appstate下connector的使用

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#230]
希望能回答一下，connector在appstate到pagestate这俩层中应该如何使用。例如我一个页面需要使用appstate中的主题颜色，
```dart
class DetailConn extends ConnOp<AppState, DetailPageState> {
  @override
  DetailState get(AppState state) {
    return state.detailPageState;
  }

  @override
  void set(AppState state, DetailPageState subState){
    state.detailPageState = subState;
  }
}
```
如果这样写，那我的appState，需要把要用到主题色字段的所有page的state都要持有才行，但是我的pagestate仅仅想要知道appState中一个color属性的更新，这样appState会不会太重了。下面的代码是我的一个想法。
```dart
class DetailConn extends ConnOp<AppState, DetailPageState> {
  @override
  DetailState get(AppState state,DetailPageState oldDetailPageState) {
    oldDetailPageState??=DetailPageState.initState();
    return oldDetailPageState.clone()..themeColor=state.themeColor;
  }

  @override
  void set(AppState state, DetailPageState subState){
    state.detailPageState = subState;
  }
}
```
如上，get函数能获得subState的当前状态，或者说最后一次的状态，如果是初始化则为null。

**Comment by zjuwjf** [comment]
> 如上，get函数能获得subState的当前状态，或者说最后一次的状态，如果是初始化则为null。

你的方案，也是目前在准备的方案之一，来解决AppRoutes在一些路由下会产生多个重复页面的问题。
通过(1)绑定应用级别的store和(2)页面级别store的更新关系，来得到统一的数据驱动。

现阶段，还是更加推荐使用PageRoutes，如果有需要公共的数据驱动，可以单独写一个静态的store，然后在需要的组件里订阅它的变化。

**Comment by a398452027** [comment]
好的，谢谢
但是静态的store，然后在需要的组件里订阅它的变化。貌似文档没有给出相应的写法。能不能写个简单的例子了？

**Comment by zjuwjf** [comment]
> 好的，谢谢
> 但是静态的store，然后在需要的组件里订阅它的变化。貌似文档没有给出相应的写法。能不能写个简单的例子了？

#239

数据驱动提供了更大的灵活性。

1、Page-Store可以订阅任意其他store的变化
```
const Store<AppState> appStore = ...;

MainRoutes extends HybridRoutes {
  MainRoutes():super(
    routes: [
      PageRoutes(
        pages: <String, Page<Object, dynamic>>{
          'home': HomePage()..connectExtraStore<AppState>(appStore, (HomeState homeState, AppState appState) {
                return homeState.clone().. themeColor = appState.themeColor;
            },
          ),
          'detail': DetailPage(),
        },
      ),
    ]
  );
}
```
这里依然强调数据流的单向性。
AppState的数据变更，推送到PageStore，引起PageState的变更与否，再由PageState的变更推送到所有页面内的组件的UI变更。



2、任意组件可以订阅任意其他store的变化
```
const Store<AppState> appStore = ...;

///effect.dart
void _init(Action action, Context<T> ctx) {
    ctx.bindObserver(appStore.subscribe);
}
```
这里强调了订阅变化的灵活性。
一个组件如果需要看到不同的数据源，可以接收不同数据源的合力驱动。比如一些ab驱动，appstore的驱动。


两种方式都是为了更加灵活的解决数据驱动的问题，弥补在少数场景下PageStore的缺陷。

**Comment by chenxianqi** [comment]
大佬0.18去掉了page onError吗

**Comment by zjuwjf** [comment]
> 大佬0.18去掉了page onError吗

设计上都统一到那几个middleware了，这样会让上层更加灵活的自定义。

你们之前使用了onError么？

**Comment by chenxianqi** [comment]
> > 大佬0.18去掉了page onError吗
> 
> 设计上都统一到那几个middleware了，这样会让上层更加灵活的自定义。
> 
> 你们之前使用了onError么？

好的，我改，少部分页面用到了
