### ISSUE TITLE
现在不定数量的page有解决办法吗？

### ISSUE THREAD

**Issue by ykrank** [alibaba/fish-redux#232]
现在有这样一个简化的需求。一开始从服务器拉取一个list数据，里面是A[a1, a2, a3......an]。现在显示一个page，对应数据集是a1，里面有个按钮，一个输入框。输入框中填入index，点击按钮就跳转到一个新的page，对应的数据集是A[index]，并且以此类推，不断输入index，不断跳转到新的page。最后按返回键依次返回上一个。
不知道是不是我对这框架认知错误，我看了很多遍源码，也没找到在使用approutes时有解决办法。或者这种情况下只能使用多 store，那么该怎么实现呢？

开发App使用fish-redux，因为这个原因，已经停顿了很久，如果按照框架设计本来就不打算支持这种情况，那我也好早点放弃了。

**Comment by zjuwjf** [comment]
非常抱歉才回复这个问题。

用PageRoutes会有什么问题？

**Comment by ykrank** [comment]
> 非常抱歉才回复这个问题。
> 
> 用PageRoutes会有什么问题？是这些页面需要公用一部分state么？
> 
> AppRoutes 在处理多个重复页面的case下，是有缺点的，这个问题在ReduxJS也同样存在。
> 
> 方案一：对原有的AppRoutes做一个尽可能小的改动，让它可以注册一个App级别的store， 而页面也可以存在一个独立的store， 框架负责维持这两个store之间的更新纽带？
> 
> 方案二：对Context 增加一个observe(store)的api， 可以让组件定制需要接收的额外的store的驱动？
> 
> 哪一种会是期望的样子？

感谢回复。
这两种方案都可以接受。方案一更符合AppRoutes现在的需求，而方案二更开放了，感觉可以同时解决之后很多没想到的需求。

**Comment by ykrank** [comment]
目前是直接使用AppRoutes的，因此对PageRoutes不熟，如果PageRoutes能解决这个需求的话，我就暂时考虑先用PageRoutes实现了，和现在的AppRoutes的同步使用广播不知道有没有问题。

**Comment by zjuwjf** [comment]
> 目前是直接使用AppRoutes的，因此对PageRoutes不熟，如果PageRoutes能解决这个需求的话，我就暂时考虑先用PageRoutes实现了，和现在的AppRoutes的同步使用广播不知道有没有问题。

如果是自己自定义的广播，当然没问题。 
如果是希望PageRoutes和AppRoutes之间（参考它们的构造函数）通过框架来完成的，通过DispatchBus也是互通的。
