### ISSUE TITLE
如何定义多个store?

### ISSUE THREAD

**Issue by hightfly** [alibaba/fish-redux#234]
Page(父)      ->     Component(子)
    |                         |
reducer                  reducer
   |                          |
state->     connector    <-state

父组件和子组件各有各自的store . 如何让两个store 相关更新呀 ?

**Comment by zjuwjf** [comment]
> Page(父) -> Component(子)
> | |
> reducer reducer
> | |
> state-> connector <-state
> 
> 父组件和子组件各有各自的store . 如何让两个store 相关更新呀 ?

目前父组件和子组件是公用一个store。
