### ISSUE TITLE
ctx.broadcastEffect 和 ctx.broadcast 有什么区别?

### ISSUE THREAD

**Issue by hightfly** [alibaba/fish-redux#237]
在子组件通过ctx.broadcastEffect 发送action 时, 在父组件的Effect 中能够接收到.但是,Reducer中接收不到. 
在使用ctx.broadcast 发送的action 时 在父组件中的effect 和 Reducer 都接收不到action.  
 ctx.broadcastEffect 和 ctx.broadcast 有什么区别?
希望 文档和 example  文件全, 把一些常用的重要特性. 能够通过案例. 说明一下.

**Comment by chenxianqi** [comment]
dispath搞定

**Comment by zjuwjf** [comment]
Duplicate of #235
