### ISSUE TITLE
Should We have an example about Authentication?

### ISSUE THREAD

**Issue by phattranky** [alibaba/fish-redux#238]
Does anyone know the right way to Store global State or share the state like Authentication Data with Fish Redux. I search many places but seems all our examples is only the independency store pages. Thanks in advance.

**Comment by chenxianqi** [comment]
Packing one AppProvide

**Comment by zjuwjf** [comment]
#239

Two more flexible data-driven methods are available, now.

1. PageStore can subscribe to any other store changes.
Maybe this is what you are looking for.
```
const Store<AppState> appStore = ...;

MainRoutes extends HybridRoutes {
  MainRoutes():super(
    routes: [
      PageRoutes(
        pages: <String, Page<Object, dynamic>>{
          'home': HomePage()..connectExtraStore<AppState>(appStore, (HomeState homeState, AppState appState) {
                return homeState.clone().. themeColor = appState.themeColor;
            },
          ),
          'detail': DetailPage(),
        },
      ),
    ]
  );
}
```

The unidirectional nature of the data flow is still emphasized here.
AppState data changes, pushed to PageStore, causing PageState changes or not, if PageState changes, and then pushed to the UI of the components in all pages.



2. Any component can subscribe to any other store changes
```
const Store<AppState> appStore = ...;

///effect.dart
void _init(Action action, Context<T> ctx) {
    ctx.bindObserver(appStore.subscribe);
}
```

The flexibility of subscription changes is highlighted here.
A component can receive the combined drive of different data sources if it needs to see different data sources. For example, from the ab-test driver, from the AppStore driver.


Both methods are designed to more flexibly solve data-driven problems and make up for the defects of PageStore in a few scenarios.

**Comment by phattranky** [comment]
Many thanks, @chenxianqi, especially @zjuwjf for the quick response and very useful MR right time

**Comment by chenxianqi** [comment]
It's like creating a page.
No page view component is required

**Comment by chenxianqi** [comment]
![image](https://user-images.githubusercontent.com/27764334/58106986-96f34f80-7c1b-11e9-9b3c-a4c16e39f9a2.png)
Look at my catalogue

**Comment by chenxianqi** [comment]
![image](https://user-images.githubusercontent.com/27764334/58107099-c6a25780-7c1b-11e9-83cf-f55da290dc7e.png)
This index is the output single column

**Comment by zjuwjf** [comment]
> @zjuwjf one more concern. it's a doubt, But can you help me clarify, How can I create a global separate Store like your example `const Store<AppState> appStore = ...;` Don't know what is behind the sign `...`

Sorry for using vague symbols, which makes confused.

You could create a store via createStore<T>(T state, Reducer<T> reducer) api.

**Comment by phattranky** [comment]
Many Thanks, @chenxianqi  and @zjuwjf. I'm clear now

**Comment by wilfordw** [comment]
> Refer to #239
> 
> Two more flexible data-driven methods are available, now.
> 
> 1. PageStore can subscribe to any other store changes.
>    Maybe this is what you are looking for.
> 
> ```
> const Store<AppState> appStore = ...;
> 
> MainRoutes extends HybridRoutes {
>   MainRoutes():super(
>     routes: [
>       PageRoutes(
>         pages: <String, Page<Object, dynamic>>{
>           'home': HomePage()..connectExtraStore<AppState>(appStore, (HomeState homeState, AppState appState) {
>                 return homeState.clone().. themeColor = appState.themeColor;
>             },
>           ),
>           'detail': DetailPage(),
>         },
>       ),
>     ]
>   );
> }
> ```
> 
> The unidirectional nature of the data flow is still emphasized here.
> AppState data changes, pushed to PageStore, causing PageState changes or not, if PageState changes, and then pushed to the UI of the components in all pages.
> 
> 1. Any component can subscribe to any other store changes
> 
> ```
> const Store<AppState> appStore = ...;
> 
> ///effect.dart
> void _init(Action action, Context<T> ctx) {
>     ctx.bindObserver(appStore.subscribe);
> }
> ```
> 
> The flexibility of subscription changes is highlighted here.
> A component can receive the combined drive of different data sources if it needs to see different data sources. For example, from the ab-test driver, from the AppStore driver.
> 
> Both methods are designed to solve data-driven problems more flexibly and make up for the defects of PageStore in a few scenarios.

```dart
const Store<AppState> appStore = ...;

///effect.dart
void _init(Action action, Context<T> ctx) {
    ctx.bindObserver(appStore.subscribe);
}
```
this way only support for component? I could't get view update when using it in page
