### ISSUE TITLE
page和component关系

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#240]
一个component许多地方用到，每个page都要创建一个conn吗，可不可以把conn放在component的state中呢，这样就不用每个page都加入conn

**Comment by zjuwjf** [comment]
1、可以让 PageState mixin MapLike， 得到数据结构，一定的灵活性。
2、面向MapLike 写这个component的conn。
3、各个Page下复用conn & component。

**Comment by xfhomedream** [comment]
谢谢，有实例吗？有点明白，但是具体还是有点不怎么会实现。

**Comment by hzgotb** [comment]
#248

**Comment by hzgotb** [comment]
> 1、可以让 PageState mixin MapLike， 得到数据结构，一定的灵活性。
> 2、面向MapLike 写这个component的conn。
> 3、各个Page下复用conn & component。

如果用 `MapLike` 的话，还能精确到某个数据改变吗？

**Comment by xfhomedream** [comment]
`
mixin LoginState on MapLike implements Cloneable<LoginState> {
  @override
  Object operator [](String key) {
    return null;
  }

  @override
  void operator []=(String key, Object value) {}

  @override
  void clear() {}

  @override
  LoginState clone() {
    return null;
  }

  @override
  bool containsKey(String key) {
    return null;
  }

  @override
  void copyFrom(MapLike from) {}
}

class LoginPageState extends MapLike with LoginState {}

LoginPageState initState(Map<String, dynamic> args) {
  return new LoginPageState();
}
`
我这样写有问题吗

**Comment by zjuwjf** [comment]
> > 1、可以让 PageState mixin MapLike， 得到数据结构，一定的灵活性。
> > 2、面向MapLike 写这个component的conn。
> > 3、各个Page下复用conn & component。
> 
> 如果用 `MapLike` 的话，还能精确到某个数据改变吗？

当然可以， MapLike 只是一种更加接近JS的对象模式。

**Comment by xfhomedream** [comment]
但是我这里写的估计是有问题，报这个错误`The following assertion was thrown building MyApp(dirty):
I/flutter (16058): type '_Dependent<MapLike, TextFieldState>' is not a subtype of type 'Dependent<LoginState>'
I/flutter (16058): `
组件安装地方是这样的：
`import 'effect.dart';
import 'reducer.dart';
import 'state.dart';
import 'view.dart';

class LoginPage extends Page<LoginState, Map<String, dynamic>> {
  LoginPage()
      : super(
          initState: initState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          dependencies: Dependencies<LoginState>(
              adapter: null,
              slots: <String, Dependent<LoginState>>{
                "user": TextFieldStateConnOp(initTextFieldState) + TextFieldComponent(),
                "pwd": TextFieldStateConnOp(initTextFieldState) + TextFieldComponent(),
              }),
          middleware: <Middleware<LoginState>>[],
        );
}
`
组件的state：
`import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/widgets.dart';

class TextFieldState implements Cloneable<TextFieldState> {
  bool userClearEnable = false; //账号输入框是否显示清除按钮
  bool enable = false;
  TextEditingController userController;
  String hintText = "手机号/邮箱";
  String text = "";

  @override
  TextFieldState clone() {
    print("TextFieldState clone $userClearEnable");
    return TextFieldState()
      ..userClearEnable = userClearEnable
      ..userController = userController
      ..text = text
      ..enable = enable
      ..hintText = hintText;
  }
}

TextFieldState initTextFieldState(MapLike mak) {
  return TextFieldState()
    ..enable
    ..text;
}

class TextFieldStateConnOp<T extends MapLike>
    extends AutoInitConnector<T, TextFieldState> {
  TextFieldStateConnOp(init) : super(init);

  @override
  void set(MapLike state, TextFieldState subState) {
    state["subState"] = subState;
    super.set(state, subState);
  }

  @override
  TextFieldState get(MapLike state) {
    final TextFieldState reportState = TextFieldState();
    reportState.text = "";

    var enable = reportState.enable;
    print("BtnConnector get enable>>>>>>>$enable");
    return reportState;
  }
}
`

**Comment by zjuwjf** [comment]
> 
> 我这样写有问题吗

```dart
class LoginPageState with MapLike implements Cloneable<LoginPageState> {
       /// your code here
}

class MapLikeConnector<T extends MapLike, P> extends ConnOp<T, P> {
  static int _nextId = 0;

  final String key;
  final P Function(T state) init;

  MapLikeConnector({this.init, String key}) : key = key ?? (_nextId++);

  @override
  P get(T state) =>
      state.containsKey(key) ? state[key] : (state[key] = init(state));

  @override
  void set(T state, P subState) => state[key] = subState;
}

**Comment by xfhomedream** [comment]
好的谢谢！

![image](https://user-images.githubusercontent.com/14237960/59204437-354b5300-8bd3-11e9-8f14-07184a50842c.png)
这个地方这样写的吗

**Comment by zjuwjf** [comment]
> 好的谢谢！
> 
> ![image](https://user-images.githubusercontent.com/14237960/59204437-354b5300-8bd3-11e9-8f14-07184a50842c.png)
> 这个地方这样写的吗

需要增加范型约束

```
'btn': MapLikeConnOp<LoginState, ButtonState>() + ButtonComponent()
```

**Comment by xfhomedream** [comment]
已解决，非常感谢你
