### ISSUE TITLE
升级了fish-redux0.1.8之后 程序报错

### ISSUE THREAD

**Issue by CoolBerry** [alibaba/fish-redux#243]
E/flutter (28347): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This ComponentWidget<MainPageState> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter (28347): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (28347):   ComponentWidget<MainPageState>-[<MainPagePage>](state: ComponentState<MainPageState>#eab34)

之前代码都是好好的，升级了之后就报错了。
报错的是在Component的effect里面，Lifecycle.initState的时候执行了一个reducer的时候报错的，具体更细节的话就是这个component的是appstate下面的一个component的，与appstate有get，set的方法。
怀疑是flutter的这次更新与fish redux的某些逻辑产生了冲突。

多谢解答！

**Comment by CoolBerry** [comment]
补充一下，我又用我们fish redex的example测试了一下，似乎是通过dependencies 然后 slots 这样子的component的里面的effect，在initState这个生命周期时候就没法dispatch来更新state。自定义的action应该OK，其他生命周期函数还没有测。

**Comment by CoolBerry** [comment]
更新一下，好像是fish-redux0.1.8的问题，回退到0.1.7之后报错消失。暂时是这样，flutter我也回退到最新的一个stable版本，1.5.4hotfix2版本。之后的不清楚情况，可能跟flutter关系不大。

**Comment by zjuwjf** [comment]
非常感谢反馈，能提供一个能复现这个问题的最小集的demo么？
