### ISSUE TITLE
支持Flutter for web 吗？

### ISSUE THREAD

**Issue by cbyniiaii** [alibaba/fish-redux#247]
引入的包变了：
import 'package:flutter_web/material.dart';

可以支持不？

**Comment by zjuwjf** [comment]
> material

fish-redux框架并不依赖material等上层UI，理论上是支持ffw的。

如果有问题，欢迎反馈。

**Comment by cbyniiaii** [comment]
```
/Users/dengyongdong/fish-redux/lib/src/redux_component/basic.dart
import 'package:flutter/widgets.dart';

Flutter for web 里是使用
import 'package:flutter_web/widgets.dart';

```

**Comment by zjuwjf** [comment]
感谢反馈 我会近期调整看是否能比较简单的适配ffw。

**Comment by zjuwjf** [comment]
flutter_web目前还是Flutter的一个分支。
这意味着，在此期间支持flutter_web，所有Flutter pub都需要创建自己的forks，然后导入flutter_web而不是导入flutter，然后在pub上提供两个不同的包，类似于fish_redux和fish_redux_web。

如果在此期间，你有诉求的话，我的建议是fork一份fish_redux， 然后修改里面的相关的import。

但克隆将为社区带来很多开销。我们应该等待flutter_web正确地合并到Flutter中。所以包括fish_redux在内的包都可以正常工作而不需要这种类型的修改。

希望flutter_web很快就能融合起来！

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/fish-redux  可以git方式引入 我给改了下 等正式版发布了 可以再换导包

**Comment by HappyGhostz** [comment]
麻烦问一下  现在可以支持了吗  1.9

**Comment by HappyGhostz** [comment]
@zjuwjf

**Comment by zjuwjf** [comment]
@HappyGhostz 一直支持。

**Comment by HappyGhostz** [comment]
好的  谢谢
但在我现在的版本  flutter：1.7.8+hotfix.4  fish_redux:0.2.6  
使用context 会报context的路径不对  viewService.context是flutter的context  但需要的是flutter_web的
MediaQuery.of(viewService.context).size.height - 80

在flutter1.9一下  只有像上面的那种解决放法吗？

**Comment by HappyGhostz** [comment]
@zjuwjf    谢谢

**Comment by zjuwjf** [comment]
@HappyGhostz 不是很清楚你的问题，可以新开一个issue，详细描述下。如何可以，加个demo。
