### ISSUE TITLE
page变量问题

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#248]
component访问page中的变量只能同过conn吗

**Comment by chenxianqi** [comment]
yes，只能以数据流传递

**Comment by xfhomedream** [comment]
谢谢

**Comment by zjuwjf** [comment]
fish-redux 的数据驱动是store 扁平的通知到各个组件。
## 1. 组件如何确定自己要刷新
默认是根据组件的state是不是同一个对象的引用来决定。（除非我们自定义shouldUpdate）
这里会有几个关注点：
a）如果我们直接修改state.field 将会判断为同一个对象，所以我们需要clone或其他手段，在reducer函数中返回新的state。（它的上级state，上上级state的clone，是框架自动会处理的）。
b）组件的state如何而来？它是通过我们配置的connector.get 而来。如果我们的get函数永远返回一个新的对象，它不是最佳实践，带来多余的组件刷新。这种情况下要考虑使用reselect来将上级state的若干要素，只有在对应要素发生变化的情况下才会生成新的下级state。

## 2. 在PageStore的场景下
1. 组件如何确定自己要刷新
这里和上面的规则是一样的

2. 如何让appstore的变化也能精确驱动组件的变化
这里的精确指的是，只有在对应要素发生变化的时候才发生刷新。
a）将AppState 和 PageState 进行链接， 当AppState里有PageState关心的要素发生变化时，自动计算出最新PageState。
b）PageState的精确变化，驱动关心了PageState里对应要素的任意组件发生刷新。
这个过程是精确而清晰的。

所以核心来看，fish-redux中的数据驱动的核心是connector。
理解Connector，就能真正理解fish-redux。

**Comment by hzgotb** [comment]
问题1：getSub0从父组件获取值后，是不是会作为computed的参数？
问题2：子组件的`State`是不是必须要声明一个属性去接收父组件的值？就好像下面`Connector`的computed的行为。
问题3： 如果按下面的写法，在父组件值更新时，子组件原本有的状态会被丢弃。我应该怎么写才能确保子组件的原本的状态依旧有效。

```dart
// lib/home_page/app_bar_component/state.dart

import '../state.dart';

class AppBarState implements Cloneable<AppBarState> {

  TabController tabController;

  @override
  AppBarState clone() {
    final AppBarState state = new AppBarState();
    return state;
  }
}

// 通过此`Connector`从父组件`HomePage`获取数据
class AppBarConnector extends Reselect1<HomeState, AppBarState, TabController> {
  @override
  AppBarState computed(TabController sub0) {
    return new AppBarState()..tabController = sub0;
  }

  @override
  TabController getSub0(HomeState state) {
    return state.tabController;
  }

  @override
  void set(HomeState state, AppBarState subState) {
    // TODO: implement set
  }
}
```

**Comment by chenxianqi** [comment]
1.是对数据的clone 
2.需要声明去链接
3.我认为你需要一个独立的store 处理

**Comment by chenxianqi** [comment]
状态声明在page state 里，然后在con,处理set和get，事件可以在子组件完成

**Comment by hzgotb** [comment]
> 状态声明在page state 里，然后在con,处理set和get，事件可以在子组件完成

意思是，我需要把子组件的状态备份到父组件中，是吗？

**Comment by chenxianqi** [comment]
应该是说你一个页面的状态都应该放在page state 里，通过链接传递给子组件，如果需要使用全局的状态你可以参考0.18的新特性

**Comment by hzgotb** [comment]
所以意思是：
`Page`有一个`State`，然后`Page`的所有子组件的`State`是托管在`Page`的`State`里的，而子组件自身的`State`是作为`Page`的`State`里属于子组件部分的链接，子组件改变状态，设置自身`State`，然后框架就会通过`connector`将数据同步到`Page`上，而`Page`修改子组件的状态，也会通知`connector`通知子组件。

**Comment by chenxianqi** [comment]
是的，还有你要想达到在子组件修改能同步到page state你应该在connector的set方法里做相应的操作

**Comment by hzgotb** [comment]
好的。谢谢

**Comment by hzgotb** [comment]
有问题。既然如此，组件其实可以不需要state啊。直接从page拿就行了，为什么还要做个链接。

**Comment by chenxianqi** [comment]
这就是所谓的分治的所在？

**Comment by xfhomedream** [comment]
组件的数据更新了 你的page里面的数据没更新啊

**Comment by hzgotb** [comment]
> 组件的数据更新了 你的page里面的数据没更新啊

set那一步没写。上面的代码只是表达一下我的疑惑。

**Comment by hzgotb** [comment]
> 这就是所谓的分治的所在？



如果是分治的话，为什么我还需要在page上做component的状态。page的状态，和component的状态分开，两者通过connector进行通讯，不应该是这样的吗？

如下面 @zjuwjf 所说的b点来看，子组件的状态是从connector拿到的。

connector的数据是子组件本身的状态+页面传过来的状态组成。现在我所知道的有两个方式定义connector。一种是ConnOp，另外一种是Reselect。ConnOp的get总是返回一个新的子组件状态。而Reselect是当页面传进来值有改变时，才通过computed去计算出新的子组件状态。

但问题是，这两种方式都无法保留子组件的原本状态，从目前的情况看来就是子组件没有自身的内部状态，以为着子组件所有的状态都应该暴露出去，托管到页面。

不知道这样理解正不正确。如果正确的话，从前端的角度来看，会有点别扭。因为无论是`React`还是`Vue`。子组件从`props`属性接受从父组传进来的值，子组件自身也有状态。

> fish-redux 的数据驱动是store 扁平的通知到各个组件。
> 
> ## 1. 组件如何确定自己要刷新
> 默认是根据组件的state是不是同一个对象的引用来决定。（除非我们自定义shouldUpdate）
> 这里会有几个关注点：
> a）如果我们直接修改state.field 将会判断为同一个对象，所以我们需要clone或其他手段，在reducer函数中返回新的state。（它的上级state，上上级state的clone，是框架自动会处理的）。
> b）组件的state如何而来？它是通过我们配置的connector.get 而来。如果我们的get函数永远返回一个新的对象，它不是最佳实践，带来多余的组件刷新。这种情况下要考虑使用reselect来将上级state的若干要素，只有在对应要素发生变化的情况下才会生成新的下级state。
> 
> ## 2. 在PageStore的场景下
> 1. 组件如何确定自己要刷新
>    这里和上面的规则是一样的
> 2. 如何让appstore的变化也能精确驱动组件的变化
>    这里的精确指的是，只有在对应要素发生变化的时候才发生刷新。
>    a）将AppState 和 PageState 进行链接， 当AppState里有PageState关心的要素发生变化时，自动计算出最新PageState。
>    b）PageState的精确变化，驱动关心了PageState里对应要素的任意组件发生刷新。
>    这个过程是精确而清晰的。
> 
> 所以核心来看，fish-redux中的数据驱动的核心是connector。
> 理解Connector，就能真正理解fish-redux。

**Comment by chenxianqi** [comment]
您的理解是正确的，fish redux框架还是强调数据流,你可以这样理解fish redux保留了js redux的所有优点，一个PAGE 就是一个store，当然你也可以创建一个全局的store来提供全局可用共享state, 什么是数据流，我认为您也比较了解，框架文档也对各个概念描述的比较清楚了，我也刚接触fish redux，和您差不多的一个水平，技术的提升离不开社区的探讨与研究

**Comment by hzgotb** [comment]
嗯嗯。谢谢。不过因为不是开发的人，文档也不齐全，所以暂时不知道这个是没考虑到的点，还是框架自身就是这样设计的。

**Comment by zjuwjf** [comment]
@hzgotb 
1. 组件没有自身局部状态
 - 组件的所有状态的定义来自于组件定义的state。

2. 组件的state 来自于上一级的组件state（通过connector表达数据映射关系），最终来自于store。

3. ConnOp & Reselect
- ConnOp 适合用在上级的state中已经声明了子state的字段的情况，它就是一个简单的get／set。
- Reselect 适用于需要根据上级的state中一个或者若干个要素，合并成一个新的sub-state的情况。（作用是做最精确的刷新控制）。

**Comment by hzgotb** [comment]
了解。谢谢。我觉得这个概念应该要写进文档里面。

**Comment by zjuwjf** [comment]
> 有问题。既然如此，组件其实可以不需要state啊。直接从page拿就行了，为什么还要做个链接。

组件是独立的单元，它可以在PageA<A>下，也可以是ComponentB<B>下。
它不关心是在哪里被使用到，它不关心对应的store的state是什么。
组件Component<T>,  只要关心自己的T就够了。

**Comment by ikonan** [comment]
你好, 我现在有个一个问题,我有一个 页面级变量, 比如说 scrollController, 需要监听滚动的偏移量在,我这个变量要放到 state 中么, 但是state中的其他数据改变 都会将state拷贝一份,然后 scrollController 变量就会导致监听失效. 这个问题我应该怎么解决了. 谢谢.

**Comment by zjuwjf** [comment]
> 但是state中的其他数据改变 都会将state拷贝一份,然后 scrollController 变量就会导致监听失效. 这个问题我应该怎么解决了. 谢谢.

1、 建议也将scrollController放入 state中
2、 你的监听失败是指？ 监听了一个过期的state？ 那你可以监听ctx.state， 它永远是最新的state。

**Comment by ikonan** [comment]
> > 但是state中的其他数据改变 都会将state拷贝一份,然后 scrollController 变量就会导致监听失效. 这个问题我应该怎么解决了. 谢谢.
> 
> 1、 建议也将scrollController放入 state中
> 2、 你的监听失败是指？ 监听了一个过期的state？ 那你可以监听ctx.state， 它永远是最新的state。

谢谢你的回答,但是我还有个疑问,我的scrollController 监听初始化是放到 effect 的初始化方法里面么, 每次state 的更新, 会不会执行effect 的初始化都重新去添加监听 @zjuwjf

**Comment by zjuwjf** [comment]
不会。state的变化，会处罚UI的刷新，但不会再次处罚initstate。

**Comment by ikonan** [comment]
> 不会。state的变化，会触发UI的刷新，但不会再次触发initstate。
那么 scrollController.addListener() , 我放在initState, 中途 state.clone 了 scrollController.addListener() 这个方法就会不执行了 @zjuwjf

**Comment by zjuwjf** [comment]
> > 不会。state的变化，会触发UI的刷新，但不会再次触发initstate。
> > 那么 scrollController.addListener() , 我放在initState, 中途 state.clone 了 scrollController.addListener() 这个方法就会不执行了 @zjuwjf

可以单独提一个issue， 附下上下文代码。

**Comment by hzgotb** [comment]
> @hzgotb
> 
> 1. 组件没有自身局部状态
> 
> * 组件的所有状态的定义来自于组件定义的state。
> 
> 1. 组件的state 来自于上一级的组件state（通过connector表达数据映射关系），最终来自于store。
> 2. ConnOp & Reselect
> 
> * ConnOp 适合用在上级的state中已经声明了子state的字段的情况，它就是一个简单的get／set。
> * Reselect 适用于需要根据上级的state中一个或者若干个要素，合并成一个新的sub-state的情况。（作用是做最精确的刷新控制）。

如果子组件使用`Connector`的话，那他的`initState`方法还有用吗？

**Comment by huang12zheng** [comment]
> > 有问题。既然如此，组件其实可以不需要state啊。直接从page拿就行了，为什么还要做个链接。
> 
> 组件是独立的单元，它可以在PageA下，也可以是ComponentB下。
> 它不关心是在哪里被使用到，它不关心对应的store的state是什么。
> 组件Component<T>, 只要关心自己的T就够了。

If I have a shareSubWidget which would be used in PageA and PageB. And PageA and PageB are a lot dislike. Then, How Can I define T?
~~Or I need to write  SubWidget twice?  ~~
Or I just need to implement Conn twice?
