### ISSUE TITLE
Effect 内执行Timer.periodic计时器问题

### ISSUE THREAD

**Issue by chenxianqi** [alibaba/fish-redux#249]
Page Effect
_onEffect 内执行Timer.periodic计时器的同时在Timer.periodic内部执行dispatch，会出现_onEffect自身也被通知到，导致死循环的现象

最小复现代码
```dart
void _onEffect(Action action, Context<T> ctx){
   printf('倒计时外输出');
  Timer.periodic(Duration(milliseconds: 1000), (_){
    ctx.dispatch(ActionCreator.action());
    printf('倒计时内输出');
  });
}
```

控制台输出
![image](https://user-images.githubusercontent.com/27764334/58300351-b86b5b80-7e14-11e9-9e04-29ba99b763f5.png)

**Comment by zjuwjf** [comment]
设计如此

任意一个action的流程

进入effect， 确认是否被消费
     -1）如果被消费，终止
     -2）如果未被消费
            -- a）进入middleware->reducer
            -- b）进入当前Store下的所有被创建的组件的Effect部分。（广播）

**Comment by chenxianqi** [comment]
那么应该在哪实现，类似获取验证码倒计时，每一秒钟更新视图呢？

**Comment by chenxianqi** [comment]
我搞错了，大佬，action 指向当前执行的effect了，抱歉
