### ISSUE TITLE
fish_redux 0.1.8 Connector computed函数不调用

### ISSUE THREAD

**Issue by qq329401134** [alibaba/fish-redux#253]
timedata结构
![image](https://user-images.githubusercontent.com/38587734/58369752-8e5b8b80-7f31-11e9-8c8f-44e9d9217b9e.png)
connector函数
![image](https://user-images.githubusercontent.com/38587734/58369750-813e9c80-7f31-11e9-9b6c-31fcbd154a13.png)
主要是component有个计时器来倒计时显示在界面上。结果是界面上的数字不变化，在hotrelod的时候会临时刷新一下。最后调试发现每一秒在getSub0处下断会断下来，，但是不会computed所以界面上的数据不会变化，不仅如此computed是什么原因呢，应该怎么解决。希望可以得到你的帮助。谢谢各位了

**Comment by hzgotb** [comment]
SplashPageState的代码看一下

**Comment by qq329401134** [comment]
page
![image](https://user-images.githubusercontent.com/38587734/58369844-ef379380-7f32-11e9-9bcb-614dc153f6ed.png)
CountComponentState
![image](https://user-images.githubusercontent.com/38587734/58369861-fc548280-7f32-11e9-9bdf-d349fb4045ef.png)
SplashPageState
![image](https://user-images.githubusercontent.com/38587734/58369864-1726f700-7f33-11e9-914c-d33fb2c946e8.png)

**Comment by hzgotb** [comment]
你在更新reducer那里打断点，看赋值成功没。

**Comment by hzgotb** [comment]
你传入的是一个class实例，是一个`object`。我看了一下`connector`的源码，现在不知道`object`的clone ，所以可能没检测到你对象的属性已经改变。你换成Map传进去试试吧。

**Comment by zjuwjf** [comment]
如果你修改timedata， 需要返回一个新的TimeData，框架才能感知到数据的变化。

**Comment by qq329401134** [comment]
对的，我之前用的是将state.clone()，这种方式我用着没效果，现在改为重新new 一个TimeData是可以正确更新数据的，谢谢各位了
