### ISSUE TITLE
Reducer not trigger after implement Effect with same action

### ISSUE THREAD

**Issue by phattranky** [alibaba/fish-redux#254]
I have implement reducer part like this
```
import 'package:fish_redux/fish_redux.dart';
import 'package:flash8/models/topic.dart';
import 'action.dart';

Reducer<TopicModel> buildReducer() {
  return asReducer(
    <Object, Reducer<TopicModel>>{
      SelectTopicItemAction.select: _onSelect,
    },
  );
}

TopicModel _onSelect(TopicModel state, Action action) {
  final String id = action.payload;
  if (state.id == id) {
    return state.clone()..selected = !state.selected;
  }

  return state;
}
```
All working well, I can update state through action `select`. But after I implement an `effect` for it, even empty function. The reducer doesn't trigger anymore.

```
import 'package:fish_redux/fish_redux.dart';
import 'package:flash8/models/topic.dart';
import 'package:flash8/pages/choose_topic_page/select_topic_item_component/action.dart';
import 'package:flash8/services/couchdb.dart';

const DEFAULT_LANGUAGE_CODE = 'vi';

Effect<TopicModel> buildEffect() {
  return combineEffects(<Object, Effect<TopicModel>>{
    SelectTopicItemAction.select: _onSelect
  });
}

void _onSelect(Action action, Context<TopicModel> ctx) {
  // CouchDbService.setTopicSelected(DEFAULT_LANGUAGE_CODE, action.payload, !ctx.state.selected);
}
```

I think this is a normal implement of Redux Pattern.
Do I implement wrong something with Fish Redux? Can anyone please help me. Thanks in advance.

**Comment by hzgotb** [comment]
in effect. call reducer via 
```dart
ctx.dispatch(SelectTopicItemActionCreator.select())
```

**Comment by zjuwjf** [comment]
An action's travel：
1.  Action is usually born in view or effect.
2. The first place to visit is the effect. 
3. If the place attracts it, it will not move on.
4. If the effect does not attract it，it will move on.
  -a) visit other component's effect.
  -b) visit the middleware first then the reducer

**Comment by zjuwjf** [comment]
> in effect. call reducer via
> 
> ```dart
> ctx.dispatch(SelectTopicItemActionCreator.select())
> ```

It shouldn't work.  Dispatch in view and effect are the same.

**Comment by phattranky** [comment]
Many Thanks for the quick response @zjuwjf.
