### ISSUE TITLE
关于子组件component的问题

### ISSUE THREAD

**Issue by mingtianguohou100** [alibaba/fish-redux#258]
子组件component里面的数据和state里面的数据都必须要来自父组件吗？
比如我在子组件的state里面创建一个变量，只在子组件的reducer中去刷新这个数据

```dart
ReportState _addClick(ReportState state, Action action) {
  println("addClick_start${state.clickAdd}");
  state.clone().clickAdd++;
  println("addClick_finish${state.clickAdd}");
  return state.clone();
}
```
这段代码是在example中的ReportComponent buildview添加了一个的点击事件执行的，日志state.clone().clickAdd一直是0，是我哪里理解不对吗？

**Comment by zjuwjf** [comment]
1、 substate应该是上一级state的子集。
2、clickAdd一直是0， 是因为这句存不存在 state.clone().clickAdd++; 和返回无关。

**Comment by mingtianguohou100** [comment]
请教一下，我的首页整体布局是一个adapter，首页的banner等其他样式是一个head，这样写可以吗？
`
class HomeAdapter extends DynamicFlowAdapter<HomeState> {
  HomeAdapter()
      : super(
          pool: <String, Component<Object>>{
            "head": HomeHeadComponent(),
            "item": HomeItemComponent(),
          },
          connector: _HomeConnector(),
        );
}

class _HomeConnector extends ConnOp<HomeState, List<ItemBean>> {
  @override
  List<ItemBean> get(HomeState state) {
    List<ItemBean> items = [];
    items.add(ItemBean("head", state));
    items.addAll(state.itemData
        .map<ItemBean>((String item) => ItemBean("item", item))
        .toList(growable: true));
    return items;
  }

  @override
  void set(HomeState state, List<ItemBean> items) {
    if (items != null) {
      List<String> itemData = [];
      for (int i = 0; i < items.length; i++) {
        items[i].type == "head"
            ? state == items[i].data
            : itemData.add(items[i].data);
      }
      state.itemData = itemData;
    }
  }
}
`

**Comment by mingtianguohou100** [comment]
请教一下，我的首页整体布局是一个adapter，首页的banner等其他样式是一个head，可以这样写吗？
`
class HomeAdapter extends DynamicFlowAdapter<HomeState> {
  HomeAdapter()
      : super(
          pool: <String, Component<Object>>{
            "head": HomeHeadComponent(),
            "item": HomeItemComponent(),
          },
          connector: _HomeConnector(),
        );
}

class _HomeConnector extends ConnOp<HomeState, List<ItemBean>> {
  @override
  List<ItemBean> get(HomeState state) {
    List<ItemBean> items = [];
    items.add(ItemBean("head", state));
    items.addAll(state.itemData
        .map<ItemBean>((String item) => ItemBean("item", item))
        .toList(growable: true));
    return items;
  }

  @override
  void set(HomeState state, List<ItemBean> items) {
    if (items != null) {
      List<String> itemData = [];
      for (int i = 0; i < items.length; i++) {
        items[i].type == "head"
            ? state == items[i].data
            : itemData.add(items[i].data);
      }
      state.itemData = itemData;
    }
  }
}
`

**Comment by zjuwjf** [comment]
```dart

class HomeAdapter extends StaticFlowAdapter<HomeState> {
  HomeAdapter()
      : super(
          slots: <String, Component<Object>>[
            "head": _HeaderConnOp()+ HomeHeadComponent(),
            "list": DynamicFlowAdapter(
                pool: <String, Component<Object>>{
                   "item": HomeItemComponent(),
                },
               connector: _ListConnector(),
             ),
          ]
        );
}


```

使用下组合关系，会简单明了。

**Comment by learyR** [comment]
> ```dart
> class HomeAdapter extends StaticFlowAdapter<HomeState> {
>   HomeAdapter()
>       : super(
>           slots: <String, Component<Object>>[
>             "head": _HeaderConnOp()+ HomeHeadComponent(),
>             "list": DynamicFlowAdapter(
>                 pool: <String, Component<Object>>{
>                    "item": HomeItemComponent(),
>                 },
>                connector: _ListConnector(),
>              ),
>           ]
>         );
> }
> ```
@zjuwjf 
在StaticFlowAdapter中得slots只能是List<Dependent<Object>>类型呀，不能进行这样得组装，不知道你的为什么可以这样。


@mingtianguohou100 请问你那样写得话，除了_HomeConnector里面会区分state之外，其他地方还会区分吗，或者有更家简洁得方式吗？

**Comment by zjuwjf** [comment]
> > ```dart
> > class HomeAdapter extends StaticFlowAdapter<HomeState> {
> >   HomeAdapter()
> >       : super(
> >           slots: <String, Component<Object>>[
> >             "head": _HeaderConnOp()+ HomeHeadComponent(),
> >             "list": DynamicFlowAdapter(
> >                 pool: <String, Component<Object>>{
> >                    "item": HomeItemComponent(),
> >                 },
> >                connector: _ListConnector(),
> >              ),
> >           ]
> >         );
> > }
> > ```
> 
> @zjuwjf
> 在StaticFlowAdapter中得slots只能是List<Dependent>类型呀，不能进行这样得组装，不知道你的为什么可以这样。
> 
> @mingtianguohou100 请问你那样写得话，除了_HomeConnector里面会区分state之外，其他地方还会区分吗，或者有更家简洁得方式吗？

抱歉 是应该List<Dependent>类型。
