### ISSUE TITLE
PageRoutes 定义的路由,如何在Android 中 通过FlutterView 来加载一个Flutter page?

### ISSUE THREAD

**Issue by hightfly** [alibaba/fish-redux#259]
flutter端:
以下通过PageRoutes定义的路由:
final AbstractRoutes routes = new HybridRoutes(routes: <AbstractRoutes>[
  PageRoutes(pages: <String, Page<Object, dynamic>>{
    RouteNames.welcomePage: WelcomePage(),
    RouteNames.loginPage: LoginPage(),
    RouteNames.mainPage: MainPage(),
    RouteNames.maintainInfoPage: MaintainInfoPage(),
    RouteNames.maintainInfoExtraPage: MaintainInfoExtraPage(),
  })
]);
android 端:
通过路由名称, 调用Flutter Page:

        ViewGroup layout_root = (ViewGroup) LayoutInflater.from(this).inflate(R.layout.layout_maintain_activity, null, true);
        LineChart chart = layout_root.findViewById(R.id.multi_chart);
        LineChart time_chart = layout_root.findViewById(R.id.time_chart);
        FrameLayout flutter_maintain_info = layout_root.findViewById(R.id.fragment_flutter_maintain_info);

        FlutterView flutterView = new FlutterView(this);
        flutterView.setInitialRoute("MaintainInfoExtraPage");
        flutterView.pushRoute("MaintainInfoExtraPage");
        flutterView.setMessageHandler("maintain_channel", new BinaryMessenger.BinaryMessageHandler() {
            @Override
            public void onMessage(ByteBuffer byteBuffer, BinaryMessenger.BinaryReply binaryReply) {
                String s = BinaryUtil.binary_to_str(byteBuffer);
                binaryReply.reply(BinaryUtil.str_to_binary(" reply message"));
            }
        });
        FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT,
                FrameLayout.LayoutParams.WRAP_CONTENT);
        flutter_maintain_info.addView(flutterView, params);

        setContentView(layout_root);

在android 端,在AppCompAction 中 通过给FlutterView设置的路由的名称, 是无法成功的记载Flutter Page.

请问大神, 如何通过路由名称 在 android 中加载 Flutter Page???

**Comment by zjuwjf** [comment]
混合栈的问题可以参考flutter boost。
