### ISSUE TITLE
page与page之间关系

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#260]
page跟page怎么通信，比如说我这个page有数据更新了，想更新另外一个page怎么处理呢

**Comment by zjuwjf** [comment]
1、公共数据同步
 建议是将公共数据制作为一个独立的AppStore， 之后将它和所需的PageStore建立单向的连接关系，
AppStore => PageStore => Page & Component

可以参考 example。

2、页面之间Action的互通
```dart
/// Each page has a unique store.
@immutable
class PageRoutes implements AbstractRoutes {
  final Map<String, Page<Object, dynamic>> pages;
  final DispatchBus bus;

  PageRoutes({
    @required this.pages,
    DispatchBus bus,
  })  : assert(pages != null, 'Expected the pages to be non-null value.'),
        bus = bus ?? DispatchBus();

  @override
  Widget buildPage(String path, dynamic arguments) =>
      pages[path]?.buildPage(arguments, bus: bus);
}
```

也就是PageRoutes下，所有的Page会公用同一个DispatchBus，所以通过显式的API：
```dart
ctx.broadcast(action);
```
所有页面的组件的effect部分，以及PageStore，都将收到这个action。

**Comment by xfhomedream** [comment]
好的，谢谢

**Comment by xfhomedream** [comment]
class ConnectRoutes {
  // 工厂模式
  factory ConnectRoutes() => _getInstance();

  static ConnectRoutes get instance => _getInstance();
  static ConnectRoutes _instance;

  ConnectRoutes._internal() {
    // 初始化
  }

  final AbstractRoutes pages =
      PageRoutes(pages: <String, Page<Object, dynamic>>{
    'indexPage': IndexPage(), //首页
    'deviceList': DeviceListPage(), //设备列表页面
  }, bus: new DispatchBus());

  static ConnectRoutes _getInstance() {
    if (_instance == null) {
      _instance = new ConnectRoutes._internal();
    }
    return _instance;
  }

  Widget buildPage(path, arguments) {
    return pages.buildPage(path, arguments);
  }
}

@immutable
class PageRoutes implements AbstractRoutes {
  final Map<String, Page<Object, dynamic>> pages;
  final DispatchBus bus;

  PageRoutes({
    @required this.pages,
    DispatchBus bus,
  })  : assert(pages != null, 'Expected the pages to be non-null value.'),
        bus = bus ?? DispatchBus();

  @override
  Widget buildPage(String path, dynamic arguments) =>
      pages[path]?.buildPage(arguments, bus: bus);
}
``
我这想写有问题吗？ 为啥这两个页面ctx.broadcast(action);没用
