### ISSUE TITLE
请问appState的模式下，监听路由跳转的RouteAction.route会在什么时候执行？

### ISSUE THREAD

**Issue by CoolBerry** [alibaba/fish-redux#264]
我现在一个appstate下面的‘component’页面，在路由跳转之后该页面的首次加载，对的，只有首次加载，会以 RouteAction.route -> Lifecycle.initState -> RouteAction.route的方式执行。
这样会导致我在initState里面更新的state又被route里面的方法给重置掉，十分头疼。

想请问一下，RouteAction.route是一个什么样的Action？ 为什么会偶尔在一次跳转之后执行多次？
谢谢回复

**Comment by CoolBerry** [comment]
发现页面里进行了一次非纯函数写法所致。。

**Comment by CoolBerry** [comment]
上述问题表述 测试发现 app 启动起来之后 第一次进入一个页面component 会导致RouteAction.route执行两次。

**Comment by zjuwjf** [comment]
目前 AppRoutes 已经不再推荐使用。

如果有页面之间的数据共享的需求：
1、创建一个公共的AppStore，按需将它和PageStore做单向的链接。
     参考 example

2、组件的Context提供了addObservable api， 提供更加灵活的外部数据驱动能力。
    

3、如果是一簇页面，可以通过一个Page完成。
    如详情、预览、编辑， 他们的数据是同一份。
    a 通过将 二、三级页面以组件的形式注册到第一个页面;
    b 通过navigator.push( ctx.buildComponent('next-page') );
既能完成一簇页面受到同一个store的驱动，以及所有的消息的通行。 （redux视角是同一个store下的组件， flutter视角是不同的页面）。
