### ISSUE TITLE
Page view切换页面后状态丟失，如何解决

### ISSUE THREAD

**Issue by hunter-jin** [alibaba/fish-redux#272]
网上说用AutomaticKeepAliveClientMixin，但在fish redux模式下如何处理？

**Comment by zjuwjf** [comment]
#58 

鉴于这个问题被提到了很多次

KeepAliveMixin
```dart
class _KeepAliveStfState<T> extends ComponentState<T>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;
}

mixin KeepAliveMixin<T> on Component<T> {
  @override
  ComponentState<T> createState() => _KeepAliveStfState<T>();
}

class ComponentKeepAlive<T> extends Component<T> with KeepAliveMixin<T> {
  ComponentKeepAlive()
      : super(
          view: null,
        );
}
```


SingleTickerProvider
```dart

class _SingleTickerProviderStfState<T> extends ComponentState<T>
    with SingleTickerProviderStateMixin {}

mixin SingleTickerProviderMixin<T> on Component<T> {
  @override
  _SingleTickerProviderStfState<T> createState() =>
      _SingleTickerProviderStfState<T>();
}

class ComponentSingleTicker<T> extends Component<T>
    with SingleTickerProviderMixin<T> {
  ComponentSingleTicker()
      : super(
          view: null,
          effect: (Action action, Context<T> ctx) {
            if (action.type == Lifecycle.initState) {
              final Object tickerProvider = ctx.stfState;
              AnimationController controller =
                  AnimationController(vsync: tickerProvider);

              ///balabala
            }
            return null;
          },
        );
}
```

TabController 类似

**Comment by hunter-jin** [comment]
谢谢。真的很棒！

**Comment by hunter-jin** [comment]
试了一下，发现将Page的createState overwrite后，走不到buildView, 报错如下：
 Another exception was thrown: A build function returned null. 不知何原因请指点。

代码如下：
class KeepAliveStfState<T> extends ComponentState<T>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;
}

class HomePage extends Page<HomeState, Map<String, dynamic>> {
  HomePage()
      : super(
          initState: initState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          dependencies: Dependencies<HomeState>(
              adapter: null,
              slots: <String, Dependent<HomeState>>{
              }),
          middleware: <Middleware<HomeState>>[
            logMiddleware(tag: Constants.app_tag),
          ],
        );

  @override
  ComponentState<HomeState> createState() {
    return KeepAliveStfState();
  }
}

**Comment by hunter-jin** [comment]
试了一下，发现将Page的createState overwrite后，走不到buildView, 好象走到AutomaticKeepAliveClientMixin的build,返回null
 报错如下：
Another exception was thrown: A build function returned null. 不知何原因请指点。

代码如下：
class KeepAliveStfState extends ComponentState
with AutomaticKeepAliveClientMixin {
@override
bool get wantKeepAlive => true;
}

class HomePage extends Page<HomeState, Map<String, dynamic>> {
HomePage()
: super(
initState: initState,
effect: buildEffect(),
reducer: buildReducer(),
view: buildView,
dependencies: Dependencies(
adapter: null,
slots: <String, Dependent>{
}),
middleware: <Middleware>[
logMiddleware(tag: Constants.app_tag),
],
);

@override
ComponentState createState() {
return KeepAliveStfState<HomeState>();
}
}

**Comment by hunter-jin** [comment]
SingleTickerProvider的没问题，就是KeepAliveStfState不行。 能否加个example？

**Comment by zjuwjf** [comment]
了解了。 然后有个问题，为什么要给Page做Mixin？而不是给Component做Mixin ？

**Comment by hunter-jin** [comment]
类似喜马拉雅布局，是否首页是一个page，pageview中都用component? 原来想法是各page基本上独立功能，数据放在各pagestate中会更模块化，用component数据都得从根pagestate中取. 那我先用component试试。谢谢！

**Comment by hunter-jin** [comment]
换成component 还是不行

**Comment by zjuwjf** [comment]
```dart

class KeepAliveWidget extends StatefulWidget {
  final Widget child;

  const KeepAliveWidget(this.child);

  @override
  State<StatefulWidget> createState() => _KeepAliveState();
}

class _KeepAliveState extends State<KeepAliveWidget>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return widget.child;
  }
}

Widget keepAliveWrapper(Widget child) => KeepAliveWidget(child);

class ReportComponent extends Component<ReportState> {
  ReportComponent()
      : super(
          view: buildView,
          wrapper: keepAliveWrapper,
        );
}

```

**Comment by hunter-jin** [comment]
非常感谢，完美解决！ 为您点个赞！
