### ISSUE TITLE
定义的组件在for循环创建时，报错

### ISSUE THREAD

**Issue by mofan20** [alibaba/fish-redux#273]
Duplicate key found: [<[<HomeTabListComponent>]>]

**Comment by zjuwjf** [comment]
没有更多的信息，无法确定是哪一层的问题。 

如果可以的话，贴下最小能复现的代码。

**Comment by mofan20** [comment]
TabBarView(
              children: _tabList.map((item) => viewService.buildComponent('homelist')).toList())
 )

flutter: Duplicate key found: [<[<HomeTabListComponent>]>].

**Comment by zjuwjf** [comment]
这个场景下，应该使用adapter。

**Comment by mofan20** [comment]
好的，谢谢
