### ISSUE TITLE
How can I include the Effect inside a GlobalStore

### ISSUE THREAD

**Issue by phattranky** [alibaba/fish-redux#279]
I'm using `createStore` API to create a global store by below codes

```
import 'package:fish_redux/fish_redux.dart';

import './state.dart';
import './reducer.dart';
import './effect.dart';

class GlobalStore {
  static Store<GlobalStoreState> _globalStore;
  static GlobalStoreState get state => store.getState();
  static Store<GlobalStoreState> get store {
    if (_globalStore == null) {
      // buildEffect();
      _globalStore = createStore(GlobalStoreState(), buildReducer());
    }

    return _globalStore;
  }
}
```

Now I would like to at some effects into this Store. But don't know how to implement it. Because I didn't see any param allow to add `buildEffect` function.

Please help me clarify. Thanks.

**Comment by zjuwjf** [comment]
The standard ReduxJS does not contain an effect, as does the redux portion of the fish-redux.

The effect part is based on component.

If you want to include side effects to the store, you can do it with middleware,  just like the standard ReduxJS does.

**Comment by phattranky** [comment]
Thanks @zjuwjf for quick response
