### ISSUE TITLE
当page reducer没有注册任何action情况的bug

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#280]
使用pageRoutes情况下，appState驱动pageState。如果page没有注册任何reducer。在appState数据改变，也回调了connectExtraStore中的回调，pageState也改变，但是不会执行page中view的build方法。
必须要在page reducer中注册任意一个action。才能view build才会被执行

**Comment by zjuwjf** [comment]
非常感谢 @a398452027 的反馈。

链接AppStore 和 PageStore 依赖Api
MixedStore<T> connectStores<T, K>(
  MixedStore<T> mainStore,
  Store<K> extraStore,
  T Function(T, K) update,
) ；

其中如何将AppState的状态同步回PageState，分两步：
1. 根据update函数计算出一个新的PageState。
2. 将新的PageState，以标准reducer的处理规范，同步回PageStore。

如何将新的PageState同步回PageStore 依赖于
```dart
MixedStore<T> createMixedStore<T>(
  T preloadedState,
  Reducer<T> reducer, {
  Map<String, Dependent<T>> slots,
  StoreEnhancer<T> storeEnhancer,
  ViewMiddleware<T> viewEnhancer,
  AdapterMiddleware<T> adapterMiddleware,
  EffectMiddleware<T> effectEnhancer,
  DispatchBus bus,
}) =>
    _MixedStore<T>(
      createStore(
        preloadedState,
        _appendUpdateStateReducer<T>(reducer),
        storeEnhancer,
      ),
      slots: slots,
      bus: bus,
      viewMiddleware: viewEnhancer,
      adapterMiddleware: adapterMiddleware,
      effectMiddleware: effectEnhancer,
    );
```

其中的_appendUpdateStateReducer api。

原有这个api的实现在Page-reducer为null的边界上，处理不当，导致新的PageState无法回传到PagetStore。

修复为如下
```
// replace current state
Reducer<T> _appendUpdateStateReducer<T>(Reducer<T> reducer) =>
    (T state, Action action) => action.type == _UpdateState.Assign
        ? action.payload
        : reducer == null ? state : reducer(state, action);
```
