### ISSUE TITLE
数据订阅和middleware的讨论

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#282]
场景是这样的，我的state中有俩个bool驱动是否跳转到下一个页面，这个俩个bool都是异步获取的。这里有俩种方案。
1.effect接收lifecycle.build 在build方法中查看俩个bool状态，执行跳转
2.在每个bool变化后，先发送action给reducer改变状态，紧接着再发一个action给effect执行检测，检测后跳转。

**Comment by a398452027** [comment]
这里俩个方案各有利弊，
方案一，可以把buildAction，看作是数据更新后的回调。每次数据更新都可以在这里检测。但是这里如果业务复杂，每次build会做一些额外的判断。
方案二，可以让意图更加清晰，但是需要添加更多acion来执行相应的方法。而且感觉先改变然后再执行验证，有点绕，其实这里build函数本来就要执行。

**Comment by zjuwjf** [comment]
确切的描述，这是一个 订阅数据变化的问题， 并不是多个数据驱动。

如果对数据变化做订阅：
1. store 级别
   a) store.subscribe
   b) 自定义的middleware

2. 组件级别，有一些hook：
   a) shouldUpdate
   b) Lifecycle.build

**Comment by a398452027** [comment]
明白了，谢谢。忘了有middleware这个东西了。

**Comment by a398452027** [comment]
希望能说一下middleware ，viewMiddleware，effectMiddleware，adapterMiddleware的各自使用场景和方法。主要是调用时机和场景

**Comment by zjuwjf** [comment]
> 希望能说一下middleware ，viewMiddleware，effectMiddleware，adapterMiddleware的各自使用场景和方法。主要是调用时机和场景

1、 middleware 是针对store.dispatch的aop，这里和传统的reduxjs中的middleware不管是设计还是实现是完全对齐的。
    可以做一些数据跟踪、调试、数据存储同步等

2、viewMiddleware 是针对所有component.view的aop
   可以参考如[safetyView](https://github.com/alibaba/fish-redux/blob/master/lib/src/redux_middleware/view_middleware/safety_view.dart)

可以做异常处理，甚至是任意组件的动态性（比如针对UI级别的线上的hotfix）。

3、effectMiddleware是针对所有component.effect的aop
  可以做埋点（手动或自动）、行为日志等等

**Comment by Hiram-Y** [comment]
获取短信验证码，需要不断更新view的状态倒计时，这种场景怎么去实现呢，
页面结束对timer取消的逻辑不能在view里处理呢，应该怎么去实现呢

**Comment by zjuwjf** [comment]
> 应该

和生命周期相关，需要在effect中去 注册和反注册timer

**Comment by zjuwjf** [comment]
> 页面结束对timer取消的逻辑不能在view里处理呢，应该怎么去实现呢

伪代码

方案1:
```
void _onInit(Action action, Context<T> ctx) {
  const timeout = Duration(seconds: 3);
  final timer = Timer(timeout, () {
   /// your run loop
  });

 /// 在组件销毁时，退出
  ctx.registerOnDisposed(() {
    timer.cancel();
  });

}
```


方案2:
```
class MyLocalProps extends LocalProps<MyLocalProps> {
  Timer timer;

  MyLocalProps(Context<Object> ctx) : super(ctx);

  factory MyLocalProps.of(ExtraData ctx) {
    return LocalProps.provide((_) => MyLocalProps(_)).of(ctx);
  }

  @override
  void destructor(Context<Object> ctx) {
    timer?.cancel();
  }
}

void _onInit(Action action, Context<T> ctx) {
  const timeout = Duration(seconds: 3);
  ComponentLocalProps.of(ctx).timer = Timer(timeout, () {
   /// your run loop
  });

 /// 在改组件的任意的effect，或者View中，都可以获取到ComponentLocalProps.of(ctx).timer 执行操作
}
```
