### ISSUE TITLE
类似探探的左右滑动切换页面的实现使用fish-redux方便么？

### ISSUE THREAD

**Issue by opengpu** [alibaba/fish-redux#285]
类似探探的左右滑动切换页面的实现使用fish-redux方便么？

**Comment by hzgotb** [comment]
fish-redux只是关注数据的框架。UI的实现还是具体到Flutter上。

**Comment by opengpu** [comment]
哦好的谢谢，那就是包括把数据和视图解耦等功能。那就可以放心用了。
版本呢，fish-redux和flutter有相应的版本对应关系吧？

**Comment by hzgotb** [comment]
ui部分写在view.dart里，其余的都是关于数据部分。版本的话你用最新的就行。

**Comment by zjuwjf** [comment]
fish-redux是一个上层应用框架，并不耦合具体的ui展现。

对ui的表达，fish-redux做了一个约束，它必须表达在view的函数内。

如果
var view = template(state); 

那么我们的view部分编写的代码， 本质是template的表达形式。

更多的，我们可以通过viewMiddleware， 将template函数动态化， 得到ui的动态能力。
