### ISSUE TITLE
闲鱼内部在用，那应该很成熟了吧？是什么协议呢，可以拿来商用么？另外，例子有点少啊，example目录下就三个，两个还是todo... 另外，fish-redux是目前flutter的最好的框架？可以作为通用的app框架来使用？

### ISSUE THREAD

**Issue by opengpu** [alibaba/fish-redux#286]
闲鱼内部在用，那应该很成熟了吧？是什么协议呢，可以拿来商用么？另外，例子有点少啊，example目录下就三个，两个还是todo...
另外，fish-redux是目前flutter的最好的框架？可以作为通用的app框架来使用？

**Comment by chenxianqi** [comment]
Fish Redux is released under the Apache 2.0 license. See LICENSE for details.

**Comment by hzgotb** [comment]
是不是最好不清楚，但是已经商用这是确定的，意味着可用于生产。
另外纠正一个观念就是，Fish Redux是关注数据的框架，对于UI部分还是依赖Flutter的。

**Comment by ikonan** [comment]
fish-serializable 什么时候开源

**Comment by hzgotb** [comment]
這個就要問幾位大佬了。

**Comment by zjuwjf** [comment]
1、fish-redux是目前闲鱼生产环境最重要的客户端应用框架。 闲鱼也是[flutter应用场景](https://flutter.dev/showcase)中和 flutter 团队紧密的合作伙伴。

2、是目前flutter的最好的框架？
这完全取决了你的场景。架构选择上，没有最好的，只有最合适的。

3、可以作为通用的app框架来使用？
是的，fish-redux是一个和闲鱼具体业务无关的，面向通用应用的上层框架。

**Comment by lwanghaol** [comment]
fish-serializable 什么时候开源

**Comment by nEdAy** [comment]
fish-serializable 什么时候开源
