### ISSUE TITLE
关于AppStore的疑问

### ISSUE THREAD

**Issue by hzgotb** [alibaba/fish-redux#289]
```text
lib/
  store/
    action.dart
    reducer.dart
    state.dart
    store.dart
  pages/
    home/
      page.dart
      effect.dart
```
```dart
// store/action.dart
enum GlobalAction { updateState }

class GlobalActionCreator {
  static Action cacheUserInfo(User userInfo) {
    return Action(GlobalAction.updateState, payload: { StateKey.userInfo: userInfo });
  }
}

// store/state.dart
class GlobalState extends Cloneable<GlobalState> {
  User userInfo;

  @override
  GlobalState clone() {
    return new GlobalState()
      ..userInfo = userInfo;
  }
}

// store/store.dart
...
export 'action.dart';
final Store<GlobalState> globalStore = createStore(GlobalState(), buildReducer());
T _connectExtraStoreUpdate<T extends Cloneable<T>>(T target, GlobalState source) {
  if (target.runtimeType == HomeState) {
    (target as HomeState).userInfo = source.userInfo;
  }
  return target;
}
Page<T, dynamic> storeConnectTo<T extends Cloneable<T>>(Page<T, dynamic> page) {
  return page
    ..connectExtraStore(globalStore, _connectExtraStoreUpdate);
}
```
现在的用法中，在一个页面里如果有更新`AppStore`，我需要在`effect.dart`里引入`store/store.dart`。
然后`globalStore.dispatch(GlobalActionCreator.cacheUserInfo(user));`。

问题1：假设我获取globalStore里的userInfo，可不可以直接通过引入`store.dart`文件，访问`globalStore.getState().userInfo。而不需要使用`_connectExtraStoreUpdate`方法去混入数据到page中。

问题2：假设问题1是不可行的。那我注意到ctx里有一个extra的变量，可不可以用来挂载外部store，而不需要使用`_connectExtraStoreUpdate`去赋值。

期望结果：减少代码量，通过全局混入一个外部store，而不需要层层传递。

我有注意到有一个`addObservable`的方法，但具体的使用并不理解。

**Comment by zjuwjf** [comment]
关于App级别或者外接数据源驱动
1、 通过 page.connectExtraStore api, 建立AppStore 和 PageStore 之间的单向驱动
好处是数据驱动结构清晰、UI刷新精准控制

2、通过context. addObservable 可以给组件增加额外的外部驱动源
好处是使用灵活、但是可能会产生额外无效的组件刷新。
同时如果滥用这个api的话，对项目维护会带来一定的损失。

**Comment by hzgotb** [comment]
所以设计思想是这样的吗？
![微信图片_20190604142858](https://user-images.githubusercontent.com/50480095/58856404-2f3a0b80-86d5-11e9-8db5-0d6dffebf198.jpg)

**Comment by zjuwjf** [comment]
component 不存在独立的store。 一个页面内所有组件公用一个store。
