### ISSUE TITLE
How to using retrive the data from the Global store using `addObservable`

### ISSUE THREAD

**Issue by phattranky** [alibaba/fish-redux#293]
Following the recommend in https://github.com/alibaba/fish-redux/issues/238
In one effect I use addObservable (I think the old name is bindObsevable) to connect with GlobalStore.

But after that, I don't know how to get these data (the global state) in the Store of Current Page.

```
void _init(Action action, Context<ChooseWishListWordState> ctx) {
  // Bind Observable with Global Store
  ctx.addObservable(GlobalStore.store.subscribe);
}
```

**Comment by zjuwjf** [comment]
If you use GlobalStore.store.getState() in the View function,

```dart
Text(GlobalStore.store.getState().name);
```

Then you will hope that when the GlobalStore.store.getState().name changes, the UI of the component should be automatically refreshed.

This is what the addObservable api helps with, subscribe to a data source, and refresh the UI when the data source changes.

So if you don't need this refresh UI, especially if you use GlobalStore only in effect function, you should not need the addObservable api.

Going back to your question, how do you get the global state?
In fact, the framework does not do anything, you could be able to get it directly, just like the code above.
```dart
GlobalStore.store.getState();
```

**Comment by phattranky** [comment]
Many thanks, @zjuwjf ,

```
This is what the addObservable api helps with, subscribe to a data source, and refresh the UI when the data source changes.
```

This is what I concerned. Because before I thought the `addObservable` will add the global state to internal state, I'm wrong.
