### ISSUE TITLE
为什么pageview切换后，state里面的数据被清空了?

### ISSUE THREAD

**Issue by poikl369** [alibaba/fish-redux#298]

**Comment by DDDrop** [comment]
我也遇到同样问题。很不解，keepalivie了，state也会没掉。

**Comment by zjuwjf** [comment]
参考 #272

**Comment by poikl369** [comment]
我已经设置了keepalive，
以下是我的代码
class KeepAliveWidget extends StatefulWidget {
  final Widget child;

  const KeepAliveWidget(this.child);

  @override
  State<StatefulWidget> createState() => _KeepAliveState();
}

class _KeepAliveState extends State<KeepAliveWidget>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return widget.child;
  }
}

class LikeComponent extends Component<LikeState> {
  LikeComponent()
      : super(
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          wrapper: _keepAliveWrapper,
          dependencies: Dependencies<LikeState>(
            adapter: LikeListAdapter(),
          ),
        );
}

Widget _keepAliveWrapper(Widget child) => KeepAliveWidget(child);

**Comment by zjuwjf** [comment]
方便给一个最小demo么？

@hunter-jin 能分享你的经验么？

**Comment by poikl369** [comment]
表现形式，我有三个component，分别是A,B,C。A为当前展示的component，当A显示时的逻辑initState->http request->reducer->显示列表，没有问题，此时我切换到B,initState->http request->reducer->显示列表，当B走到reducer中的重新设置State之后，A的State中保存的网络数据就没有了。代码晚点提供吧。因为业务代码比较多，不太好抽出来。

**Comment by poikl369** [comment]
问题找到了，是我的clone没有把对应的state赋值。
