### ISSUE TITLE
Action冲突

### ISSUE THREAD

**Issue by Bedroome** [alibaba/fish-redux#303]
`Error: 'Action' is imported from both 'package:flutter/src/widgets/actions.dart' and 'package:fish_redux/src/redux/basic.dart'.`
请问出现这个问题要怎么解决

**Comment by zjuwjf** [comment]
你可以通过
```dart
import 'xxx' as yyy;
```
来解决命名冲突问题。

**Comment by Bedroome** [comment]
这个是我安装了依赖后fish_redux包里面报的错.这个要怎么解决

**Comment by Bedroome** [comment]
> 你可以通过
> 
> ```dart
> import 'xxx' as yyy;
> ```
> 
> 来解决命名冲突问题。

这个是我安装了依赖后fish_redux包里面报的错.这个要怎么解决

**Comment by zjuwjf** [comment]
能贴下 你的 flutter doctor 信息么？

**Comment by Bedroome** [comment]
> 能贴下 你的 flutter doctor 信息么， 以及 使用的fish-redux的版本信息

```
[✓] Flutter (Channel master, v1.7.4-pre.30, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.35.0)
[✓] Connected device (1 available)
```
版本是 fish_redux: ^0.2.1

**Comment by zjuwjf** [comment]
目前支持flutter1.5 stable版本，还没升级到flutter 1.7 pre版本， 可能存在兼容性问题。

建议先使用flutter1.5 - stable版本.

**Comment by Bedroome** [comment]
> 目前支持flutter1.5 stable版本，还没升级到flutter 1.7 pre版本， 可能存在兼容性问题。
> 
> 建议先使用flutter1.5 - stable版本. 对1.7 pre版本的兼容欢迎👏PR。

我刚才把Channel换到了stable是1.5.4运行也是报错.不过我下载了包之后把Action换了个名字倒是正常了.

**Comment by liangwei0101** [comment]
> > 目前支持flutter1.5 stable版本，还没升级到flutter 1.7 pre版本， 可能存在兼容性问题。
> > 建议先使用flutter1.5 - stable版本. 对1.7 pre版本的兼容欢迎👏PR。
> 
> 不过我下载了包之后把Action换了个名字倒是正常了.

你咋改的，我改的不正常

**Comment by liangwei0101** [comment]
> 目前支持flutter1.5 stable版本，还没升级到flutter 1.7 pre版本， 可能存在兼容性问题。
> 
> 建议先使用flutter1.5 - stable版本. 对1.7 pre版本的兼容欢迎👏PR。

我的flutter版本为 v1.5.4-hotfix.2，跑demo出毛病，看着也是这个问题。

**Comment by DDDrop** [comment]
flutter 1.7.2 增加的 Action 。 如果要同时玩 flutter_web。 建议 checkout 1.7.1。

**Comment by xiong425** [comment]
//按照Example的写法，_init不能赋值给Lifecycle.initState
Effect<ReportListState> buildEffect() {
  return combineEffects(<Object, Effect<ReportListState>>{
    Lifecycle.initState: _init,
  });
}

void _init(Action action, Context<ReportListState> ctx) {
  ctx.dispatch(ReportListActionCreator.load());
}

**Comment by zjuwjf** [comment]
先 通过 widgets.dart hide Action #308 兼容。
但是这会给 flutter 1.7.2 以上的开发者带来一些琐碎的hide代码。 需要一个更优的方案。

**Comment by zjuwjf** [comment]
跟进 https://github.com/flutter/flutter/issues/34395

**Comment by longgui0318** [comment]
@zjuwjf 1.7.8发布了，包含了 actions的，看样子 底层应该是不改了，咱们这个库，是否要hide 或者改action名称呢？现在不敢更新，怕一更新就挂，麻烦有空先处理一下这个

**Comment by zjuwjf** [comment]
大家也一起去 https://github.com/flutter/flutter/issues/34395 反馈下

**Comment by Pikaurd** [comment]
> 大家也一起去 [flutter/flutter#34395](https://github.com/flutter/flutter/issues/34395) 反馈下

人已经进了stable了，从版本稳定性上来说也不能往出移了吧，还是咱改吧；只能说没能再更早的时候去处置吧

**Comment by longgui0318** [comment]
@zjuwjf 根据 flutter目前发布情况来看，发 hotfix的情况少之又少，长期解决问题 的确有更好的方式，针对目前而言，有临时的一个fix版本能够输出一下吗？

**Comment by zjuwjf** [comment]
目前fish-redux是可以在flutter 1.7 版本上运行。  需要上层业务代码在
```dart
import 'package:flutter/material.dart' hide Action;
import 'package:flutter/cupertino.dart' hide Action;
import 'package:flutter/widget.dart' hide Action;
```

**Comment by longgui0318** [comment]
@zjuwjf 是我操作不对吗？编译报错

```
files:///xxx/.pub-cache/hosted/pub.flutter-io.cn/fish_redux-0.2.2/lib/src/redux_component/basic.dart:3:1: Error: 'Action' is imported from both 'package:flutter/src/widgets/actions.dart' and 'package:fish_redux/src/redux/basic.dart'.
import '../redux/redux.dart';
```

**Comment by zjuwjf** [comment]
可以先依赖目前的master分支。 暂未发布。

**Comment by longgui0318** [comment]
@zjuwjf 
1、英语不好，只能看看懂，故未参与flutter #34395关于这个的议论
2、从flutter #34395内反馈来看，因为已经加上去，所以再移除带来的负面内容可能更多
3、从flutter #34395来看，flutter应该不会再去修改这块了

故，对此，咱们现在对于这个问题是闲置，还是要准备处理了呢？

目前，事情已然发生，可能更多的是针对现有问题如何去处理，同时，这种影响比较大的，最好是决策快一些

**Comment by zjuwjf** [comment]
改名同样存在会再次冲突的风险。

目前建议 如 flutter/flutter#34395 提示hide action 或者自定义导出。

更多的建议和讨论，建议去flutter/flutter#34395参与。

**Comment by learyR** [comment]
咱们改吧，长痛不如短痛。try fish_action fish_state...

**Comment by HowieHai** [comment]
还是在 @liangwei0101 的提示下，降了flutter 版本。也希望官方文档在首页能有个提醒。

**Comment by zjuwjf** [comment]
> 还是在 @liangwei0101 的提示下，降了flutter 版本。也希望官方文档在首页能有个提醒。

现在支持最新版本的flutter。 在具体遇到action 冲突的时候，使用hide，或者自定义导出。

**Comment by longgui0318** [comment]
@zjuwjf   @hyjfine  @hzgotb  这个，flutter那边恐怕是不改了，咱们真的 就hide这样子 一直用了吗？就个人看法而言，还是希望 fish-redux能够对这个做下处理，因为flutter上了action，已经造成了影响，那么再下必然又是一轮大规模的问题，如果 用fish-redux和flutter的人数相差不大，那么还是flutter改合适，但两边影响不是一个量级的，所以从对外部的伤害，和持续性的伤害而言，希望能够调整一下。至于说的改了可能还有其他冲突，我觉得还是针对问题处理问题，毕竟这个已经发生，而其他的不一定发生。

**Comment by zjuwjf** [comment]
> @zjuwjf @hyjfine @hzgotb 这个，flutter那边恐怕是不改了，咱们真的 就hide这样子 一直用了吗？就个人看法而言，还是希望 fish-redux能够对这个做下处理，因为flutter上了action，已经造成了影响，那么再下必然又是一轮大规模的问题，如果 用fish-redux和flutter的人数相差不大，那么还是flutter改合适，但两边影响不是一个量级的，所以从对外部的伤害，和持续性的伤害而言，希望能够调整一下。至于说的改了可能还有其他冲突，我觉得还是针对问题处理问题，毕竟这个已经发生，而其他的不一定发生。

感谢建议，我们还在讨论，近期会有结果。

**Comment by danieldai** [comment]
哈哈，建议直接把Action改成Intent，一看这Action这个东西比较别扭。

**Comment by zhangruiyu** [comment]
改Intent就扯了好吧

**Comment by jinyaqiao1102** [comment]
真坑

**Comment by jinyaqiao1102** [comment]
@zjuwjf 还没有解决方案嘛

**Comment by Pikaurd** [comment]
> @zjuwjf 还没有解决方案嘛


> 目前fish-redux是可以在flutter 1.7 版本上运行。 需要上层业务代码在
> 
> ```dart
> import 'package:flutter/material.dart' hide Action;
> import 'package:flutter/cupertino.dart' hide Action;
> import 'package:flutter/widget.dart' hide Action;
> ```

人早就说怎么弄了好么……

**Comment by jinyaqiao1102** [comment]
> > @zjuwjf 还没有解决方案嘛
> 
> > 目前fish-redux是可以在flutter 1.7 版本上运行。 需要上层业务代码在
> > ```dart
> > import 'package:flutter/material.dart' hide Action;
> > import 'package:flutter/cupertino.dart' hide Action;
> > import 'package:flutter/widget.dart' hide Action;
> > ```
> 
> 人早就说怎么弄了好么……

这不是最终解决方案

**Comment by DDDrop** [comment]
> 哈哈，建议直接把Action改成Intent，一看这Action这个东西比较别扭。

Flutter 也定义 Intent，所以跟 Action 没啥区别呀。

**Comment by longgui0318** [comment]
@zjuwjf @hyjfine @hzgotb 

请问 这个最终方案何时能出呢，咱们这个项目star还是很多的，用的人也很多，若临时方案存在太久，也会带来其他负面影响。个人认为，这个问题本身并不是一个技术难题，而是一个抽象层上、认知层上问题，这类问题建议还是尽早处理（若是担心名称变更带来兼容性问题，可将Action作为继承者，不影响现有业务的情况下弃用）

个人还是很喜欢这个项目的，虽然很年轻，但有潜力，希望能够一直进步而非停滞

**Comment by zjuwjf** [comment]
@longgui0318 
感谢你的认可。
目前我们的犹豫在改名对项目后续的持续发展上 。
本质上还是dart语言构建大型软件系统上的问题。
也看到了dart的不断的迭代优化。
可能以后这个不会再是问题，或者有更加简单的解法。
从我们自己的实践看，目前使用方自定义hide，或者使用自定义的export也没有特别大的成本。

我觉得，你可以发起一个新的issue来讨论，看大家是否都需要讲action更名。

**Comment by danieldai** [comment]
确实，这个和dart本身也有一定的关系

**Comment by zmGitHub** [comment]
所以大家讨论的结果是 近期会有新版吗? 在最新的 flutter 上能跑的, 如果没有 计划是什么样呢?

**Comment by zjuwjf** [comment]
> 所以大家讨论的结果是 近期会有新版吗? 在最新的 flutter 上能跑的, 如果没有 计划是什么样呢?

目前没有直接修改Action的计划。 建议使用的时候通过 hide 。
