### ISSUE TITLE
List Adapter如何添加分隔线

### ISSUE THREAD

**Issue by xiong425** [alibaba/fish-redux#304]
List Adapter如何添加分隔线, 不能像flutter一样吗?

**Comment by zjuwjf** [comment]
Adapter 和 分割线 并不冲突， 还是以flutter的形式来添加分隔线。

**Comment by xiong425** [comment]
//flutter 是使用以下的代码来添加
 ListView.separated(
              separatorBuilder: (context, index) =>
                  Divider(
                    height: 1,
                  ),
              itemCount: reports.length,
              itemBuilder: (context, index) {}
而在List Adapter中，使用DynamicFlowAdapter, 它调用pool创建组件和数据，针对的是每一个item项，没有找到类似的separatorBuilder.

**Comment by zjuwjf** [comment]
我的理解也是你的separatorBuilder 应该自己实现，它和具体的item应该无关。
```dart
ListView.separated(
    separatorBuilder: (context, index) => Divider(height: 1),
    itemCount: listAdapter.itemCount,
    itemBuilder: listAdapter.itemBuilder,
)
```
