### ISSUE TITLE
adapter怎么共用

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#310]
怎么在不同页面共用adapter呢

**Comment by zjuwjf** [comment]
能具体说下你的场景么？

**Comment by wangbo4020** [comment]
我有个类似场景，比如知乎主页，一个界面多个Tab，不同Tab下是不同的ListView。

如果用现有结构实现这样是否合理呢：
main_page
    list_adapter
        依旧使用adapter，只不过不用ListView，这是tabs的adapter
    tab_component
        first_component
            action.dart
            component.dart
            ....
            list_adapter
                adapter.dart
        second_component
            action.dart
            component.dart
            ....
            list_adapter
                adapter.dart
        third_component
            action.dart
            component.dart
            ....
            list_adapter
                adapter.dart

**Comment by wangbo4020** [comment]
好像不能缩进
![image](https://user-images.githubusercontent.com/5559403/59754261-55a49d00-92b8-11e9-8ada-16c5013f02ca.png)

**Comment by zjuwjf** [comment]
目前在在：origin/reconstruction_0.2 分支 做了重构
大体做了3大部分
1、分解了MixedStore为3部分，将store（状态管理），AOP，通信（组件间，页面间）3者独立。 期望源码上更加易读易懂。
2、对Context做了部分重构。 去除了 TwinContext， ViewUpdater等概念和实现。
3、对Dependencies.adapter做了优化，使其变成一个通用的dependent，提高adapter的组装复用能力。

其中第三部分，能最大限度提升目前的复用问题。

**Comment by zjuwjf** [comment]
已合入master。
