### ISSUE TITLE
appbar的问题

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#311]
你好，我把appbar做成一个component，然后在一个页面buildComponent结果会报强转异常，这个有什么处理方法吗

**Comment by hzgotb** [comment]
po一下代码。还有报错信息。

**Comment by xfhomedream** [comment]
`Widget buildView(
    SubscribeState state, Dispatch dispatch, ViewService viewService) {
  var adapter = viewService.buildAdapter();
  return Scaffold(
    appBar: viewService.buildComponent("appBar"),
    body: state.list == null || state.list.length == 0
        ? buildEmptyView(
            dispatch, viewService, "抱歉，您还未预约！", "assets/icon_no_sub.png")
        : Container(
            margin: EdgeInsets.only(top: 15),
            child: ListView.builder(
              itemBuilder: adapter.itemBuilder,
              itemCount: adapter.itemCount,
            ),
          ),
  );
}`
page代码：
`class SubscribePage extends Page<SubscribeState, Map<String, dynamic>> {
  SubscribePage()
      : super(
          initState: initSubscribeState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          dependencies: Dependencies<SubscribeState>(
              adapter: SubAdapter(),
              slots: <String, Dependent<SubscribeState>>{
                "btn": ButtonConnOp<SubscribeState, ButtonState>(
                        key: "btn", init: initButtonState) +
                    ButtonComponent(),
                "appBar": AppBarConnOp<SubscribeState, AppBarState>(init: initAppBarState) +
                    AppBarComponent()
              }),
          middleware: <Middleware<SubscribeState>>[],
        );
}
`
appbar state代码
`class AppBarState implements Cloneable<AppBarState> {
  String rightText;
  String title;
  String rightIcon;
  bool showRight = false;

  @override
  AppBarState clone() {
    return AppBarState()..rightText = rightText;
  }
}

AppBarState initAppBarState(MapLike map) {
  //String title,
  //    {String rightText, String rightIcon, bool showRight}
  AppBarState appBarState = map['appBar'];
  return appBarState;
}

class AppBarConnOp<T extends MapLike, P> extends ConnOp<T, P> {
  final String key;
  final P Function(T state) init;

  AppBarConnOp({this.init, String key}) : key = key ?? ('');

  @override
  P get(T state) {
    return state.containsKey(key) ? state[key] : (state[key] = init(state));
  }

  @override
  void set(T state, P subState) {
    state[key] = subState;
  }
}
`

**Comment by xfhomedream** [comment]
错误信息：
): The following assertion was thrown building ComponentWidget<SubscribeState>-[<SubscribePage>](dirty,
I/flutter ( 2542): state: ComponentState<SubscribeState>#cb45d):
I/flutter ( 2542): type 'ComponentWidget<AppBarState>' is not a subtype of type 'PreferredSizeWidget'
I/flutter ( 2542): 
I/flutter ( 2542): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 2542): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 2542): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 2542):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 2542): 
I/flutter ( 2542): When the exception was thrown, this was the stack:
I/flutter ( 2542): #0      buildView (package:elminda/home/subscribe/view.dart:14:25)

**Comment by hzgotb** [comment]
```dart
Widget buildView( SubscribeState state, Dispatch dispatch, ViewService viewService) {
  var adapter = viewService.buildAdapter();
  return Scaffold(
    appBar: viewService.buildComponent("appBar"),
    body: state.list == null || state.list.length == 0
      ? buildEmptyView( dispatch, viewService, "抱歉，您还未预约！", "assets/icon_no_sub.png")
      : Container(
        margin: EdgeInsets.only(top: 15),
        child: ListView.builder(
          itemBuilder: adapter.itemBuilder,
          itemCount: adapter.itemCount,
        ),
        ),
  );
}
```

page代码：
```dart
class SubscribePage extends Page<SubscribeState, Map<String, dynamic>> {
  SubscribePage() : super(
    initState: initSubscribeState,
    effect: buildEffect(),
    reducer: buildReducer(),
    view: buildView,
    dependencies: Dependencies<SubscribeState>(
      adapter: SubAdapter(),
      slots: <String, Dependent<SubscribeState>>{
        "btn": ButtonConnOp<SubscribeState, ButtonState>( key: "btn", init: initButtonState) + ButtonComponent(),
        "appBar": AppBarConnOp<SubscribeState, AppBarState>(init: initAppBarState) + AppBarComponent()
      },
    ),
    middleware: <Middleware<SubscribeState>>[],
  );
}
```
appbar state代码
```dart
class AppBarState implements Cloneable {
  String rightText;
  String title;
  String rightIcon;
  bool showRight = false;

  @override
  AppBarState clone() {
  return AppBarState()..rightText = rightText;
  }
}

AppBarState initAppBarState(MapLike map) {
  //String title,
  // {String rightText, String rightIcon, bool showRight}
  AppBarState appBarState = map['appBar'];
  return appBarState;
}

class AppBarConnOp<T extends MapLike, P> extends ConnOp<T, P> {
  final String key;
  final P Function(T state) init;

  AppBarConnOp({this.init, String key}) : key = key ?? ('');

  @override
  P get(T state) {
    return state.containsKey(key) ? state[key] : (state[key] = init(state));
  }

  @override
  void set(T state, P subState) {
    state[key] = subState;
  }
}
```

**Comment by hzgotb** [comment]
你的appbar的view代码吗？

**Comment by xfhomedream** [comment]
`Widget buildView(
    AppBarState state, Dispatch dispatch, ViewService viewService) {
  return AppBar(
      centerTitle: true,
      title: Text(
        state.title,
        style: TextStyle(color: AppTheme.appBarTitleColor, fontSize: 17),
      ),
      actions: [
        state.showRight
            ? (state.rightText == null
                ? Image(image: AssetImage(state.rightIcon))
                : Text(
                    state.rightText,
                    style: TextStyle(
                        color: AppTheme.appBarTitleColor, fontSize: 15),
                  ))
            : null
      ]);
}
`这个是appbar view代码

**Comment by hzgotb** [comment]
你尝试这样子写。
```dart
"appBar": AppBarComponent().asDependent(AppBarConnOp<SubscribeState, AppBarState>(init: initAppBarState))
```

**Comment by xfhomedream** [comment]
你好刚试了一下 还是报同样的错误  是不是还要改其他地方呢

type 'ComponentWidget' is not a subtype of type 'PreferredSizeWidget'

**Comment by zjuwjf** [comment]
参考 #272 

```dart
type 'ComponentWidget' is not a subtype of type 'PreferredSizeWidget'
```
就fish-redux 而言， 默认的任意组件生成的Widget类型都是ComponentWidget(它是一个普通的StatefulWidget)

而从报错信息看
```dart
Scaffold(
    appBar: viewService.buildComponent("appBar"),
)
```

需要一个PreferredSizeWidget类型的Widget

方案1:
```dart
Scaffold(
    appBar: PreferredSizeWidget(width:10, height: 10, child: viewService.buildComponent("appBar")),
)
```

方案2 (设置WidgetWrapper):
```dart
class AppBarComponent extends Component<T>{
     AppBarComponent():super(
         wrapper : preferredSizeWrapper(),
     )
}
```

**Comment by namenoteasy** [comment]
![image](https://user-images.githubusercontent.com/19269133/60868899-8c8b2480-a260-11e9-871f-53e064d33646.png)
我加了PreferredSizeWidget，可是报这个错

**Comment by zjuwjf** [comment]
检查下代码编译问题，应该是OK的。
