### ISSUE TITLE
question: How I can use some componetAs in componetB?

### ISSUE THREAD

**Issue by huang12zheng** [alibaba/fish-redux#312]
## question
I would want to use some componetA_s in componetB, And componetB it is not Page.
So What I need to do?

## idea
implement dependencies, and it is what code place.
1.1 connect/reselect<Page,componetAState> in Page--page.dart
1.2 import subComponent or Adapter in componetB--adapter.dart
1.3 slots in componetB--component.dart

## other
it would be  code everywhere, it is difficult to remember

**Comment by zjuwjf** [comment]
Sorry, I didn't understand what you mean, maybe you are talking about how to use components.

```dart
ComponentB extends Component<B> {
    ComponentB():super(
        dependencies: Dependencies<B>(
             slots: <String, Dependent<B>>{
                  'a': ConnOpBA() +  ComponetA(),
             }
        )
   )
}
```

**Comment by huang12zheng** [comment]
Yes,It is. 
I don't find that in example which make me a at a loss.
But you just give a ConnOpBA.
What  is ConnOpBA extends from?
Do it is 
ConnOpBA extends from ConnOp<PageState, A>

**Comment by huang12zheng** [comment]
If it is extends from ConnOp<PageState, A> ,  I would place ConnOpBA in page.dart.
Is it is a good way?

**Comment by huang12zheng** [comment]
https://github.com/huang12zheng/f1
use two MenuButton in PassportPage
