### ISSUE TITLE
Question: How can I unsubscribe store changes in dispose

### ISSUE THREAD

**Issue by phattranky** [alibaba/fish-redux#315]
I see We have a subscribe callback

```
GlobalStore.store.subscribe(() {
      ///
    });
```

But because this is the Global Store so it's still subscribing even the Component, or page was destroyed. Can anyone guide me How to unsubscribe when dispose the Widget

Thanks in advance

**Comment by zjuwjf** [comment]
Maybe the code below is what you are looking for
```dart
final void Function() unsubscribe = GlobalStore.store.subscribe(() {
      ///
    });
ctx.registerOnDisposed(unsubscribe);
```

**Comment by phattranky** [comment]
ah thanks
