### ISSUE TITLE
BottomNavigationBar 和 fish-redux如何结合使用呢

### ISSUE THREAD

**Issue by hufu4635** [alibaba/fish-redux#317]
因为BottomNavigationBar 的body需要的是一个Widget数组，没有很好的思路去把两者结合，特来请教

**Comment by DDDrop** [comment]
我用 component 包裹了一个 BottomNavigationBar，点击是更新这个 component 的 index。Page 里面载入这个component，同步一下 page 的 index 和 component 的 index。Page 根据 index 来切换页面。

**Comment by hufu4635** [comment]
方便看下 具体的Demo实现代码么 之前看到你提的问题不是看的很明白

**Comment by hufu4635** [comment]
已解决  每个子页面当做组件来处理，通过page 界面的viewservice 获取子组件的widget来配合使用
`viewService.buildComponent('hall');`

**Comment by nancy54264** [comment]
> 已解决 每个子页面当做组件来处理，通过page 界面的viewservice 获取子组件的widget来配合使用
> `viewService.buildComponent('hall');`

请问你这种实现方法，在使用BottomNavigationBar 切换page 时，页面会重绘吗？如果每个页面都有自己的状态，是否当切换page时，页面的状态会重新加载。

**Comment by Javamr123** [comment]
大哥，你解决了，就不告诉别人了吗，，，，，，，求来个demo
