### ISSUE TITLE
修改Component的state,只重新buildview Component

### ISSUE THREAD

**Issue by zhangruiyu** [alibaba/fish-redux#319]
Component里改变state同步到page里后,只改变Component需要的数据,不想把整个page都重新buildview,只能重新buildview下当前Component,怎么实现呢

**Comment by zjuwjf** [comment]
目前做的是最小化范围刷新和最优的刷新时机。
这里有几点：
1. 只有数据发生变化的组件才会刷新。
2. 有是否刷新定制的，可以复写shouldUpdate。

简单起见，我以下面的数据结构举例
```javascript
    var state = {
       p : {
             a:{
                  x,
                  y,
                  z,
              },
             b:{},
             c:{}
       },
    }

   当 x 数据 通过reducer 发生变化为 x'， 框架为自动完成以下的变化
  var nextState = {
       p' : {
             a':{
                  x',
                  y,
                  z,
              },
             b:{},
             c:{}
       },
    }

关心 y，z， b，c 的组件不会得到刷新。

关心 x，a， p的组件将默认得到一次刷新。

这里有一点小的细节。  当 p组件刷新的时候，如何保证， b，c组件不被build。

在框架实现内部，对组件都的一层widget-cache，来保证父组件的刷新不会引起子组件的刷新。

```

**Comment by zhangruiyu** [comment]
ganxie 0-0

**Comment by XingXiaoWu** [comment]
我也遇到这个问题了
page里面有个component，component有个定时器，每秒刷新component的state，但是set到了page的state，刷新了整个page。
怎么解决的呢

**Comment by XingXiaoWu** [comment]
> 目前做的是最小化范围刷新和最优的刷新时机。
> 这里有几点：
> 
> 1. 只有数据发生变化的组件才会刷新。
> 2. 有是否刷新定制的，可以复写shouldUpdate。
> 
> 简单起见，我以下面的数据结构举例
> 
> ```js
>     var state = {
>        p : {
>              a:{
>                   x,
>                   y,
>                   z,
>               },
>              b:{},
>              c:{}
>        },
>     }
> 
>    当 x 数据 通过reducer 发生变化为 x'， 框架为自动完成以下的变化
>   var nextState = {
>        p' : {
>              a':{
>                   x',
>                   y,
>                   z,
>               },
>              b:{},
>              c:{}
>        },
>     }
> 
> 关心 y，z， b，c 的组件不会得到刷新。
> 
> 关心 x，a， p的组件将默认得到一次刷新。
> 
> 这里有一点小的细节。  当 p组件刷新的时候，如何保证， b，c组件不被build。
> 
> 在框架实现内部，对组件都的一层widget-cache，来保证父组件的刷新不会引起子组件的刷新。
> ```

请问下，这里需要重写的shouldUpdate应该是指page的shouldUpdate对吗？

**Comment by EaglesChen** [comment]
> 目前做的是最小化范围刷新和最优的刷新时机。
> 这里有几点：
> 
> 1. 只有数据发生变化的组件才会刷新。
> 2. 有是否刷新定制的，可以复写shouldUpdate。
> 
> 简单起见，我以下面的数据结构举例
> 
> ```js
>     var state = {
>        p : {
>              a:{
>                   x,
>                   y,
>                   z,
>               },
>              b:{},
>              c:{}
>        },
>     }
> 
>    当 x 数据 通过reducer 发生变化为 x'， 框架为自动完成以下的变化
>   var nextState = {
>        p' : {
>              a':{
>                   x',
>                   y,
>                   z,
>               },
>              b:{},
>              c:{}
>        },
>     }
> 
> 关心 y，z， b，c 的组件不会得到刷新。
> 
> 关心 x，a， p的组件将默认得到一次刷新。
> 
> 这里有一点小的细节。  当 p组件刷新的时候，如何保证， b，c组件不被build。
> 
> 在框架实现内部，对组件都的一层widget-cache，来保证父组件的刷新不会引起子组件的刷新。
> ```

jifeng大佬，这些我理解了，我子组件里有个倒计时显示的状态x，每一秒都更新一次，导致p a 每秒都更新一次，这种情况如何优化。
