### ISSUE TITLE
flutter dev版本在1.7之后新增action类造成无法编译,望更新

### ISSUE THREAD

**Issue by rolends1986** [alibaba/fish-redux#322]
flutter更新参见 https://github.com/flutter/flutter/commit/387e2b060229f66fc8681c28de69215e025bb2de#diff-c3c5ef0329417ec1e4afff1e7c4f3175

建议action改名 
使用import show的话编码不太方便

**Comment by chenxianqi** [comment]
短期內不會得到更改，估計您得先自行解決該問題，因為fish redux 目前支持到1.5，還沒有對更高的flutter版本支持，該問題請觀察 #303

**Comment by zjuwjf** [comment]
Duplicate of #303
