### ISSUE TITLE
page的initstate和component的 initState 不能共存是什么原因呢

### ISSUE THREAD

**Issue by hufu4635** [alibaba/fish-redux#323]

**Comment by zjuwjf** [comment]
原因是因为一个页面一个store，而非一个组件一个store。
page的initstate是用来第一次初始化store的state的，而component不需要initState，因为它是通过connector 从 store里取出自己关心的一部分state。

**Comment by hzgotb** [comment]
因为目前的设计，页面内的所使用的组件，其内部的状态都是通过`connector`向页面获取的，所以组件的`initState`是无用的。

**Comment by hufu4635** [comment]
多谢
