### ISSUE TITLE
component中如何dispose

### ISSUE THREAD

**Issue by 331299** [alibaba/fish-redux#326]
您好，我封装了一个input的组件，其中使用到了TextEditingController。如果在component的effect中监听 Lifecycle.dispose，进行dispose，会在刷新的时候报错。如果在页面的dispose事件中，dispatch组件的的action去dispose TextEditingController的话，组件收不到事件。是必须要在页面的state中保存input组件的state，然后再通过保存的组件的state进行组件的dispose么？

**Comment by chenxianqi** [comment]
类似这样的组件可以不需要用component去做的，您可以直接使用StatefulWidget实现即可，抛出各个回调接口

**Comment by 331299** [comment]
> 类似这样的组件可以不需要用component去做的，您可以直接使用StatefulWidget实现即可，抛出各个回调接口

谢谢。
