### ISSUE TITLE
page处理子component dispatch过来的action，在page中的effect处理并返回值，子component接收到的返回值为null

### ISSUE THREAD

**Issue by wangbo4020** [alibaba/fish-redux#328]
page处理子component dispatch过来的action，在page中的effect处理并返回值，子component接收到的返回值为null。
page调用自己的dispatch可以正常接收返回值。

具体需求是在一个页面有几个tab_component，每个tab都有下拉刷新，现在tab_component中的刷新收不到返回的Future，导致刷新收不回去。
page中的effect确实是返回了Future的。

**Additional context**
1. fish-redux 0.2.2
2. 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (1 available)

• No issues found!

**Comment by wangbo4020** [comment]
补充一下，有调用到了page的effect方法。

**Comment by hzgotb** [comment]
可以贴一下connector的代码吗？

**Comment by wangbo4020** [comment]
page的adapter和connector
![image](https://user-images.githubusercontent.com/5559403/59906754-0be4bf80-943c-11e9-9f9d-1bb8c233ae69.png)
tab_component中的action，自己没有消费该事件
![image](https://user-images.githubusercontent.com/5559403/59906838-3df62180-943c-11e9-8f13-2584d56dc71e.png)

tab_component/view.dart 这里打印没有返回值
![image](https://user-images.githubusercontent.com/5559403/59906917-6e3dc000-943c-11e9-8a48-234ae5bd7bbc.png)

tab_component/effect.dart 这里打印返回值是有的
![image](https://user-images.githubusercontent.com/5559403/59907078-caa0df80-943c-11e9-8694-a0bda7f68879.png)

**Comment by hzgotb** [comment]
你的tab_component有定义 `connector` 吗？不是adapter的。

**Comment by wangbo4020** [comment]
tab_component没有定义connector
![image](https://user-images.githubusercontent.com/5559403/59910557-c4aefc80-9444-11e9-9c65-e07931ac1c49.png)

**Comment by wangbo4020** [comment]
这是tab_component/list_adapter中的
![image](https://user-images.githubusercontent.com/5559403/59910940-7e0dd200-9445-11e9-93e4-a69a6409cf8d.png)

**Comment by hzgotb** [comment]
1. 你应该在组件dispatch的应该是自身的action，而不是页面的action，这样你的effect返回才会到组件去。
2. 组件的数据都是通过connector向父组件获取的，组件向父组件传递数据是通过connector的set方法。

**Comment by hzgotb** [comment]
`adapter` 的 connector 和 组件的的 connector 是两码事。

例如这样：
```dart
class WorkOrderListConnector extends Reselect1<HomeState, WorkOrderListState, List<WorkOrder>> {
  @override
  WorkOrderListState computed(List<WorkOrder> list) {
    return WorkOrderListState()
      ..workOrderList = list;
  }

  @override
  List<WorkOrder> getSub0(state) {
    return state.workOrderList;
  }

  @override
  void set(HomeState state, WorkOrderListState subState) {
    // 这里写子组件向父组件赋值。
  }
}
```

**Comment by wangbo4020** [comment]
好的，非常感谢您的指点，我试试

**Comment by wangbo4020** [comment]
用法出现偏差了😂，我很多地方设置数据全都是直接用页面的effect监听组件的action来向下同步的。

**Comment by hzgotb** [comment]
> 用法出现偏差了😂，我很多地方设置数据全都是直接用页面的effect监听组件的action来向下同步的。

在赶文档。仓库里有demo，你可以先参考一下。

**Comment by wangbo4020** [comment]
好的，谢谢
