### ISSUE TITLE
sample中两个EditableText同时出现焦点光标

### ISSUE THREAD

**Issue by TianbinTobin** [alibaba/fish-redux#33]
![image](https://user-images.githubusercontent.com/16282973/53871307-fe472d80-4036-11e9-9053-34d641e7c2ce.png)
在模拟器中与真机中运行都有这个问题

**Comment by hyjfine** [comment]
EditableText不提供焦点控制，这里其实用TextField会好些
/// This widget interacts with the [TextInput] service to let the user edit the
/// text it contains. It also provides scrolling, selection, and cursor
/// movement. This widget does not provide any focus management (e.g.,
/// tap-to-focus).

**Comment by hyjfine** [comment]
问题是focusNode引起的，下班开始仔细看了2个小时，最后断点发现EditableText的_handleSelectionChanged在切换焦点时会丢失一个。同样的例子不用fish_redux是ok的。所以应该是fish_redux细节没用对，仔细一看EditableText的FocusNode是每次update都会实例化的，而这个应该是要state传过来才是科学的。

**Comment by TianbinTobin** [comment]
@hyjfine 还是没懂造成这个问题的原因，在不用fish_redux时，两个EditAbleText同样是参数focusNode: FocusNode()，也是每次update都是new 一个新的FocusNode 实例吧？，但是并没有造成同时出现两个光标，但是用fish_redux为什么会造成这个问题呢？

**Comment by andyxiaoxi** [comment]
我也出现这个问题了，感觉很疑惑
