### ISSUE TITLE
同步问题

### ISSUE THREAD

**Issue by qq329401134** [alibaba/fish-redux#334]
![image](https://user-images.githubusercontent.com/38587734/59989882-821f3700-9673-11e9-8fa6-7f122b5d2933.png)
这是一个effect，我想要的效果是，设置showTextField这个标志位，让TextField显示，然后聚焦到它，但是我这样写了以后每次都是显示了TextField而没有聚焦，就是说聚焦操作在TextField完全显示之前就执行了，请问下该如何让它等待TextField显示然后执行聚焦

**Comment by zjuwjf** [comment]
disptach 并不提供刷新的回掉。

也许你需要的是如下的方式
```dart
  Future<void> untilNextFrame() {
    final Completer<void> completer = Completer<void>();
    WidgetsBinding.instance.addPostFrameCallback((Duration _) {
      completer.complete();
    });
    return completer.future;
  }

  void _onFocus(Action action, Context<dynamic> ctx) async {
    ctx.dispatch(xxx);
    await untilNextFrame();
    FocusScope.xxx
  }

```

**Comment by qq329401134** [comment]
你这个也可以，我之前采用的是在生命周期的build阶段调用FocusScope.xxx。效果一样

**Comment by qq329401134** [comment]
谢谢了
