### ISSUE TITLE
为什么不能替换Widget

### ISSUE THREAD

**Issue by qq329401134** [alibaba/fish-redux#335]
场景，我有一个搜索页面SearchPage，分为上下两个部分，上面是输入框，下面搜索结果是一个独立的page：ResultPage，输入框是一个无状态组件.
使用：
1.点击搜索的时候根据SearchPage的query属性传参到ResultPage，让其去获取和展示搜索结果
2.当我改变query的值，触发搜索函数的时候执行如下代码
![image](https://user-images.githubusercontent.com/38587734/60065849-cecc4600-9737-11e9-9bf8-c0cc417ff2b6.png)

![image](https://user-images.githubusercontent.com/38587734/60065811-afcdb400-9737-11e9-8a63-342fabfe9590.png)，
问题：搜索结果组件默认为resultPage = Container();
我将query设为111，第一次点击搜索会正常出现搜索111的ResultPage，当我改变query为222第二次点击搜索的时候，发现ResultPage并没有被替换为搜索222的ResultPage，依然是搜索111的ResultPage这是为什么呢，有点迷
请教下@zjuwjf

**Comment by zjuwjf** [comment]
用法非常的发散！
widget 不应该是state（状态）的一部分。 建议通过将ResultPage改为ResultComponent合适，然后由SearchBarComponent 发一个query的action给ResultComponent。

**Comment by qq329401134** [comment]
那请问下用approutes的方案怎么样，和你那个ResultComponent哪种比较好呢

**Comment by qq329401134** [comment]
> 用法非常的发散！
> widget 不应该是state（状态）的一部分。 建议通过将ResultPage改为ResultComponent合适，然后由SearchBarComponent 发一个query的action给ResultComponent。

那请问下用approutes的方案怎么样，和你那个ResultComponent哪种比较好呢
