### ISSUE TITLE
请教一下，使用 PageRoutes 怎么拦截类似登录的操作呢

### ISSUE THREAD

**Issue by Hiram-Y** [alibaba/fish-redux#337]
场景：
用户点击按钮，需要跳转（账户、实名、订单）等页面，这些页面都是要做登陆拦截，不知道PageRoutes 能支持这种行为？

**Comment by zjuwjf** [comment]
建议通过在Page上配置 EffectMiddleware 来拦截对应Page的Lifecycle.initState, 判断是否要登录拦截。

目前在重构部分代码，计划下期能通过PageRoutes 来完成上述的EffectMiddleware的配置。

**Comment by dyzyang** [comment]
还有个问题想要请教一下，如何做登录成功的监听，然后刷新页面呢? 我使用了store_util 工具类。
```
class StoreUtil {
  static Store<AppState> _globalStore;

  static Store<AppState> get globalStore {
    if (_globalStore == null) {
      _globalStore = createStore<AppState>(initState('test'), buildReducer());
    }
    return _globalStore;
  }
}

class AppState implements Cloneable<AppState> {
  String userName;
  bool isLogin;

  @override
  AppState clone() {
    return AppState()
      ..userName = userName
      ..isLogin = isLogin;
  }
}

AppState initState(String name) {
  final AppState state = AppState();
  state.userName = name;
  state.isLogin = false;
  return state;
}

Reducer<AppState> buildReducer() {
  return asReducer<AppState>(<Object, Reducer<AppState>>{
    AppAction.login: _login,
    AppAction.logout: _logout,
  });
}

AppState _login(AppState state, Action action) {
  final AppState newState = state.clone();

  newState.userName = action.payload['name'];
  newState.isLogin = action.payload['isLogin'];

  return newState;
}

AppState _logout(AppState state, Action action) {
  final AppState newState = initState('empty');
  return newState;
}

enum AppAction { login, logout }

class AppActionCreator {
  static Action login(String name, bool isLogin) {
    return Action(AppAction.login, payload: {'name': name, 'isLogin': isLogin});
  }

  static Action logout() {
    return Action(AppAction.logout);
  }
}
```

**Comment by zjuwjf** [comment]
设计上通过EffectMiddleware，应该比较容易完成。

```dart
typedef EffectMiddleware<T> = Composable<Effect<dynamic>> Function(
  AbstractLogic<dynamic>,
  Store<T>,
);

EffectMiddleware<T> interceptLogin<T>() {
    return (AbstractLogic<dynamic> logics, Store<T> store) =>
         (Effect<Object> next) => 
               (Action action, Context<Object> ctx) async {
                       if(action.type == Lifecycle.initState && logics is Page && need to intercept) {
                             await  拦截模块()；
                       } 
                       return next(action, ctx);
               };
}

```

**Comment by dyzyang** [comment]
好的 非常感谢，能否建个群 方便沟通 @zjuwjf

**Comment by dyzyang** [comment]
> ```dart
> interceptLogin
> ```
每个页面的中间件都需要配置一个这个吗？

**Comment by dyzyang** [comment]
> 还有个问题想要请教一下，如何做登录成功的监听，然后刷新页面呢? 我使用了store_util 工具类。
> 
> ```
> class StoreUtil {
>   static Store<AppState> _globalStore;
> 
>   static Store<AppState> get globalStore {
>     if (_globalStore == null) {
>       _globalStore = createStore<AppState>(initState('test'), buildReducer());
>     }
>     return _globalStore;
>   }
> }
> 
> class AppState implements Cloneable<AppState> {
>   String userName;
>   bool isLogin;
> 
>   @override
>   AppState clone() {
>     return AppState()
>       ..userName = userName
>       ..isLogin = isLogin;
>   }
> }
> 
> AppState initState(String name) {
>   final AppState state = AppState();
>   state.userName = name;
>   state.isLogin = false;
>   return state;
> }
> 
> Reducer<AppState> buildReducer() {
>   return asReducer<AppState>(<Object, Reducer<AppState>>{
>     AppAction.login: _login,
>     AppAction.logout: _logout,
>   });
> }
> 
> AppState _login(AppState state, Action action) {
>   final AppState newState = state.clone();
> 
>   newState.userName = action.payload['name'];
>   newState.isLogin = action.payload['isLogin'];
> 
>   return newState;
> }
> 
> AppState _logout(AppState state, Action action) {
>   final AppState newState = initState('empty');
>   return newState;
> }
> 
> enum AppAction { login, logout }
> 
> class AppActionCreator {
>   static Action login(String name, bool isLogin) {
>     return Action(AppAction.login, payload: {'name': name, 'isLogin': isLogin});
>   }
> 
>   static Action logout() {
>     return Action(AppAction.logout);
>   }
> }
> ```
@zjuwjf 这种情况需要怎么处理呢？我用下面的方式不管用
![image](https://user-images.githubusercontent.com/51750139/60240543-d3356200-98e3-11e9-801d-d4eabd614233.png)

**Comment by dyzyang** [comment]
> > ```dart
> > interceptLogin
> > ``
> 
> ![image](https://user-images.githubusercontent.com/51750139/60245630-93747780-98ef-11e9-9e01-790c7725c7c0.png)
> 我去试一下
我用了另一种方式，不然有的页面不太好处理,
比如：webview 打开链接，有的链接需要登陆才能打开，有的链接不需要登陆，但是webviewpage是同一个
```
  static void pushPage(BuildContext context, String routerPath, {dynamic arguments,bool interceptLogin = false}) {
    if (context == null || routerPath == null) return;
    if(interceptLogin){
      Navigator.push(context, CupertinoPageRoute<void>(builder: (ctx) => global.buildPage(RoutePath.XN_LOGIN_PAGE,arguments)));
 return;
    }
    Navigator.push(context, CupertinoPageRoute<void>(builder: (ctx) => global.buildPage(routerPath,arguments)));
  }
```

**Comment by tianlinzx** [comment]
这个重构是已经完成了吗？

**Comment by dyzyang** [comment]
> 了

我用的另一种方式，
弄了一个路由工具类，所有的跳转都通过路由来完成，在跳转的时候 传递是否需要登录拦截
`  
static void pushPage(BuildContext context, String routerPath, {dynamic arguments,bool interceptLogin = false}) {
    if (context == null || routerPath == null) return;
    if(interceptLogin && !isLogin()){
      Navigator.push(context, CupertinoPageRoute<void>(builder: (ctx) => global.buildPage(RoutePath.XN_LOGIN_PAGE,arguments)));
      return;
    }
    Navigator.push(context, CupertinoPageRoute<void>(builder: (ctx) => global.buildPage(routerPath,arguments)));
  }
`

**Comment by zjuwjf** [comment]
> 这个重构是已经完成了吗？

已经在master上了。

**Comment by YourksChan** [comment]
> 设计上通过EffectMiddleware，应该比较容易完成。
> 
> ```dart
> typedef EffectMiddleware<T> = Composable<Effect<dynamic>> Function(
>   AbstractLogic<dynamic>,
>   Store<T>,
> );
> 
> EffectMiddleware<T> interceptLogin<T>() {
>     return (AbstractLogic<dynamic> logics, Store<T> store) =>
>          (Effect<Object> next) => 
>                (Action action, Context<Object> ctx) async {
>                        if(action.type == Lifecycle.initState && logics is Page && need to intercept) {
>                              await  拦截模块()；
>                        } 
>                        return next(action, ctx);
>                };
> }
> ```

EffectMiddleware使用请问有案例吗?

**Comment by itmagus** [comment]
> ```dart
> 拦截模块
> ```

请问，await  拦截模块()；具体怎么跳转到登录界面呢？
