### ISSUE TITLE
能否创建一个 微信群或者钉钉群 方便大家沟通

### ISSUE THREAD

**Issue by Hiram-Y** [alibaba/fish-redux#338]

**Comment by zjuwjf** [comment]
Github 作为全球最大的同性交流网站，应该是程序员们沟通的首选。如果有需要更近一步的沟通联系，可以给我发邮件。

**Comment by tingkai-zhang** [comment]
除了开发者的问题以外，还会有学习者的问题。这些问题不一定都适合在github上提问。
为什么要阻止建立学习社区？如果没有提供足够好的学习社区，那么学习者就很难转变成贡献者。
我想提这个issue的人指的是学习群，而且很多开源项目都有自己的slack，方便用户交流。
我建议打开这个issue。
我这里建立了一个qq群：871395124
欢迎想学习交流fish redux的同学加入。
