### ISSUE TITLE
fish-redux多语言切换

### ISSUE THREAD

**Issue by liangwei0101** [alibaba/fish-redux#339]
在flutter使用本地化时，如果使用官方提供的界面写法，切换语言后，界面上绑定语言对应的资源是会变化的。而使用了fish-redux后，使用本地化后，值变了界面重新build后，绑定语言对应的资源依旧没有变化，不知道是否因为view的刷新值只State中变量变化有关。于是我强制性拦截Lifecycle，强制将值覆盖，是会生效的，但是每个view要多写这种代码，view很多，那么会有很多重复代码。请问这个怎么优化呢？

**Comment by zjuwjf** [comment]
看描述是fish-redux的bug。 有没有可以运行的demo例子 ？

**Comment by liangwei0101** [comment]
https://github.com/liangwei0101/fish_redux_issue.git 这个是刚写的demo，在main.dart中的
child: Test(),  // 这是可以的
//child: FishTestPage().buildPage(null),  // 这是不可以的
切换着跑一下就能看出来。

**Comment by zjuwjf** [comment]
这里的问题是在于 fish-redux 是基于redux的数据驱动的框架，所以没有数据变化是不会有UI的变化的。

在语言切换上也是如此。

正确的做法是：
1、创建一个AppStore，保存语言信息
2、为任意需要用到语言信息的页面和AppStore做一次单向的链接
3、发Action到AppStore，修改语言信息，所有相关的页面或者组件就会自然的最小刷新。

**Comment by liangwei0101** [comment]
您能否在上面那个可以运行的demo上做个小改造，让我这么参考下呢？

**Comment by liangwei0101** [comment]
> 这里的问题是在于 fish-redux 是基于redux的数据驱动的框架，所以没有数据变化是不会有UI的变化的。
> 
> 在语言切换上也是如此。
> 
> 正确的做法是：
> 1、创建一个AppStore，保存语言信息
> 2、为任意需要用到语言信息的页面和AppStore做一次单向的链接
> 3、发Action到AppStore，修改语言信息，所有相关的页面或者组件就会自然的最小刷新。

您能否在上面那个可以运行的demo上做个小改造，让我这么参考下呢？

**Comment by zjuwjf** [comment]
修改语言和修改应用主题，是一致的，可以参考example。
