### ISSUE TITLE
静态适配器和动态适配器的使用区别是啥

### ISSUE THREAD

**Issue by niugengyun** [alibaba/fish-redux#340]
能否举例给个具体的使用场景？

比如下图 ，应该怎么搞

<img width="305" alt="WX20190626-112105@2x" src="https://user-images.githubusercontent.com/4466086/60148650-8af34280-9804-11e9-94c2-3bef9d248130.png">

@zjuwjf

**Comment by a314730500** [comment]
封装Component和Adapte  然后组装StaticFlowAdapter
class UserCenterPage extends Page<UserCenterState, Map<String, dynamic>> {
  UserCenterPage()
      : super(
            initState: initState,
            effect: buildEffect(),
            reducer: buildReducer(),
            view: buildView,
            dependencies: Dependencies<UserCenterState>(
                adapter: StaticFlowAdapter<UserCenterState>(
                  slots: <Dependent<UserCenterState>>[
                    UserHeaderComponent().asDependent(HeaderComponentCon()),
                    ListImageItemAdapter().asDependent(ListConnectorSection6()),
                    UserCenterBottomComponent().asDependent(BottomComponentCon()),
.....
                  ]
                ),
                slots: <String, Dependent<UserCenterState>>{
                }),
            middleware: <Middleware<UserCenterState>>[
            ],);

}
在view里面
 final ListAdapter adapter = viewService.buildAdapter();
  return Scaffold(
    body: Container(
      color: Color.fromRGBO(245, 245, 245, 1),
      child: Column(
        children: <Widget>[
          Expanded(
              child: ListView.builder(
                  itemBuilder: adapter.itemBuilder,
                  itemCount: adapter.itemCount))
        ],
      ),
    ),
  );
这样子调用

**Comment by niugengyun** [comment]
这里个用➕好链接是一样的吧 

UserHeaderComponent().asDependent(HeaderComponentCon()),
ListImageItemAdapter().asDependent(ListConnectorSection6()),
UserCenterBottomComponent().asDependent(BottomComponentCon())

**Comment by niugengyun** [comment]
静态的这个我基本可有理解，能否继续讲解动态的使用场景（Listview吗）

**Comment by zjuwjf** [comment]
Adapter 是什么？

回答这个问题前， 我们先来看下UI组件化，它普遍存在于各个前端、客户端框架中。

组件化就是将局部的展示和逻辑封装成独立的标准化单元，然后像乐高积木一样，在特定的插槽位置，插入标准化的组件。

这个过程在fish-redux中称之为插槽。 我们可以通过 dependencies.slots 配置。

但是组件化是否只有一种形态，是否只有插槽一种场景？

fish-redux的答案是我们还需要另一种的组件抽象，来适应列表的场景。

为什么呢？

事实上插槽场景适合于切分一个圆形的蛋糕（Map），将一个页面或者大的组件，切分成若干更细的小组件。

而在面向列表（Array）场景，用slots的切分在很多时候是有很大缺陷的，所以在对列表的场景下，fish-redux提出了一个新的组件化概念Adapter。

Adapter也是一个组件化的标准。对比Component，Component是展示和逻辑的封装单元，Adapter是[0-n]行UI的展示和逻辑的封装。

一个列表必然是一个Adapter，然后里面的每一个子项可以是Adapter（子列表、巨大Cell的拆分等）负责了其中[0-n]行UI的展示和逻辑，也可以是Component负责了其中1行UI的展示和逻辑。

具体来说Adapter的三个类：
1、DynamicFlowAdapter
    这个可能是大家最熟悉的一种形式。在长列表的场景下，我们预制了确定的有限种类的Component或者Adapter，然后受到不定长度的数组数据的驱动，
    渲染出一个[0-∞]行的列表。
    它本质上是一个Adapter的容器管理。
 
2、StaticFlowAdapter
    这可能是大家非常不熟悉的一种形式。但它又非常有用。比如内容详情，但在内容详情特别复杂，又对性能有很高要求的场景下，我们希望内容详情也是一个列表。
    但是传统的我们用DynamicFlowAdapter来表达一个详情的列表有一些缺陷：
    1、耦合性： 详情的数据往往是一个MapLike的对象，而非数组，而当业务复杂的情况下，数据的转化会带来很高的耦合性，比如要再详情页增加一个组件，会需要改很多地方，而理想的是完成一个独立的新组件，然后在一个配置区域，简单配置即可。

    2、状态的集中管理：比如详情里的一个组件的状态发生了变化（比如发生了一次评论），我们期望在其他组件中（评论个数的展示）也能快速同步反应变化。而以DynamicFlowAdapter的形态，数据是数组，本质上数组的每一项数据都是隔离的，做数据的联动会增加一定的复杂度。

所以总结来看DynamicFlowAdapter 适合数据源是数组，同时组件之间相对更独立的场景。 

而在类似详情的场景中，逻辑上，它更适合用插槽的形式来做。为了更好的性能，如何将插槽和列表进行结合呢？ fish-redux 给出的解法是StaticFlowAdapter。

传统的插槽是需要设定插槽的位置点（key），而在列表的场景下，插槽的位置点是Item的顺序。

所以
StaticFlowAdapter({
    @required List<Dependent<T>> slots,
})
它是这样的，它的slots是一个数组。 根据有没有数值，按slots的配置顺序显示。

3、Adapter
    它是用来做自定义的[0-n]行的展示和逻辑的封装。比如对一个大的Cell，它的逻辑是一体的，但是我们可以优化它的展示，从1个cell, 变成n个cell。

**Comment by niugengyun** [comment]
> Adapter 是什么？
> 
> 回答这个问题前， 我们先来看下UI组件化，它普遍存在于各个前端、客户端框架中。
> 
> 组件化就是将局部的展示和逻辑封装成独立的标准化单元，然后像乐高积木一样，在特定的插槽位置，插入标准化的组件。
> 
> 这个过程在fish-redux中称之为插槽。 我们可以通过 dependencies.slots 配置。
> 
> 但是组件化是否只有一种形态，是否只有插槽一种场景？
> 
> fish-redux的答案是我们还需要另一种的组件抽象，来适应列表的场景。
> 
> 为什么呢？
> 
> 事实上插槽场景适合于切分一个圆形的蛋糕（Map），将一个页面或者大的组件，切分成若干更细的小组件。
> 
> 而在面向列表（Array）场景，用slots的切分在很多时候是有很大缺陷的，所以在对列表的场景下，fish-redux提出了一个新的组件化概念Adapter。
> 
> Adapter也是一个组件化的标准。对比Component，Component是展示和逻辑的封装单元，Adapter是[0-n]行UI的展示和逻辑的封装。
> 
> 一个列表必然是一个Adapter，然后里面的每一个子项可以是Adapter（子列表、巨大Cell的拆分等）负责了其中[0-n]行UI的展示和逻辑，也可以是Component负责了其中1行UI的展示和逻辑。
> 
> 具体来说Adapter的三个类：
> 1、DynamicFlowAdapter
> 这个可能是大家最熟悉的一种形式。在长列表的场景下，我们预制了确定的有限种类的Component或者Adapter，然后受到不定长度的数组数据的驱动，
> 渲染出一个[0-∞]行的列表。
> 它本质上是一个Adapter的容器管理。
> 
> 2、StaticFlowAdapter
> 这可能是大家非常不熟悉的一种形式。但它又非常有用。比如内容详情，但在内容详情特别复杂，又对性能有很高要求的场景下，我们希望内容详情也是一个列表。
> 但是传统的我们用DynamicFlowAdapter来表达一个详情的列表有一些缺陷：
> -- 1、耦合性： 详情的数据往往是一个MapLike的对象，而非数组，而当业务复杂的情况下，数据的转化会带来很高的耦合性，比如要再详情页增加一个组件，会需要改很多地方，而理想的是完成一个独立的新组件，然后在一个配置区域，简单配置即可。
> 
> -- 2、状态的集中管理：比如详情里的一个组件的状态发生了变化（比如发生了一次评论），我们期望在其他组件中（评论个数的展示）也能快速同步反应变化。而以DynamicFlowAdapter的形态，数据是数组，本质上数组的每一项数据都是隔离的，做数据的联动会增加一定的复杂度。
> 
> 所以总结来看DynamicFlowAdapter 适合数据源是数组，同时组件之间相对更独立的场景。
> 
> 而在类似详情的场景中，逻辑上，它更适合用插槽的形式来做。为了更好的性能，如何将插槽和列表进行结合呢？ fish-redux 给出的解法是StaticFlowAdapter。
> 
> 传统的插槽是需要设定插槽的位置点（key），而在列表的场景下，插槽的位置点是Item的顺序。
> 
> 所以
> StaticFlowAdapter({
> @required List<Dependent> slots,
> })
> 它是这样的，它的slots是一个数组。 根据有没有数值，按slots的配置顺序显示。
> 
> 3、Adapter
> 它是用来做自定义的[0-n]行的展示和逻辑的封装。比如对一个大的Cell，它的逻辑是一体的，但是我们可以优化它的展示，从1个cell, 变成n个cell。

能否根据上图  给一个代码大概的框架，主要告诉我我们怎么分离组件、用那种适配器就行了   不用写的太详细

**Comment by zjuwjf** [comment]
生命周期话题：
当Adapter用来管理 [0-n]行的UI的展示的时候，我们就不得不思考一个生命周期的问题。  什么时候是这个Adapter的创建和销毁。

组件的生命周期我们很好理解，对应了WidgetState的初始化和销毁，当一个组件划入可视区，组件得到了创建，当组件滑出可视区，组件得到了销毁。

那Adapter呢？ 它管理的是不定行数的组件。

在这里fish-redux给出了一个最优的答案，Adapter的生命周期和ListView的生命周期一致。

这样的设计，带来巨大收益：
1、组件化更加彻底。 当不管是整体的大Adapter，还是列表子项其中局部的小Adapter，生命周期都提升后，局部的单元它们更加解耦，能完成完整的独立功能，比如自己的初始化，网络请求，资源的释放等等。
2、当小Adapter生命周期提升，我们就有能力额外的提供了，划入可视区（appear）和滑出可视区（disappear）事件，带来更佳完整的能力。

**Comment by zjuwjf** [comment]
> 能否根据上图 给一个代码大概的框架，主要告诉我我们怎么分离组件、用那种适配器就行了 不用写的太详细

参考下example里的todolist把

**Comment by niugengyun** [comment]
> > 能否根据上图 给一个代码大概的框架，主要告诉我我们怎么分离组件、用那种适配器就行了 不用写的太详细
> 
> 参考下example里的todolist把

谢谢  ，如果想监听app的生命周期，应该怎么写（切换到后台、从后台唤起）

**Comment by zjuwjf** [comment]
> > > 能否根据上图 给一个代码大概的框架，主要告诉我我们怎么分离组件、用那种适配器就行了 不用写的太详细
> > 
> > 
> > 参考下example里的todolist把
> 
> 谢谢 ，如果想监听app的生命周期，应该怎么写（切换到后台、从后台唤起）

#359

**Comment by TangYuanHuan** [comment]
可以给一个可以运行的StaticFlowAdapter使用demo看看吗，没看懂StaticFlowAdapter是怎么用的，尝写代码学习怎么使用StaticFlowAdapter会一直报错
