### ISSUE TITLE
关于HybridRoutes的疑问

### ISSUE THREAD

**Issue by codlin** [alibaba/fish-redux#343]
我看官方自带的TodoList的例子，里面
```dart
Widget createApp() {
  final AbstractRoutes routes = HybridRoutes(routes: <AbstractRoutes>[
    PageRoutes(
      pages: <String, Page<Object, dynamic>>{
        'todo_list': pageConfiguration(ToDoListPage()),
        'todo_edit': pageConfiguration(TodoEditPage()),
      },
    ),
  ]);

  return MaterialApp(
    title: 'Fluro',
    debugShowCheckedModeBanner: false,
    theme: ThemeData(
      primarySwatch: Colors.blue,
    ),
    home: routes.buildPage('todo_list', null),
    onGenerateRoute: (RouteSettings settings) {
      return MaterialPageRoute<Object>(builder: (BuildContext context) {
        return routes.buildPage(settings.name, settings.arguments);
      });
    },
  );
}
```
HybridRoutes.buildPage方法会循环所有routes，对每个route根据path来buildPage，如果有一个build成功即返回。
上面代码HybridRoutes routes有一个PageRoutes，其中path为todo_list，home: routes.buildPage('todo_list', null)最终会会返回widget。
但问题是：
如果routes中有多个PageRoutes，其中有多个todo_list，那后面的岂不是执行不了了？

请问HybridRoutes的设计理念是什么？ 是否会出现我说的这种情况？

谢谢

**Comment by hzgotb** [comment]
HybridRoutes 原本是为了挂载一个全局Store到页面里所加上去的。所以你在例子你看到了 pageConfiguration 这个方法。
至于你说的多个todo_list的情况，你要具体说一下。通常，我们不会用相同的key做路由名称。而且，这个本质上还是使用了 MaterialApp 自带的路由功能。

**Comment by codlin** [comment]
谢谢~
