### ISSUE TITLE
adapter 中的 component组件 如何取到 adapter state之外的数据。

### ISSUE THREAD

**Issue by Mar-er** [alibaba/fish-redux#344]
比如：三个页面组件完全相同，只有adapter中的component 的 某个小图标 不一样，如果想三个路由公用一个页面，需要通过判断路由来显示不同的图标，如何从pageStore中拿到保存的路由信息用于显示不同的图标

**Comment by Mar-er** [comment]
数据结构是这样的
pageState: {
 list: [],
 currentRouteName: 'string'
}
list 是 adapter 中 componentState 的数据集合，如何从 adapter 的 component 中 取到 currentRouteName 的值

**Comment by hzgotb** [comment]
其实，你完全可以把adapter拿出来做一个公用组件。然后通过传参的方式判断显示哪一个小图标。至于怎么传参。
像例子里的:
```dart
onGenerateRoute: (settings) {
  return MaterialPageRoute(
    builder: (context) => routes.buildPage(settings.name, settings.arguments)
  );
},
```

**Comment by Mar-er** [comment]
> 其实，你完全可以把适配器拿出来做一个公用组件然后通过传参的方式判断显示哪一个小图标至于怎么传参。
> 像例子里的：
> 
> ```dart
> onGenerateRoute :(设置）{
>    return  MaterialPageRoute（
>     builder ：（context）= > routes。buildPage（settings.name，settings.arguments）
>   ）;
> }，
> ```

adapter怎么拿出来做公共组件。我现在就是通过路由传参把当前路由名字传到pageState的 currentRouteName 中，但是adapter中的component不知道如何获取currentRouteName的值

**Comment by hzgotb** [comment]
你可以发一下你的adapter的connector部分吗？

**Comment by zjuwjf** [comment]
fish-redux的设计理念是纯粹的单一数据驱动。
所以任意的一个Component或者Adapter，只关心它所能看到的\<T\>，然后只受\<T\>数据变化的驱动。
如果你想看到额外的状态，那么它应该是\<T\>的一部分。

任意的一个Component或者Adapter不应该假设自己会被那个页面或者容器使用。
