### ISSUE TITLE
这库模版代码真多，感觉是封装过度，还不如 flutter_redux。

### ISSUE THREAD

**Issue by AibiTi** [alibaba/fish-redux#346]
**Describe the bug**
Show the code you wrote as completely as possible.
```dart
/// your code here
``` 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
1. The version of fish-redux which you are using.
2. The information from flutter doctor.

**Comment by hzgotb** [comment]
欢迎提出好的建议。

**Comment by zjuwjf** [comment]
这个属于选择问题。 每一个框架都有适合的场景。
fish-redux 更适合于有一定规模的项目。他们有业务的复杂度、需要更好的团队协作和长期的维护。

如果不需要这些，我的建议是可以直接基于Flutter库来开发。当项目开始变得越来越大，难以长期维护和协作的时候，可以考虑使用fish-redux。
