### ISSUE TITLE
fish-redux state 更新 导致界面 焦点重置

### ISSUE THREAD

**Issue by longgui0318** [alibaba/fish-redux#348]
目前使用 fish-redux 中，通过redux state更新倒计时时间，每次更新导致界面焦点丢失，键盘回弹效果如下 ：
![a9ca8541-a7da-4586-b163-6b5bb35d3574](https://user-images.githubusercontent.com/3406303/60323017-7ef9b300-99b3-11e9-84cb-6f7ac9cae392.gif)
      但不使用fish-redux的，通过StatefulWidget setState 更新倒计时时间，效果如下
![de328887-b0ab-44e8-894d-55b2f3f7db82](https://user-images.githubusercontent.com/3406303/60323166-e283e080-99b3-11e9-97cd-7d83554fc8a0.gif)

**Comment by DDDrop** [comment]
没有代码，只能推测是state的clone没写全。

**Comment by longgui0318** [comment]
@DDDrop 不是，代码比较多，简单而言 跟 state怎么存无关，TextFormField 的焦点丢失而不是其他的丢失，我尝试 将controller、focusNode、autofocus都通过state保存下来（尝试焦点还原），state更新依然会重置焦点 导致键盘回弹

**Comment by hzgotb** [comment]
cc @zjuwjf

**Comment by zjuwjf** [comment]
没有代码，我们无法帮助到你

**Comment by longgui0318** [comment]
``` 
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart';

import 'action.dart';
import 'state.dart';

Widget buildView(TestState state, Dispatch dispatch, ViewService viewService) {
  final _formKey = GlobalKey<FormState>();
  return Scaffold(
    appBar: AppBar(title: const Text('测试'), centerTitle: true),
    body: Form(
      key: _formKey,
      child: Column(
        children: <Widget>[
          SizedBox(
            width: 200,
            height: 50,
            child: TextFormField(
              keyboardType: TextInputType.number,
              autofocus: false,
            ),
          ),
          RawMaterialButton(
              child: Text("计数${state.count}"),
              onPressed: () {
                dispatch(TestActionCreator.onAction(state.count + 1));
              }),
        ],
      ),
    ),
  );
}

```
代码如上，问题找到了，是buildView 时候 创建了GlobalKey<FormState> 触发了该组件树的强制刷新
