### ISSUE TITLE
求相关demo或详细文档

### ISSUE THREAD

**Issue by 553559555** [alibaba/fish-redux#349]
本人刚入坑flutter不久，求大神给一个详细一点的demo。
看了一下官方提供的demo感觉有点封装过度，
对于我这种刚入坑的人不是很友好。
如果有相关的demo地址请给我一份，再此先谢过了。

**Comment by hzgotb** [comment]
https://github.com/hzgotb/fish-redux-get-started.git
比较简单的，你可以简单的看一下。

**Comment by 553559555** [comment]
@hzgotb 好的 谢谢

**Comment by hzgotb** [comment]
也可以暂时看一下这个。https://hzgotb.github.io/fish-redux-docs/zh/guide/get-started/ 。
