### ISSUE TITLE
sample android的功能目录有问题,build.gradle 等文件丢失,需要自己从新生成

### ISSUE THREAD

**Issue by CharlesZqikai** [alibaba/fish-redux#35]
虽然不难,可能给刚入门的同学带来麻烦!我就是刚入门的同学 哈哈

**Comment by zjuwjf** [comment]
参考命令即可
cd ./sample
flutter create .
flutter run

**Comment by hyjfine** [comment]
从实用看内置build.gradle也是可以的，这里fish redux团队没有内置的考虑是大家的sdk和gradle版本会不一样，减少依赖？@zjuwjf

**Comment by zjuwjf** [comment]
是的，减少依赖和冲突， 然后我们也在readme中加入了如何来运行sample的参考命令。
