### ISSUE TITLE
createStoreBuilder

### ISSUE THREAD

**Issue by codlin** [alibaba/fish-redux#351]
createStoreBuilder是否需要给外部使用？ 是不是应该是_createStoreBuilder？
谢谢

**Comment by hzgotb** [comment]
cc @zjuwjf lib/src/redux_component/page.dart createStoreBuilder

**Comment by zjuwjf** [comment]
大部分时候不需要， 因为fish-redux对使用者来说，是隐藏了store的创建和reducer组装的相关细节。

但是
1、作为一个标准的redux， createStoreBuilder 是需要提供的。
2、在有些场景，比如建立一个AppStore的时候，开发者会用到。

**Comment by codlin** [comment]
好，谢谢回答
