### ISSUE TITLE
关于生命周期的一个问题

### ISSUE THREAD

**Issue by dyzyang** [alibaba/fish-redux#355]
场景：
     首页： BottomNavigationBarItem + IndexedStack
     总共有四个页面，这四个页面有一个是webview ，
     当我切换到webview的时候，我想重新reload一下页面，
问题1：能通过生命周期的方式去监测吗？我没找到是否显示的监听呢？
还是通过点击之间去通知webview刷新呢？
问题2:  现在底部按钮切换的时候 每个page都会执行一次，不应该显示的page才执行吗？

**Comment by hzgotb** [comment]
老哥，这些问题看flutter文档，应该可以解决的。
