### ISSUE TITLE
buildComponent parameter getter

### ISSUE THREAD

**Issue by codlin** [alibaba/fish-redux#357]
buildComponent的参数getter是store的getState函数吧，感觉此处用getter语义很模糊，能不能详细解释一下。谢谢

**Comment by zjuwjf** [comment]
buildComponent的参数不一定是 store.getState.  只有Page的buildComponent的参数是 store.getState。

而普通Component的参数，是通过connector 层层传递的。

**Comment by codlin** [comment]
谢谢~
