### ISSUE TITLE
flutter 1.7.11中bug

### ISSUE THREAD

**Issue by dlwslb** [alibaba/fish-redux#360]
fish_redux 0.2.2  无NoneConn
好像还不支持1.711
 Lifecycle.initState: _init,
PageAction.onAdd: _onAdd, 类型不匹配

**Comment by tianlinzx** [comment]
本来就说了只支持1.5版本啊，试试master分支能不能支持1.7.11吧。

**Comment by DDDrop** [comment]
应该是 #303 这个问题。

**Comment by zjuwjf** [comment]
Duplicate of #303
