### ISSUE TITLE
官方案例AppStore的bug

### ISSUE THREAD

**Issue by YourksChan** [alibaba/fish-redux#362]
环境:
Flutter 1.7.12-pre.42 • channel master • https://gitee.com/yourks/flutter.git
Framework • revision 9e1b4b22c2 (4 days ago) • 2019-06-30 22:40:09 -0700
Engine • revision e96900df2f
Tools • Dart 2.4.0

fish-redux版本:
Thu Jul  4 14:46:49 最新版

问题：

当我使用此方法（ToDoListPage().buildPage(null)）创建一个page的时候，将会收不到全局刷新数据更新.

visitor -> page.connectExtraStore 中无法拦截到ToDoListPage回调事件

**Comment by zjuwjf** [comment]
在1.7中， 暂未验证。  建议使用 flutter stable 版本。

**Comment by zjuwjf** [comment]
使用的bug。

ToDoListPage() 重新创建的Page 并未建立和AppStore的连接关系。
