### ISSUE TITLE
flutter web 报错

### ISSUE THREAD

**Issue by zhennayw** [alibaba/fish-redux#363]
我将fish-redux 2.2 集成进工程，在dart2js的时候报错，我怎样修改不会影响fish-redux正常运行？感谢！

bogon:caricature_app cibn$ webdev serve --hostname 127.0.0.1
[INFO] Reading cached asset graph completed, took 573ms
[INFO] Checking for updates since last build completed, took 1.6s
[INFO] Serving `web` on http://127.0.0.1:8080
[SEVERE]build_web_compilers:ddc on lib/external/fish_redux/src/redux_connector/generator.dartdevc.module: Error compiling dartdevc module:caricature_app|lib/external/fish_redux/src/redux_connector/generator.ddc.js

[error] The integer literal '0x3FFFFFFFFFFFFFFF' can't be represented exactly in JavaScript. The nearest value that can be represented exactly is '0x4000000000000000'. (package:caricature_app/external/fish_redux/src/redux_connector/generator.dart, line 5, col 21)

Please fix all errors before compiling (warnings are okay).
}

**Comment by zhennayw** [comment]
代码：

String Function() generator() {
  int nextId = 0;
  String prefix = '';
  return () {
    if (++nextId >= 0x3FFFFFFFFFFF) {
      nextId = 0;
      prefix = '\$' + prefix;
    }
    return prefix + nextId.toString();
  };
}

**Comment by YourksChan** [comment]
flutter_web不支持插件

Plugins
Plugins are not currently supported in flutter web.

https://github.com/flutter/flutter/wiki/Building-a-web-application-with-Flutter
