### ISSUE TITLE
关于在异步请求中使用 Dialog 的问题

### ISSUE THREAD

**Issue by dxGuan** [alibaba/fish-redux#365]
如题：
若某个 action 触发了 effect，在 effect 中需要调用一些异步的请求，我希望在调用请求前显示 dialog，在请求后（无论成功/失败）都主动 dismiss 该 dialog。

这种场景，相关的 showDialog / dismissDialog 是应该放在 effect 中处理 还是应该再 dispatch 一个action 给 reducer，然后 reducer 再生成一个 state（里面包含指定是否 loading 的状态），最后在 view 中通过这个 loading 去决定是否显示 dialog？

如果是后者的话，那在 buildView 中应该如何去获取 context 并显示 dialog 呢？

**Comment by hzgotb** [comment]
建议是在effect去写。

**Comment by dxGuan** [comment]
> 建议是在effect去写。

想请问一下，为何建议在 effect 去写?
如果说 effect 就是处理一些与非修改数据的行为，那这种 showDialog 的 UI 层面的行为，是否其实放在  view 处理会更好？想了解一下建议放在 effect 去写的原因？thx

然后另外的问题是，如果我在 effect 去处理 dialog，在调用异步请求前，直接调用 showDialog() 这个方法没有效果，相关代码如下：

```dart
_onXXXX(Action action, Context<XXXXState> ctx) {
  showDialog(
      context: ctx.context,
      builder: (buildContext) {
        return CircularProgressIndicator();
      });
  // 异步请求
  ....
}
```

**Comment by zjuwjf** [comment]
Dialog 是 api 驱动的，而非数据驱动的，所以它应该放在effect里更加合适。

同时使用Dialog，强烈建议是通过异步函数，来完成交互过程。

```dart
_onXXXX(Action action, Context<XXXXState> ctx) async {
  final String result = await showDialog(必要的参数);
  if(result == 'YES') {
  }
  // 异步请求
  ....
}
```

**Comment by dxGuan** [comment]
了解，thx。
