### ISSUE TITLE
Advise: 移除在combineEffects()中返回值改写行为

### ISSUE THREAD

**Issue by cornsauce** [alibaba/fish-redux#366]
**情景描述**

几分钟前，我吹着9.9买来的电风扇，啃着西瓜，写着代码。一瞬间，我浑身发毛，一个巨无霸BUG显现了。记得那是一个简单的effect，只是为了让弹出层关闭的时候恢复弹出时保存在某个犄角旮旯的SystemStatusBar的颜色而已。但是我发现，颜色恢复了，弹出层没关掉。于是我火速诊断问题，我发现state没啥变化，再一看state，卧槽！还是没有变化。我开始慌了，我不知道为什么会导致这样的问题。凭借着我熟读FR的经验来看，我估摸着是FR官方闲着没事整了个新middleware消遣时光？在我查看完logic.dart这个文件的时候，我开始怀疑人生了，为什么没有！按理来说，应该会有一个middleware进来。于是我不相信，便从page.dart又看了一遍，好像没添加啥middleware啊。这就让我摸不着头脑了，于是我赶忙跑到_applyOnAction函数中一探究竟。这一探倒是不要紧，关键是我发现，返回值居然被他娘的改写了！！！我吓得赶忙关上了我那9.9的豪华大风量电风扇，把西瓜放在旁边的《编译原理》上，我这下真的不知道怎么办了，我吓得甚至想打110平复我的心情。但是我觉得，事出必有果，我凭借着我的毅力，跑到自个写的辣鸡effect的最后一行敲下了这段代码

```dart
print('stub!!!');
```

并且打上了断点，一套流利的快捷键 Ctrl + F2 和 Shift + F9，顺势发出，大概过了个一年半载，我身边的手机亮起了熟悉的破烂app界面，紧接着我一套流利的操作，进入了断点。几下 F7 之后，我找到了罪魁祸首 `/lib/src/redux_component/helper.dart` 中第 `67` 行

```dart
return subEffect?.call(action, ctx) ?? subEffect != null;
```

我这一看，卧槽！这不是罪魁祸首吗，这踏马居然神奇地改写了返回值，导致了**返回值为true，所以effect不会再继续肆无忌惮地next()下去了**。紧接着，我跑去了天台，并且点燃了手中那颗3.5一盒的白沙烟，我觉得人生中宝贵的几分钟都浪费了。所以为了不让更多人浪费时间，我来到了这里，写下了我的处女issue，希望官方能听老夫一句劝。

** 期望 **

把这个莫名其妙的蜜汁改写删了可好，一般来说如果没有明确的要阻止effect链的行为，那多数人还是希望effect链可以执行到底，整这样没用的东西只会增加更多的麻烦。

当然了，我觉得我这个提议被采纳的可能性不大，毕竟咸鱼在那放着不是。。。

**Comment by zjuwjf** [comment]
1、什么是combineEffects

combineEffects 并不是一个基础的api， 它更像是一个helper类型的api。

没有combineEffects-api的情况下， 我们可以去写一个完整的Effect函数如
```dart
dynamic  _effect(Action action, Context ctx) {
       switch(action.type) {
             /// bala bala
       }
}
```

但是如果case 足够复杂，我们就需要将每一个分支独立，这时候就会用到combineEffects。
它可以将很多独立的小分支effect函数，合并为一个大的effect函数。

2、combineEffects的默认行为
我们在1中讲了 combineEffects的角色和责任， 然后就是他的实现了。 实现上会考虑哪些case会是更加常见的。

比如大部分的effect分支，都应该是到此为止的。只有极少的case才会有诉求通过effect处理后，再进入reducer。

所以从常用性出发，我们给combineEffects设定了默认行为，如果函数没有返回值的话，默认不再继续传递。当然就像你代码所示
```dart
return subEffect?.call(action, ctx) ?? subEffect != null;
```
这里留了一个很小的口，可以返回false，达到这样的既进入effect小分支的处理，也能达到reducer。

当然让你花了这个多时间来调试这个问题，是我们的错，非常抱歉。
文档和代码指引上应该更加清晰的说明这一点。

3、去掉combineEffects的默认行为
目前是不准备这样做的，当然如果有这样的诉求，可能是要增加一个类似的helper类型的api？
