### ISSUE TITLE
flutter v1.7.8+hotfix.2 适配问题

### ISSUE THREAD

**Issue by GitTradWang** [alibaba/fish-redux#368]
**flutter 1.7.8+hotfix.2 release了！fish-redux什么时候适配哇**

**Comment by Jack-SunQi** [comment]
是不是遇到了Action冲突的问题？

**Comment by learyR** [comment]
不兼容额

**Comment by GitTradWang** [comment]
> 是不是遇到了Action冲突的问题？

嗯，是的

**Comment by GitTradWang** [comment]
> 不兼容额

所以希望尽快兼容了啦 自己在demo阶段 还未应用到项目中所以不想自己fork改代码了

**Comment by Yxjie** [comment]
我也遇到过了 buildEffect方法 combineEffects方法中 第二个参数提示 类型不匹配 从原来 Action 变成dynamic类型了

**Comment by zjuwjf** [comment]
Duplicate of #303
