### ISSUE TITLE
关于Effect的疑惑

### ISSUE THREAD

**Issue by MEiDIK** [alibaba/fish-redux#37]
假设组件A dispatch一个action时，会调用自己的effect，如果自己没有消耗掉的话，会进行广播，这时其他组件也会调用自己的effect。
这里我有两个问题：
1. 由于组件A也注册了广播，自己的effect会再次被调用，这里是否要避免一下？
2. 请问这个广播触发其他组件一起调用effect具体能用在什么情境下？

```
  static Middleware<T> _applyOnAction<T>(OnAction onAction, Context<T> ctx) {
    return ({Dispatch dispatch, Get<T> getState}) {
      return (Dispatch next) {
        return (Action action) {
          final Object result = onAction?.call(action);
          if (result != null && result != false) {
            return;
          }

          //skip-lifecycle-actions
          if (action.type is Lifecycle) {
            return;
          }

          if (!shouldBeInterrupttedBeforeReducer(action)) {
            ctx.pageBroadcast(action);
          }

          next(action);
        };
      };
    };
  }
}
```

**Comment by zjuwjf** [comment]
1. 去组织Effect的时候，往往是通过combineEffects来完成的，其实内部有个hash能快速的确定 A-Effect要不要消费 Action。也就是即使广播进入了A-Effect也能快速跳出。
2. 这个是做组件间副作用部分的通信的， 同时将通信的流程扁平化，和视图的结构解耦。

总结来说， dispatch 是一个自我优先消费的广播系统。这样的设计是用最简单的api，完成我们几乎所有的通信诉求。

**Comment by MEiDIK** [comment]
@zjuwjf 问题一中，我看sample中的effect都是完整消费了整个action，如果存在一个情况是effect要进行某个操作，但同时需要通知其他组件的，即effect返回fasle，如下代码

```
dynamic _onEffect(Action action, Context<PageState> ctx) {
  println('_onEffect_');
  //...other codes
  return false;
}
```

这样这个_onEffect方法就会被执行两次，控制台打印：
```
_onEffect_
_onEffect_
```

**Comment by zjuwjf** [comment]
虽然从设计上期望，消费或者不消费是一个明确的事。
你给的建议非常棒，我会考虑处理。

**Comment by zjuwjf** [comment]
已处理，对广播增加了 excludedSelf 参数。

**Comment by brsun** [comment]
为什么3月份就解决了，9月使用^0.2.6，返回false，onEffect还是会调用两次呢...

**Comment by runchen0518** [comment]
如果接收到了两次action，可以检查一下，是不是自己在一个page里面调用了两次buildReducer()；
