### ISSUE TITLE
一个页面中有多个同级adapter该如何写

### ISSUE THREAD

**Issue by Mar-er** [alibaba/fish-redux#370]
一个页面中有多个同级的adapter该怎么写，如果模仿咸鱼的ItemBodyComponent写法，那么adapter的connector如何写。
![image](https://user-images.githubusercontent.com/19943499/60873568-2f47a100-a269-11e9-9bd9-34eab533bb90.png)

**Comment by zjuwjf** [comment]
不是很理解你说的怎么写的具体问题是什么？

事实上adapter的connector 和 component 的connector 写法上并无区别。

**Comment by Mar-er** [comment]
> 不是很理解你说的怎么写的具体问题是什么？
> 
> 事实上adapter的connector 和 component 的connector 写法上并无区别。

![image](https://user-images.githubusercontent.com/19943499/60952454-e86faf00-a32d-11e9-9b88-d16031c30bcb.png)

一般是一个对象类似于上图，但adapter数据是一个数组类似于下图这样，所以不知道adapter的connector 怎么写，难道需要先用两个component分别包裹adapter形成 page ->component ->(adapter ->component)这样的结构吗

![image](https://user-images.githubusercontent.com/19943499/60950131-25857280-a329-11e9-9f4e-251574549437.png)

**Comment by Mar-er** [comment]
> 不是很理解你说的怎么写的具体问题是什么？
> 
> 事实上adapter的connector 和 component 的connector 写法上并无区别。

![image](https://user-images.githubusercontent.com/19943499/60958980-f6c3c800-a339-11e9-89ba-9c5818c08c32.png)

connector 一般类似于上图这样，而adapter数据是数组类似于下图，所以不知道adapter的connector怎么写。难道需要用component包裹adapter形成 page -> component -> adapter -> component这种结构吗

![image](https://user-images.githubusercontent.com/19943499/60958843-a3517a00-a339-11e9-82cd-c7ac7306c9bb.png)

**Comment by zjuwjf** [comment]
抱歉并不是特别理解你的具体的疑惑。

参考 #340 ？

Adapter的数据不一定是数值，也可以是一个普通的Bean。

**Comment by zhangruiyu** [comment]
@zjuwjf 希望buildadapter时候能传递参数,这样Adapter的ConnOp可以根据传递的参数区分数据,当tabview里添加多个listview时候会导致无法区分数据

**Comment by Mar-er** [comment]
@zjuwjf  谢谢大佬的指点，参考[#340](https://github.com/alibaba/fish-redux/issues/340)使用StaticFlowAdapter可以满足需求。之前不知道怎么写是因为不理解静态适配器

**Comment by TangYuanHuan** [comment]
> @zjuwjf 谢谢大佬的指点，参考[#340](https://github.com/alibaba/fish-redux/issues/340)使用StaticFlowAdapter可以满足需求。之前不知道怎么写是因为不理解静态适配器

是否可以给一个可以运行的StaticFlowAdapter使用demo看看吗
