### ISSUE TITLE
移除HigherEffect和EffectPart之后现在用什么代替

### ISSUE THREAD

**Issue by ykrank** [alibaba/fish-redux#376]
今天更新后发现这个被移除了，导致之前代码都要重写。什么时候API才能稳定一些的

**Comment by zjuwjf** [comment]
非常抱歉，0.2.3版本的升级给您造成了影响。

在0.2.3中，产生了如下的breaking-change
```dart
- Breaking-change 
  - Reconstruct dependencies
  - Remove HigherEffect
  - Remove OOP style
  - Remove deprecated api(Connector, createMixedStore, AutoDispose:follow, AutoDispose:follower)
  - Remove unused DisposedException
```

特别是[HigherEffect]，和[OOP style]。

重要的原因是，它们一直处于不推荐使用，并且对后续的持续维护产生了非常大的影响。

如果你想跟随到最新版本，同时不想过多调整书写方式，可以参考之前的实现，做自定义一份EffectPart。

如果有具体的无法兼容的case，欢迎继续探讨。
