### ISSUE TITLE
IOS的HybridRoutes isn't defi报错，在windows不报错

### ISSUE THREAD

**Issue by namenoteasy** [alibaba/fish-redux#379]
在mac os的Android Studio会报错
![image](https://user-images.githubusercontent.com/19269133/61101065-09094780-a49b-11e9-8c34-44802ece4be2.png)

Steps to reproduce the behavior.
我是在vm虚拟机安装的

**Comment by zjuwjf** [comment]
在0.2.3 移除了， 直接使用PageRoutes。
