### ISSUE TITLE
The getter 'dispatch' was called on null.

### ISSUE THREAD

**Issue by ykrank** [alibaba/fish-redux#380]
**Describe the bug**
Show the code you wrote as completely as possible.
```dart
viewService.broadcast(AppActionCreator.init(Localizations.localeOf(context)));
``` 

**To Reproduce**
广播时会崩溃。
I/flutter (29140): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (29140): The following NoSuchMethodError was thrown building Builder(dirty, dependencies:
I/flutter (29140): [_LocalizationsScope-[GlobalKey#1f087]]):
I/flutter (29140): The getter 'dispatch' was called on null.
I/flutter (29140): Receiver: null
I/flutter (29140): Tried calling: dispatch
I/flutter (29140): 
I/flutter (29140): When the exception was thrown, this was the stack:
I/flutter (29140): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (29140): #1      DispatchBusDefault.broadcast (package:fish_redux/src/redux_component/dispatch_bus.dart:38:49)
I/flutter (29140): #2      LogicContext.broadcast (package:fish_redux/src/redux_component/context.dart:122:40)

原因是dispatch_bus.dart的void broadcast(Action action, {DispatchBus excluded})中使用了parent?.dispatch(action, excluded: excluded.dispatch); 但是excluded默认是null的

**Additional context**
1. The version of fish-redux which you are using.
2. The information from flutter doctor.

**Comment by ykrank** [comment]
I/flutter (30521): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30521): The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(392.7,
I/flutter (30521): 850.9), devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
I/flutter (30521): EdgeInsets(0.0, 34.9, 0.0, 0.0), viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter (30521): alwaysUse24HourFormat: false, accessibleNavigation: false, disableAnimations: false, invertColors:
I/flutter (30521): false, boldText: false)):
I/flutter (30521): The getter 'state' was called on null.
I/flutter (30521): Receiver: null
I/flutter (30521): Tried calling: state
I/flutter (30521): 
I/flutter (30521): When the exception was thrown, this was the stack:
I/flutter (30521): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (30521): #1      _AppDefaultPrivateComponent&AppComponent&PrivateReducerMixin.createDispatch.<anonymous closure> (package:fish_redux/src/redux_component/private_reducer_mixin.dart:35:23)
I/flutter (30521): #2      LogicContext.onLifecycle (package:fish_redux/src/redux_component/context.dart:89:5)
I/flutter (30521): #3      ComponentContext.onLifecycle (package:fish_redux/src/redux_component/context.dart:175:11)
I/flutter (30521): #4      ComponentState.initState (package:fish_redux/src/redux_component/component.dart:194:13)
I/flutter (30521): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)

**Comment by ykrank** [comment]
另外一个类似的问题，现在处于完全不可用状态

**Comment by zjuwjf** [comment]
#375

**Comment by zjuwjf** [comment]
非常抱歉，给你造成的影响。 目前还是测试用例覆盖不充分。

欢迎加入进来，一起完善。

**Comment by zjuwjf** [comment]
#382
