### ISSUE TITLE
effect.dart 错误，采用 #303的解法不好使

### ISSUE THREAD

**Issue by xiaobt** [alibaba/fish-redux#384]
**Describe the bug**
将flutter升级到1.7.8+hotfix.3,然后报如下错误
<img width="833" alt="effect_issue" src="https://user-images.githubusercontent.com/7822738/61173044-5a5f2700-a5c0-11e9-9ce1-06df92591d66.png">

**Comment by zjuwjf** [comment]
请升级 fish-redux 到 0.2.4

#303
