### ISSUE TITLE
可以运行，点击就报错。

### ISSUE THREAD

**Issue by xiangyao0906** [alibaba/fish-redux#39]
可以运行，点击就报错。

error: The named parameter 'backgroundCursorColor' isn't defined. (undefined_named_parameter at [sample] lib/todo_edit_page/view.dart:37)
error: The named parameter 'backgroundCursorColor' isn't defined. (undefined_named_parameter at [sample] lib/todo_edit_page/view.dart:63)

**Comment by zjuwjf** [comment]
建议升级到flutter1.2。 flutter1.0没有这个参数。

**Comment by hyjfine** [comment]
flutter channel stable
flutter upgrade
flutter --version
当前最新版本是1.2.1
