### ISSUE TITLE
The method 'asDependent' isn't defined for the class

### ISSUE THREAD

**Issue by xiaobt** [alibaba/fish-redux#392]
fish-redux升级到0.2.4时，报以下错误
<img width="812" alt="屏幕快照 2019-07-14 下午4 32 31" src="https://user-images.githubusercontent.com/7822738/61181196-71038d80-a655-11e9-9d28-d0781385ce9b.png">

**Comment by zjuwjf** [comment]
asDependent API 做为一个被废弃的API，正式在0.2.4中移除了。

你可以直接通过
```dart
_MyConn() + MyComponent();
```
的形式直接得到Dependent
