### ISSUE TITLE
How to connect page to partial AppStore

### ISSUE THREAD

**Issue by CoolBerry** [alibaba/fish-redux#396]
AppStore里面可能有许多需要页面间同步的state，比如A，B页面之间需要同步object1，C，D页面间需要同步object2。

所以，符合当前设计的做法是，将object1和object2放在appStore里，然后要怎么分别关联呢？

Version: 0.2.4

**Comment by CoolBerry** [comment]
所以，是不是可以让AppState implements多个base state。

**Comment by zjuwjf** [comment]
1、你可以选择将这样的连接关系通用化，AppStore和多个页面使用同一种连接关系， 如 example里的所示。
2、你可以将这样的连接关系case by case 的解决， 如你上面提到的。 你可以在具体的Page中的构造函数中调用 connectExtraStore的api。
