### ISSUE TITLE
TabBarView结合adapter示例

### ISSUE THREAD

**Issue by jpdan** [alibaba/fish-redux#399]
#215 
TabBarView返回一个或多个相同的component，如何用adapter实现，能给个简单的示例吗？

**Comment by zjuwjf** [comment]
1、adapter 会返回一个数组结构，怎么用，在于自己的选择。
2、KeepAliveMixin 已经在fish-redux中提供。[参考](https://github.com/alibaba/fish-redux/blob/master/lib/src/redux_component_mixin/keep_alive_mixin.dart)

**Comment by jpdan** [comment]
谢谢解答，已实现

**Comment by zhangruiyu** [comment]
老哥 我也遇到这个问题了 你怎么解决啊
