### ISSUE TITLE
StaticFlowAdapter中使用DynamicFlowAdapter的问题

### ISSUE THREAD

**Issue by a314730500** [alibaba/fish-redux#402]
闲鱼客户端中有个这个页面，我看文档里面也有说到这个
![image](https://user-images.githubusercontent.com/46081104/61357787-87a32200-a8ab-11e9-8465-917f66248a90.png)

![image](https://user-images.githubusercontent.com/46081104/61357400-cb495c00-a8aa-11e9-8032-dd1edaecca3b.png)
就是不知道这个评论的Adapter是怎么写的 用DynamicFlowAdapter实现吗？
我这边用StaticFlowAdapter + DynamicFlowAdapter 实现后 结果是ListView 不是GridView 
![image](https://user-images.githubusercontent.com/46081104/61357465-ef0ca200-a8aa-11e9-9dc1-327c678d6da8.png)
```
class MainViewPage extends Page<MainViewState, Map<String, dynamic>> {
  MainViewPage()
      : super(
          initState: initState,
          effect: buildEffect(),
          reducer: buildReducer(),
          view: buildView,
          dependencies: Dependencies<MainViewState>(
              adapter: NoneConn<MainViewState>() +
                  StaticFlowAdapter<
                      MainViewState>(slots: <Dependent<MainViewState>>[
                    MainTitleComponentConn() + MainTitleComponentComponent(),
                    BannerComponentConn() + BannerComponentComponent(),
                    SortComponentConn() + SortComponentComponent(),
                    BrandComponentConn() + BrandComponentComponent(),
                    RecommendAdapterConn() + RecommendListAdapter(),
//                    RecommendComponentConn() + RecommendComponentComponent(),
                  ]),
              slots: <String, Dependent<MainViewState>>{}),
          middleware: <Middleware<MainViewState>>[],
        );
}

```

page的view实现方法
```
Widget buildView(
    MainViewState state, Dispatch dispatch, ViewService viewService) {
  final ListAdapter adapter = viewService.buildAdapter();
  return Scaffold(
    body: Container(
      color: Color.fromRGBO(245, 245, 245, 1),
      child: Column(
        children: <Widget>[
          Expanded(
            child: RefreshIndicator(
              key: state.refreshIndicatorKey,
              onRefresh: () => dispatch(MainViewActionCreator.onRefresh()),
              child: ListView.builder(
                  itemBuilder: adapter.itemBuilder,
                  itemCount: adapter.itemCount),
            ),
          ),
        ],
      ),
    ),
  );
}
```

这是原本想实现的效果 是用一个Component实现的 结果性能差了很多
![image](https://user-images.githubusercontent.com/46081104/61357752-75c17f00-a8ab-11e9-9380-4eee111117c2.png)

**Comment by zjuwjf** [comment]
1、 闲鱼的评价，使用的是自定义Adapter（集成于Adapter，个性化实现它的adapter配置），不是Dynamic或者Static。

2、是否显示成网格（推荐商品Adapter），和Adapter本身无关，Adapter只是提供了一个ListAdapter的数据结构。我们是一行行的小组件（2个商品）组成了推荐商品的DynamicAdapter。

**Comment by a314730500** [comment]
明白了！Adapter其实就是个把component组装起来的数组。
```
final ListAdapter adapter = viewService.buildAdapter();
adapter.itemBuilder(viewService.context, 0),
adapter.itemCount
```
具体怎么用看自己。
这个页面到最后就归结到listview 与gridview怎么嵌套的问题了。

另外我还有些疑问，希望大神能解疑：
1. Lifecycle.disappear 这个是怎么触发的呀？我在这个StaticFlowAdapter 里面的Component和DynamicAdapter的Component 都监听这个 都收不到呀？
2. 闲鱼现在flutter图片内存回收是怎么处理的，有木有新的进展啊。

**Comment by zjuwjf** [comment]
1、任意的一个Adapter（Static、Dynamic、自定义）mixin [VisibleChangeMixin](https://github.com/alibaba/fish-redux/blob/master/lib/src/redux_component_mixin/visible_change_mixin.dart) 就能收到该Adapter的appear & disappear 事件了。 
注意⚠️，不管是否mixin这个特性，adapter的initState和dispose和ListView是一致的，除非它在ListView上真实不存在。

2、闲鱼图片是基于外接纹理做的，所有的图片资源的管理是复用了原有Native图片中间件。我们没有特别的图片内存回收问题。

**Comment by a314730500** [comment]
我看adapter下面的component dispatch 都会用这个，但是这个里面又有个count，是不是会导致第一个显示以后，后面的都不会dispatch了？
另外由于有这个count的存在导致disappear 也不准了
```
class _VisibleChangeDispatch extends AutoDispose {
  int _appearsCount = 0;
  final Dispatch dispatch;

  _VisibleChangeDispatch(this.dispatch);

  void onAction(Action action) {
    if (action.type == Lifecycle.appear) {
      assert(_appearsCount >= 0);
      if (_appearsCount == 0) {
        if (!isDisposed) {
          dispatch(action);
        }
      }
      _appearsCount++;
    } else if (action.type == Lifecycle.disappear) {
      _appearsCount--;
      assert(_appearsCount >= 0);
      if (_appearsCount == 0) {
        if (!isDisposed) {
          dispatch(action);
        }
      }
    }
  }
}
```

**Comment by a314730500** [comment]
好像明白了！这个appear和disappear是说整个adpater 显示和消失 不是子控件的显示消失…这个还真容易理解错。子控件的显示消失应该是在其init和dispose里面监听了

**Comment by zjuwjf** [comment]
对Adapter的appear和disappear是对当前Adapter生效的，而非Adapter（Static，Dynamic）内的Component而言的。

当然将一个Component转为为一个Adapter是非常简易的一件事。
