### ISSUE TITLE
GlobalState 问题

### ISSUE THREAD

**Issue by xfhomedream** [alibaba/fish-redux#407]
```dart
abstract class GlobalBaseState {
  Color get themeColor;
  set themeColor(Color color);
}

class GlobalState implements GlobalBaseState, Cloneable<GlobalState> {
  @override
  Color themeColor;

  @override
  GlobalState clone() {
    return GlobalState();
  }
}
```
你好，看了例子这里的themeColor初始值是null，如果我想给个初始值要在哪初始化呢

**Comment by zjuwjf** [comment]
应该在 AppStore 创建的时候，初始化AppState

**Comment by xfhomedream** [comment]
谢谢，component怎么用这个GlobalBaseState呢  也是这样实现吗

**Comment by hzgotb** [comment]
> 谢谢，component怎么用这个GlobalBaseState呢 也是这样实现吗

Component 的 state 是通过 connector 向其挂载的父组件或页面来流通的。
所以，如果 Component 想要用到 GlobalStore 的 state ，一定是自上而下的。
也就是说，不能让 Component 去实现 GlobalBaseState 。

**Comment by xfhomedream** [comment]
好的谢谢

**Comment by hzgotb** [comment]
那我关闭这个issue了。
