### ISSUE TITLE
源码的注释有点少 太简单 关于Connector和Adapter的特有概念说明文档太少 例子中很少有注释

### ISSUE THREAD

**Issue by liushiyueyueniao** [alibaba/fish-redux#41]
源码的注释有点少 太简单 关于Connector和Adapter的特有概念说明文档太少 例子中很少有注释

**Comment by CharlesZqikai** [comment]
注释确实太少了,特别是ToDoListPage里这个的定义表示很疑惑
     slots: <String, Dependent<PageState>>{
                'report':ReportConnector() + ReportComponent()
              }),

ReportConnector() + ReportComponent() 怎么就成了一个Dependent?

**Comment by MEiDIK** [comment]
@CharlesZqikai 在connector中重定义了+运算符：
```
class ConnOp<S, P> implements Connector<S, P> {
  final P Function(S) _getter;
  final void Function(S, P) _setter;

  ConnOp({P Function(S) get, void Function(S, P) set})
      : _getter = get,
        _setter = set;

  @override
  P get(S state) => _getter(state);
  @override
  void set(S state, P substate) => _setter(state, substate);

  Dependent<S> operator +(Logic<P> logic) => createDependent<S, P>(this, logic);
}
```

**Comment by CharlesZqikai** [comment]
> @CharlesZqikai 在connector中重定义了+运算符：
> 
> ```
> class ConnOp<S, P> implements Connector<S, P> {
>   final P Function(S) _getter;
>   final void Function(S, P) _setter;
> 
>   ConnOp({P Function(S) get, void Function(S, P) set})
>       : _getter = get,
>         _setter = set;
> 
>   @override
>   P get(S state) => _getter(state);
>   @override
>   void set(S state, P substate) => _setter(state, substate);
> 
>   Dependent<S> operator +(Logic<P> logic) => createDependent<S, P>(this, logic); //这里
> }
> ```

thinks

**Comment by zjuwjf** [comment]
文档优化部分，目前是我们高优先级的任务。如果有更加具体的问题的话，会更加容易回答。

**Comment by liushiyueyueniao** [comment]
@zjuwjf 例子看懂了  关于Connector和Adapter还差点意思 尤其是Adapter的使用  
class ReportConnector extends ConnOp<PageState, ReportState> {
  @override
  ReportState get(PageState state) {
    final ReportState reportState = ReportState();
    reportState.total = state.toDos.length;
    reportState.done = state.toDos.where((ToDoState tds) => tds.isDone).toList().length;
    return reportState;
  }

  @override
  void set(PageState state, ReportState substate) {}
}
ReportConnector 只实现了get  是不是可以认为这个ReportConnector 是单向的  只能从PageState 到 ReportState ， set是空实现  或者不实现  ReportState 就无法或者不需要把变化同步给PageState

**Comment by liushiyueyueniao** [comment]
class ToDoListAdapter extends DynamicFlowAdapter<PageState> {
  ToDoListAdapter()
      : super(
          pool: <String, Component<Object>>{ 'toDo': ToDoComponent(),},
          connector: _ToDoListConnector(),
          reducer: buildReducer(),
        );
}

ToDoListAdapter pool参数是什么含义

**Comment by CharlesZqikai** [comment]
class DynamicFlowAdapter<T> extends Logic<T>
    with RecycleContextMixin<T>
    implements AbstractAdapter<T> {
  final Map<String, AbstractLogic<Object>> pool;
  final Connector<T, List<ItemBean>> connector;

在 dynamicFlowAdapter中可以看出pool 是个map
key String类型
value AbstractLogic

Component 继承自AbstractLogic

**Comment by zjuwjf** [comment]
> @zjuwjf 例子看懂了 关于Connector和Adapter还差点意思 尤其是Adapter的使用
> class ReportConnector extends ConnOp<PageState, ReportState> {
> @override
> ReportState get(PageState state) {
> final ReportState reportState = ReportState();
> reportState.total = state.toDos.length;
> reportState.done = state.toDos.where((ToDoState tds) => tds.isDone).toList().length;
> return reportState;
> }
> 
> @override
> void set(PageState state, ReportState substate) {}
> }
> ReportConnector 只实现了get 是不是可以认为这个ReportConnector 是单向的 只能从PageState 到 ReportState ， set是空实现 或者不实现 ReportState 就无法或者不需要把变化同步给PageState

是的

**Comment by liushiyueyueniao** [comment]
> class DynamicFlowAdapter extends Logic
> with RecycleContextMixin
> implements AbstractAdapter {
> final Map<String, AbstractLogic> pool;
> final Connector<T, List> connector;
> 
> 在 dynamicFlowAdapter中可以看出pool 是个map
> key String类型
> value AbstractLogic
> 
> Component 继承自AbstractLogic

@CharlesZqikai 嗯是的    这是做什么用的？里面为什么放的是pool: <String, Component>{ 'toDo': ToDoComponent(),}, @zjuwjf

**Comment by CharlesZqikai** [comment]
这个pool 我的理解是:  可以像android原生的适配器一样,实现多类型列表, "toDo"是item type ,ToDoComponent()是item view

**Comment by liushiyueyueniao** [comment]
@CharlesZqikai 嗯嗯  @zjuwjf 官方解答一下

**Comment by han-xiaowei** [comment]
什么时候能出API文档

**Comment by zjuwjf** [comment]
更新了一些文档， 可以参考

[目录](https://github.com/alibaba/fish-redux/blob/master/doc/README-cn.md)
[What's-adapter](https://github.com/alibaba/fish-redux/blob/master/doc/concept/what's-adapter.md)
[What's-connector](https://github.com/alibaba/fish-redux/blob/master/doc/concept/what's-connector.md)

**Comment by liushiyueyueniao** [comment]
@zjuwjf adapter 好抽象  
StaticFlowAdapter
DynamicFlowAdapter
CustomAdapter

这三个adapter 适用于什么情况 文字和图片都太苍白  还是代码更具体  show me the code

**Comment by guodf** [comment]
> 源码的注释有点少 太简单 关于Connector和Adapter的特有概念说明文档太少 例子中很少有注释

#61

**Comment by guodf** [comment]
#61
