### ISSUE TITLE
adapter表现不一致情况如何处理

### ISSUE THREAD

**Issue by jpdan** [alibaba/fish-redux#410]
一个列表数据，前3个item表现形式不一致，比如UI布局、大小、某些数据字段不显示等，但是数据源ItemBean是一样的，但是没有数据字段能够区分，只能靠index去区分，请问有什么好的方式实现吗?

**Comment by hzgotb** [comment]
你所说的实现方式指的的是什么？

**Comment by jpdan** [comment]
adapter中列表item需要用到index去做区分

**Comment by jpdan** [comment]
我现在是这样实现的
`
class ItemsState {
  Item firstItem;
  Item secondItem;
  Item threeItem;
}
FirstItemConnector
SecondItemConnector
ThreeItemConnector
ItemAdapter => 其他item集合
`
感觉很繁琐

**Comment by zhangruiyu** [comment]
创建ItemBean时候,根据数据源在ItemBean里添加一个index属性呗

**Comment by jpdan** [comment]
也想过给每个item添加index，总感觉不太好。
而且还有个问题，我这个是TabBarView，有5个tab，而第一个tab页的前三个item显示不一样，其他tab页都是一样的，而每一个item数据源都是一样的，这样就导致如果不拆分item，还需要把type传进去，让item知道是属于哪一个tab的

**Comment by MMMzq** [comment]
> 也想过给每个item添加index，总感觉不太好。
> 而且还有个问题，我这个是TabBarView，有5个tab，而第一个tab页的前三个item显示不一样，其他tab页都是一样的，而每一个item数据源都是一样的，这样就导致如果不拆分item，还需要把type传进去，让item知道是属于哪一个tab的

同样的难受,adapter和tabview真的结合起来很难受,一个page只能有一个adapter真的太难受了

**Comment by MMMzq** [comment]
现在用多了真的觉得adapter没有设计好,有的地方不用adapter不行,用起来又太奇怪

**Comment by zjuwjf** [comment]
@MMMzq 有具体的场景和例子吗？

**Comment by MMMzq** [comment]
#215  主要是TabBarView和Adapter结合使用会出现一些问题
1.  Page只能有一个Adapter的限制
在我平时的开发中,如果一个页面使用到了TabView就说明这个Page很可能就会有多个列表,例如一个TabView对应一个Adapter,并且每个Adapter都是不同类型。
对于这种需求我现在已知的有三种方式:
*  在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug
* 使用Component来封装Adapter,以达到一个page有多个Adapter的目的,但是这样做会多了一步connector的操作,导致传递数据的层数变长,并且多了很多模板代码,而且如果以后添加了新属性也要进行修改,维护性降低了很多
* page嵌套page,最外层page来控制TabView，然后每个TabView又对应一个Page,这种方式是我目前的方法,个人认为比前两者好很多并且分层也比较明显

2. Adapter 也能接受一些额外的数据源
其实这个时第一个问题的另外一种解决方法，但是和框架原来的设计理念相违背？如果buildAdapter也能和buildPage一样能额外传入“数据源“,那么第一个问题就能很好的解决

其实对于第一点放宽Adpater的限制,我觉得还是可行的,而第二个点只是一种建议😁

另外除了这些我认为的”开发痛点“，fish_redux还很不错的,配合一些工具做一些模板代码生成,开发速度还是挺不错的

**Comment by zhangruiyu** [comment]
@zjuwjf 希望adapter能接受额外数据

**Comment by zjuwjf** [comment]
如果存在 dependencies 可以接收一个adapters的map，是否比较接近于大家想要的
1、一个page下多个adapter
2、adapter能接受额外数据

**Comment by zhangruiyu** [comment]
第二个吧，配置多个adapter没法动态啊，后台传多个tab，需要动态创建

**Comment by zjuwjf** [comment]
> 动态

理论上，配置是全量的，具体使用了哪几个，应该是配置的子集。

**Comment by zhangruiyu** [comment]
0-0  希望大佬能尽快解决 焦急0-0

**Comment by zjuwjf** [comment]
@zhangruiyu 计划下周会完整考虑这个场景和它需要的特性。

**Comment by charmfocus** [comment]
我用page代替了tabbarview每项的component，就可以用buildPage来传参了，如果后面框架有更好的支持最好了

**Comment by zhangruiyu** [comment]
焦急等待

**Comment by zjuwjf** [comment]
@zhangruiyu 如果可以通过让一个人页面配置多个人

**Comment by zhangruiyu** [comment]
> @zhangruiyu 如果可以通过让一个人页面配置多个人

不大明白啊  我只是个菜鸡 只是想使用fish_redux写tabview  但是具体怎么做 我就不大清楚啊

**Comment by MMMzq** [comment]
@zjuwjf 
我说一下我的观点:

#### 其实这两种方式并不对立,都能实现需求,并且各有各好的地方:

第一种方式,往往会比第二种方式表达更清晰,举个例子:

假如:TabViewA有一个AdaterA,TabViewB有一个AdapterB

第一种方式: 直接清晰,TabViewA用AdaterA,TabViewB用AdapterB,因为这个过程已经隐含了一种选择的意图

第二种方式: 显式的传参让Adapter展现出不同的“类型”。

很显然这种情况下第一种方式是优于第二种的

#### 对于目前的情况我更倾向于第一种方式,改动小,兼容好.我认为是目前最好的选择.

那是不是不要第二种呢?我觉得在可以实现的前提下还是需要的,并且可以放在下个大版本再进行改动.
这样也可以考虑全面一点,比如都能实现buildApapter传参了,是不是buildCompoent也可以呢？等等之类的.

**Comment by zjuwjf** [comment]
@MMMzq 
我看了你的#215例子，如果你需要的key = {foodData, clothesData, etc} 本身就是state的一部分，是不是更加自然些？

在tab中的切换，改变了state.key, 然后在connector中，自然的获得了一个新的List\<Item\>

**Comment by zjuwjf** [comment]
Adapter本质上是一种虚拟组件，它同父组件的生命周期，如果让一个父组件下面挂多了Adapter（虚拟组件），会让事件有些复杂。

举个例子，Adapter的生命周期事件同父组件，那么多个Adapter是同时触发，还是按Adapter创建触发？如果按Adapter创建触发，后面创建的Adapter怎么弥补遗漏的之前的生命周期事件？

**Comment by MMMzq** [comment]
> @zjuwjf 
> 我看了你的 #215 例子，如果你需要的key = {foodData, clothesData, etc} 本身就是state的一部分，是不是更加自然些？
> 
> 在tab中的切换，改变了state.key, 然后在connector中，自然的获得了一个新的List<Item>

其实你说的这种情况就是:
> 在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug

举个🌰:
有一个`TabBarViewA`和`TabBarViewB`,而`TabBarViewA`想要有一个`AdadterA`,`TabBarViewB`想要有一个`AdadterB`。
如果只用一个`state.key`能做到吗?做不到.因为`Adapter`在`connector`的过程中根本不知道我是在build的是第几个TabBarView.而且`state.key`不能被多个`TabBarView`公用,如果共用了下次触发state的修改会导致所有TabBarView的adapter都是某一类adapter.

这还是只有TabBarViewA,B的情况,要是以后再多几个TabBarViewC,D之类的,那可真是太糟糕了
```dart
 //假设每个TabBarView只显示Adapter,第一个是TabBarViewA,第二个是TabBarViewB
final adapter = viewService.buildAdapter()
TabBarView(children: Iterable.generate(2,(index){
          if(index==0){
            state.key=="keyA";  //假设会dispatch一个事件修改state,这里省略
          }else{
            state.key=="keyB"; //假设会dispatch一个事件修改state,这里省略
          }
          //假设index==0时,AdapterA会生成对应的List<AItem>
          //index==1时,修改key=="keyB"; 
          // 这时会触发AdapterA会重新`connector`这时AdapterA就会生成List<BItem>
          return ListView.builder(itemBuilder: adapter.itemBuilder);
 }).toList())
```

**Comment by MMMzq** [comment]
> Adapter本质上是一种虚拟组件，它同父组件的生命周期，如果让一个父组件下面挂多了Adapter（虚拟组件），会让事件有些复杂。
> 
> 举个例子，Adapter的生命周期事件同父组件，那么多个Adapter是同时触发，还是按Adapter创建触发？如果按Adapter创建触发，后面创建的Adapter怎么弥补遗漏的之前的生命周期事件？

可能这部分我就没什么发言权了,既然能用多个Compoent封装Adapter达到一个Page有多个”Adapter“的假象,那么多个Adapter是不是可以看成多个Compoent一样?

**Comment by zjuwjf** [comment]
@MMMzq 

> > 在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug

并不是很理解这个含义。 从构建adapter-ui的过程中不需要判断逻辑。
```dart
final adapter = viewService.buildAdapter();
final listView = ListView.builder(itemBuilder: adapter.itemBuilder);
```
具体使用了哪一个数据，是在connector.get中确定的
```dart
List<Item> get(state) {
     if(state.select == 'home') {
         return state.homeList;
     } else if(state.select == 'discovery') {
        return state.discoveryList;
     }
}
```

**Comment by MMMzq** [comment]
> @MMMzq
> 
> > > 在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug
> 
> 并不是很理解这个含义。 从构建adapter-ui的过程中不需要判断逻辑。
> 
> ```dart
> final adapter = viewService.buildAdapter();
> final listView = ListView.builder(itemBuilder: adapter.itemBuilder);
> ```
> 
> 具体使用了哪一个数据，是在connector.get中确定的
> 
> ```dart
> List<Item> get(state) {
>      if(state.select == 'home') {
>          return state.homeList;
>      } else if(state.select == 'discovery') {
>         return state.discoveryList;
>      }
> }
> ```

你可以先运行一下这个例子,你就会发现这种方式有很明显的问题
[#example](https://github.com/MMMzq/fish_redux_adapter_example)
1. 切换时有很大的延迟
2. 先滚动A到某个位置,切换到B再切换到A,发现A的滚动位置复原了

**Comment by zhangruiyu** [comment]
> > @MMMzq
> > > > 在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug
> > 
> > 
> > 并不是很理解这个含义。 从构建adapter-ui的过程中不需要判断逻辑。
> > ```dart
> > final adapter = viewService.buildAdapter();
> > final listView = ListView.builder(itemBuilder: adapter.itemBuilder);
> > ```
> > 
> > 
> > 具体使用了哪一个数据，是在connector.get中确定的
> > ```dart
> > List<Item> get(state) {
> >      if(state.select == 'home') {
> >          return state.homeList;
> >      } else if(state.select == 'discovery') {
> >         return state.discoveryList;
> >      }
> > }
> > ```
> 
> 你可以先运行一下这个例子,你就会发现这种方式有很明显的问题
> [#example](https://github.com/MMMzq/fish_redux_adapter_example)
> 
> 1. 切换时有很大的延迟
> 2. 先滚动A到某个位置,切换到B再切换到A,发现A的滚动位置复原了

是的,而且预加载第二个页面也不行

**Comment by zhangruiyu** [comment]
> > > @MMMzq
> > > > > 在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug
> > > 
> > > 
> > > 并不是很理解这个含义。 从构建adapter-ui的过程中不需要判断逻辑。
> > > ```dart
> > > final adapter = viewService.buildAdapter();
> > > final listView = ListView.builder(itemBuilder: adapter.itemBuilder);
> > > ```
> > > 
> > > 
> > > 具体使用了哪一个数据，是在connector.get中确定的
> > > ```dart
> > > List<Item> get(state) {
> > >      if(state.select == 'home') {
> > >          return state.homeList;
> > >      } else if(state.select == 'discovery') {
> > >         return state.discoveryList;
> > >      }
> > > }
> > > ```
> > 
> > 
> > 你可以先运行一下这个例子,你就会发现这种方式有很明显的问题
> > [#example](https://github.com/MMMzq/fish_redux_adapter_example)
> > 
> > 1. 切换时有很大的延迟
> > 2. 先滚动A到某个位置,切换到B再切换到A,发现A的滚动位置复原了
> 
> 是的,而且预加载第二个页面也不行

tab切换修改state里的key然后刷新其他的listview,其实是其他页面默认都展示了第一个页面的数据,然后再改变的,这样会很奇怪

**Comment by jpdan** [comment]
第一个是TabBarViewA： FirstTabBarConnector
第二个是TabBarViewB： SecondTabBarConnector
TabBarView:
```
if (isFirst) return viewService.buildComponent('first_tabbarview')
else if (isSecond) return viewService.buildComponent('second_tabbarview')
else
return LayoutBuilder(
        key: Key(currentIndex),
        builder: (BuildContext context, BoxConstraints constraints) {
          return viewService.buildAdapter().itemBuilder(context, currentIndex);
        },
      );
```

**Comment by zjuwjf** [comment]
@MMMzq @zhangruiyu 
可以考虑使用 
```dart
class NoneConn<T> extends ImmutableConn<T, T> with ConnOpMixin<T, T> {
  @override
  T get(T state) => state;

  @override
  T set(T state, T subState) => subState;
}
```

目前框架里已经提供的通用Conn么？

一个page下，挂载多个component\<T\>, 一个component\<T\>挂载一个adapter\<T\>， 其中的component和adapter之前的conn可以不用自定义。

**Comment by zhangruiyu** [comment]
可是这样 好像component还是需要动态传递参数,后台传递的数据告诉我有几个tab页,总不能我们把所有tab都注册创建,如果页面有100个tab页呢

**Comment by zjuwjf** [comment]
设计上都要提前注册好。

当然注册100个类似的组件，可以自己实现批方法。

**Comment by zhangruiyu** [comment]
那肯定不行啊，可是我每个tab ui是一样的，

**Comment by zhangruiyu** [comment]
目前要实现的是后台传递几个tab类型，我们就显示几个tab，这是一个很基本的功能啊

**Comment by zjuwjf** [comment]
@zhangruiyu 
我想你应该使用一个Adapter，通过数组状态去驱动产生n个tab的实例。
至于每一个tab里的组件应该继续包含一个ListView？

**Comment by zhangruiyu** [comment]
😂这么说吧，后台给出  附近的人和全国的人  2个列表，动态创建tab后，怎么才能让这2个列表从page的数据集合里取出相对应的值，毕竟这2个tab的listview的主state是同一个，而且conn也是一样的，这个区分的字段应该在创建控件时候就传过去，而不是等页面切换再去根据tab的脚标刷新页面，那样其实对将要显示的页面多做了绘制操作，因为页面还没切换过去时，将要显示的页面已经根据上一个得页面数据显示出来了，因为此时tabview的脚标是上一个页面

**Comment by zhangruiyu** [comment]
😂怎么搞，老哥

**Comment by zjuwjf** [comment]
为什么我说的上面方案不可行？

**Comment by zhangruiyu** [comment]
下发一个二维数组，adapter怎么取对应数组里的值，没法传递参数，conn是公用的一个，怎么区分当前conn是第几个listview在取值，

**Comment by zjuwjf** [comment]
Adapter 是一个数组结构，所以是符合你的模型的。

大意：页面配置一个一级Adapter，它可以生成N个tab页面（服务端下发多少tab就生成多少）。

任意一个Tab页面配置一个二级Adapter，它负责生成具体一个tab页面里的长列表。

**Comment by zhangruiyu** [comment]
有具体点的代码例子吗😂不大明白，感觉肯定有人和我一样懵

**Comment by zhangruiyu** [comment]
@zjuwjf 老哥0-0

**Comment by zjuwjf** [comment]
大致的伪代码

```dart

class TabBarPage {
     dependencies : {
          adapter: TbasConn() + DynamicAdapter(
               pool: <String, Component<Object>>{
                   'tab-body': TabBodyComponent()
               },
          ),
     }
}


class TabBodyComponent  {
     dependencies : {
          adapter: CardsConn() + DynamicAdapter(
               pool: <String, Component<Object>>{
                   'card': CardComponent()
               },
          ),
     }
}

class TabBarPageState {
     List<ItemBean> tabs;
}

// ItemBean.data => List<ItemBean> cards;

TabsConn.get => TabBarPageState.tabs;

CardsConn.get => data.cards;
```

**Comment by zjuwjf** [comment]
如果没有更近一步的问题，这里先关闭了。 如果问题 欢迎新开一个issue展开。

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/65373258-993ee680-dcad-11e9-844f-bb27874574fc.png)
实现了大佬说的方式 给各位参考下目录 只能说很复杂

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/65373266-b96ea580-dcad-11e9-980a-881a47d488e7.png)
二级adapter实现

**Comment by zjuwjf** [comment]
@zhangruiyu 如果需要你可以新开一个issue。 可能并没有完全get到你的需求。 我觉得不是一件复杂的事。

**Comment by AngusPei** [comment]
> connector

这种判断是有缺陷的，在tabbar进行切换的时候，每次调用ListView Build，如果是Adapter动态获取，实际上是不能正确从State中返回准确的数据的 见#534

**Comment by AngusPei** [comment]
> @MMMzq
> 
> > > 在state加入某些判断属性提供给Adapter用来区分,但是这种做法实际开发后个人认为并不好,adapter充斥的大量判断代码，及需要维护一些属性提高了维护的成本，也容易出现bug
> 
> 并不是很理解这个含义。 从构建adapter-ui的过程中不需要判断逻辑。
> 
> ```dart
> final adapter = viewService.buildAdapter();
> final listView = ListView.builder(itemBuilder: adapter.itemBuilder);
> ```
> 
> 具体使用了哪一个数据，是在connector.get中确定的
> 
> ```dart
> List<Item> get(state) {
>      if(state.select == 'home') {
>          return state.homeList;
>      } else if(state.select == 'discovery') {
>         return state.discoveryList;
>      }
> }
> ```

这种判断是有缺陷的，在tabbar进行切换的时候，每次调用ListView Build，如果是Adapter动态获取，实际上是不能正确从State中返回准确的数据的 见#534

**Comment by githublsy** [comment]
> ![image](https://user-images.githubusercontent.com/10591822/65373266-b96ea580-dcad-11e9-980a-881a47d488e7.png)
> 二级adapter实现

你好 demo方便发一份给我吗

**Comment by zhangruiyu** [comment]
> > ![image](https://user-images.githubusercontent.com/10591822/65373266-b96ea580-dcad-11e9-980a-881a47d488e7.png)
> > 二级adapter实现
> 
> 你好 demo方便发一份给我吗

https://github.com/zhangruiyu/flutter_cw_open  已经在我开源项目里了  可以自己找下

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/flutter_cw_open  解决方案 我已经放在自己的开源项目里,目录:lib/funcation/main/community
