### ISSUE TITLE
为什么更新子状态，引起了父状态及父状态下所有关联子状态都被重建了？

### ISSUE THREAD

**Issue by charmfocus** [alibaba/fish-redux#414]
当在view中调用`dispatch(SubActionCreator.update(xx));`时会引起父级state被重新创建。比如我对scrollview添加了ScrollController().addListener，在监听中进行对SubState进行更新，当我滚动scrollview时，父级state被不断的重新创建

**Comment by hzgotb** [comment]
怎么关闭了？是什么原因？
