### ISSUE TITLE
Componnent里面嵌入adapter，该Component中无法获取adapter内容

### ISSUE THREAD

**Issue by baotoushashou** [alibaba/fish-redux#416]
情景是这样的：我定义了一个Page页面，里面有一个TabBarView，这个TabBarView有三个Component，其中一个Component里面定义了一个Adapter，如下图所示。
![image](https://user-images.githubusercontent.com/4074258/62002864-60681280-b13f-11e9-909d-57dcf6daa43c.png)

问题是该Component无法获取Adapter的内容。调试发现adapter的itemCount是0。但是该Adapter的connector已经执行了，并且有元素。为什么该Component对应的View中获取到的itemCount是0呢？

fish_redux版本是0.2.4
![image](https://user-images.githubusercontent.com/4074258/62002929-762a0780-b140-11e9-8f8b-efa6d76898f3.png)

**Comment by zjuwjf** [comment]
有能复现的最小demo么？

**Comment by zjuwjf** [comment]
没有进一步的信息的话，先关闭了。
