### ISSUE TITLE
page被pop以后再次push进入reducer接收不到action

### ISSUE THREAD

**Issue by a398452027** [alibaba/fish-redux#417]
场景是
1.用户登陆后进入主页面
2.退出登陆
3.再次登陆进入主页面。
4.主页面的reducer接收不到任何action。
版本是0.2.2

**Comment by a398452027** [comment]
用调试观察，貌似_isDisposed被设置为true了。

**Comment by a398452027** [comment]
push使用的是pushNamedAndRemoveUntil

**Comment by zjuwjf** [comment]
能提供一个最小化的demo么？

**Comment by a398452027** [comment]
不好意思，是我们自己的问题，把ComponentWidget 实例放在静态队列里面，然而ComponentWidget的宿主PageWidget已经销毁，所以导致ComponentWidget的reducer不接收action。
