### ISSUE TITLE
page中connector子组件state问题 [local_props 问题]

### ISSUE THREAD

**Issue by jpdan** [alibaba/fish-redux#418]
一个层级很深的子组件，需要用户controller，初始化controller必须依赖page的lifecycle.initStaet数据，但是只有这个子组件会用到，而且也不用set给父类，是只读的，现在必须在page中定义且实例化，再通过一层层connector给到子组件，page很复杂的情况下，page的state很大，且嵌套层级很深，能否把controller放到childstate中实例化，但是connector必须childstate()会导致controller丢失，
很什么方式能让component保持一些独立的状态吗？

**Comment by zjuwjf** [comment]
```dart
class ComponentLocalProps extends LocalProps<ComponentLocalProps> {
  final TextEditingController controller = TextEditingController();

  ComponentLocalProps(Context<Object> ctx) : super(ctx);

  factory ComponentLocalProps.of(ExtraData ctx) {
    return LocalProps.provide((_) => ComponentLocalProps(_)).of(ctx);
  }

  @override
  void destructor(Context<Object> ctx) {
    controller.dispose();
  }
}
```

/// in View
/// ```dart
/// ComponentLocalProps.of(viewService).controller
/// ```
/// in effect
/// ```dart
/// ComponentLocalProps.of(ctx).controller
/// ```

[参考](https://github.com/alibaba/fish-redux/blob/master/lib/src/redux_component/local.dart)

LocalProps的状态变化不会触发View的刷新

**Comment by jpdan** [comment]
谢谢，试过很好用
