### ISSUE TITLE
关于在Effect使用Dialog的问题

### ISSUE THREAD

**Issue by wjbd** [alibaba/fish-redux#421]
我在Effect中的一个Action中ShowDialog，这个Dialog有一个Button是根据Dialog里的TextField内容长度来控制是否可以点击以及颜色的，此时我需要更新Dialog里面的UI，请问大佬，这个功能该用什么方式来开发?

**Comment by zjuwjf** [comment]
可以写成一个子Component注册，然后通过 ctx.buildComponent('dialog')。

**Comment by wjbd** [comment]
好哒，我去尝试使用一下Component组件，虽然我现在通过Dialog外面包了一层StatefulBuilder用来刷新Dialog局部状态，但是还是可以尝试一下Component组件方式。
