### ISSUE TITLE
release模式下,Lifecycle.initState无效

### ISSUE THREAD

**Issue by Zhang123Ashan** [alibaba/fish-redux#423]
> Lifecycle.initState 执行如下代码

`
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart' hide Action;
import 'action.dart';
import 'state.dart';

Effect<WelcomeState> buildEffect() {
  return combineEffects(<Object, Effect<WelcomeState>>{
    Lifecycle.initState: _init,
    WelcomeAction.enterSystem: _enterSystem
  });
}

void _init(Action action, Context<WelcomeState> ctx) {
  var list = new List<String>();
  list.add(
      "http://b-ssl.duitang.com/uploads/item/201310/08/20131008222038_8aUjU.jpeg");
  list.add(
      "http://b-ssl.duitang.com/uploads/item/201607/28/20160728233258_sPkYQ.thumb.700_0.jpeg");
  list.add(
      "http://b-ssl.duitang.com/uploads/item/201702/05/20170205210328_4VCFk.jpeg");
  var obj = Future<List<String>>(() {
    return list;
  });
//模拟从远程获取数据
  ctx.dispatch(WelcomeActionCreator.oninitImages(obj));
}

void _enterSystem(Action action, Context<WelcomeState> ctx) {
  Navigator.of(ctx.context).pushNamedAndRemoveUntil(action.payload, (route) => route == null);
}

`

> view

`
Widget buildView(
    WelcomeState state, Dispatch dispatch, ViewService viewService) {
    List<Slide> slides = new List();
    Future geturls() {
      return state.urls.then((urls) {
        urls.forEach((img) {
          slides.add(new Slide(
              title: "11111",
              description: "22222",
              styleDescription: TextStyle(
                  color: Colors.white, fontSize: 20.0, fontFamily: 'Raleway'),
              marginDescription: EdgeInsets.only(
                  left: 20.0, right: 20.0, top: 20.0, bottom: 70.0),
              colorBegin: Color(0xffFFDAB9),
              colorEnd: Color(0xff40E0D0),
              directionColorBegin: Alignment.topLeft,
              directionColorEnd: Alignment.bottomRight,
              backgroundImage: img,
              backgroundImageFit: BoxFit.fill));
        });
      });
  }

  Widget _buildFuture(BuildContext context, AsyncSnapshot snapshot) {
    print(snapshot);
    switch (snapshot.connectionState) {
      case ConnectionState.none:
        print('还没有开始网络请求');
        return Text('还没有开始网络请求');
      case ConnectionState.active:
        print('active');
        return Text('ConnectionState.active');
      case ConnectionState.waiting:
        print('waiting');
        return Center(
          child: CircularProgressIndicator(),
        );
      case ConnectionState.done:
        print('done');
        if (snapshot.hasError) return Text('Error: ${snapshot.error}');
        return IntroSlider(
          slides: slides,
          onDonePress:()=>dispatch(WelcomeActionCreator.onEnterSystem(main)),
          nameSkipBtn: "跳过",
          nameNextBtn: "下一页",
          nameDoneBtn: "进入",
        );
      default:
        return null;
    }
  }
  return FutureBuilder(builder: _buildFuture, future: geturls());
}
`

在debug模式下可用，一切正常，在release模式下无法获取到图片

**Comment by charmfocus** [comment]
网络权限没开吧，在android/app/src/main/AndroidManifest.xml中增加
```xml
<uses-permission android:name="android.permission.INTERNET" />
```

**Comment by Zhang123Ashan** [comment]
对不起，添乱了
