### ISSUE TITLE
组件复用后Action重复接收问题，导致各组件数据混乱问题

### ISSUE THREAD

**Issue by zhangdt** [alibaba/fish-redux#424]
### 我在一个父page里面需要放着3个界面一样的Component，在父page 的state 中也维护了3份 substate, 但是我的网络请求是放在子Component里面，当我调用某一个子Component的Action 去update数据后，3个子Component的Reducer都回被调用  然后3个子state都会更新成一个  有什么更好的解决办法？

![image](https://user-images.githubusercontent.com/12447121/62587896-6ce62b00-b8f6-11e9-92a2-e3b0d25e6eef.png)

![image](https://user-images.githubusercontent.com/12447121/62587880-5d66e200-b8f6-11e9-93f0-785e11f8097e.png)

![image](https://user-images.githubusercontent.com/12447121/62587875-563fd400-b8f6-11e9-809b-4e1261aaf15b.png)

![image](https://user-images.githubusercontent.com/12447121/62587858-47f1b800-b8f6-11e9-8e33-23f7b70c99b6.png)

![image](https://user-images.githubusercontent.com/12447121/62587929-82f3eb80-b8f6-11e9-9af8-525be44412ab.png)

**Comment by zjuwjf** [comment]
Action 应该设计是私有的，在需要多组件通信的情况下才是多个组件共有的。

**Comment by zhangdt** [comment]
@zjuwjf 你好，非常感谢你的回复，但是我现在是同一个组件，但是复用 用了3次，然后一个组件里面的action会被另外一个组件接收到，这有什么办法限制？

**Comment by zjuwjf** [comment]
你可以让你的Component\<T\> with PrivateReducerMixin\<T\>

**Comment by zjuwjf** [comment]
#134

**Comment by XingXiaoWu** [comment]
我也是相同的问题。。。使用 with PrivateReducerMixin<T>依旧无效。。

**Comment by zjuwjf** [comment]
> 我也是相同的问题。。。使用 with PrivateReducerMixin依旧无效。。

可以提供一个复现的最小demo么？

**Comment by XingXiaoWu** [comment]
> > 我也是相同的问题。。。使用 with PrivateReducerMixin依旧无效。。
> 
> 可以提供一个复现的最小demo么？
> 
> 可能需要参考 #457 这里讨论的问题。

感谢您的回答，我可能是一些使用不规范引起的，目前已经解决了。谢谢您

**Comment by qq329401134** [comment]
> 你可以让你的Component<T> with PrivateReducerMixin<T>

请问下有没有PrivateEffectMixin呢，我的effect混乱了好麻烦
