### ISSUE TITLE
在effect中获取MediaQuery直接崩溃

### ISSUE THREAD

**Issue by HappyGhostz** [alibaba/fish-redux#427]
if (MediaQuery.of(ctx.context) != null && MediaQuery.of(ctx.context).alwaysUse24HourFormat != null) {
    systemUse24HourFormat = MediaQuery.of(ctx.context).alwaysUse24HourFormat;
  }
运行这段代码直接崩溃，请问有了解吗，谢谢

**Comment by charmfocus** [comment]
systemUse24HourFormat未定义吧

**Comment by HappyGhostz** [comment]
找到了原因，我是在initstate里调用的，😓
