### ISSUE TITLE
tabcontroller 练的那个async参数怎么传 ，能否给个例子

### ISSUE THREAD

**Issue by niugengyun** [alibaba/fish-redux#428]
https://github.com/alibaba/fish-redux/issues/58  看过这个了  没看懂

**Comment by zjuwjf** [comment]
能具体描述你的问题么

**Comment by niugengyun** [comment]
> 能具体描述你的问题么

TabController(length: null, vsync: null)   vsync这个参数应该怎么穿进去？

**Comment by MMMzq** [comment]
@niugengyun  你可以看看这个例子 [example](https://github.com/MMMzq/fish_redux_adapter_example)

**Comment by niugengyun** [comment]
> @niugengyun 你可以看看这个例子 [example](https://github.com/MMMzq/fish_redux_adapter_example)

谢谢
