### ISSUE TITLE
关于如何定义一个全局共享的store

### ISSUE THREAD

**Issue by mrdaios** [alibaba/fish-redux#43]
比如说登录成功后，需要把用户信息共享在多个界面访问，能访问全局app的配置吗？类似store.of(context)

**Comment by Ljw127** [comment]
我们现在即将启动一个一个全新的项目，fish_redux目前是否稳定，不想项目中后期再有较大的变动

**Comment by zjuwjf** [comment]
类似store.of(context)？可以自定义一个Provider，来用来读写全局的配置信息。fish-redux 目前更聚焦做页面内的最佳解决方案。

**Comment by yohom** [comment]
通过根widget继承Page的方式来实现全局的store是否可行？@zjuwjf

**Comment by zjuwjf** [comment]
> 通过根widget继承Page的方式来实现全局的store是否可行？@zjuwjf

在设计上Component或者Page并不是Widget。它是一个容器的概念，其中Widget是它UI的表达的部分。

**Comment by mrdaios** [comment]
好的，谢谢
