### ISSUE TITLE
onLongPressUp无响应问题

### ISSUE THREAD

**Issue by oreofish** [alibaba/fish-redux#431]
需要实现一个录音按钮：
1. 按住录音，显示录音动画
2. 释放时停止，隐藏录音动画

问题是显示录音动画时，dispatch修改state，触发view重绘，按钮失效了，也就拿不到释放消息了。请问这种情况该如何处理？

谢谢

**Comment by zjuwjf** [comment]
如果有具体示例代码的话，可能会有帮助

**Comment by zjuwjf** [comment]
没有更多的信息，先close了。如有需要可以随时reopen。
