### ISSUE TITLE
adapter 中的 component 不能获取到自己的context吗？

### ISSUE THREAD

**Issue by abings** [alibaba/fish-redux#432]
我想获取adapter 中的 component 自己的 size 信息，
但是无论在buildView  时 (viewService.context).size 还是initState 时(cox.context).size 获取到的都是父类的context, 怎么才能获取到自己的context?

谢谢

**Comment by abings** [comment]
虽然通过key 的方式可以处理，但是GlobalKey的开销太大，请问自身怎么获取到？

**Comment by zjuwjf** [comment]
adapter(虚拟组件):
ctx.context   // 父组件的buildContext

component:
ctx.context   // 自身的buildContext

所以可能问题不在框架上。
