### ISSUE TITLE
对buildPage arguments的疑问

### ISSUE THREAD

**Issue by zakicheung** [alibaba/fish-redux#434]
`
  @override
  Widget buildPage(String path, dynamic arguments) =>
      pages[path]?.buildPage(arguments);
`
第二个参数在page中如何提取接收？以及在哪些场景下需要用到？
请不吝指教。感谢

**Comment by zjuwjf** [comment]
设计是路由系统携带过来的参数。

会在 Page:initState函数中作为唯一的入参，用于初始化store的state。

**Comment by zakicheung** [comment]
> 设计是路由系统携带过来的参数。
> 
> 会在 Page:initState函数中作为唯一的入参，用于初始化store的state。

首先感谢您的回答，我有在源码中看到是用于初始化store的
`
  @override
  void initState() {
    super.initState();
    _store = widget.page.createStore(widget.param);
    _pageBus = widget.page.createPageBus();
  }
`
只是我尚未发现如何获取到传入参数。

**Comment by cenumi** [comment]
initState方法 `PageState initState(Map<String, dynamic> args)` 这个 args 就是传过来的参数

**Comment by zakicheung** [comment]
> initState

噢！写了个demo，发现了。感谢您的帮助。问题我关闭了。
