### ISSUE TITLE
当adapter的某个item数据改变时,刷新问题

### ISSUE THREAD

**Issue by zhangruiyu** [alibaba/fish-redux#440]
当adapter的某个item数据改变时,会造成所以item重新build,但是我想达到的是对应item重绘,重写item的shouldUpdate,也没走到这,大概步骤是怎么搞呢

**Comment by zjuwjf** [comment]
重写 使用了adapter组件的shouldUpdate。精确控制避免不必要的List刷新。只刷新其中所需的item。

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/63648243-7b8a6a00-c75f-11e9-814a-e157e4d7c854.png)
可是shouldUpdate没有调用
![image](https://user-images.githubusercontent.com/10591822/63648250-8644ff00-c75f-11e9-96c2-e1cdadb5130a.png)

**Comment by zjuwjf** [comment]
shouldUpdate 如果都没调用的话，是不可能刷新的。
