### ISSUE TITLE
关于在ListView使用Adapter的时候如何获取position？

### ISSUE THREAD

**Issue by wjbd** [alibaba/fish-redux#443]
虽然通过fish_redux的adapter使得开发者不需要关注position（事实也是这样的），但是在某些页面的时候，需要用到这个position，我该怎么获取呢？

**Comment by wjbd** [comment]
准确的说，我是想在component的buildView里面获取position，来控制显示当前的item位置

**Comment by zjuwjf** [comment]
参考flutter 获取 position的方式

**Comment by wjbd** [comment]
我想知道这个listview的item是第几个，没办法在buildview里面拿到啊

**Comment by zjuwjf** [comment]
这个问题其实提到了挺多次了，之前给的解法是将你需要的要素表达在对应的state中。

可能会有一点点的繁琐。

如果是这样的形式
```dart

/// 注入
ctx.buildAdapter(foreach:(int index, Context<Object> ctx) {
      ctx.extra['index'] = index;
})；

/// 使用
final int index = ctx.extra['index'];

```

是否是预期的

**Comment by wjbd** [comment]
如果有这种形式的方式来实现，是挺好的，目前我也只能通过在State里添加这个index字段，来保证我的使用。

**Comment by zjuwjf** [comment]
@wjbd 我最近比较忙，这个特性我会在下周完整考虑，确定是否需要在下个版本中增强。

**Comment by wjbd** [comment]
这是一个非常棒的解决方案，非常咸鱼团队能够提供这种解决方案，可以很好的解决了我需要在State里面添加一个Index字段的解决方式。
再次感谢咸鱼官方团队提出的解决方案，这是一个非常棒的答案。
