### ISSUE TITLE
有没有全局loading的解决方案或者思路

### ISSUE THREAD

**Issue by jefferybai** [alibaba/fish-redux#444]
如果在每个page的view里面添加一个loading容器，关联至全局的store，
然后在网络请求的组件里面派发request_start ， request_end，就能实现全局loading，
但是问题在于， 路由栈里面的组件统一也关注的全局store，那样会导致他们也刷新。

有没有关于全局loading的一个比较好的解决方案。

**Comment by zjuwjf** [comment]
个人建议  网络请求的loading和状态可以无关，更接近于一个api的调用。

比如你可以基于dialog （api的形式）来展示loading。

**Comment by andyxiaoxi** [comment]
可以给个demo，展示使用方法吗
