### ISSUE TITLE
请教下page下子组件drawer再嵌套子组建如何使用adapter?

### ISSUE THREAD

**Issue by melontaro** [alibaba/fish-redux#446]
![image](https://raw.githubusercontent.com/melontaro/enterprisecms/master/2019-08-30_082730.png)

如上图,我参考下这个[＃340](https://github.com/alibaba/fish-redux/issues/340),
发现这个是单page下多个list,
而我这个是单个component下多个list.
page下子组件drawer再嵌套子组件list如何使用adapter?

**Comment by TangYuanHuan** [comment]
可以给一个可以运行的StaticFlowAdapter使用demo看看吗，没看懂StaticFlowAdapter是怎么用的，尝写代码学习怎么使用StaticFlowAdapter会一直报错
