### ISSUE TITLE
android改造全局middleware，使用onGenerateRoute函数闪烁

### ISSUE THREAD

**Issue by jefferybai** [alibaba/fish-redux#447]
因为使用最新版本fish-redux的全局middleware插件，所以路由需要改成onGenertageRoute函数去串联middleware， 但是：

一旦使用了， onGenerateRoute函数，安卓客户端会出现从客户端跳转到flutter页面闪烁的情况。

如果直接拿到ui.window.defaultRouteName 然后再home里面解析路由，不会闪烁。

**Comment by zjuwjf** [comment]
能有代码示例或demo吗
