### ISSUE TITLE
example 里的 == 不太懂

### ISSUE THREAD

**Issue by richardchey** [alibaba/fish-redux#45]
![default](https://user-images.githubusercontent.com/6816901/54023179-426d3600-41cf-11e9-87d1-e91c9f2f6b75.png)

`lib/todo_list_page/list_adapter/reducer.dart`
这地方看起来不太对哦（不止这一处）

**Comment by zjuwjf** [comment]
thanks for your suggestion. The useless code has been removed.

**Comment by richardchey** [comment]
I am a novice, don't get me wrong.
