### ISSUE TITLE
dispatch need some info about Effect or Reducer, for code jump.

### ISSUE THREAD

**Issue by huang12zheng** [alibaba/fish-redux#451]
(1)In Bloc, I get jump to code quickly through by [TodosBloc].
```
BlocProvider.of<TodosBloc>(context).dispatch(DeleteTodo(todo))
                   ^                             ^
                   ^                             ^
                   |                             |
                   |                             |
```
(2)In Fish,First,I would open effect.dart.Second, ctrl+F "onRemove", then, find out code.
What's more, if effect is many dispatch, I would open many effect.dart.
```
dispatch(ToDoActionCreator.onRemoveAction(state.uniqueId));
```

* So, how could I just jump to code instand of open effect.dart or reducer.dart?

**Comment by zjuwjf** [comment]
if you write the codes of ActionCreator in effect.dart or reducer.dart， is that works for you ？

**Comment by huang12zheng** [comment]
It seem good. But, it is working only if effect,reducer and creator would in one dart.
