### ISSUE TITLE
在Page中如何监听一个effect的状态

### ISSUE THREAD

**Issue by qq329401134** [alibaba/fish-redux#455]
当effect在执行代码的时候await的时候，当前的effect状态为loading。当effect执行所有代码以后，effect的状态变为complet，有这个监听功能吗

**Comment by zjuwjf** [comment]
你可以试试 EffectMiddleware， 前提需要想清楚你最后抽象的东西需要什么。

**Comment by lvzhiyi** [comment]
> 当effect在执行代码的时候await的时候，当前的effect状态为loading。当effect执行所有代码以后，effect的状态变为complet，有这个监听功能吗

我也遇到这个问题，请问你是怎么做的？
