### ISSUE TITLE
关于在一个页面里使用多个controller

### ISSUE THREAD

**Issue by VoterLin** [alibaba/fish-redux#456]
**情景描述：**
当我在一个Page或Component中需要使用多个Controller时, 只是让Page或Component混合fish_rudex暴露出来的SingleTickerProviderMixin<T>是已经不够用了，我在fish_redux的redux_component_mixin目录下找适配TickerProviderStateMixin的相关类但是一无所获。
**我的解决方式：**
所以，照着TickerProviderStateMixin自己写了个Mixin来适配TickerProviderStateMixin
`
port 'package:fish_redux/fish_redux.dart';
import 'package:flutter/widgets.dart';

mixin TickerProviderMixin<T> on Component<T> {
  @override
  _TickerProviderStfState<T> createState() =>
      _TickerProviderStfState<T>();
}

class _TickerProviderStfState<T> extends ComponentState<T>
    with TickerProviderStateMixin {}
`
使用这个Mixin后程序暂时没有出现什么问题。
**我的问题：**
fish redux 后续会有相关适配吗？还是已经有其他解决方法？

**Comment by zjuwjf** [comment]
非常不错的实践。 
如果可以，你可以pr进来，补充在redux_component_mixin下。如果这个是一个通用而标准的mixin。

**Comment by VoterLin** [comment]
已经pr。

**Comment by Muzm** [comment]
请问实现的TickerProviderMixin 如何使用可以给个例子吗

**Comment by redclo** [comment]
可否给个例子
