### ISSUE TITLE
关于监听器(listener)摆放位置的请教

### ISSUE THREAD

**Issue by guopeng1994** [alibaba/fish-redux#46]
来自flutter小白的请教：
如果需要添加类似下面这种监听器
 focusNode.addListener((){
       if(focusNode.hasFocus){
         // do something or dispatch some action
      } else {
        // other things or dispatch other action
     }
})

那么应该在什么哪个位置添加？如果在State中声明focusNode 并初始化， 那么addListener也应该在这个时候就添加了么？但是如果在这个时候添加的话，那么监听器处理函数里面又怎么去dispatch相关的action来另外处理呢？

**Comment by zjuwjf** [comment]
我愿意将这类非响应式的事件源和action的绑定过程放在effect的initState。
