### ISSUE TITLE
TickerProviderStateMixin dispose 报错

### ISSUE THREAD

**Issue by bitterking** [alibaba/fish-redux#461]
在Lifecycle.dispose 中将正在执行的animationController dispose掉，会报错
![image](https://user-images.githubusercontent.com/9761414/64685703-0090b580-d4ba-11e9-8ecd-3e3400606426.png)
感觉TickerProviderStateMixin 的dispose会先于ComponentState 中的dispose执行
`Effect<SeatsState> buildEffect() {
  return combineEffects(<Object, Effect<SeatsState>>{
    Lifecycle.initState: _init,
    Lifecycle.dispose: _dispose,
    SeatsAction.volumeChanged: _onVolumeChanged,
    SeatsAction.selfVolumeChanged: _onSelfVolumeChanged,
  });
}

void _init(Action action, Context<SeatsState> ctx) {
  final Object tickerProvider = ctx.stfState;
  ctx.state.volumeAnimationControllers = List.generate(8, (index) {
    return AnimationController(
        duration: Duration(milliseconds: 1000), vsync: tickerProvider);
  });
}

void _dispose(Action action, Context<SeatsState> ctx) {
  ctx.state.volumeAnimationControllers.forEach((controller) {
    controller.dispose();
  });
}`

**Comment by zjuwjf** [comment]
能提供一个最小的demo么？

**Comment by bitterking** [comment]
https://github.com/bitterking/redex_sample

@zjuwjf 麻烦大佬看一下，谢谢~~

**Comment by MMMzq** [comment]
@bitterking  这个问题我好像遇到过

我之前的推断原因是:

flutter执行了"错误"的生命周期导致的:initState->initState->dispose,

导致dispose的是最新的controller。

暂时的解决办法:
ctx.extra来保存需要销毁的AnimationController
像这样:
```dart
void _initState(Action action, Context<FriendsContactItemState> ctx) {
    ....
    ctx.extra["closeAnimation"] = clone.controller;
    ...
}

void _dispose(Action action, Context<FriendsContactItemState> ctx) {
    (ctx.extra["closeAnimation"] as AnimationController)?.dispose();
     ctx.extra["closeAnimation"] = null;
}
```

**Comment by zjuwjf** [comment]
@MMMzq @bitterking 你们的问题解决了么？

**Comment by MMMzq** [comment]
@zjuwjf 
那个问题并没有解决
[](url)
我写了的个example来重现: [example](https://github.com/MMMzq/fish_redux_adapter_example/tree/animation)

重现步骤
1.进去直接下拉刷新一次  (如果不刷新第一次是正常的)
2.展开ExpansionTile,点击里面的item (发现动画不能正常启动)

初步推断原因:
生命周期函数触发"错误"：initState->initState->dispose,

**Comment by qq329401134** [comment]
我也是遇到了同样的问题

**Comment by zjuwjf** [comment]
> 2.展开ExpansionTile,点击里面的item (发现动画不能正常启动)

你说的问题，我并没有复现。  initState  两次 是因为有两个item。

我的环境：flutter v1.9.1-hotfixes

**Comment by MMMzq** [comment]
我的版本信息:

> Flutter 1.9.1+hotfix.2 • channel unknown • unknown source
> Framework • revision 2d2a1ffec9 (2 weeks ago) • 2019-09-06 18:39:49 -0700
> Engine • revision b863200c37
> Tools • Dart 2.5.0

![git](https://github.com/MMMzq/fish_redux_adapter_example/raw/animation/bug.gif)

**Comment by zjuwjf** [comment]
@MMMzq 非常感谢你提供的这个case。

为什么通过 
在effect-dispose中通过
```
ctx.state.controller.dispose(); 
```
会dispose最新的controller， 而非想要的dispose那份老的controller。

而通过
```
ctx.extra["controller''].dispose(); 
```
是正确的。

这引导我们去思考一个问题🤔： 状态的生命周期问题。

ctx.state 是一个函数，它总会根据固定的方法（connector）去获取自己最新的状态。在绝大多数场景（slots）下，它work的很好，但是在DynamicFlowAdapter场景下，情况会变的复杂。

一般而言，我们都说，组件是有生命周期的，状态是无生命周期的。

但是在@MMMzq 的case中，列表中的每一项状态，都是需要有生命周期的。

DynamicFlowAdapter的列表下
每一个组件如何获取它的最新state， 特别是 ListView 刷新下， 存在组件的复用和不复用的case下，组件如何获取它的state。

上面 @MMMzq 提到的问题就是，当为每一个组件设置一个唯一Key的时候，也就是每一个组件都不复用，那如何让**刷新前**的第1项的组件获得的state是**刷新前**的state，而让**刷新后**的第1项的组件获得的state是**刷新后**的state，尽管他们都是通过index来获取状态的。

再考虑这样的场景，当List下的某一个Item组件，发出一个action，被自己的reducer所处理，如何让列表下的组件合理的获取自己最新的state？

在考虑一个场景，当List 被插入一行数据的时候，状态和widget又是如何在被复用的？

**Comment by zjuwjf** [comment]
我会随后发布一个新版本。

**Comment by MMMzq** [comment]
@zjuwjf 

非常感谢,问题解决了😀.

但是我还有一个问题就是:为什么现在还是`initState->initState->dispose`这个流程呢🤔?
这个流程很反直觉,正常来讲不应该是`initState->dispose->initState`这个过程的么?

**Comment by zjuwjf** [comment]
这个是flutter内部的处理流程， 从我理解，比较符合预期，先创建再释放。

一个listview下有2个item

initState item0
initState item1
下拉刷新
initState item2
initState item3
dispose 1
dispose 2

**Comment by MMMzq** [comment]
@zjuwjf  请问一下什么时候可以把这个改动发版？

**Comment by zjuwjf** [comment]
> @zjuwjf 请问一下什么时候可以把这个改动发版？

@MMMzq 已发布 0.2.7
