### ISSUE TITLE
Effect返回类型为bool时返回值为null，其他类型可以正常返回

### ISSUE THREAD

**Issue by sf294383583** [alibaba/fish-redux#462]

**Comment by zjuwjf** [comment]
能给更加清晰的描述么？

可能你说的下面的代码？
```dart
Effect<T> combineEffects<T>(Map<Object, SubEffect<T>> map) =>
    (map == null || map.isEmpty)
        ? null
        : (Action action, Context<T> ctx) {
            final SubEffect<T> subEffect = map.entries
                .firstWhere(
                    (MapEntry<Object, SubEffect<T>> entry) =>
                        action.type == entry.key,
                    orElse: () => null)
                ?.value;

            /// false
            return subEffect?.call(action, ctx) ?? subEffect != null;
          };
```

**Comment by sf294383583** [comment]
抱歉我没描述清楚。使用的时候发现Effect中返回类型为bool时
bool _onHasMyMerchanical(Action action, Context<MineState> ctx) {
  if (bulabula.......) {
    return true;
  }
  return false;
}
则dispatch(MineActionCreator.onHasMyMerchanical())的返回值为null，如果改为其他类型
int _onHasMyMerchanical(Action action, Context<MineState> ctx) {
  if (bulabula.......) {
    return 1;
  }
  return 0;
}
则dispatch(MineActionCreator.onHasMyMerchanical())的返回值为1或0，其他类型也可以正常返回。刚学习中，不知道是用法不对还是什么原因，感谢指导！

**Comment by zjuwjf** [comment]
事实上是 返回 true的话，会得到true， 返回false的话，会得到null。

因为从设计看，返回false会主动不拦截。 你这样做的出发点是什么呢？

**Comment by sf294383583** [comment]
这样啊，我的返回值确实是false，所以一直看到的是null。这是为了判断Offstage的显示和隐藏，因为逻辑不叫多，所以到Effect中去处理了。谢谢！
