### ISSUE TITLE
关于嵌套page的情况下的状态共享，以及AppRoutes的相关咨询

### ISSUE THREAD

**Issue by kerneltea** [alibaba/fish-redux#471]
想咨询下，我看到在master线上AppRoutes和HybirdRoutes被移除了，因为看到提交记录上并没有详细介绍为什么移除 ，想要咨询下移除他的原因是什么？那现在想在共享store需要用什么替代方法？

现在我打算通过GlobalStore来解决多个页面共享数据的问题，我现在有一个case是这样的。
我们这边用了BottomNavigationBar,下面有三个TAB，其中对应了三个page,主页面是一个page
其中这四个page的state都实现了全局状态（参照了demo的themeColor）

大概的依赖状态是这样的
**main_tab_page**包含了**discovery_page** ,**create_page** ,**profile_page**
但是现在的问题是我通过GlobalStore来dispatch这个全局状态的时候只有main_tab_page可以收到相应的状态更改，我理解是不是因为main_tab_page是当前的页面，并没有下发给其它三个子page?
可能我也不是很理解，是不是我这边用的有问题？

也希望能指点下在BottomNavigationBar这种嵌套子page的情况下，应该怎样达到状态共享？

**Comment by kerneltea** [comment]
想问下，有相关的demo参照么

**Comment by zjuwjf** [comment]
example里有。

**Comment by kerneltea** [comment]
我们的全局状态是account这些，还是挺重的

**Comment by niuxinhuai** [comment]
> 想咨询下，我看到在master线上AppRoutes和HybirdRoutes被移除了，因为看到提交记录上并没有详细介绍为什么移除 ，想要咨询下移除他的原因是什么？那现在想在共享store需要用什么替代方法？
> 
> 现在我打算通过GlobalStore来解决多个页面共享数据的问题，我现在有一个case是这样的。 我们这边用了BottomNavigationBar,下面有三个TAB，其中对应了三个page,主页面是一个page 其中这四个page的state都实现了全局状态（参照了demo的themeColor）
> 
> 大概的依赖状态是这样的 **main_tab_page**包含了**discovery_page** ,**create_page** ,**profile_page** 但是现在的问题是我通过GlobalStore来dispatch这个全局状态的时候只有main_tab_page可以收到相应的状态更改，我理解是不是因为main_tab_page是当前的页面，并没有下发给其它三个子page? 可能我也不是很理解，是不是我这边用的有问题？
> 
> 也希望能指点下在BottomNavigationBar这种嵌套子page的情况下，应该怎样达到状态共享？
您好，请问下你最终是如何解决这个问题的？
