### ISSUE TITLE
GlobalState接收不到相应的事件

### ISSUE THREAD

**Issue by kerneltea** [alibaba/fish-redux#472]
您好，我将example的代码改成了BottomNavigationBar的形式，我新建了一个MainPage,这个page是一个bottomNavigationBar的的格式，我在新的路由中添加了
![image](https://user-images.githubusercontent.com/1260653/64872522-ebfb1b80-d679-11e9-8732-f542fcc2e7c1.png)
在构建app的时候我先启动的这个**mainpage**,如下
![image](https://user-images.githubusercontent.com/1260653/64872590-0e8d3480-d67a-11e9-8700-8cd16d0e9ef6.png)
相应的MainPage是这样定义的：
![image](https://user-images.githubusercontent.com/1260653/64873313-5cef0300-d67b-11e9-910b-f412150af25e.png)
对应的mainPageState如下：
![image](https://user-images.githubusercontent.com/1260653/64873350-6ed0a600-d67b-11e9-80b9-6f7fcbd97913.png)
MainView是这样定义的：
![image](https://user-images.githubusercontent.com/1260653/64873437-a63f5280-d67b-11e9-9150-46303b9ebdde.png)

现在的问题是我在点击**ToDoEdit**中的**change theme**的时候在APP中注册的visitor**没有回调**，相应的主题颜色也没有随之变化，在初始化的时候已经确定对应的Page都成功调用了**connectExtraStore**函数来监听全局变化监听。
现在我怀疑有可能是我在main_tab中的**dependense**实现的有问题，不知道是否跟这个有关，
还有就是对应的routes没有通过navigator来启动，而是自己创建的，从而不在visitor的监听范围内？这一点我不是很理解。
还请作者帮忙分析？

我现在如果想要实现这样一个结构的APP，应该怎样完成数据共享？

还请帮忙分析一下，我还有一个疑问是，为什么GlobalStore在已经connectExtraStore的情况下收不到对应的响应？

**Comment by zjuwjf** [comment]
如果提供一个demo，可能会有帮助。

**Comment by kerneltea** [comment]
> 如果提供一个demo，可能会有帮助。

https://github.com/kerneltea/files/blob/master/0001-bottom-navigation-bar-demo.patch
这是我基于fish-redux中master线的example通过**git format-patch -1** 生成的patch文件改靠patch,麻烦帮忙看下

**Comment by ForeverLiuyaqi** [comment]
我也遇到了类似的问题，

**Comment by zjuwjf** [comment]
如果想要使用在visitor中绑定的关系，那么应该使用 routes.buildPage。

通常直接new APage() 是不存在和AppStore的链接关系的。

```dart
/// Each page has a unique store.
@immutable
class PageRoutes implements AbstractRoutes {
  final Map<String, Page<Object, dynamic>> pages;

  PageRoutes({
    @required this.pages,

    /// For common enhance
    void Function(String, Page<Object, dynamic>) visitor,
  }) : assert(pages != null, 'Expected the pages to be non-null value.') {
    if (visitor != null) {
      pages.forEach(visitor);
    }
  }

  @override
  Widget buildPage(String path, dynamic arguments) =>
      pages[path]?.buildPage(arguments);
}
```

**Comment by kerneltea** [comment]
问题已解决，非常感谢
