### ISSUE TITLE
父级view中无法dispatch子组件中的effect事件，只能调用Reducer中的事件

### ISSUE THREAD

**Issue by charmfocus** [alibaba/fish-redux#473]
例：APageView中一个按钮onTap中dispatch了子组件SubComponent的一个事件onAction,只能调到Reducer中的同名事件，无法调用effect中定义的同名事件（已经注释掉了Reducer中的同名事件）

**Comment by zjuwjf** [comment]
两种可能：
1、发送onAction的单元（component或者adapter）的effect消费了这个action。
2、SubComponent已经销毁，不存在于widgetTree中。

**Comment by charmfocus** [comment]
> 两种可能：
> 1、发送onAction的单元（component或者adapter）的effect消费了这个action。
> 2、SubComponent已经销毁，不存在于widgetTree中。
感谢在节日中还抽出时间回答问题！
确实我没在APageView中引入SubComponent，引入后可正常调用到effect。
那为什么在没有引入SubComponent时，确能调用到Reducer的事件

**Comment by zjuwjf** [comment]
1、Reducer 是静态的， 在创建页面前，已经确定，也没有生命周期等。（修改状态本身并不需要依赖组件）。

2、给Effect处理的action和给Reducer处理的action，建议做明确的区分。简单易维护。

**Comment by charmfocus** [comment]
嗯，好！
