### ISSUE TITLE
如何创建一个全局的state,还有就是在使用fish_redux时是否还需要配合其他的一些状态管理框架

### ISSUE THREAD

**Issue by Ljw127** [alibaba/fish-redux#48]
我们的即将启动一个全新的app,想了解fish_redux是否稳定,包括是否需要一些其他框架做配合,不想项目中后期或有较大的变动

**Comment by zjuwjf** [comment]
Fish_redux is now a stable version. If you have any problems, you can give us issues. We will actively deal with them.

**Comment by Ljw127** [comment]
Ok, thank you for your answer.

**Comment by wtus** [comment]
我也想知道，全局的状态管理怎么弄？看了下sample，好像没有涉及

**Comment by wtus** [comment]
我把问题具体一点吧，如果我要做国际化，夜间模式。。。等等这些全局的功能应该怎么处理方便一些？还是fish-redux只是关心页面的状态？

**Comment by guopeng1994** [comment]
+1

**Comment by bluepine0808** [comment]
提交记录里，这笔提交“add extra for app provider“，PageProvider提供了一个extra，我理解是可以做额外的全局状态管理。
