### ISSUE TITLE
请问多个页面（page）可以共享同一个 store 吗？

### ISSUE THREAD

**Issue by tk-canday** [alibaba/fish-redux#484]
我的理解是每个页面都有一套自己的 store。
那如果我想多个页面(Page) 共享一个 store， 利用 fish_redux 可以做到吗 ？

**Comment by xiaxiangfeng** [comment]
其实有一个全局store是多个页面共享的。
redux之所以就一个store ，是应为那是单页应用。
其实多个页面（page）共享同一个 store这需求是个伪需求（个人认为），页面共享数据基本都是路由传递参数。

**Comment by DDDrop** [comment]
#153 有讨论 
example 也有例子可以参考一下：
https://github.com/alibaba/fish-redux/tree/master/example/lib/global_store

**Comment by zjuwjf** [comment]
没有更一步的问题，先关闭。如有需要可以随时reopen。
