### ISSUE TITLE
type 'MaterialPageRoute<Object>' is not a subtype of type 'Route<String>'

### ISSUE THREAD

**Issue by dingzuhua** [alibaba/fish-redux#486]
When I use Navigator. Of (ctx.context). MaybePop (); And with a return parameter.

**Comment by zjuwjf** [comment]
有解决么？ 似乎不是fish-redux相关的问题。

**Comment by zjuwjf** [comment]
没有更一步的问题，先关闭。如有需要可以随时reopen。
