### ISSUE TITLE
能和flutter_boost 一起用吗

### ISSUE THREAD

**Issue by xchenzhen** [alibaba/fish-redux#488]

**Comment by zjuwjf** [comment]
当然可以。

**Comment by xchenzhen** [comment]
Page页面怎么管理，

flutter_bost:
 FlutterBoost.singleton.registerPageBuilders({
      Router.MY_SETTING_PAGE_URL: (pageName, params, _) => MySettingPage(),
});

fish-redux:
final AbstractRoutes routes = PageRoutes(
    pages: <String, Page<Object, dynamic>>{
      /// 注册登陆主页面
      "login": LoginPage(),
});

这两个地方怎么改，有demo吗

**Comment by chaishuanzhu** [comment]
> Page页面怎么管理，
> 
> flutter_bost:
> FlutterBoost.singleton.registerPageBuilders({
> Router.MY_SETTING_PAGE_URL: (pageName, params, _) => MySettingPage(),
> });
> 
> fish-redux:
> final AbstractRoutes routes = PageRoutes(
> pages: <String, Page<Object, dynamic>>{
> /// 注册登陆主页面
> "login": LoginPage(),
> });
> 
> 这两个地方怎么改，有demo吗

这个问题解决了吗？

**Comment by niechaoqun9456** [comment]
> > Page页面怎么管理，
> > flutter_bost:
> > FlutterBoost.singleton.registerPageBuilders({
> > Router.MY_SETTING_PAGE_URL: (pageName, params, _) => MySettingPage(),
> > });
> > fish-redux:
> > final AbstractRoutes routes = PageRoutes(
> > pages: <String, Page<Object, dynamic>>{
> > /// 注册登陆主页面
> > "login": LoginPage(),
> > });
> > 这两个地方怎么改，有demo吗
> 
> 这个问题解决了吗？

AbstractRoutes routes = PageRoutes(
  pages: <String, Page<Object, dynamic>>{
    'index': IndexPage(),
  },
);

FlutterBoost.singleton.registerPageBuilders(<String, PageBuilder>{
  '/index': (String pageName, Map<dynamic, dynamic> params, String uniqueId) {
    return routes.buildPage('index', null);
  },
});

**Comment by chaishuanzhu** [comment]
> > > Page页面怎么管理，
> > > flutter_bost:
> > > FlutterBoost.singleton.registerPageBuilders({
> > > Router.MY_SETTING_PAGE_URL: (pageName, params, _) => MySettingPage(),
> > > });
> > > fish-redux:
> > > final AbstractRoutes routes = PageRoutes(
> > > pages: <String, Page<Object, dynamic>>{
> > > /// 注册登陆主页面
> > > "login": LoginPage(),
> > > });
> > > 这两个地方怎么改，有demo吗
> > 
> > 
> > 这个问题解决了吗？
> 
> ```
> AbstractRoutes routes = PageRoutes(
>   pages: <String, Page<Object, dynamic>>{
>     'index': IndexPage(),
>   },
> );
> ```
> 
> ```
> FlutterBoost.singleton.registerPageBuilders(<String, PageBuilder>{
>   '/index': (String pageName, Map<dynamic, dynamic> params, String uniqueId) {
>     return routes.buildPage('index', null);
>   },
> });
> ```

我是这样做的
```
class _MyAppState extends State<MyApp> {
final PageRoutes routes = PageRoutes(
    pages: <String, Page<Object, dynamic>>{
      'index': IndexPage(),
  },
);

@override
  void initState() {
    super.initState();
    Map<String, PageBuilder> builders = {};
    routes.pages.forEach((key, value) {
      builders[key] =
          (pageName, params, _) => routes.buildPage(pageName, params);
    });

    FlutterBoost.singleton.registerPageBuilders(builders);
    FlutterBoost.singleton
        .addBoostNavigatorObserver(TestBoostNavigatorObserver());
  }
}
```
