### ISSUE TITLE
Adapter 应该是个很重要的概念，但感觉例子呈现的东西太少

### ISSUE THREAD

**Issue by a573367014** [alibaba/fish-redux#49]
生命周期、他的特点，例子好像都没有呈现出来，看文档有点不好理解

**Comment by zjuwjf** [comment]
更新了一些文档, 可以参考

[目录](https://github.com/alibaba/fish-redux/blob/master/doc/README-cn.md)
[What's-adapter](https://github.com/alibaba/fish-redux/blob/master/doc/concept/what's-adapter.md)
