### ISSUE TITLE
TodoEditPage中每次修改编辑框内容，都会重新buildView()，这样难道不会影响性能吗？

### ISSUE THREAD

**Issue by KaiXuan666** [alibaba/fish-redux#492]
如题，这段逻辑很奇怪，我在此页面修改编辑框内容，view层的nameEditController会在Effect中监听处理，最终在Reducer中修改状态，刷新回View
但是奇怪的是：我把编辑框内容改为1，此时view层的编辑框内容已经被我修改过了，为什么还要绕这么一大圈，最后又通知回view，执行buildView()，这样我每次修改编辑框内容，都会反复执行，并且都毫无意义，因为编辑框内容肯定已经是最新的了。
请问这样做有什么意义？

**Comment by KaiXuan666** [comment]
@zjuwjf 大佬回答下鸭

**Comment by hzgotb** [comment]
你看一下文档。[文档](https://hzgotb.github.io/fish-redux-docs/zh/guide/get-started/#%E6%9E%84%E5%BB%BA%E5%BA%94%E7%94%A8)
localProps是后面加的。文档暂时里没写。

我晚上把example更新一下吧。

**Comment by zjuwjf** [comment]
@KaiXuan666 问题挺好的，之前也没注意到。

1、这样做，会有额外的build 产生，好处是代码比较简单。
2、需要避免无效的rebuild，需要复写 shouldUpdate 函数。

```dart
bool shouldUpdate(TodoEditState oldState, TodoEditState newState) {
    return oldState.nameEditController != newState.nameEditController ||
    oldState.descEditController != newState.descEditController ||
    oldState.focusNodeName != newState.focusNodeName ||
    oldState.focusNodeDesc != newState.focusNodeDesc ||
    oldState.themeColor != newState.themeColor ;
}
```

**Comment by hzgotb** [comment]
> @KaiXuan666 问题挺好的，之前也没注意到。
> 
> 1、这样做，会有额外的build 产生，但好处是代码比较简单。
> 2、要避免无效的rebuild，需要复写 shouldUpdate 函数。
> 
> ```dart
> bool shouldUpdate(TodoEditState oldState, TodoEditState newState) {
>     return oldState.nameEditController != newState.nameEditController ||
>     oldState.descEditController != newState.descEditController ||
>     oldState.focusNodeName != newState.focusNodeName ||
>     oldState.focusNodeDesc != newState.focusNodeDesc ||
>     oldState.themeColor != newState.themeColor ;
> }
> ```
> 
> 让toDo不参与shouldUpdate。

那把 toDo 写进localProps是否可行？

**Comment by zjuwjf** [comment]
> > @KaiXuan666 问题挺好的，之前也没注意到。
> > 1、这样做，会有额外的build 产生，但好处是代码比较简单。
> > 2、要避免无效的rebuild，需要复写 shouldUpdate 函数。
> > ```dart
> > bool shouldUpdate(TodoEditState oldState, TodoEditState newState) {
> >     return oldState.nameEditController != newState.nameEditController ||
> >     oldState.descEditController != newState.descEditController ||
> >     oldState.focusNodeName != newState.focusNodeName ||
> >     oldState.focusNodeDesc != newState.focusNodeDesc ||
> >     oldState.themeColor != newState.themeColor ;
> > }
> > ```
> > 
> > 
> > 让toDo不参与shouldUpdate。
> 
> 那把 toDo 写进localProps是否可行？


我觉得

1、不监听EditController， 在页面返回中，创建新的TODO返回。
2、复写shouldUpdate， 让TODO不参与刷新。
3、使用 localProps

前两种简单些。 都是可行的。

**Comment by hzgotb** [comment]
其实不用toDo也可以。最后提交的时候直接拿TextEditController的text出来组合就行了。感觉添加listener多余了。

**Comment by KaiXuan666** [comment]
对，应该是不需要加监听的，谢谢大佬们的回复。我还以为阿里大佬们写的代码都是最佳实践呢

**Comment by zjuwjf** [comment]
> 我还以为阿里大佬们写的代码都是最佳实践呢

感谢反馈，已修正。

**Comment by XingXiaoWu** [comment]
> @KaiXuan666 问题挺好的，之前也没注意到。
> 
> 1、这样做，会有额外的build 产生，但好处是代码比较简单。
> 2、要避免无效的rebuild，需要复写 shouldUpdate 函数。
> 
> ```dart
> bool shouldUpdate(TodoEditState oldState, TodoEditState newState) {
>     return oldState.nameEditController != newState.nameEditController ||
>     oldState.descEditController != newState.descEditController ||
>     oldState.focusNodeName != newState.focusNodeName ||
>     oldState.focusNodeDesc != newState.focusNodeDesc ||
>     oldState.themeColor != newState.themeColor ;
> }
> ```
> 
> 让toDo不参与shouldUpdate。

请问shouldUpdate写在呢

**Comment by hzgotb** [comment]
> 对，应该是不需要加监听的，谢谢大佬们的回复。我还以为阿里大佬们写的代码都是最佳实践呢

你这样说放学出不了校门口的 /滑稽

**Comment by hzgotb** [comment]
> > @KaiXuan666 问题挺好的，之前也没注意到。
> > 1、这样做，会有额外的build 产生，但好处是代码比较简单。
> > 2、要避免无效的rebuild，需要复写 shouldUpdate 函数。
> > ```dart
> > bool shouldUpdate(TodoEditState oldState, TodoEditState newState) {
> >     return oldState.nameEditController != newState.nameEditController ||
> >     oldState.descEditController != newState.descEditController ||
> >     oldState.focusNodeName != newState.focusNodeName ||
> >     oldState.focusNodeDesc != newState.focusNodeDesc ||
> >     oldState.themeColor != newState.themeColor ;
> > }
> > ```
> > 
> > 
> > 让toDo不参与shouldUpdate。
> 
> 请问shouldUpdate写在呢

在构建 page 时，传给super。伪代码：
```dart
class DemoPage extends Page<DempPageState> {
  DemoPage() : super(
    shouldUpdate: (DempPageState oldState, DempPageState newState) {
      // TODO 判断哪些是需要更新的。
      return true;
    },
  )
}
```

**Comment by XingXiaoWu** [comment]
> > > @KaiXuan666 问题挺好的，之前也没注意到。
> > > 1、这样做，会有额外的build 产生，但好处是代码比较简单。
> > > 2、要避免无效的rebuild，需要复写 shouldUpdate 函数。
> > > ```dart
> > > bool shouldUpdate(TodoEditState oldState, TodoEditState newState) {
> > >     return oldState.nameEditController != newState.nameEditController ||
> > >     oldState.descEditController != newState.descEditController ||
> > >     oldState.focusNodeName != newState.focusNodeName ||
> > >     oldState.focusNodeDesc != newState.focusNodeDesc ||
> > >     oldState.themeColor != newState.themeColor ;
> > > }
> > > ```
> > > 
> > > 
> > > 让toDo不参与shouldUpdate。
> > 
> > 
> > 请问shouldUpdate写在呢
> 
> 在构建 page 时，传给super。伪代码：
> 
> ```dart
> class DemoPage extends Page<DempPageState> {
>   DemoPage() : super(
>     shouldUpdate: (DempPageState oldState, DempPageState newState) {
>       // TODO 判断哪些是需要更新的。
>       return true;
>     },
>   )
> }
> ```

舒服了，谢谢
