### ISSUE TITLE
遇到Reducers may not dispatch actions问题

### ISSUE THREAD

**Issue by hyccode** [alibaba/fish-redux#494]
![image](https://user-images.githubusercontent.com/26076350/66621469-ed871780-ec16-11e9-9f67-47bf3da798f0.png)
遇到一个问题，第一个dispatch调用后会触发第二个dispatch，然后会报这个错误！
我给第二个dispatch添加延迟触发可以解决这个问题，但感觉不是很好，想问下还有其他更好的处理方式吗？

**Comment by zjuwjf** [comment]
相信报错是比较清晰的。 你在reducer函数中操作dispatch，它又触发了action。
想象一下一颗被改了一半的状态树，又收到一个action要修改状态。
这让reducer变成非纯函数，让状态变更也无法预测。
你可以搜下相关的issue。有更详细的解释。
