### ISSUE TITLE
在fish_redux怎么使用SingleTickerProviderStateMixin

### ISSUE THREAD

**Issue by YunhuiLiu140502** [alibaba/fish-redux#501]
使用TabBar需要state  with SingleTickerProviderStateMixin，TabController中有个参数是vsync，但是不知道fish_redux里面该如何实现使用TabBar

**Comment by hzgotb** [comment]
#58 看一下这个。

**Comment by zjuwjf** [comment]
没有更一步的问题，先关闭。如有需要可以随时reopen。
