### ISSUE TITLE
请大佬帮忙，运行在android emulator 上出错，但是运行在chrome web时没有问题。什么原因？

### ISSUE THREAD

**Issue by oneredorange** [alibaba/fish-redux#502]
class LayoutPage extends Page<LayoutState, Map<String, dynamic>> {
  LayoutPage()
      : super(
            initState: initState,
            effect: buildEffect(),
            reducer: buildReducer(),
            view: buildView,
            dependencies: Dependencies<LayoutState>(
                adapter: null,
                slots: <String, Dependent<LayoutState>>{
                  'flowdemo': FlowdemoConnector() + FlowdemoComponent(),
                }),
            middleware: <Middleware<LayoutState>>[
            ],);

}

Built build\app\outputs\apk\debug\app-debug.apk.
E/flutter (15058): [ERROR:flutter/lib/ui/ui_dart_state.cc(155)] Unhandled Exception: type '_Dependent<dynamic, dynamic>' is not a subtype of type 'Dependent<LayoutState>'

E/flutter (15058): #0      new LayoutPage 
package:gruhub/…/layout_page/page.dart:19
E/flutter (15058): #1      createApp 
package:gruhub/app.dart:21
E/flutter (15058): #2      main 
package:gruhub/main.dart:5
E/flutter (15058): #3      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:239:25)
E/flutter (15058): #4      _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (15058): #5      _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (15058): #6      _runZoned  (dart:async/zone.dart:1516:10)
E/flutter (15058): #7      runZoned  (dart:async/zone.dart:1500:12)
E/flutter (15058): #8      _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:231:5)
Launching lib\main.dart on Android SDK built for x86 in debug mode...
E/flutter (15058): #9      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (15058): #10     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by zjuwjf** [comment]
运行在浏览器上，应该是转化为js，是弱类型。
看报错是泛形签名不正确，检查下泛形即可。
