### ISSUE TITLE
怎么样获取GlobalState中的值？

### ISSUE THREAD

**Issue by ludy520** [alibaba/fish-redux#504]
根据demo，改了GlobalState，

![image](https://user-images.githubusercontent.com/4113005/67558334-5e671d00-f749-11e9-8a92-99a70840a7b2.png)

在某个界面获取数据也填充好了GlobalState中的parentInfo和students,然后在我的界面中获取，
![image](https://user-images.githubusercontent.com/4113005/67558484-aab25d00-f749-11e9-8c8d-a6b12a093c2c.png)
![image](https://user-images.githubusercontent.com/4113005/67558554-c61d6800-f749-11e9-87ea-cfc136bf5cbe.png)
在上面1中获取失败，而2的方式可以获取到，请教正确获取GlobalState中的值该怎么做？？

**Comment by zjuwjf** [comment]
appStore和pageStore的连接关系中，需要将appStore的状态赋值给pageStore。

**Comment by XingXiaoWu** [comment]
看一下demo的mian文件
![image](https://user-images.githubusercontent.com/22769131/67733940-af715c80-fa3a-11e9-9cfd-cb9657e126ba.png)
这个地方需要连接appStore和pageStore。
且pageState需要extaned GlobalBaseState

**Comment by ludy520** [comment]
好的好的，非常感谢
