### ISSUE TITLE
Effect didChangeDependencies 调showDialog报错

### ISSUE THREAD

**Issue by xchenzhen** [alibaba/fish-redux#505]
// Effect
class ExpandFunctionEffect {
static Effect buildEffect() {
return combineEffects(<Object, Effect>{
Lifecycle.didChangeDependencies: _init,
});
}

// 初始化
static _init(Action action, Context ctx) async {
showLoading(ctx.context);
HBResponse response = await MeApi.getExtendServiceAccount();
if (!response.isSuccess()) {
ViewUtils.showToast(response.getErrorInfo());
// dismissLoading(ctx.context);
return;
}
}`

错误信息：
10-28 15:20:53.764 29913-29973/im.huoban.test E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
Overlay-[LabeledGlobalKey#1eac4](state: OverlayState#d728b(entries: [OverlayEntry#878df(opaque: false; maintainState: false), OverlayEntry#94900(opaque: false; maintainState: true), OverlayEntry#64393(opaque: false; maintainState: false), OverlayEntry#e00e4(opaque: false; maintainState: true)]))
The widget which was currently being built when the offending call was made was:
_PageWidget<ExpandFunctionState, Map<String, dynamic>>(state: _PageState<ExpandFunctionState, Map<String, dynamic>>#2bfc4)
#0 Element.markNeedsBuild. (package:flutter/src/widgets/framework.dart:3503:11)
#1 Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3529:6)
#2 State.setState (package:flutter/src/widgets/framework.dart:1133:14)
#3 OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:346:5)
#4 OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
#5 TransitionRoute.install (package:flutter/src/widgets/routes.dart:180:11)
#6 ModalRoute.install (package:flutter/src/widgets/routes.dart:895:11)
#7 NavigatorState.push (package:flutter/src/widgets/navigator.dart:1742:11)
#8 BoostContainerState.push (package:flutter_boost/container/boost_container.dart:224:30)
#9 showGeneralDialog (package:flutter/src/widgets/routes.dart:1558:53)
#10 showDialog (package:flutter/src/material/dialog.dart:705:10)
#11 showLoading (package:huoban_im_flutter/component/dialog/loading_dialog.dart:46:3)
#12 ExpandFunctionEffect._init (package:huoban_im_flutter/page/setting/state/expand_function_state.dart:72:5)

**Comment by zjuwjf** [comment]
应该是和fish-redux框架无关的问题。
请参考 https://github.com/flutter/flutter/issues/26458
