### ISSUE TITLE
can component get action creator from parent page or comppnent?

### ISSUE THREAD

**Issue by swaitw** [alibaba/fish-redux#506]
i am trying to reuse a component which need to dispatch a parent action to init the state. currently have to import the parent action creator to dispatch the action ,which means it be locked with the current parent component, i cant reused it as a dependent for other components, so is it possible to get parent's action creator  dynamically or have other ways can reuse such component?  if it possible please give some example thanks.

**Comment by zjuwjf** [comment]
Maybe you should move your 'parent's action creator' to some 'common action creator'.
