### ISSUE TITLE
fish-redux可以实现类似于安卓EventBus的事件总线吗

### ISSUE THREAD

**Issue by KaiXuan666** [alibaba/fish-redux#507]
如题，假如我Home页面下有两个子Page：A和B，他们各自下面又拥有A1，A2，B1，B2
此时，我需要
上级到下级的通讯，如：A发送事件到A1，
或下级到上级的通讯，如：B1发送给B，
或跨级通讯，如：A1发送消息给B2，
这种场景要怎样实现？
在Demo中我只看到了，子页面直接和AppState通讯，没有看到其他
todo_edit_page向todo_list_page传递数据，也是通过原生的Navigator
请问fish-redux自身可以实现这种需求吗？有没有相关例子？

**Comment by zjuwjf** [comment]
cc `ctx.broadcast(action)`

**Comment by KaiXuan666** [comment]
谢谢
