### ISSUE TITLE
GlobalStore更新数据问题

### ISSUE THREAD

**Issue by xfmaster** [alibaba/fish-redux#508]
GlobalStore怎么更新adapter中item数据

**Comment by zjuwjf** [comment]
1、GlobalStore 可以更新PageStore 里的状态
2、Adapter中item的状态，必然都来自于PageStore

所以想不到为什么会有这个问题？

**Comment by xfmaster** [comment]
当前显示的列表没有刷新，list集合数据已经更新了

**Comment by zjuwjf** [comment]
看上去是使用上有错误；如果可以提供一个最小化的demo的话，会有帮助；

**Comment by xfmaster** [comment]
`class NewsAdapter extends DynamicFlowAdapter<IndexState> {
  NewsAdapter()
      : super(pool: <String, Component<Object>>{
          'normal': NormalComponent(),
          'item': ItemComponent(),
          'study': StudyComponent(),
          'banner': BannerComponent(),
          'column': ColumnComponent(),
        }, connector: _NewsConnector());
}

class _NewsConnector extends ConnOp<IndexState, List<ItemBean>> {
  @override
  List<ItemBean> get(IndexState state) {
    if (state.list?.isNotEmpty == true) {
      return state.list.map<ItemBean>((ItemState data) {
        if (data.bean != null && data.bean.type == 2) {
          return ItemBean('normal', data);
        } else if (data.bean != null && data.bean.type == 1) {
          return ItemBean('item', data);
        } else if (data.bean == null &&
            data.banners == null &&
            data.columnData != null) {
          return ItemBean('column', data);
        } else if (data.banners != null) {
          return ItemBean('banner', data);
        } else {
          return ItemBean('study', data);
        }
      }).toList(growable: true);
    } else {
      return <ItemBean>[];
    }
  }

  @override
  void set(IndexState state, List<ItemBean> items) {
    if (items?.isNotEmpty == true) {
      state.list = List<ItemState>.from(items.map<ItemState>((ItemBean bean) {
        ItemState data = bean.data;
        data.appTheme = state.appTheme;
        return data;
      }).toList());
    } else {
      state.list = <ItemState>[];
    }
  }

  @override
  subReducer(reducer) {
    println("subReducer");
    return super.subReducer(reducer);
  }
}
`
pagestate
`
class IndexState implements GlobalBaseState, Cloneable<IndexState> {
  NewsListBean bean;
  Data data;
  RefreshController refreshController;
  List<ItemState> list;

  @override
  IndexState clone() {
    println("index-----clone");
    return IndexState()
      ..appTheme = appTheme
      ..bean = bean
      ..data = data
      ..refreshController = refreshController
      ..list = list;
  }

  @override
  AppTheme appTheme;
}

IndexState initState(Map<String, dynamic> args) {
  return IndexState()
    ..refreshController = new RefreshController()
    ;
}
`
itemstate
`import 'package:daily_app/base/app_theme.dart';
import 'package:daily_app/bean/news_bean.dart';
import 'package:daily_app/global_store/state.dart';
import 'package:fish_redux/fish_redux.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

class ItemState implements Cloneable<ItemState> ,GlobalBaseState{
  NewsBean bean;
  AppTheme appTheme;
  List<NewsBean> banners;
  int now;
  ColumnData columnData;
  RefreshController refreshController;
  double itemWidth;

  @override
  ItemState clone() {
    println("ItemState----------------------clone");
    return ItemState()
      ..bean = bean
      ..appTheme = AppTheme.getInstance()
      ..itemWidth = itemWidth
      ..banners = banners
      ..columnData = columnData
      ..refreshController = refreshController
      ..now = now;
  }
}

ItemState initItemState(
    NewsBean bean, List<NewsBean> banners, ColumnData columnData) {
  RefreshController refreshController;
  if (columnData != null) {
    refreshController = new RefreshController();
    var name = columnData.column.name;
    println("initItemState----------------------$name");
  }

  return ItemState()
    ..bean = bean
    ..appTheme = AppTheme.getInstance()
    ..now = DateTime.now().millisecondsSinceEpoch
    ..columnData = columnData
    ..banners = banners
    ..refreshController = refreshController;
}
`

**Comment by zjuwjf** [comment]
GlobalStore 是如何更新PageStore状态的？

**Comment by xfmaster** [comment]
`final AbstractRoutes routes = PageRoutes(
  pages: <String, Page<Object, dynamic>>{
    /// 主页面
    'main': MainPage(),
    'home': HomePage(),
    'index': IndexPage(),
    'labs': LabsPage(),
    'webview': WebPage(),
    'menu': MenuPage(),
  },
  visitor: (String path, Page<Object, dynamic> page) {
    /// 只有特定的范围的 Page 才需要建立和 AppStore 的连接关系
    /// 满足 Page<T> ，T 是 GlobalBaseState 的子类
    if (page.isTypeof<GlobalBaseState>()) {
      page.connectExtraStore<GlobalState>(GlobalStore.store,
          // ignore: missing_return
          (Object pageState, GlobalState appState) {
        final GlobalBaseState p = pageState;
        if (p.appTheme != null && p.appTheme.dark == appState.appTheme.dark) {
          return pageState;
        } else {
          if (pageState is Cloneable) {
            final Object copy = pageState.clone();
            final GlobalBaseState newState = copy;
            newState.appTheme = appState.appTheme;
            return newState;
          }
        }
      });
    }

    /// AOP
    /// 页面可以有一些私有的 AOP 的增强， 但往往会有一些 AOP 是整个应用下，所有页面都会有的。
    /// 这些公共的通用 AOP ，通过遍历路由页面的形式统一加入。
    page.enhancer.append(
      /// View AOP
      viewMiddleware: <ViewMiddleware<dynamic>>[
        safetyView<dynamic>(),
      ],

      /// Adapter AOP
      adapterMiddleware: <AdapterMiddleware<dynamic>>[safetyAdapter<dynamic>()],

      /// Effect AOP
      effectMiddleware: <EffectMiddleware<dynamic>>[],

      /// Store AOP
      middleware: <Middleware<dynamic>>[
        logMiddleware<dynamic>(tag: page.runtimeType.toString()),
      ],
    );
  },
);
`

**Comment by zjuwjf** [comment]
参考下 reselect 。

如果子状态不是父级状态的一个字段的情况下。

你的case下，数据流不是很合理，特别的是ItemState 和 IndexState之间的关系。

**Comment by xfmaster** [comment]
好的，谢谢，不合理这里怎么说了

**Comment by zjuwjf** [comment]
> 好的，谢谢，不合理这里怎么说了

一个状态多次重复表达：indexstate. appTheme 和 itemstate. appTheme 是同一个状态。

**Comment by xfmaster** [comment]
当前显示的列表数据没有更新，滑出屏幕后再回来就更新了

**Comment by xfmaster** [comment]
> > 好的，谢谢，不合理这里怎么说了
> 
> 一个状态多次重复表达：indexstate. appTheme 和 itemstate. appTheme 是同一个状态。

那要怎么使用indexstate中的状态呢

**Comment by xfmaster** [comment]
adapter应该是有缓存吧，看了当前显示的item buildview并没有刷新

**Comment by zjuwjf** [comment]
> 那要怎么使用indexstate中的状态呢

建议看下reselect，能解决你的问题

**Comment by xfmaster** [comment]
好的 谢谢
