### ISSUE TITLE
自身的EXAMPLE切换主题色都有问题，文档也不清晰，能不能解决了

### ISSUE THREAD

**Issue by 134355** [alibaba/fish-redux#520]
**Describe the bug**
Show the code you wrote as completely as possible.
```dart
/// your code here
``` 
![image](https://user-images.githubusercontent.com/38032758/68559421-f1a58f80-0477-11ea-9727-f661f3cdb1b9.png)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
1. The version of fish-redux which you are using.
2. The information from flutter doctor.

**Comment by zjuwjf** [comment]
如果问题不能描述清楚，后面会很难有效沟通 -  -

**Comment by zjuwjf** [comment]
你可以随时reopen这个issue，如果有需要的话。
