### ISSUE TITLE
淘宝这种global底部tab导航，上面view适合做成page还是component？

### ISSUE THREAD

**Issue by CoolBerry** [alibaba/fish-redux#521]
做成page的话，逻辑上更好一点，因为数据相对独立，某些数据需要共享的话就做成global store。
我现在的方案是view里面切换之后直接buildPage。但是不能KeepAlive（或许可以，但我没成功）。

做成component的话，那就数据都集中在一起管理了。体验比较差。但应该可以keepalive。

希望可以在example中添加一个底部导航的范例，实现keepAlive。

**Comment by zjuwjf** [comment]
1、建议是Page方式，独立灵活。
2、KeepAlive 参考 #272， 理论上Page也是一个Component。

如果2有具体的无法KeepAlive的问题，欢迎给下代码或者demo。

**Comment by CoolBerry** [comment]
@zjuwjf 嗯嗯，谢谢，可能哪里用得不对。

简述一下场景就是HomePage里面切换bottomNavigationBar， 然后上面是不同的pages。然后每一个page是 AppRoute.global.buildPage（routeName，args）的写法。

具体的举一个page的例子，其他都一样：

class MePage extends Page<MeState, Map<String, dynamic>> {
  MePage()
      : super(
            initState: initState,
            effect: buildEffect(),
            reducer: buildReducer(),
            wrapper: keepAliveWrapper,
            view: buildView,
            dependencies: Dependencies<MeState>(
                adapter: null,
                slots: <String, Dependent<MeState>>{
                }),
            middleware: <Middleware<MeState>>[
            ],);
}

然后wrapper就是 [#272](https://github.com/alibaba/fish-redux/issues/272)里面的用法
class KeepAliveWidget extends StatefulWidget {
  final Widget child;

  const KeepAliveWidget(this.child);

  @override
  State<StatefulWidget> createState() => _KeepAliveState();
}

class _KeepAliveState extends State<KeepAliveWidget>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    print(widget.child);
    super.build(context);
    return widget.child;
  }
}

Widget keepAliveWrapper(Widget child) => KeepAliveWidget(child);

以上这样似乎不work。每次切换tab之后，pages都会重新走initState生命周期。

**Comment by CoolBerry** [comment]
然后尝试了 fish redux里面引入的KeepAliveMixin ，就直接在class 后面 with KeepAliveMixin，也不work。

**Comment by zjuwjf** [comment]
可以给一个最小化的可运行的demo么？

**Comment by CoolBerry** [comment]
> 可以给一个最小化的可运行的demo么？

添加了一个[repos](https://github.com/CoolBerry/Fish_Redux_Global_Tab)

基本上是在example基础上加了一个简单的global 切换

**Comment by zjuwjf** [comment]
@CoolBerry 看了你的代码，和fish-redux本身无关。

参考这里，https://stackoverflow.com/questions/53011686/flutter-automatickeepaliveclientmixin-is-not-working-with-bottomnavigationbar

**Comment by CoolBerry** [comment]
谢谢，已经解决

**Comment by hbshun** [comment]
@CoolBerry 请问一下是怎么实现的 谢谢

**Comment by CoolBerry** [comment]
> @CoolBerry 请问一下是怎么实现的 谢谢

就是前面提到的[https://stackoverflow.com/questions/53011686/flutter-automatickeepaliveclientmixin-is-not-working-with-bottomnavigationbar](https://stackoverflow.com/questions/53011686/flutter-automatickeepaliveclientmixin-is-not-working-with-bottomnavigationbar)里面说的，用pageView或者stack的方法都是可以的

**Comment by hbshun** [comment]
> > @CoolBerry 请问一下是怎么实现的 谢谢
> 
> 就是前面提到的https://stackoverflow.com/questions/53011686/flutter-automatickeepaliveclientmixin-is-not-working-with-bottomnavigationbar里面说的，用pageView或者stack的方法都是可以的

谢谢
