### ISSUE TITLE
如何和页面保活  AutomaticKeepAliveClientMixin使用

### ISSUE THREAD

**Issue by 134355** [alibaba/fish-redux#522]
**Describe the bug**
Show the code you wrote as completely as possible.
```dart
/// your code here
``` 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
1. The version of fish-redux which you are using.
2. The information from flutter doctor.

**Comment by 134355** [comment]
使用其他方式进行保活的时候，发现不能和原生提供的一些方法进行融合使用，
大佬能提供示例吗

**Comment by zjuwjf** [comment]
参考  #272

**Comment by 134355** [comment]
感谢大佬
