### ISSUE TITLE
reselect怎么使用能否在官方例子中使用出来学习一下

### ISSUE THREAD

**Issue by qq329401134** [alibaba/fish-redux#525]
请问下这个怎么用啊特别 factors 这个方法不知道咋整 @zjuwjf

**Comment by zjuwjf** [comment]
参考上面的提交。

在reselect中factors，代表你关心的要素集。

以example为例，上方的report信息，关心todo-list这个集合，只有这个集合内的任意一个要素发生了变化，reselect才会重新触发计算。

**Comment by qq329401134** [comment]
额  你那个是看懂了，但是像我这种例子该怎么写呢，我只写了一部分不知道问号的部分怎么填
我在这个一面有个计时器组件，页面传timer和second过去，请问下这种情况factors怎么写呢

class PageState extends MutableSource
    implements GlobalBaseState, Cloneable<PageState> {
  Timer timer;
  int second;

}

class CountConnector extends ConnOp<PageState, CountState>
    with ReselectMixin<PageState, CountState> {
  @override
  CountState computed(PageState state) {
    return ReportState()
      ..timer = state.timer
      ..second = state.second;
  }

  @override
  List<dynamic> factors(PageState state) {
    /// ????
    return ;
  }

  @override
  void set(PageState state, CountState subState) {
    throw Exception('Unexcepted to set PageState from ReportState');
  }
}

**Comment by zjuwjf** [comment]
```dart
  @override
  List<dynamic> factors(PageState state) {
    return <dynamic>[state.timer, state.second];
  }
```

表示，只有当state.timer 或 state.second 发生变化时，才会重新计算。

**Comment by qq329401134** [comment]
那么按照这个道理，就是把关注的元素放到一个数组里面返回，那么官方的例子我写成
  @override
  List<dynamic> factors(PageState state) {
    return <dynamic>[state.toDos];
  }
这样以后state.toDos发生变化，不会重新计算，这是咋情况

**Comment by zjuwjf** [comment]
> 那么按照这个道理，就是把关注的元素放到一个数组里面返回，那么官方的例子我写成
> @override
> List factors(PageState state) {
> return [state.toDos];
> }
> 这样以后state.toDos发生变化，不会重新计算，这是咋情况

因为在示例中，更新具体某一项todo，toDos 没有被拷贝，前后都是同一个引用对象。

写成下面会更加容易理解

```dart
  @override
  List<dynamic> factors(PageState state) {
    return <int>[state.toDos.where((ToDoState tds) => tds.isDone).length, state.toDos.length];
  }
```

**Comment by qq329401134** [comment]
了解了   谢谢

**Comment by qq329401134** [comment]
你们的技术支持做的真好哈哈哈 ，非常感谢你们的帮助

**Comment by limeng-uuuqwr** [comment]
> > 那么按照这个道理，就是把关注的元素放到一个数组里面返回，那么官方的例子我写成
> > @override
> > List factors(PageState state) {
> > return [state.toDos];
> > }
> > 这样以后state.toDos发生变化，不会重新计算，这是咋情况
> 
> 因为在示例中，更新具体某一项todo，toDos 没有被拷贝，前后都是同一个引用对象。
> 
> 写成下面会更加容易理解
> 
> ```dart
>   @override
>   List<dynamic> factors(PageState state) {
>     return <int>[state.toDos.where((ToDoState tds) => tds.isDone).length, state.toDos.length];
>   }
> ```
> 
> 但是如果，理解其中的变化，下面是性能最佳的一个特例。
> 
> ```dart
>   @override
>   List<dynamic> factors(PageState state) {
>     return state.toDos;
>   }
> ```

下面的这种写法也是对的吧？@zjuwjf
ReportState computed(PageState state) {
    return ReportState()
      ..done = factors(state)[0]
      ..total = factors(state)[1];
  }

  @override
  List<dynamic> factors(PageState state) {
    return <int>[
      state.toDos.where((ToDoState tds) => tds.isDone).length,
      state.toDos.length
    ];
  }

**Comment by zjuwjf** [comment]
会降低性能 @limeng-uuuqwr
