### ISSUE TITLE
TabBarView中使用Adapter的若干问题

### ISSUE THREAD

**Issue by AngusPei** [alibaba/fish-redux#534]
**问题描述**
TabBarView是由对应的ListView构建而成，每个ListView中的Item实际上又由不同的component通过Abdapter动态构建，在使用过程中有如下问题：
- 当切换非连续的tab时，会报以下错误
type 'DiscoveryItemState' is not a subtype of type 'DesignItemState'
![image](https://user-images.githubusercontent.com/4378435/69300831-51a5ee00-0c4f-11ea-853a-118d7d4d2d6e.png)
- 已添加KeepAliveWidget来解决Listview来保持页面状态，但是无效，依然会BuildItem。

**数据结构**
``` dart
enum ItemType {
  none,
  design,
  recruit,
  discovery,
}

class ItemModel {
ItemType type = ItemType.none;
}
abstract class GlobalItem<T extends GlobalItem<T>> extends Cloneable<T> {
  ItemModel item;
}

class RecruitItemState implements GlobalItem<RecruitItemState> {
  ItemModel item = new ItemModel()..type = ItemType.recruit;
}

class DiscoveryItemState implements GlobalItem<DiscoveryItemState> {
  ItemModel item = new ItemModel()..type = ItemType.discovery;
}

class DesignItemState implements GlobalItem<DesignItemState> {
  ItemModel item = new ItemModel()..type = ItemType.design;
}

```

**Adapter代码**
```dart
class HomeListItemAdapter extends DynamicFlowAdapter<HomeState> {
  HomeListItemAdapter()
      : super(
          pool: <String, Component<Object>>{
            'DiscoveryItem': DiscoveryItemComponent(),
            'RecruitItem': RecruitItemComponent(),
            'DesignItem': DesignItemComponent(),
          },
          connector: _HomeListItemConnector(),
        );
}

class _HomeListItemConnector extends ConnOp<HomeState, List<ItemBean>> {
  @override
  List<ItemBean> get(HomeState state) {
    // List<List<Object>> tabList;   // Object是GlobalItem的子类
    // Map<int, String> tabs; // tabs会动态从服务器中获取，其中Key决定了tabList对应要获取的内容
    if (state.tabs?.isNotEmpty == true && state.tabList?.isNotEmpty == true) {
      return state.tabList[state.currentIndex].map<ItemBean>((itemState) {
        println(itemState.toString());
        String itemType;
        // 根据state中存储的的type类型动态生成Componet
        switch ((itemState as GlobalItem).item.type) {
          case ItemType.design:
            itemType = 'DesignItem';
            break;
          case ItemType.recruit:
            itemType = 'RecruitItem';
            break;
          case ItemType.discovery:
            itemType = 'DiscoveryItem';
            break;
          default:
            itemType = 'DesignItem';
            break;
        }
        if (itemType.isNotEmpty) {
          return ItemBean(itemType, itemState);
        } else {
          return null;
        }
      }).toList();
    } else {
      return <ItemBean>[];
    }
  }
}
``` 

**View使用**
``` dart
Widget buildView(HomeState state, Dispatch dispatch, ViewService viewService) {
  final adapter = viewService.buildAdapter();
  println("适配器的数量：${adapter.itemCount}");
  return Scaffold(
//    resizeToAvoidBottomPadding: false,
    backgroundColor: Color(0xFFF5F5F5),
    body: Container(
      height: 1000,
      child: CustomScrollView(
        controller: state.customScrollViewController,
        slivers: <Widget>[
          _buildSliverAppBar(state, viewService),
          SliverList(
            delegate: SliverChildListDelegate(
              [
                _buildMyApplication(),
                Container(
                  padding: EdgeInsets.only(
                      top: 15, left: _leftAndRight, right: _leftAndRight),
                  child: viewService.buildComponent('middleBanner'),
                ),
                _buildHotTopic(state),
                Container(
                  padding: EdgeInsets.only(top: 32),
                  child: state.tabController == null
                      ? LoadingView()
                      : _buildTabBar(
                          state,
                          dispatch,
                          viewService.context,
                        ),
                ),
              ],
            ),
          ),
          SliverFillRemaining(
            child: Container(
              child: state.tabController == null
                  ? LoadingView()
                  : TabBarView(
                      // physics: NeverScrollableScrollPhysics(), // 禁滑动事件
                      controller: state.tabController,
                      // *******异常*********
                      children: state.tabs.keys.map((v) {
                        return KeepAliveWidget(
                          Container(
                            child: ListView.builder(
//                          controller: ,TODO: 用于控制列表被拉上去了，禁止滑动事件
                              itemBuilder: adapter.itemBuilder,
                              itemCount: adapter.itemCount,
                            ),
                          ),
                        );
                      }).toList(),
                    ),
            ),
          )
        ],
      ),
    ),
  );
}
```

**期望**
1. TabbarView中的每个ListView中展现的Item可以不一样
2. 每个ListView中可以有不同Item
3. 能正确保持页面状态，能正确切换

**Comment by AngusPei** [comment]
![image](https://user-images.githubusercontent.com/4378435/69303718-fbd64380-0c58-11ea-8fe2-737929dad45c.png)

**Comment by AngusPei** [comment]
![image](https://user-images.githubusercontent.com/4378435/69303783-39d36780-0c59-11ea-9da3-1d5dcbb68f7b.png)

**Comment by AngusPei** [comment]
**buildEffect====> Lifecycle.initState: _onInitAction 中初始化tabController **
![image](https://user-images.githubusercontent.com/4378435/69303859-7d2dd600-0c59-11ea-81f4-3dcb3a775536.png)

**Comment by AngusPei** [comment]
@danieldai @danieldai @Yacumima @christyuj 
各位大牛们，能否指导一下？😊

**Comment by AngusPei** [comment]
经过我的测试，我发现不使用ListView.builder 来动态构建Item则能正确Keep Alive Widget，而如果使用ListView.builder则不能正确显示

**Comment by AngusPei** [comment]
KeepAliveWidget 失效的原因是adapter.itemCount 数据传入的总是为当前ListView的总数导致
![image](https://user-images.githubusercontent.com/4378435/69324983-681a6c80-0c84-11ea-9ce5-2e1c6089b0c4.png)

**Comment by AngusPei** [comment]
**当切换非连续的tab时，会报以下错误**
type 'DiscoveryItemState' is not a subtype of type 'DesignItemState'

这个问题也找到原因了，调用itemBuilder: adapter.itemBuilder,  实际依然会调用了四次（有4个tab），由于我在Adapter中get数据时的判断依据是当前tabbar点击的index，倒是每个页面数量不对、并且返回的ItemType也不对，所以才会有异常。

![image](https://user-images.githubusercontent.com/4378435/69327259-2db2ce80-0c88-11ea-8c2d-33cc62457746.png)

我很好奇，难道适配器不能用在tabbarView中？当前tabbar切换就算是KeepAliveWidget加持也会调用itemBuilder: adapter.itemBuilder, 那么我如何去区分每次应该返回的ItemBean呢？

求解

**Comment by AngusPei** [comment]
我打算将ListView放在Componet中，结果发现Componet并能传参数，导致一组数据没法通过get componentState 来进行区分。那么我真的只能采用BuildPage来传入参数一个参数。然后用它来想sever请求List数据。好吧 我没问题了

**Comment by zjuwjf** [comment]
多个Component（每一个Component包含一个Adapter）这样的模式不可以么？

**Comment by AngusPei** [comment]
首先非常感谢大神抽空回复，如果使用“多个Component（每一个Component包含一个Adapter）”是可以实现的。但是我希望能有一种更加简便的方法：
使用一个Component来实现各ListView中的列表内容，给Component传入一个参数，通过该参数去服务端拉取列表数据，而每一项数据都有一个标志，标志自己应该采用的是什么类型的Item Component。

如果采用多个List Component，那么有多少个ListView就要用多少个Component 代码复用性不高。

**Comment by zjuwjf** [comment]
```dart
class PageState implements MutableSource {
    List<FragmentState> fragments;
   
   @override
   int get itemCount => fragments.length;

  @override
  String getItemType(int index) => '/// TODO';

  @override
  void setItemData(int index, Object data) => fragments[i] = data;
}

class FragmentState {
   List<ItemState> items;

   @override
   int get itemCount => items.length;

  @override
  String getItemType(int index) => '/// TODO';

  @override
  void setItemData(int index, Object data) => items[i] = data;
}

class ItemState {
}
```

一个Page 包含一个PageSourceAdater，产生一组Fragment；
一个Fragment包含一个FragmentSourceAdater，产生一组ItemComponent；

**Comment by AngusPei** [comment]
> ```dart
> class PageState implements MutableSource {
>     List<FragmentState> fragments;
>    
>    @override
>    int get itemCount => fragments.length;
> 
>   @override
>   String getItemType(int index) => '/// TODO';
> 
>   @override
>   void setItemData(int index, Object data) => fragments[i] = data;
> }
> 
> class FragmentState implements MutableSource  {
>    List<ItemState> items;
> 
>    @override
>    int get itemCount => items.length;
> 
>   @override
>   String getItemType(int index) => '/// TODO';
> 
>   @override
>   void setItemData(int index, Object data) => items[i] = data;
> }
> 
> class ItemState {
> }
> ```
> 
> 一个Page 包含一个PageSourceAdapter，产生一组Fragment；
> 一个Fragment包含一个FragmentSourceAdapter，产生一组ItemComponent；

我想请教一下，如何在TabBarView中触发PageSourceAdapter？

**Comment by AngusPei** [comment]
```dart
TabBarView(
  controller: state.tabController,
  children: List<Widget>(adapter.itemCount)
      .asMap()
      .keys
      .map((k) {
    return adapter.itemBuilder(viewService.context, k);
  }).toList()),
```

**Comment by daigewuwy** [comment]
楼主，请问你的问题解决了嘛，我现在遇到一样的问题

**Comment by AngusPei** [comment]
> 楼主，请问你的问题解决了嘛，我现在遇到一样的问题

通过使用MutableSource已解决

**Comment by KevinBluce** [comment]
楼主能提供一个demo 么 我也遇到了同样的问题

**Comment by Muzm** [comment]
@KevinBluce https://github.com/Muzm/Felt/blob/master/fish-redux-relate.md#2-fish-redux-%E4%B8%AD%E4%BD%BF%E7%94%A8-mutablesource-adapter-%E5%A4%9A%E6%BA%90%E9%80%82%E9%85%8D%E5%99%A8
