### ISSUE TITLE
pushNamedAndRemoveUntil

### ISSUE THREAD

**Issue by XingXiaoWu** [alibaba/fish-redux#536]
使用pushNamedAndRemoveUntil回退到路由栈中的历史页面，历史页面的状态被重置了，不知道是否是我的用法有问题
截图如下
main.dart
![image](https://user-images.githubusercontent.com/22769131/69480339-ac9f3700-0e41-11ea-9fa6-35650aca3739.png)
![image](https://user-images.githubusercontent.com/22769131/69480346-b2951800-0e41-11ea-9a1a-4497041afbd0.png)
![image](https://user-images.githubusercontent.com/22769131/69480350-b6c13580-0e41-11ea-9210-8917be08845b.png)

回退使用
![image](https://user-images.githubusercontent.com/22769131/69480374-d5bfc780-0e41-11ea-9441-89cb873775e9.png)

**Comment by XingXiaoWu** [comment]
页面已经使用keepalive保持了状态

**Comment by zjuwjf** [comment]
fish-redux 本身并没有做实际路由相关的工作，建议参考其他开源路由框架，结合使用。

**Comment by zjuwjf** [comment]
具体上面的问题，可以参考pushNamedAndRemoveUntil api文档， 它依赖于静态注册。

**Comment by XingXiaoWu** [comment]
不好意思，回复较晚。
我明白您的意思，fish_redux并未做任何路由有关的内容。
但是页面注册是通过AbstractRoutes注入的，与官方的原始写法或者别的路由框架不同，因此才有此一问。
![image](https://user-images.githubusercontent.com/22769131/69803928-674f8080-1218-11ea-97e5-4ee04b98bb24.png)
非常感谢您的回答
