### ISSUE TITLE
fish-redux升级到0.3.1，子组件发送父组件的action无法触发父组件reducer，但能触发父组件effect

### ISSUE THREAD

**Issue by Mar-er** [alibaba/fish-redux#538]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

fish-redux: 0.3.1

fish-redux升级到0.3.1之后，子组件不能通过发送父组件的action调用父组件的reducer，但可以调用父组件的effect

**Comment by zjuwjf** [comment]
麻烦提供下最小化的demo。

**Comment by Javamr123** [comment]
解决了吗？大佬，解决了的话，麻烦说下啥原因，我也遇到了

**Comment by zjuwjf** [comment]
> 解决了吗？大佬，解决了的话，麻烦说下啥原因，我也遇到了

基本不是框架的问题。 如果有类似问题，欢迎提供最小化demo。

**Comment by chenxianqi** [comment]
[0.3.1]
rename AdapterSource’s api
add PureViewComponent
deprecate broadcastEffect

是不是弃用了广播，导致这个问题呢？0.3.1在子组件确实无法触发父组件的reducer去更新page state

**Comment by chenxianqi** [comment]
https://github.com/alibaba/fish-redux/commit/f87f28157948aebb2116a7a8ac5b4ade2088230d

**Comment by suo801** [comment]
还没解决吗？

**Comment by cnting** [comment]
遇到同样问题，debug的时候发现dispatch(TestActionCreator.didTest())时候调用的是DispatchBusDefault.dispatch()方法，而不是LogicContext.dispatch()

**Comment by cnting** [comment]
> 遇到同样问题，debug的时候发现dispatch(TestActionCreator.didTest())时候调用的是DispatchBusDefault.dispatch()方法，而不是LogicContext.dispatch()

找到原因，component里没有设置effect、reducer、dependencies，满足了下面条件，
`
bool isPureView() {
    return protectedReducer == null &&
        protectedEffect == null &&
        protectedDependencies == null;
  }
`
就会直接用DispatchBusDefault.dispatch()，这里的dispatch只会找effect里的action

不懂为什么这么处理，是不提倡子组件直接调用父组件的reducer吗。正确做法是不是应该子组件改变子state，然后通过ConnOp更新到父state?

**Comment by DDDrop** [comment]
> 正确做法是不是应该子组件改变子state，然后通过ConnOp更新到父state

我觉得是这样的。子模块调用父模块的的 reducer 就起不到解耦的作用了。

**Comment by zjuwjf** [comment]
非常感谢 @chenxianqi @cnting 的精准反馈，看上去是bug。

会计划尽快修复发布。

fish-redux的dispatch 的功能包含三部分，两阶段
第一阶段：
1、连接 组件内的View和Effect（优先消费）
第二阶段
2、更新状态 （发送给所有的Reducer）
3、事件总线 （发送给其他组件的Effect）

这个原则一直是稳定的。
