### ISSUE TITLE
redux太过于繁琐臃肿，能否再简化？

### ISSUE THREAD

**Issue by sessionboy** [alibaba/fish-redux#539]
我不知道是什么原因非得按redux的思想来构建这个状态库，但我认为redux太过于繁琐和臃肿，加重开发和维护的难度，现阶段redux有些过时了。
能否再进行简化呢？ 最好可以结合flutter_hooks。
可以参考[react-model](https://github.com/byte-fe/react-model)，这个基于react hooks的原生状态库，非常的简洁，拥有redux所有的功能，且易于拆分。这是我觉得比较理想的状态库之一。

**Comment by leeewh** [comment]
我觉得mobx是比较理想的状态库

**Comment by zjuwjf** [comment]
个人体会：
状态管理本质上是通过增加一层状态层，来达到彻底解耦视图的目的。
这里的三个关键点：
1、如何定义状态层
2、状态层的变化如何同步到视图层
3、如果操作状态层

不同的状态库，在上面的基础上，还带有一些各自的特色的优点/缺点。

同时具体的实现手段，往往和语言特性有关（比如mobx）。

相比而言，Redux是一种通用，易扩展的架构，和语言特性无关。

臃肿和简化，一定程度上和“封装”以及”语法糖“相关。
