### ISSUE TITLE
inheritFromWidgetOfExactType可否用ancestorInheritedElementForWidgetOfExactType替换

### ISSUE THREAD

**Issue by bluepine0808** [alibaba/fish-redux#54]
我这个文章https://medium.com/flutter-community/reactive-programming-streams-bloc-6f0d2bd2d248 里看到这个优化点，想咨询下，是否可以替换呢？

**Comment by zjuwjf** [comment]
这类问题可以去 [flutter](https://github.com/flutter/flutter) 咨询。  如果仅仅从遍历的效率而言，ancestorInheritedElementForWidgetOfExactType更有优势。
