### ISSUE TITLE
doc/concept/evolution-of-fish-redux.md 文档错误

### ISSUE THREAD

**Issue by zhongwencm** [alibaba/fish-redux#55]
> 2. 将"留言"这个"Big-Cell"
    -   4.2 解决逻辑的独立性
        > 以闲鱼的详情业务场景为例，其中有两个"Big-Cell":留言和推荐。如果我们将留言和推荐以 Component 形态来组装，就会使得留言和推荐成为两个非常巨大的 Widget，极大的影响了页面的 FPS。
    -   4.3
        > 以闲鱼的详情业务场景为例，其中有两个"Big-Cell":留言和推荐。如果我们将留言和推荐以 Component 形态来组装，就会使得留言和推荐成为两个非常巨大的 Widget，极大的影响了页面的 FPS。

4.2 和 4.3 重复了.
4.1.2 内容缺失

**Comment by zjuwjf** [comment]
thanks for reminding, will be fixed soon.
