### ISSUE TITLE
请问一下我听别人说在页面返回的时候上一个页面会build一次，但是貌似用redux貌似就不会build

### ISSUE THREAD

**Issue by luckysmg** [alibaba/fish-redux#559]
我现在恰恰需要他build一次，因为build里面我写了状态栏颜色的变化方法，如果不build的话就还是返回页面之前的那个状态栏的颜色，有没有什么方法能够让他自动build一次捏？

**Comment by adigest** [comment]
【捂脸】
不是没build，是build了多次，二级页面的build把它又覆盖了
