### ISSUE TITLE
请教一下，如何实现一个listview中item选中效果，adapter接入成功，数据也绑定了，现在遇到的问题是，在点击item的component时不知道怎么去通知page该切换选中状态。

### ISSUE THREAD

**Issue by xiongjianchang** [alibaba/fish-redux#573]
请教一下，如何实现一个listview中item选中效果，adapter接入成功，数据也绑定了，现在遇到的问题是，在点击item的component时不知道怎么去通知page该刷新和切换选中状态。
我还没学习透子组件怎么和父组件通讯，目前知道可以用Connector对依赖数据进行捆绑，但不知道有没有存粹一点的父子组件之间的事件通知方法。
我在子组件effect代码中dispatch父组件的action，但父组件的effect或reducer并没有收到通知。

**Comment by doubleSkinMilk** [comment]
我在子组件effect代码中dispatch父组件的action，但父组件的effect或reducer并没有收到通知。
-------
这个不应该吧.
