### ISSUE TITLE
tabcontroller

### ISSUE THREAD

**Issue by PandaCVBRO** [alibaba/fish-redux#58]
如何在 fish redux 中使用 tabcontroller？ with 放到哪里呢？

**Comment by zjuwjf** [comment]
Maybe 
[basic.dart](https://github.com/alibaba/fish-redux/blob/master/lib/src/redux_component/basic.dart) Context<T>.stfState
could help you.

**Comment by layou1989** [comment]
能给个具体的例子怎么使用吗，还有，什么时候会将这个特性放到pub上

**Comment by layou1989** [comment]
这个特性什么时候能放到pub上

**Comment by layou1989** [comment]
> Maybe
> [basic.dart](https://github.com/alibaba/fish-redux/blob/master/lib/src/redux_component/basic.dart) Context.stfState
> could help you.
> 
> In Context:
> 
> ```
> /// In general, we should not need this field.
>   /// When we have to use this field, it means that we have encountered difficulties.
>   /// This is a contradiction between presentation & logical separation, and Flutter's Widgets system.
>   ///
>   /// How to use ?
>   /// For example, we want to use SingleTickerProviderStateMixin
>   /// We should
>   /// 1. Define a new ComponentState
>   ///    class CustomStfState extends ComponentState<T> with SingleTickerProviderStateMixin {}
>   /// 2. Override the createState method of the Component with the newly defined CustomStfState.
>   ///    @override
>   ///    CustomStfState createState() => CustomStfState();
>   /// 3. Get the CustomStfState via context.stfState in Effect.
>   ///    AnimationController controller = AnimationController(vsync: context.stfState);
>   ///    context.dispatch(ActionCreator.createController(controller));
>   State get stfState;
> ```
这个特性什么时候能放到pub上

**Comment by layou1989** [comment]
@zjuwjf 这个特性什么时候能放到pub上

**Comment by zjuwjf** [comment]
0.1.2 has been published, which includes the getter of stfState feature.

**Comment by layou1989** [comment]
@zjuwjf 
![image](https://user-images.githubusercontent.com/7498703/54411274-bb1d4680-4729-11e9-93de-bb0f059631b7.png)
我照着例子写这边报错，是什么原因呢

**Comment by zjuwjf** [comment]
> @zjuwjf
> ![image](https://user-images.githubusercontent.com/7498703/54411274-bb1d4680-4729-11e9-93de-bb0f059631b7.png)
> 我照着例子写这边报错，是什么原因呢

```
final TickerProvider tickerProvider = ctx.stfState;
...
```

**Comment by jkyeo** [comment]
Same here. (type can not be assigned to ...)
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/4645158/54473303-cd25e480-4810-11e9-847a-1ffb14d5cf9f.png">

**Comment by jkyeo** [comment]
> Same here. (type can not be assigned to ...)
> <img alt="image" width="1438" src="https://user-images.githubusercontent.com/4645158/54473303-cd25e480-4810-11e9-847a-1ffb14d5cf9f.png">


it worked as:  final TickerProvider tickerProvider = ctx.stfState as CustomStfState;

**Comment by Aries233** [comment]
`
// state.dart
class IndexState extends StatefulWidget implements Cloneable<IndexState> {
  Orders orders;

  @override
  IndexState clone() {
    return IndexState()..orders = orders;
  }

  @override
  _IndexStateState createState() => _IndexStateState();
}

class _IndexStateState extends State<IndexState>
    with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
`
// effect.dart
![image](https://user-images.githubusercontent.com/23191466/54473682-f432e500-4815-11e9-8799-0fd402f1a8c5.png)
ctx.stfState 返回的类型，不是tickerProvider，而是state

**Comment by zjuwjf** [comment]
参考说明应该是这样

component.dart
```
class _IndexComponentState extends ComponentState<IndexState> with SingleTickerProviderStateMixin {}

class IndexComponent extends Component<class Index> {
	
	@override
  	_IndexComponentState createState() => _IndexComponentState();
}


```


Effect.dart
```dart
final TickerProvider tickerProvider = ctx.stfState;
```

**Comment by qq329401134** [comment]
按照如上方式做了tabcontroller 想要添加keepalive功能应该如何配置呢，我这样配置了以后会报错
> ![image](https://user-images.githubusercontent.com/38587734/54485300-1e85b080-48b1-11e9-8a78-48f3cc6f2cb5.png)
> 
> ![image](https://user-images.githubusercontent.com/38587734/54485318-54c33000-48b1-11e9-9f38-a62cbacb9773.png)

**Comment by zjuwjf** [comment]
如何可以， 把上下文的代码都贴下。

**Comment by qq329401134** [comment]
page的state
![image](https://user-images.githubusercontent.com/38587734/54486014-4d098880-48bd-11e9-8554-d391893d10ad.png)
with SingleTickerProviderStateMixin的新state
![image](https://user-images.githubusercontent.com/38587734/54486020-55fa5a00-48bd-11e9-8f21-beb2e69b7226.png)
page
![image](https://user-images.githubusercontent.com/38587734/54486058-af628900-48bd-11e9-8b2a-a7d9370f2dee.png)

effect
![image](https://user-images.githubusercontent.com/38587734/54486036-74605580-48bd-11e9-9b6c-9fe105ba10c7.png)
view
![image](https://user-images.githubusercontent.com/38587734/54486040-85a96200-48bd-11e9-966a-81f14d57e9fc.png)
这样操作以后tabcontroller可以正常使用，然后我想加keepalive功能
于是将新state改为如下
![image](https://user-images.githubusercontent.com/38587734/54486071-e0db5480-48bd-11e9-9173-d453b9617550.png)
运行后报错
![image](https://user-images.githubusercontent.com/38587734/54486073-e8026280-48bd-11e9-9bc3-3614483ef4d2.png)

**Comment by jkyeo** [comment]
> page的state
> ![image](https://user-images.githubusercontent.com/38587734/54486014-4d098880-48bd-11e9-8554-d391893d10ad.png)
> with SingleTickerProviderStateMixin的新state
> ![image](https://user-images.githubusercontent.com/38587734/54486020-55fa5a00-48bd-11e9-8f21-beb2e69b7226.png)
> page
> ![image](https://user-images.githubusercontent.com/38587734/54486058-af628900-48bd-11e9-8b2a-a7d9370f2dee.png)
> 
> effect
> ![image](https://user-images.githubusercontent.com/38587734/54486036-74605580-48bd-11e9-9b6c-9fe105ba10c7.png)
> view
> ![image](https://user-images.githubusercontent.com/38587734/54486040-85a96200-48bd-11e9-966a-81f14d57e9fc.png)
> 这样操作以后tabcontroller可以正常使用，然后我想加keepalive功能
> 于是将新state改为如下
> ![image](https://user-images.githubusercontent.com/38587734/54486071-e0db5480-48bd-11e9-9173-d453b9617550.png)
> 运行后报错
> ![image](https://user-images.githubusercontent.com/38587734/54486073-e8026280-48bd-11e9-9bc3-3614483ef4d2.png)
> 
> @zjuwjf

What’s the lifecycle that calling _init function in effect? If it is Lifecycle.build my case the problem above.

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54498802-73273b00-4946-11e9-9c77-42f6aafc9761.png)
My problem is that once I add AutomaticKeepAliveClientMixin in newstate, the program doesn't work properly.
![image](https://user-images.githubusercontent.com/38587734/54498836-c5685c00-4946-11e9-8ca4-c5fb9d361132.png)

**Comment by zjuwjf** [comment]
嗯，看了下 是 AutomaticKeepAliveClientMixin 内部实现的问题， 它覆盖了ComponentState的build方法，导致返回了null。  你可以通过在page上添加一个wraper(widget => widget) 可以达到你的需求。

**Comment by qq329401134** [comment]
> 嗯，看了下 是 AutomaticKeepAliveClientMixin 内部实现的问题， 它覆盖了ComponentState的build方法，导致返回了null。 你可以通过在page上添加一个wraper(widget => widget) 可以达到你的需求。

你这个操作在文档里面没有，有点看不懂，具体该怎么做啊？？ @zjuwjf

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54502889-d4abd180-4967-11e9-85a1-72912305c431.png)
![image](https://user-images.githubusercontent.com/38587734/54502891-d83f5880-4967-11e9-8343-36d278f63fae.png)
第二个图要怎么设置呢，文档没详细说...

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54503734-8a2c5400-496b-11e9-8ab3-dcf0c68fed60.png)
![image](https://user-images.githubusercontent.com/38587734/54503738-8dbfdb00-496b-11e9-98e1-024e098c2c73.png)
第二个图不会操作了，能不能指点下要如何配置，网上找不到相关配置 @zjuwjf

**Comment by zjuwjf** [comment]
```
class KeepAliveWidget extends StatefulWidget {
  final Widget child;

  const KeepAliveWidget(this.child);

  @override
  State<StatefulWidget> createState() => KeepAliveState();
}

class KeepAliveState extends State<KeepAliveWidget>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}

Widget keepAliveWrapper(Widget child) {
  return KeepAliveWidget(child);
}
```

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54504827-42f49200-4970-11e9-931e-14569d237bd2.png)
![image](https://user-images.githubusercontent.com/38587734/54504830-46881900-4970-11e9-9844-b0c362df5c36.png)
依然不会保持，咋办

**Comment by Aries233** [comment]
> ![image](https://user-images.githubusercontent.com/38587734/54503734-8a2c5400-496b-11e9-8ab3-dcf0c68fed60.png)
> ![image](https://user-images.githubusercontent.com/38587734/54503738-8dbfdb00-496b-11e9-98e1-024e098c2c73.png)
> 第二个图不会操作了，能不能指点下要如何配置，网上找不到相关配置 @zjuwjf

所以 楼主，后面实现AutomaticKeepAliveClientMixin效果了吗？我使用你们的方式，依旧没有实现

**Comment by zjuwjf** [comment]
看上去可能和fish-redux无关 https://github.com/flutter/flutter/issues/28345

**Comment by qq329401134** [comment]
> > ![image](https://user-images.githubusercontent.com/38587734/54503734-8a2c5400-496b-11e9-8ab3-dcf0c68fed60.png)
> > ![image](https://user-images.githubusercontent.com/38587734/54503738-8dbfdb00-496b-11e9-98e1-024e098c2c73.png)
> > 第二个图不会操作了，能不能指点下要如何配置，网上找不到相关配置 @zjuwjf
> 
> 所以 楼主，后面实现AutomaticKeepAliveClientMixin效果了吗？我使用你们的方式，依旧没有实现

其实可以的，创建一个dart内容如下
class KeepAliveWidget extends StatefulWidget {
  final Widget child;

  const KeepAliveWidget(this.child);

  @override
  State<StatefulWidget> createState() => KeepAliveState();
}

class KeepAliveState extends State<KeepAliveWidget>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}

Widget keepAliveWrapper(Widget child) {
  return KeepAliveWidget(child);
}
然后这样包裹，原理都一样，框架没问题
![image](https://user-images.githubusercontent.com/38587734/54704686-35a8f480-4b76-11e9-8722-065e3b711611.png)

**Comment by ywbpmf** [comment]
能把实现的demo开源吗？

**Comment by hzgotb** [comment]
#262

**Comment by marscj** [comment]
这个 注释还不如不写 一头雾水

**Comment by zjuwjf** [comment]
#385 在fish-redux中，直接提供这些mixin。

**Comment by XingXiaoWu** [comment]
> > > ![image](https://user-images.githubusercontent.com/38587734/54503734-8a2c5400-496b-11e9-8ab3-dcf0c68fed60.png)
> > > ![image](https://user-images.githubusercontent.com/38587734/54503738-8dbfdb00-496b-11e9-98e1-024e098c2c73.png)
> > > 第二个图不会操作了，能不能指点下要如何配置，网上找不到相关配置 @zjuwjf
> > 
> > 
> > 所以 楼主，后面实现AutomaticKeepAliveClientMixin效果了吗？我使用你们的方式，依旧没有实现
> 
> 其实可以的，创建一个dart内容如下
> class KeepAliveWidget extends StatefulWidget {
> final Widget child;
> 
> const KeepAliveWidget(this.child);
> 
> @override
> State createState() => KeepAliveState();
> }
> 
> class KeepAliveState extends State
> with AutomaticKeepAliveClientMixin {
> @override
> bool get wantKeepAlive => true;
> 
> @override
> Widget build(BuildContext context) {
> return widget.child;
> }
> }
> 
> Widget keepAliveWrapper(Widget child) {
> return KeepAliveWidget(child);
> }
> 然后这样包裹，原理都一样，框架没问题
> ![image](https://user-images.githubusercontent.com/38587734/54704686-35a8f480-4b76-11e9-8722-065e3b711611.png)

谢谢

**Comment by AngusPei** [comment]
我也遇到了类似的问题
#534
