### ISSUE TITLE
component里的action,通过dispatch调用reducer,走到了action了，但是reducer始终不执行，找了几天都没找到原因

### ISSUE THREAD

**Issue by Javamr123** [alibaba/fish-redux#585]
//action
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart' hide Action;

//TODO replace with your own action
enum SwiperviewAction { onGetImage, getImage, test }

class SwiperviewActionCreator {

  //获取轮播图
  static Action onGetImage() {
    return Action(SwiperviewAction.onGetImage);
  }

  //设置轮播图
  static Action getImage(List<Widget> imageList) {
    return Action(SwiperviewAction.getImage , payload: imageList);
  }

  static Action Test() {
    print("mmmmmmm");
    return Action(SwiperviewAction.test);
  }
}

//effect
 bool _onGetImage(Action action, Context<SwiperviewState> ctx) {
  List<Widget> imageList = List();
  imageList = [];
  imageList
    ..add(Image.network(
        'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1578028327456&di=1d013b42cd0f7196015364a43011617f&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20180730%2F0ef1ed519eee46bc8ac3da20a2d05f3c.jpeg'))
    ..add(Image.network(
        'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1578028996718&di=16622a2a4c6d7df9f34892f354ed22c0&imgtype=0&src=http%3A%2F%2F04imgmini.eastday.com%2Fmobile%2F20190319%2F20190319174327_b31bb81af38a934c2700887ff20d1a81_1.jpeg'))
    ..add(Image.network(
        'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1578028327456&di=1d013b42cd0f7196015364a43011617f&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20180730%2F0ef1ed519eee46bc8ac3da20a2d05f3c.jpeg'))
    ..add(Image.network(
        'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1578028996718&di=16622a2a4c6d7df9f34892f354ed22c0&imgtype=0&src=http%3A%2F%2F04imgmini.eastday.com%2Fmobile%2F20190319%2F20190319174327_b31bb81af38a934c2700887ff20d1a81_1.jpeg'));

  **ctx.dispatch(SwiperviewActionCreator.getImage(imageList));**
  return false;
}

//reducer
import 'package:fish_redux/fish_redux.dart';
import 'action.dart';
import 'state.dart';

Reducer<SwiperviewState> buildReducer() {
  return asReducer(
    <Object, Reducer<SwiperviewState>>{
      SwiperviewAction.getImage: _GetImage,
      SwiperviewAction.test: _test
    },
  );
}

SwiperviewState _GetImage(SwiperviewState state, Action action) {
  print('kkkkkk');
  print("${action.payload}");
  final SwiperviewState newState = state.clone()..imageList = action.payload;
  return newState;
}

最终是zzzzzzz打印了，但是kkkkk没打印，怎么回事？求解

**Comment by EaglesChen** [comment]
我觉得你可以先确认一下page.dart里面有没有buildReducer()

**Comment by Javamr123** [comment]
> 我觉得你可以先确认一下page.dart里面有没有buildReducer()

我这个是component, 不是page,在component。dart文件里也有buildReducer

**Comment by lwanghaol** [comment]
effect 中的action（getImage）不能和reducer中的是同一个（getImage）。effect收到action1后，dispatch新action2到reducer中去

**Comment by Javamr123** [comment]
> effect 中的action（getImage）不能和reducer中的是同一个（getImage）。effect收到action1后，dispatch新action2到reducer中去

不是一个哦，定义了两个不同的方法名，您仔细看

**Comment by niuxinhuai** [comment]
请问，最终这个问题是如何解决的？

**Comment by niuxinhuai** [comment]
> > effect 中的action（getImage）不能和reducer中的是同一个（getImage）。effect收到action1后，dispatch新action2到reducer中去
> 
> 不是一个哦，定义了两个不同的方法名，您仔细看

请问最终如何解决的？
