### ISSUE TITLE
page里面用了adapter，在component里面再用个adapter时候报类型错

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [alibaba/fish-redux#589]
利用fish_redux插件创建了orgloginstatus_page，里面利用 orgloginstatus_adapter循环展示了 orgstatus_component的内容（通过API接口获取的数据ListA，接口报文类型为JSON），

![image](https://user-images.githubusercontent.com/38042291/71979026-aaf5cb00-3257-11ea-9cfc-1181b273da59.png)

orgloginstatus_page/effect.dart
![image](https://user-images.githubusercontent.com/38042291/71979048-b9dc7d80-3257-11ea-92d1-0d2a59ba471c.png)

orgloginstatus_page/view.dart
![image](https://user-images.githubusercontent.com/38042291/71979057-c234b880-3257-11ea-8227-46bcb33907c8.png)

orgstatus_component是一个按钮， orgstatus_component/view.dart
![image](https://user-images.githubusercontent.com/38042291/71979078-cbbe2080-3257-11ea-8295-9298dc59f8f7.png)

效果如下：
![image](https://user-images.githubusercontent.com/38042291/71979092-d5478880-3257-11ea-96b6-649a80738115.png)

我想实现的是 当点击按钮的时候，showDailog 一个循环列表(tellerstatus_component的内容，这时在orgstatus_component下创建了tellerdialog_component)，

orgstatus_component/effect.dart
![image](https://user-images.githubusercontent.com/38042291/71979107-e2647780-3257-11ea-906a-7600c2d2cf73.png)

以下的操作就是需要操作tellerdailog_component（这里本想是和orgloginstatus_page一样，再做一个adapter循环就行，但实际报错了）。
![image](https://user-images.githubusercontent.com/38042291/71979128-eabcb280-3257-11ea-851a-12c895401d1d.png)

tellerdialog_component/effect.dart通过API接口获取循环数据
![image](https://user-images.githubusercontent.com/38042291/71979152-f6a87480-3257-11ea-813c-90bc279f97e6.png)

这样当我点击页面上的按钮时候，理想的是弹出showdailog的循环内容，可实际情况是报类型错误。
![image](https://user-images.githubusercontent.com/38042291/71979169-00ca7300-3258-11ea-9611-7be15b3efd35.png)

不知道为什么？ 界面显示的是这样的
![image](https://user-images.githubusercontent.com/38042291/71979194-0de76200-3258-11ea-8f20-741dbee2404a.png)

实际想实现的是这样的
![image](https://user-images.githubusercontent.com/38042291/71979210-163f9d00-3258-11ea-83cf-f06177e0b800.png)

请各位赐教

**Comment by zjuwjf** [comment]
可以有demo么？

**Comment by xinpiaoyuanfang** [comment]
> 可以有demo么？

您好，有邮箱么？  因为是内部网络，所以没公开

**Comment by xinpiaoyuanfang** [comment]
先关掉了，感觉应该是 没用reducer刷新state的原因
