### ISSUE TITLE
怎么可以确保打开pageA时候，pageA的effect里面的Lifecycle.initState被调用

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [alibaba/fish-redux#590]
Lifecycle.initState 初始化的数据是通过 API接口获取的！
在使用的时候 view需要获取 API接口返回的list长度，一直初始化不到

**Comment by zjuwjf** [comment]
给个不被调用的demo？ 这个不应该发生。

**Comment by xinpiaoyuanfang** [comment]
> 给个不被调用的demo？这个不应该发生。
因为接口是内部网络，所以只能提供下page的代码，抱歉

以下是state：
import 'package:fish_redux/fish_redux.dart';
import 'package:panguapp/model/Interface/opendoor/OpenDoorMapper.dart';
import 'package:panguapp/model/Interface/tellerstatus/TellerStatusMapper.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

import 'tellerdialog_component/state.dart';

class TellerStatusState implements Cloneable<TellerStatusState> {

	List<OpenDoorMapper> openList;
	RefreshController refreshController;
	List<TellerStatusMapper> tellerList;
	int index;

	@override
	TellerStatusState clone() {
		return TellerStatusState()
			..openList = openList
			..refreshController = refreshController
			..tellerList = tellerList
			..index = index;
	}
}

TellerStatusState initState(Map<String, dynamic> args) {
	TellerStatusState state = new TellerStatusState();
	state.refreshController = new RefreshController(initialRefresh: false);
	state.tellerList = new List();
	return state;
}

以下是effect：
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart' hide Action;
import 'package:panguapp/http/api.dart';
import 'package:panguapp/http/find/netUtil.dart';
import 'package:panguapp/model/Interface/opendoor/OpenDoorMapper.dart';
import 'action.dart';
import 'state.dart';

Effect<TellerStatusState> buildEffect() {
	return combineEffects(<Object, Effect<TellerStatusState>>{
		Lifecycle.initState: _init,
		TellerStatusAction.showTellerStatusEffect: _onShowTellerStatusEffect,
		TellerStatusAction.refresh: _onRefresh,
	});
}

void _init(Action action, Context<TellerStatusState> ctx) {
	ctx.dispatch(TellerStatusActionCreator.onRefresh());
}

void _onRefresh(Action action, Context<TellerStatusState> ctx) async {
	NetUtil.get(Api.OpenDoorMapper, (data) {
//	NetUtil.post('/v2/5e0583f23300005a00ec591d', (data){
		List<OpenDoorMapper> openList = getOpenDoorMapperList(data);
//		ctx.state.refreshController.refreshCompleted();
		ctx.dispatch(TellerStatusActionCreator.setNewData(openList)); //这里调到了adapter的get里面
	}, errorCallBack: (errorMsg) {
		println("error: " + errorMsg);
	});
}

void _onShowTellerStatusEffect(Action action, Context<TellerStatusState> ctx) {
	showDialog(
		context: ctx.context,
		builder: (BuildContext context) {
			return ctx.buildComponent('dialog');
		}
	);
}

以下是view：
import 'package:fish_redux/fish_redux.dart';
import 'package:flutter/material.dart';
import 'package:panguapp/store/MyButton.dart';

import 'action.dart';
import 'state.dart';

Widget buildView(TellerStatusState state, Dispatch dispatch,
	ViewService viewService) {
	return Scaffold(
		appBar: AppBar(
			title: Center(child: Text('机构签到签退状态')),
			automaticallyImplyLeading: false,
			actions: <Widget>[
				IconButton(
					icon: Icon(Icons.refresh),
					onPressed: () {
						dispatch(TellerStatusActionCreator.onRefresh());
					},
				),
			],
		),
		body: Container(
			padding: EdgeInsets.only(left: 10, right: 10, top: 10, bottom: 10),
			child: GridView.builder(
				shrinkWrap: true,
				gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
					crossAxisSpacing: 5,
					mainAxisSpacing: 5,
					crossAxisCount: 4,
					childAspectRatio: 2,
				),
				itemBuilder: (BuildContext context, int index) {
					return MyRaisedButton(
						margin: 3.0,
						color: state.openList[index].orgstatustypeid == '1'
							? Colors.blue
							: Colors.grey,
						text: state.openList[index].orgnameCn,
						onTab: () {
							state.index = index;
							dispatch(TellerStatusActionCreator.onAction());
						},
					);
				},
				itemCount: state.openList.length,
			),
		),
	);
}

**Comment by xinpiaoyuanfang** [comment]
已解决，init应该还需要调用以下reducer，刷新一下state
