### ISSUE TITLE
是否可以把 AppBar单独封装成 Component，如果可以的话怎么调用

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [alibaba/fish-redux#594]
fish_redux是否可以把 AppBar单独封装成一个Component，如果可以的话，怎么调用。
我是这封装了一下，但是嗲用报错，所AppBarComponentStatus 不是 ‘PreferredSizeWidget'的子类型

return Scaffold(appBar: viewService.buildComponent('appBar'));

AppBarComponent里面的 view.dart 直接 return AppBar(titile: Text('导航'));

**Comment by zjuwjf** [comment]
#311

**Comment by xinpiaoyuanfang** [comment]
> #311
PreferredSizeWidget(width:10, height: 10, child: viewService.buildComponent("appBar")),

PreferredSizeWidget这个在 page的view里面报错，import 'package:flutter/material.dart'; 依然报错

**Comment by xinpiaoyuanfang** [comment]
> #311

连接里面的 第二种在 appBarComponent里面 
class AppBarComponent extends Component<AppBarComponentState> {
  AppBarComponent()
      : super(
            wrapper: 
会报错，是不是最新版本的fish_redux不支持呀。

**Comment by xinpiaoyuanfang** [comment]
还未解决，后面再看看
