### ISSUE TITLE
怎么让其他page使用 login返回后的数据

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [alibaba/fish-redux#595]
不同的用户login登陆成功后，会返回很多信息，这些信息在其他page中会用到，怎么让其他page页可以使用这些信息

**Comment by o1298098** [comment]
如果有必要的话可以放到globalStore里面

**Comment by xinpiaoyuanfang** [comment]
> 如果有必要的话可以放到globalStore里面

需要怎么做？
