### ISSUE TITLE
fish-redux和annotation_route配合起来怎么用？

### ISSUE THREAD

**Issue by evelynEdison** [alibaba/fish-redux#60]

**Comment by voicewitness** [comment]
fish-redux的page会产生一个widget，annotation_route可以接受一个widget上的注释，那么我们配合使用的时候，可以先建一个自己的widget类(如TestPageWidget)，然后在build函数中填充page产生的widget，示例代码如下：
`@ARoute(url: 'scheme://host')
class TestPageWidget extends StatefulWidget {
  MyRouterOption routerOption;
  TestPageWidget(this.routerOption) : super();
  @override
  State<StatefulWidget> createState() {
    return TestPageWidgetState(routerOption);
  }
}

class TestPageWidgetState extends State<TestPageWidget> {
  MyRouterOption routerOption;
  TestPageWidgetState(this.routerOption) : super();
  @override
  Widget build(BuildContext context) {
    return TestPageContainer().buildPage(routerOption);
  }
}
class TestPageContainer extends Page<TestPageContainerState, Object> {
  TestPageContainer()
      : super(
          initState: initState,
          view: buildTestView,
          reducer: TestReducerBuilder.build(),
        );
}

`

**Comment by evelynEdison** [comment]
好的，非常感谢

**Comment by xiaobt** [comment]
> fish-redux的page会产生一个widget，annotation_route可以接受一个widget上的注释，那么我们配合使用的时候，可以先建一个自己的widget类(如TestPageWidget)，然后在build函数中填充page产生的widget，示例代码如下：
> 
> ```
> @ARoute(url: 'scheme://host')
> class TestPageWidget extends StatefulWidget {
>   MyRouterOption routerOption;
>   TestPageWidget(this.routerOption) : super();
>   @override
>   State<StatefulWidget> createState() {
>     return TestPageWidgetState(routerOption);
>   }
> }
> 
> class TestPageWidgetState extends State<TestPageWidget> {
>   MyRouterOption routerOption;
>   TestPageWidgetState(this.routerOption) : super();
>   @override
>   Widget build(BuildContext context) {
>     return TestPageContainer().buildPage(routerOption);
>   }
> }
> class TestPageContainer extends Page<TestPageContainerState, Object> {
>   TestPageContainer()
>       : super(
>           initState: initState,
>           view: buildTestView,
>           reducer: TestReducerBuilder.build(),
>         );
> }
> ```

这种在外面包一层壳的方式不太好吧，如果有很多跳转page的路由，那不是得创建很多类似的类，请问一下有没有更好的方式来解决annotation_route配合问题？
