### ISSUE TITLE
Commponent 的Effect是否也可以只有自己收到？

### ISSUE THREAD

**Issue by dy1023348109** [alibaba/fish-redux#600]
Commponent 的Effect是否也可以只有自己收到？ adapter里有很多同类型Commponent，一个dispatchAction后 其他的也收到了。是否有解决办法？

**Comment by zjuwjf** [comment]
一个Action，优先由自己Effect处理（处理完即终止）。
如果自己的Effect不处理，会发送给所有其他的Effect， 以及所有Reducer。

**Comment by dy1023348109** [comment]
感谢回复，今天debug发现了原因，原因是想在Effect处理之后 再发送给自己的Reducer，所以effect返回了false，导致其他的Component也收到了这个action。
