### ISSUE TITLE
如何在fish_redux里使用路由观察器呢 navigatorObservers

### ISSUE THREAD

**Issue by yjboy99** [alibaba/fish-redux#608]
我想查看当前页面的路由信息，是需要navigatorObservers可以实现吗

**Comment by yjboy99** [comment]
在MaterialApp  如何设置routes

**Comment by yjboy99** [comment]
![image](https://user-images.githubusercontent.com/48830994/74657391-1cb42380-51cb-11ea-9991-6e6ebfe031d9.png)

**Comment by yjboy99** [comment]
获取不到当前路由名称怎么办，点击push推送跳转指定路由，如果已经在当前页面就replace，如果不在就push

**Comment by EaglesChen** [comment]
碰到同样的问题，麻烦问一下是如何解决的
