### ISSUE TITLE
关于Global State 无法全局更新问题。

### ISSUE THREAD

**Issue by EaglesChen** [alibaba/fish-redux#619]
我参考example里的Global Store，当我的Global State 更新时，不触发其他页面的更新。看了好久没看出什么问题。

App.dart
![image](https://user-images.githubusercontent.com/30282214/75998021-25cb2180-5f3b-11ea-9ce8-ae17fbde020d.png)

globel state
![image](https://user-images.githubusercontent.com/30282214/75998120-498e6780-5f3b-11ea-876c-6b3a49c71978.png)

home state
![image](https://user-images.githubusercontent.com/30282214/75998215-72aef800-5f3b-11ea-865a-2add74009ead.png)

home view
![image](https://user-images.githubusercontent.com/30282214/75998271-85c1c800-5f3b-11ea-84e8-95521f71ccb0.png)

当我触发globel store 的reducer，更新了globel store,  home state 没有更新。按道理是会进入home state 的clone。

**Comment by zsfbest** [comment]
你的页面有写入到PageRoutes里面吗

**Comment by 1jy** [comment]
把 routers 修饰为静态变量，通过 routers 来构建页面，我是这样解决的。

**Comment by EaglesChen** [comment]
> 你的页面有写入到PageRoutes里面吗

有的，通过路由地址也能跳转。

**Comment by EaglesChen** [comment]
> 把 routers 修饰为静态变量，通过 routers 来构建页面，我是这样解决的。

我晚上回去试试，感谢提供建议。

**Comment by EaglesChen** [comment]
> 把 routers 修饰为静态变量，通过 routers 来构建页面，我是这样解决的。

hello 按照你提供的思路我将routers设置为静态变量
![image](https://user-images.githubusercontent.com/30282214/76676863-98569400-6602-11ea-8181-9ae703dcae3e.png)

我想实现切换bottombar的时候更新全局的index，然后根据index显示title。目前是GlobeState更新了，但是没有通知子组件更新。

**Comment by EaglesChen** [comment]
该问题已经解决，原因是跳转页面时需要使用静态的routers来buildPage。

Navigator.of(ctx.context).pushReplacement(
        PageRouteBuilder(
          pageBuilder: (context, animation, secAnimation) {
            return FadeTransition(
              opacity: animation,
              child: AppRoute.global.buildPage('/home/home_page', null),
            );
          },
        ),
      );

共勉
