### ISSUE TITLE
关于Effect广播的用法和说明

### ISSUE THREAD

**Issue by tom1918** [alibaba/fish-redux#62]
关于Effect 广播的一些问题，因为实例代码中没有关于Effect 广播的用法。我只知道如果让方法返回非空，就可以广播进行，但是并不知道具体如何广播。或者是如何执行的。
我看了其他的issue 作出以下做了以下尝试：
1、加入pop事件；
2、print 一下；
发现， 我的APP直接就返回至 黑屏（返回空的时候是返回上一页的）；
![image](https://user-images.githubusercontent.com/6824136/54268597-89d03980-45b6-11e9-8e44-bad1e933245c.png)
我想了解以下内容：
1、有没有更加详细的关于Effect 说明机制；
2、返回的类型有什么用；
3、这个effect 广播是如何影响其他页面的；
谢谢~

**Comment by zjuwjf** [comment]
对框架而言，它看到的是一个Effect<T> = (Action action, Context<T> ctx) => dynamic

至于它是一个函数处理N个Action，还是由N个函数（每一个函数一对一处理Action）的组合而成，框架不关心这些细节。

然后你上面的代码用到了 combineEffects 

```
Effect<T> combineEffects<T>(Map<Object, SubEffect<T>> map) =>
    (map == null || map.isEmpty)
        ? null
        : (Action action, Context<T> ctx) {
            final SubEffect<T> subEffect = map[action.type];
            return subEffect?.call(action, ctx) ?? subEffect != null; // 注意⚠️： ?? subEffect != null
          };
```

combineEffects 是将 N个函数（每一个函数一对一处理Action）的组合而成，它默认了对这N个Action都是消费的态度。

**Comment by zjuwjf** [comment]
1、有没有更加详细的关于Effect 说明机制；
	1. 一个Action(意图)，由View 和 Effect来发送. （先不考虑Middleware吧）
	2. 被发送的意图，先由自己的Effect来决定要不要消费（怎么决定？看Effect函数返回值）
	3. 如果被自己的Effect消费，消费完即终止。
	4. 如果不被自己的Effect消费，发送给所有其他存活的Effect，和 唯一的store。
2、返回的类型有什么用；
	怎么决定？看Effect函数返回值
	但是这里为什么不是boolean类型呢？ （为了兼容Future和onError）
3、这个effect 广播是如何影响其他页面的；
	dispatch不能影响其他页面。
	appBroadcast可以影响其他页面

**Comment by tom1918** [comment]
感谢~我大致了解了。目前来说combineEffects 就够用了，谢谢
