### ISSUE TITLE
关于在effect 是否需要手动释放 像 TextEditingController 或者focusNode,还是框架自己能释放

### ISSUE THREAD

**Issue by andyxiaoxi** [alibaba/fish-redux#622]
Effect<T> buildEffect() {
  return combineEffects(<Object, Effect<PageState>>{
   LifeStyle.disposs: onDisposs,
  });
}

void onDisposs(Action action, Context<T> ctx) {
 ctx.state.textEdittingController.disposs();       此代码需要手动，释放吗？
}

**Comment by charmfocus** [comment]
根据编码原则，谁创建，谁销毁，所以可以按你的逻辑进行处理

**Comment by andyxiaoxi** [comment]
> 根据编码原则，谁创建，谁销毁，所以可以按你的逻辑进行处理

我看demo,没有销毁textEdittingController，和focusNode对象

**Comment by charmfocus** [comment]
https://api.flutter.dev/flutter/widgets/TextEditingController-class.html
官方有明确的说明，必需在使用完成后，进行dispose，如果不dispose，应该会造成一定的内存泄漏。

**Comment by andyxiaoxi** [comment]
这个官方的我知道，但是我想要问的是，fish_redux,框架是否帮我们 disposs了? 我问的是fish_redux的demo,没有看到在哪disposs

**Comment by andyxiaoxi** [comment]
> https://api.flutter.dev/flutter/widgets/TextEditingController-class.html
> 官方有明确的说明，必需在使用完成后，进行dispose，如果不dispose，应该会造成一定的内存泄漏。
这个官方的我知道，但是我想要问的是，fish_redux,框架是否帮我们 disposs了? 我问的是fish_redux的demo,没有看到在哪disposs

**Comment by andyxiaoxi** [comment]
> https://api.flutter.dev/flutter/widgets/TextEditingController-class.html
> 官方有明确的说明，必需在使用完成后，进行dispose，如果不dispose，应该会造成一定的内存泄漏。

这个官方的我知道，但是我想要问的是，fish_redux,框架是否帮我们 disposs了? 我问的是fish_redux的demo,没有看到在哪disposs

**Comment by charmfocus** [comment]
框架肯定没处理dispose
