### ISSUE TITLE
需要生命周期的Controller类处理方法

### ISSUE THREAD

**Issue by Iridescentangle** [alibaba/fish-redux#633]
您好,请教一下,当前用FishRedux搭建界面,在某界面中使用TabBar+TabBarView联动,这样就需要TabController,像这一类Controller在StatefulWidget中都是在页面initState中进行初始化,在dispose中释放的,FishRedux有没有这方面的示例呀?网上确实找不到相关的示例...非常感谢,希望能帮忙解答一下!

**Comment by zsfbest** [comment]
eff里面可以定义钩子函数, 
![image](https://user-images.githubusercontent.com/39234003/78117425-3e463300-7438-11ea-8c62-7d5809c1b52e.png)

**Comment by zsfbest** [comment]
TabController你可能需要搜索一下怎么创建, 网上蛮多的

**Comment by Iridescentangle** [comment]
> TabController你可能需要搜索一下怎么创建, 网上蛮多的

好的,非常感谢!
