### ISSUE TITLE
主工程是Flutter，使用fish_redux插件做状态管理，如何进行原生交互

### ISSUE THREAD

**Issue by AngeloWangCoder** [alibaba/fish-redux#644]
请教个问题啊，主工程是Flutter，使用fish_redux插件做状态管理，先从Flutter页面打开了原生页面，经过了一些原生页面的操作，然后如何再从某个原生页面中打开另一个Flutter页面呢？

**Comment by AngeloWangCoder** [comment]
fixed

**Comment by Kimxu** [comment]
我目前的原生交互是自己写个插件，之后引入就好了，和原生交互 和fish_redux 没关系。
