### ISSUE TITLE
0.3.2版本还是报Page重名错误

### ISSUE THREAD

**Issue by buxiaojiong** [alibaba/fish-redux#646]
src/redux_component/page.dart 中 import 'package:flutter/widgets.dart' hide Action;
没有hide Page

**Comment by zjuwjf** [comment]
有相关编译错误么？

**Comment by buxiaojiong** [comment]
{
	"resource": "/Users/boxiaojiong/Desktop/ClientApp/lib/airconditioning_manager/ac_detail/ac_detail_page.dart",
	"owner": "dart",
	"code": "ambiguous_import",
	"severity": 8,
	"message": "The name 'Page' is defined in the libraries 'package:fish_redux/src/redux_component/page.dart' and 'package:flutter/src/widgets/navigator.dart (via package:flutter/widgets.dart)'.\nTry using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.",
	"source": "dart",
	"startLineNumber": 96,
	"startColumn": 28,
	"endLineNumber": 96,
	"endColumn": 32,
	"tags": []
}

**Comment by zjuwjf** [comment]
#647
