### ISSUE TITLE
MutableSource能否抽象为interface（无实现的抽象类）

### ISSUE THREAD

**Issue by wangbo4020** [alibaba/fish-redux#656]
MutableSource能否抽象为interface（无实现的抽象类）,就像GlobalState一样。

看了下源码，updateItemData方法完全可以分离为静态方法。

这样会让开发者有更多选择。或者这样设计是否有其他考虑。

**Comment by zjuwjf** [comment]
你完全可以自由的自定义。

**Comment by wangbo4020** [comment]
我是 implements MutableSource，然后把 MutableSource.updateItemData里面内容 copy 到实现类里
