### ISSUE TITLE
怎么在fish redux中使用fullscreenDialog

### ISSUE THREAD

**Issue by XinleZhou2018** [alibaba/fish-redux#657]
怎么像iOS presentviewcontroller那样从底部弹出新的页面？

**Comment by DDDrop** [comment]
最简单就是： `MaterialPageRoute` 的 `fullscreenDialog` 设置为 `true`

**Comment by XinleZhou2018** [comment]
> 最简单就是： `MaterialPageRoute` 的 `fullscreenDialog` 设置为 `true`
