### ISSUE TITLE
fish redux 中如何实现类似AutomaticKeepAliveClientMixin 的 widget keepalive 功能

### ISSUE THREAD

**Issue by danieldai** [alibaba/fish-redux#68]
我使用 fish redux 的 adapter 做了个pageview，但是当pageview切换时，切换走的pageview就把清理了。使用flutter的statefulwidget时可以使用AutomaticKeepAliveClientMixin使widget免于销毁。当完全使用fish redux该如何实现这个功能？

**Comment by zjuwjf** [comment]
可以参考那个tabcontrol issue的做法

**Comment by zjuwjf** [comment]
#
Duplicate of #58

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54485116-30198900-48ae-11e9-9307-239af51dfe36.png)
上面说了比如 KeepAlive啥啥啥，下面例子却一点都没有关于比如 KeepAlive的实现，可不可以不要这么抽象，新手一点都看不懂，能否给个配置KeepAlive的WidgetWrapper例子，具体如何使用，文档描述的太粗糙了 ，谢谢了@zjuwjf

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54485145-a918e080-48ae-11e9-9acf-e2f3c0d3e2df.png)
我的state with SingleTickerProviderStateMixin后不能继续with了要如何操作 @zjuwjf

**Comment by qq329401134** [comment]
![image](https://user-images.githubusercontent.com/38587734/54485300-1e85b080-48b1-11e9-8a78-48f3cc6f2cb5.png)
参考那个tabcontrol    issue的做法将with弄成了两个就会报错
![image](https://user-images.githubusercontent.com/38587734/54485318-54c33000-48b1-11e9-9f38-a62cbacb9773.png)
@zjuwjf
