### ISSUE TITLE
"The method 'call' was called on null" error when dispatch component action

### ISSUE THREAD

**Issue by uzuki-P** [alibaba/fish-redux#692]
I have `LoginPage` that have `InputFieldComponent` dependencies.
![image](https://user-images.githubusercontent.com/16524713/86557593-d34d5080-bf80-11ea-8a7e-a106f6512bcb.png)

This is the `PassInputConnector`
![image](https://user-images.githubusercontent.com/16524713/86557849-ae0d1200-bf81-11ea-9e1b-54971b39fd60.png)

On `InputFieldComponent` there's an `IconButton` that `dispatch` an action
this action just call a simple `reducer` that flip a bool state (enable/disable obscureText)
![image](https://user-images.githubusercontent.com/16524713/86557694-29ba8f00-bf81-11ea-89ea-11bda36c38cd.png)

**The Problem**
When I press the `IconButton`, I got this error.
![image](https://user-images.githubusercontent.com/16524713/86557964-21af1f00-bf82-11ea-8a0f-2603caa8e585.png)

Am I using the wrong connector? Or there's something that I miss?

**Comment by wangemng** [comment]
你解决了吗？

**Comment by uzuki-P** [comment]
@wangemng 
No
I migrate to bloc state management

**Comment by wangemng** [comment]
loginstate 管理？

**Comment by uzuki-P** [comment]
I didn't use fish-redux and go full Bloc
I didn't understand any chinese language so it's really hard for me to search for error. So I decided to change my state management instead.
