### ISSUE TITLE
关于子页面获取不到全局store的值

### ISSUE THREAD

**Issue by vaelsy** [alibaba/fish-redux#698]
![image](https://user-images.githubusercontent.com/29798655/87113922-ee320480-c2a1-11ea-9a9d-580b01b96b8b.png)
![image](https://user-images.githubusercontent.com/29798655/87113956-01dd6b00-c2a2-11ea-8a7f-f1ff1ec7083e.png)
![image](https://user-images.githubusercontent.com/29798655/87113972-0b66d300-c2a2-11ea-8e47-f8ced023d80a.png)
请问如何处理这种情况比较好？？？

**Comment by DDDrop** [comment]
想必，你是参照了大佬的 Example。
所以，创建页面时要通过 PageRoutes。而不是 Page.buildPage

**Comment by vaelsy** [comment]
感谢
