### ISSUE TITLE
跨页面dispatch存在bug

### ISSUE THREAD

**Issue by luneice** [alibaba/fish-redux#701]
A页面在dispatch其他页面的reducer或effect都无法成功执行,但A页面dispatch自己的reducer或effect时可以成功执行.

**Comment by luneice** [comment]
> A页面在dispatch其他页面的reducer或effect都无法成功执行,但A页面dispatch自己的reducer或effect时可以成功执行.

不知道是我的方式不对还是啥,我是在B页面的view中直接dispatch A页面的reducer或effect,单步调试时并未执行成功.

**Comment by fuhao012** [comment]
dispatch其他页面的reducer或effect都无法成功执行 要通过brocast 来执行

**Comment by CNAD666** [comment]
跨页面用广播broadcast就行了

**Comment by binzi56** [comment]
> 跨页面用广播broadcast就行了

不同modules可以用吗

**Comment by lj827** [comment]
官方demo里面有演示啊，在A页面里面dispatch自己的action，然后在B页面需要的地方比如effect里面引用A页面的action，当A页面的这个指定的action触发的时候，B页面对应的action也会触发啊
import '../todo_component/action.dart' as todo_action;   todo_action.ToDoAction.remove: _remove  搜索一下就可以知道到底是怎么运行的了

**Comment by CNAD666** [comment]
> > 跨页面用广播broadcast就行了
> 
> 不同modules可以用吗

可以；详细的看看这个：https://juejin.cn/post/6860029460524040199
