### ISSUE TITLE
购物车页面使用StaticFlowAdapter+SourceFlowAdapter，界面正常显示，但是当修改商品选中状态时报错

### ISSUE THREAD

**Issue by suhuangqiang** [alibaba/fish-redux#713]
做一个购物车的界面，因为商品属性问题，需要有两个商品列表，采用购物车页面使用了StaticFlowAdapter，集合SourceFlowAdapter，文档中的示例都是使用DynamicFlowAdapter,在插槽中使用connector。现在新的应该是使用SourceFlowAdapter，SourceFlowAdapter没有使用connector，而是使用了state继承MutableSource。所以我这边的做法是增加了一个组件CarProductListState，层级是ShoppingCartState（购物车页面） => CarProductListState(商品列表组件) => CarProductState（商品单元组件）,界面可以正常显示。现在是当修改购物车选中状态时报错，但是热重载后界面状态又改变。
报错内容：
The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'ShoppingCartState', Instance of 'CarProductListState')

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ConnOp.set (package:fish_redux/src/redux_connector/connector.dart:19:43)
#2      MutableConn.subReducer.<anonymous closure> (package:fish_redux/src/redux/connector.dart:94:9)
#3      combineSubReducers.<anonymous closure> (package:fish_redux/src/redux/combine_reducers.dart:22:24)
#4      combineReducers.<anonymous closure> (package:fish_redux/src/redux/combine_reducers.dart:45:26)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#0ed22
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(10.7, 152.3)
  finalLocalPosition: Offset(10.7, 6.9)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by yuhaocan** [comment]
想知道是如何解决的
