### ISSUE TITLE
很久没有更新了，是不是停止维护了？

### ISSUE THREAD

**Issue by kokman** [alibaba/fish-redux#724]
目前只有一个Release，已经半年没有更新了，请问是不是停止维护了？谢谢！

**Comment by lzdtech** [comment]
同问，有没有官方人员告知一下

**Comment by wangbo4020** [comment]
凉了，各位散了吧
优秀框架有很多，可以都去看看

**Comment by PhantomRay** [comment]
凉了是肯定的，大家有好的推荐吗？

**Comment by wangbo4020** [comment]
[Provider](https://pub.dev/packages/provider) , [Flutter_bloc](https://pub.dev/packages/flutter_bloc) 都不错的。

**Comment by Cvilia** [comment]
> 凉了是肯定的，大家有好的推荐吗？

为啥这么肯定

**Comment by juggist** [comment]
kpi产物

**Comment by lu-xu** [comment]
> kpi产物

ali挺多这种项目的😂

**Comment by Jungle68** [comment]
不是吧，有没有官方的人员回复下

**Comment by jlcool** [comment]
国内大厂真是让人失望

**Comment by Kimxu** [comment]
我看了一下，六天前更新了。可喜可贺啊
这框架用习惯了，还是挺顺手的

**Comment by TangYuanHuan** [comment]
框架是好框架，就是更新慢，Null safety还不支持

**Comment by henry-hz** [comment]
Maybe all the fish redux functionalities (global vs local state, etc...) could be replicated using https://pub.dev/packages/event_bus , BUT.... not enforced. Any thoughts ?

**Comment by christyuj** [comment]
大家好，整个框架还在推进维护当中，最近也有一些新特性的重构还在内部的分支没有同步过来，希望大家正确看待开源极其背后的价值，一起进行有效讨论和共建，共同形成良好的社区氛围。
无效的问题，相关contributor会进行关闭，请大家理解。
