### ISSUE TITLE
例子怎么跑起来

### ISSUE THREAD

**Issue by zhipeng6** [alibaba/fish-redux#75]
初学,提示Is your project missing an android/AndroidManifest.xml?

**Comment by hanmingkang** [comment]
1.flutter create . 补缺文件
2.flutter升级，不然会出现问题

**Comment by zhipeng6** [comment]
> 1.flutter create . 补缺文件
> 2.flutter升级，不然会出现问题

具体怎么操作,大神

**Comment by hanmingkang** [comment]
在idea中的terminal直接运行就行了，升级是flutter upgrade

**Comment by hyjfine** [comment]
readme的Examples 章节有运行方式，有报错看一下 #39。
