### ISSUE TITLE
example

### ISSUE THREAD

**Issue by hanmingkang** [alibaba/fish-redux#76]

**Comment by hanmingkang** [comment]
example中对新手不怎么友好啊，看不太懂，有没有说明什么的，类似于flutter-redux的readme

**Comment by zjuwjf** [comment]
也可以找找其他的example看看，如[/fish_redux_simple_example](https://github.com/danieldai/fish_redux_simple_example)。 同时也欢迎给fish-redux来增加更多的demo。

**Comment by hyjfine** [comment]
也可以参考下/[flutter_redux_sample](https://github.com/hyjfine/flutter_redux_sample) 的fish-redux和fish-redux-adapter分支，明天我更新下readme，补个文档：）

**Comment by hanmingkang** [comment]
好的，谢谢各位！
