### ISSUE TITLE
有支持null-safety的计划么？

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/fish-redux#761]
有支持null-safety的计划么？不要放弃啊，项目已经用了fish-redux。会继续维护项目么？后续的计划有么？不要是KPI项目啊。现在fish_redux不支持null-safety所有项目都无法升级，flutter新版本在ios编译null-safety时也存在问题（如果fish_redux支持null-safety那么就不需要指定null-safety参数可以避开flutter编译的bug），所以flutter也无法升级，其他三方库又需要flutter新版本，所以三方库也无法升级。

**Comment by flutterbest** [comment]
不要是KPI项目啊. 哈哈哈哈哈

**Comment by leftcoding** [comment]
可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux

**Comment by jiangxiaoqiang** [comment]
> 可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux

干的漂亮，可以推到阿里的主分支么，能联系下阿里的维护同学么？ 看了 貌似没人维护啊，没人管的孩子。 我先用你的项目吧

**Comment by leftcoding** [comment]
> > 可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux
> 
> 干的漂亮，可以推到阿里的主分支么，能联系下阿里的维护同学么？ 看了 貌似没人维护啊，没人管的孩子。 我先用你的项目吧

已经PR了，但是好像没人合并，估计是要验证下吧

**Comment by jiangxiaoqiang** [comment]
> > > 可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux
> > 
> > 
> > 干的漂亮，可以推到阿里的主分支么，能联系下阿里的维护同学么？ 看了 貌似没人维护啊，没人管的孩子。 我先用你的项目吧
> 
> 已经PR了，但是好像没人合并，估计是要验证下吧

我刚刚尝试升级了下，新版本的null-safety在dispatch后没有触发页面的rerender。我的逻辑代码没有调整，所有页面都存在这样的情况。能知道是哪里的原因么。需要源码的话我这里也可以提供，项目是开源的。有没有朋友升级过的可以交流一下。

**Comment by leftcoding** [comment]
> > > > 可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux
> > > 
> > > 
> > > 干的漂亮，可以推到阿里的主分支么，能联系下阿里的维护同学么？ 看了 貌似没人维护啊，没人管的孩子。 我先用你的项目吧
> > 
> > 
> > 已经PR了，但是好像没人合并，估计是要验证下吧
> 
> 我刚刚尝试升级了下，新版本的null-safety在dispatch后没有触发页面的rerender。我的逻辑代码没有调整，所有页面都存在这样的情况。能知道是哪里的原因么。需要源码的话我这里也可以提供，项目是开源的。有没有朋友升级过的可以交流一下。

你的版本是 0.3.7么？我这个是基于0.3.7升级，或者你项目地址贴出来。我看下。

**Comment by jiangxiaoqiang** [comment]
> > > > > 可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux
> > > > 
> > > > 
> > > > 干的漂亮，可以推到阿里的主分支么，能联系下阿里的维护同学么？ 看了 貌似没人维护啊，没人管的孩子。 我先用你的项目吧
> > > 
> > > 
> > > 已经PR了，但是好像没人合并，估计是要验证下吧
> > 
> > 
> > 我刚刚尝试升级了下，新版本的null-safety在dispatch后没有触发页面的rerender。我的逻辑代码没有调整，所有页面都存在这样的情况。能知道是哪里的原因么。需要源码的话我这里也可以提供，项目是开源的。有没有朋友升级过的可以交流一下。
> 
> 你的版本是 0.3.7么？我这个是基于0.3.7升级，或者你项目地址贴出来。我看下。

抱歉，回复晚了。没有看到消息，我的采用fish-redux项目地址是：https://github.com/jiangxiaoqiang/cruise-open。 目前develop分支的内容是最新的。拉取下来后，只需要将fish-redux替换成你自己的那个分支即可。我当时替换的格式是：



```
fish-redux:
    git:
      url: xxx.git
      ref: main
```


我的运行配置：


![image](https://user-images.githubusercontent.com/4521375/128665173-fa1b5436-6ad5-42f4-9e1e-b0ef23c0a188.png)


`--flavor dev --no-sound-null-safety
`

**Comment by hangYq** [comment]
> > > > > > 可以试试看，我改版的2.0 https://github.com/leftcoding/fish-redux
> > > > > 
> > > > > 
> > > > > 干的漂亮，可以推到阿里的主分支么，能联系下阿里的维护同学么？ 看了 貌似没人维护啊，没人管的孩子。 我先用你的项目吧
> > > > 
> > > > 
> > > > 已经PR了，但是好像没人合并，估计是要验证下吧
> > > 
> > > 
> > > 我刚刚尝试升级了下，新版本的null-safety在dispatch后没有触发页面的rerender。我的逻辑代码没有调整，所有页面都存在这样的情况。能知道是哪里的原因么。需要源码的话我这里也可以提供，项目是开源的。有没有朋友升级过的可以交流一下。
> > 
> > 
> > 你的版本是 0.3.7么？我这个是基于0.3.7升级，或者你项目地址贴出来。我看下。
> 
> 抱歉，回复晚了。没有看到消息，我的采用fish-redux项目地址是：[https://github.com/jiangxiaoqiang/cruise-open。](https://github.com/jiangxiaoqiang/cruise-open%E3%80%82) 目前develop分支的内容是最新的。拉取下来后，只需要将fish-redux替换成你自己的那个分支即可。我当时替换的格式是：
> 
> ```
> fish-redux:
>     git:
>       url: xxx.git
>       ref: main
> ```
> 
> 我的运行配置：
> 
> ![image](https://user-images.githubusercontent.com/4521375/128665173-fa1b5436-6ad5-42f4-9e1e-b0ef23c0a188.png)
> 
> `--flavor dev --no-sound-null-safety `

![image](https://user-images.githubusercontent.com/23026075/175500630-33dfd78c-c2f5-4951-ad9d-1abdc3cf8c2d.png)
这里改一下就好了

**Comment by leftcoding** [comment]
嗯。是的
