### ISSUE TITLE
通过路由传递的参数，怎么接收

### ISSUE THREAD

**Issue by Aries233** [alibaba/fish-redux#78]
fish-redux中 通过路由传递的参数，怎么在页面中接受使用呢？

Navigator.pushNamed(ctx.context, '/orderDetials',
      arguments: {'orderId': action.payload});

**Comment by zjuwjf** [comment]
可以参考 #60

**Comment by Aries233** [comment]
`onGenerateRoute: (RouteSettings settings) {
          WidgetBuilder builder;

          if (settings.name == '/orderDetials') {
            builder = (ctx) => OrderdetailsPage().buildPage(settings.arguments);
          }
          return new MaterialPageRoute(builder: builder, settings: settings);
        },`
已经解决了，通过在MaterialApp 配置onGenerateRoute，然后设置 .buildPage(参数)就可以。 这里的路由‘/orderDetials’名称，不需要在routes里面注册
