### ISSUE TITLE
动画的Ticker使用

### ISSUE THREAD

**Issue by guopeng1994** [alibaba/fish-redux#82]
/// For example, we want to use SingleTickerProviderStateMixin
  /// We should
  /// 1. Define a new ComponentState
  ///    class CustomStfState extends ComponentState<T> with SingleTickerProviderStateMixin {}
  /// 2. Override the createState method of the Component with the newly defined CustomStfState.
  ///    @override
  ///    CustomStfState createState() => CustomStfState();
  /// 3. Get the CustomStfState via context.stfState in Effect.
  ///    /// Through BuildContext -> StatefulElement -> State
  ///    final TickerProvider tickerProvider = context.stfState;
  ///    AnimationController controller = AnimationController(vsync: tickerProvider);
  ///    context.dispatch(ActionCreator.createController(controller));

在源代码中看到了这个， 能不能在page 中来使用？还是说必须在component中使用？

**Comment by zjuwjf** [comment]
#58

**Comment by guopeng1994** [comment]
> #58

3ks

**Comment by guopeng1994** [comment]
3ks, 我去看看
