### ISSUE TITLE
example里的ToDoListPage添加 keepalive无效

### ISSUE THREAD

**Issue by qq329401134** [alibaba/fish-redux#86]
在demo中创建了wrapper并在ToDoListPage中使用了，但是ToDoListPage内adapter创建的List依然无法保持状态，依然会被销毁，请问下是什么情况呢，是否是adapter和keepalive冲突了？应该怎么解决
![image](https://user-images.githubusercontent.com/38587734/54528304-8e7e5e80-49b7-11e9-92b5-2c3aefe295da.png)
![image](https://user-images.githubusercontent.com/38587734/54528309-95a56c80-49b7-11e9-8544-246e338841a8.png)

**Comment by zjuwjf** [comment]
可以剥离 fish-redux 试试， 看上去可框架无关

**Comment by qq329401134** [comment]
对的，我wrapper放错地方了，解决了

**Comment by qq329401134** [comment]
对的，我wrapper放错地方了，解决了
