### ISSUE TITLE
如何正确的使用showSnackBar？

### ISSUE THREAD

**Issue by Vertores** [alibaba/fish-redux#87]
在effect.dart中
![image](https://user-images.githubusercontent.com/22784899/54536035-dc509200-49ca-11e9-81f4-5b97dc511ec3.png)
运行时报错
![image](https://user-images.githubusercontent.com/22784899/54536075-f8ecca00-49ca-11e9-9ee0-0e7952d6e738.png)

**Comment by zjuwjf** [comment]
猜测是lifecycle的时机没用对，用didChangeDependencies。

**Comment by Vertores** [comment]
@zjuwjf
在didChangeDependendencies尝试后，
提示错误:
Scaffold.of() called with a context that does not contain a Scaffold.
显然ctx.context获取到的为整个widget的context
我也尝试了使用globalkey去实现显示snackBar
scaffoldkey.currentState.showSnackBar
但提示找不到showSnackBar方法
我想要的操作是，当我点按钮时，会显示snackBar。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zjuwjf** [comment]
```dart

static ScaffoldState of(BuildContext context, { bool nullOk = false }) {
  assert(nullOk != null);
  assert(context != null);
  final ScaffoldState result = context.ancestorStateOfType(const TypeMatcher<ScaffoldState>());
  if (nullOk || result != null)
    return result;
  throw FlutterError(
    'Scaffold.of() called with a context that does not contain a Scaffold.\n'
    'No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). '
    'This usually happens when the context provided is from the same StatefulWidget as that '
    'whose build function actually creates the Scaffold widget being sought.\n'
    'There are several ways to avoid this problem. The simplest is to use a Builder to get a '
    'context that is "under" the Scaffold. For an example of this, please see the '
    'documentation for Scaffold.of():\n'
    '  https://docs.flutter.io/flutter/material/Scaffold/of.html\n'
    'A more efficient solution is to split your build function into several widgets. This '
    'introduces a new context from which you can obtain the Scaffold. In this solution, '
    'you would have an outer widget that creates the Scaffold populated by instances of '
    'your new inner widgets, and then in these inner widgets you would use Scaffold.of().\n'
    'A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, '
    'then use the key.currentState property to obtain the ScaffoldState rather than '
    'using the Scaffold.of() function.\n'
    'The context used was:\n'
    '  $context'
  );
}
```
参考下代码 你的Scaffold不在期望的位置上。

**Comment by Vertores** [comment]
非常感谢，已经解决


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by cbyniiaii** [comment]
怎么解决的？可以提供一下code吗？

**Comment by Vertores** [comment]
@cbyniiaii 我的做法是新建一个context，在payload中传递
![image](https://user-images.githubusercontent.com/22784899/54580552-9c79c100-4a43-11e9-9f10-f4790a792541.png)
![image](https://user-images.githubusercontent.com/22784899/54580557-a26fa200-4a43-11e9-8546-e2c155fcb5a1.png)
![image](https://user-images.githubusercontent.com/22784899/54580562-aa2f4680-4a43-11e9-9fc9-835ebd89b4e8.png)

**Comment by niugengyun** [comment]
> @cbyniiaii 我的做法是新建一个context，在payload中传递
> ![image](https://user-images.githubusercontent.com/22784899/54580552-9c79c100-4a43-11e9-9f10-f4790a792541.png)
> ![image](https://user-images.githubusercontent.com/22784899/54580577-c632e800-4a43-11e9-9714-34dc532a557a.png)
> 
> ![image](https://user-images.githubusercontent.com/22784899/54580562-aa2f4680-4a43-11e9-9fc9-835ebd89b4e8.png)

谢谢
