### ISSUE TITLE
listview底部添加数据使得listview不滚动到顶部

### ISSUE THREAD

**Issue by layou1989** [alibaba/fish-redux#91]
在动态的像listview中添加一条数据时(比如从网络加载数据)，原来listview已经滚动到底部了，这时候需要像listview的底部添加数据(例如新闻阅读列表下滑到底部加载更多新闻)，当加载完数据时,listview会重新滚动到列表顶部，这边怎么处理?

**Comment by qq329401134** [comment]
#58 看这个里面都有

**Comment by layou1989** [comment]
> #58 看这个里面都有

感觉应该不是一个原因，我现有的界面已经能保持状态了，但是listview添加数据还是会滚动到顶部

**Comment by hyjfine** [comment]
你想要的效果是添加更多数据，页面不滚动，数据自动追加到页面尾部吧，一般的加载更多也都是这种体验。我使用fish redux和flutter redux都是能做成这种效果的，能贴一下你的buildview和reduce代码看看吗？

![0190321103411HD](https://user-images.githubusercontent.com/1013953/54730775-a4fa0500-4bc5-11e9-8d7b-cfc2721babde.gif)

**Comment by layou1989** [comment]
@hyjfine 我试了一下，单独使用listview也是可以的，应该是我引用的其他插件的问题，我在定位一下

**Comment by juggist** [comment]
> @hyjfine 我试了一下，单独使用listview也是可以的，应该是我引用的其他插件的问题，我在定位一下

你的加载更过是不是用的flutter_easyrefresh？
