### ISSUE TITLE
StaticFlowAdapter的使用

### ISSUE THREAD

**Issue by ywbpmf** [alibaba/fish-redux#92]
能在sample提供StaticFlowAdapter的使用demo吗？

[Document](https://github.com/alibaba/fish-redux/blob/master/doc/concept/static-flow-adapter-cn.md)

**Comment by zjuwjf** [comment]
目前比较忙，短期不会有特别大的sample的更新。 不过非常欢迎大家给我们PR 👏， 有更多的Samples 和 文档 可以进入到我们的项目中来。
