### ISSUE TITLE
可以讲解一下在showDialog如果使用ListAdapter+ListView

### ISSUE THREAD

**Issue by cbyniiaii** [alibaba/fish-redux#93]
final ListAdapter adapter = viewService.buildAdapter();
 showDialog(
      context: ctx.context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Dialog'),
          content: Container(
            child: ListView.builder(
                  itemBuilder: adapter.itemBuilder,
                  itemCount: adapter.itemCount)),
          )
        );
      });

**Comment by zjuwjf** [comment]
showDialog 建议是在Effect中调用， 它就像是一个发送给用户的request，而用户会异步的答复一个response。

在 Effect 中 依然是可以使用 自己定义的dependencies的，只是要做一个类型转化，目前ViewService的api并没有显示的在context中暴露出来，虽然背后它们是同一个对象contextsys。
```
final ViewService viewService = ctx as ViewService;
final ListAdapter adapter = viewService.buildAdapter();
showDialog(
  context: ctx.context,
  builder: (BuildContext context) {
    return AlertDialog(
      title: Text('Dialog'),
      content: Container(
        child: ListView.builder(
        itemBuilder: adapter.itemBuilder,
        itemCount: adapter.itemCount)),
     )
   );
});
```
