### ISSUE TITLE
how to receive the lifecycle of every single item in ListView? // 如何监听到所有的item的寿命周期？

### ISSUE THREAD

**Issue by wilin52** [alibaba/fish-redux#94]
I met a problem while I used VisibleChangeMixin in  Adapter .  Only the first item can dispatch a action.

As the code presents:  
![image](https://user-images.githubusercontent.com/9528566/54740867-9298bf00-4bf7-11e9-9186-58947edaa515.png)
Is it VisibleChangeMixin designed for adapter and not support the issue I meet?

/// 最近遇到一个问题， 在adapter 中使用 VisibleChangeMixin， 只有第一个item的action 才会发送出来，其他的会被拦截。查看代码发现问题如上图所示。
VisibleChangeMixin 本来就是设计成这样，不支持每个item 单独获取生命周期？

**Comment by zjuwjf** [comment]
如果可以，建议给更多的代码。

VisibleChangeMixin 是用来设计给子adapter添加appear&disappear的事件， 所以它应该被mixin到子adapter中。

**Comment by wilin52** [comment]
> 如果可以，建议给更多的代码。
> 
> VisibleChangeMixin 是用来设计给子adapter添加appear&disappear的事件， 所以它应该被mixin到子adapter中。

你好：
后续是否增加 VisibleChangeMixin 使用demo？
**再次查看文档，我的理解是，mixin 只针对与整个数据组，而不是单个数据。 **

文档显示：
增加了 appear 和 disappear 的生命周期， 代表这个 adapter 管理的视图数组，刚进入显示区和完全离开显示区的回调。
当一个List 简化到所有数据都是最小单元的Component， 即没有子adapter的时候，那么 VisibleChangeMixin 也就没有使用的必要了，对吧。但是很多情况下我们会更在乎的是每个item 的生命周期。以后是否会对次扩展？ （自己实现也是很简单就是了）

谢谢回复

**Comment by zjuwjf** [comment]
你是说给 父Adapter mixin 一个 VisibleChangeForSubsMixin， 然后它的所有子Adapter都有了 appear & disappear的事件？

 目前没有这样的扩展计划，不过欢迎PR👏。

**Comment by wilin52** [comment]
> 你是说给 父Adapter mixin 一个 VisibleChangeForSubsMixin， 然后它的所有子Adapter都有了 appear & disappear的事件？
> 
> 目前没有这样的扩展计划，不过欢迎PR👏。

很高兴收到你的回复。

是的， 这样子的话我们可以精确到每个adapter 里面的最小单元，他们都有自己的生命周期，在生命周期里面，可以精确控制item的行为， 比如 显示/消失动画， 列表式视频的播放和暂停等等。

**Comment by zjuwjf** [comment]
定制一个这样的mixin的侵入性太强，成本高，收益低。 还说建议是通过对单个子adapter进行mixin，如果你相对所有的子adapter都有这个mixin的效果，可以通过设定一个通用的子adapter。

**Comment by wilin52** [comment]
> 定制一个这样的mixin的侵入性太强，成本高，收益低。 建议是通过对单个子adapter进行mixin，如果你想对所有的子adapter都有这个mixin的效果，可以通过设定一个通用的子adapter。

是的，谢谢
