### ISSUE TITLE
how to use component

### ISSUE THREAD

**Issue by hanmingkang** [alibaba/fish-redux#95]
![1553161858(1)](https://user-images.githubusercontent.com/19572365/54744410-e7413780-4c01-11e9-8624-dffced37a28f.png)
![1553161889(1)](https://user-images.githubusercontent.com/19572365/54744469-0b9d1400-4c02-11e9-8225-2f7c589b870b.png)
![1553161903(1)](https://user-images.githubusercontent.com/19572365/54744473-0d66d780-4c02-11e9-8262-d12ef3110c53.png)
Component中的两个值应该怎么传，还是说不能这样写？

**Comment by zjuwjf** [comment]
参考
```
class TestComponent {
  Widget test<T>(Component<T> component, T initState) {
    final PageStore<T> store = createPageStore<T>(
      initState, component.reducer,
    );
    return component.buildComponent(store, store.getState);
  }
}
```

**Comment by hanmingkang** [comment]
看了buildPage()源码明白了，如果需要使用buildComponent（）需要向你那样定义参数了，谢谢

**Comment by hanmingkang** [comment]
page的第二个参数是必须填写吗？
![1553161858(1)](https://user-images.githubusercontent.com/19572365/54746822-24102d00-4c08-11e9-97c0-4f890aa4e3d7.png)
比如这样的必须要传入一个String

**Comment by hanmingkang** [comment]
> page的第二个参数是必须填写吗？
> ![1553161858(1)](https://user-images.githubusercontent.com/19572365/54746822-24102d00-4c08-11e9-97c0-4f890aa4e3d7.png)
> 比如这样的必须要传入一个String

加入不想使用这个额外参数的话，需要自己像上面写吗？

**Comment by zjuwjf** [comment]
这个参数， 一般代表来自路由的参数Map<String, dynamic>

这个参数会传递给 InitState， 用来构建初始化的State

**Comment by log225** [comment]
> 参考
> 
> ```
> class TestComponent {
>   Widget test<T>(Component<T> component, T initState) {
>     final PageStore<T> store = createPageStore<T>(
>       initState, component.reducer,
>     );
>     return component.buildComponent(store, store.getState);
>   }
> }
> ```

这个store能和现在已经存在page中的store一样么？怎么传值呢？

**Comment by zjuwjf** [comment]
> 这个store能和现在已经存在page中的store一样么？怎么传值呢？

1. 和page的store是一样的
2. 传入的initState是做为store的初始值

如果你还有需要了解的，可以再次打开这个issue。

**Comment by chenyang88** [comment]
能不能给一个例子
