### ISSUE TITLE
warning: $DebugOrReport.debugUpdate has not been used.

### ISSUE THREAD

**Issue by jefferybai** [alibaba/fish-redux#98]
请问logMiddleware为什么会打印这个警告， 而且警告以后无法打印后续state值。

**Comment by zjuwjf** [comment]
$DebugOrReport.debugUpdate action是在debug模式下用来提示当前那个Component被刷新了，它没有其他的作用，也不影响其他的功能。

**Comment by TshineZheng** [comment]
把 logMiddleware  提取出来，对 action 类型为 DebugOrReport.debugUpdate 时做判断，忽略这个警告即可。
昨天刚启动 demo 的时候被膈应了好久，一堆警告。

**Comment by zjuwjf** [comment]
> 把 logMiddleware 提取出来，对 action 类型为 DebugOrReport.debugUpdate 时做判断，忽略这个警告即可。
> 昨天刚启动 demo 的时候被膈应了好久，一堆警告。

合理的话，欢迎 PR 👏
